care/force-app/main/default/objects/Article_Voting_Stat__c/Article_Voting_Stat__c.object-meta.xml
<CustomObject>
    <description>Custom Object to track if the Article was helpful or not</description>
    <label>Article Voting Stat</label>
    <nameField>
        <displayFormat>AV-{0000}</displayFormat>
        <label>Article Vote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Article Voting Stats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Article_Voting_Stat__c/fields/Care_ID__c.field-meta.xml
<CustomField>
    <fullName>Care_ID__c</fullName>
    <label>Care ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Article_Voting_Stat__c/fields/Did_you_get_the_Help_you_needed__c.field-meta.xml
<CustomField>
    <fullName>Did_you_get_the_Help_you_needed__c</fullName>
    <description>Picklist that counts if article was helpful</description>
    <label>Did you get the Help you needed?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Article_Voting_Stat__c/fields/Knowledge_Article__c.field-meta.xml
<CustomField>
    <fullName>Knowledge_Article__c</fullName>
    <label>Knowledge Article</label>
    <referenceTo>US_Knowledge__kav</referenceTo>
    <relationshipLabel>Article Voting Stats</relationshipLabel>
    <relationshipName>Article_Voting_Stats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care/force-app/main/default/objects/Article_Voting_Stat__c/fields/Member_Type__c.field-meta.xml
<CustomField>
    <fullName>Member_Type__c</fullName>
    <label>Member Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BASIC</fullName>
            </value>
            <value>
                <fullName>PREMIUM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/US_Knowledge__kav/US_Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>Knowledge Articles for US Member Care team.</description>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

care/force-app/main/default/classes/CDCCCaseDeflectionController.cls
public without sharing class CDCCCaseDeflectionController {
    public class Article {
        @AuraEnabled public String id { get; set; }
        @AuraEnabled public String title { get; set; }
        @AuraEnabled public String urlName { get; set; }
        public Article(String id, String title, String urlName) {
            this.id = id;
            this.title = title;
            this.urlName = urlName;
        }
    }

    @AuraEnabled
    public static List<Article> getArticles(String articleId, Integer numArticles, String language) {
        if (language == null ) language = 'en_US';

        try {
            List<Article> articles = new List<Article>();
            Set<Id> topicIds = getTopics(articleId);
            List<KnowledgeArticleVersion> kavs = getArticlesByTopicIds(articleId, topicIds, numArticles, language);
            for (KnowledgeArticleVersion kav : kavs) {
                articles.add(new Article(kav.Id, kav.Title, kav.UrlName));
            }
            return articles;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void createVotingRecord(String articleId, String memberId, String memberType, String isArticleHelpful){
        try {
            Article_Voting_Stat__c vote = new Article_Voting_Stat__c(
                Knowledge_Article__c = articleId,
                Care_ID__c = memberId,
                Member_Type__c = memberType,
                Did_you_get_the_help_you_needed__c = isArticleHelpful
            );
            insert vote;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    private static Set<Id> getTopics(String articleId) {
        Set<Id> topicIds = new Set<Id>();
        if (String.isBlank(articleId)) {
            return topicIds;
        }
        Id networkId = Test.isRunningTest() ? [SELECT Id FROM Network WHERE UrlPathPrefix = 'families' LIMIT 1].Id : Network.getNetworkId();
        List<AggregateResult> results = [
            SELECT TopicId 
            FROM TopicAssignment 
            WHERE EntityId = :articleId AND EntityType = 'US_Knowledge__kav' AND NetworkId = :networkId
            GROUP BY TopicId
        ];
        for (AggregateResult result : results) {
            topicIds.add((Id)result.get('TopicId'));
        }
        return topicIds;
    }

    private static List<KnowledgeArticleVersion> getArticlesByTopicIds(String articleId,  Set<Id> topicIds, Integer numArticles, String language) {
        List<KnowledgeArticleVersion> kavs = new List<KnowledgeArticleVersion>();
        if (topicIds.size() == 0) {
            return kavs;
        }
        if (numArticles == null || numArticles <= 0) {
            numArticles = 1;
        }
        Id networkId = Test.isRunningTest() ? [SELECT Id FROM Network WHERE UrlPathPrefix = 'families' LIMIT 1].Id : Network.getNetworkId();
        List<TopicAssignment> topicAssignments = [
            SELECT EntityId
            FROM TopicAssignment
            WHERE TopicId IN :topicIds AND EntityType = 'US_Knowledge__kav' AND EntityId != :articleId AND NetworkId = :networkId
        ];
        if (topicAssignments.size() > 0) {
            Set<Id> articleIds = new Set<Id>();
            for (TopicAssignment ta : topicAssignments) {
                articleIds.add(ta.EntityId);
            }
            kavs = [
                SELECT Id, Title, UrlName
                FROM KnowledgeArticleVersion
                WHERE Id IN :articleIds AND IsLatestVersion = true AND PublishStatus = 'Online'  AND Language = :language
                ORDER BY ArticleTotalViewCount DESC
                LIMIT :numArticles
            ];
        }
        return kavs;
    }
}