care/force-app/main/default/objects/Process_Control_Settings__mdt/Process_Control_Settings__mdt.object-meta.xml
<CustomObject>
    <description>Generic Configuration settings to switch on or off multiple processes like gdpr,retention etc..</description>
    <label>Process Control Settings</label>
    <pluralLabel>Process Control Settings</pluralLabel>
</CustomObject>

care/force-app/main/default/objects/Process_Control_Settings__mdt/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>Describes the process name Ex: GDPR</description>
    <label>Process Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GDPR</fullName>
                <default>true</default>
                <label>GDPR</label>
            </value>
            <value>
                <fullName>GDPR Fail Over</fullName>
            </value>
            <value>
                <fullName>Intl Retention</fullName>
            </value>
            <value>
                <fullName>Intl Retention Fail Over</fullName>
            </value>
            <value>
                <fullName>Intl Retention Batch</fullName>
            </value>
            <value>
                <fullName>Intl Retention Admin Notification</fullName>
            </value>
            <value>
                <fullName>GDPR Admin Notification</fullName>
            </value>
            <value>
                <fullName>GDPR Sterling Sync</fullName>
            </value>
            <value>
                <fullName>Intl Retention Sterling Sync</fullName>
            </value>
            <value>
                <fullName>Update Salesforce Last Action Date</fullName>
            </value>
            <value>
                <fullName>Integration User</fullName>
            </value>
            <value>
                <fullName>CCPA Deletion</fullName>
            </value>
            <value>
                <fullName>CCPA Access Data</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Process_Control_Settings__mdt/fields/Switch__c.field-meta.xml
<CustomField>
    <fullName>Switch__c</fullName>
    <label>Switch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On</fullName>
                <default>true</default>
                <label>On</label>
            </value>
            <value>
                <fullName>Off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/classes/Test_BatchGDPRMemberRequestCount.cls
@isTest(SeeAllData=false)
private class Test_BatchGDPRMemberRequestCount{
    private static ID seekerRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('International Seeker').getRecordTypeId();
    private static ID safetyAlertRecId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('International Safety Alert').getRecordTypeId();
    @isTest(SeeAllData=false)
    static void test() 
    {        
        Account a=new Account(lastname='Test',Gdpr_request__c='RTBF',recordtypeid=seekerRecId);
        insert a;
        Account a2=new Account(lastname='Test',Gdpr_request__c='GDPR',recordtypeid=seekerRecId);
        insert a2;
        Case caseObj1=new Case(subject='Test Subject',accountid=a.id,recordtypeid=safetyAlertRecId);
        Case caseObj2=new Case(subject='Test Subject',accountid=a.id,recordtypeid=safetyAlertRecId);
        insert new List<Case>{caseObj1,caseObj2};
        Test.startTest();
        //Database.executeBatch(new BatchGDPRMemberRequestCount(true));
        List<User> userList=[select id,firstname,lastname,email,name,username from user where email in ('mohammed.ashwaq@care.com')];
        List<Process_Control_Settings__mdt> pcsm = [select id,DeveloperName,MasterLabel,Process_Name__c,Switch__c from Process_Control_Settings__mdt where Process_Name__c in ('GDPR Fail Over','Intl Retention Fail Over')];
        System.schedulebatch(new BatchGDPRMemberRequestCount(false,userList),'GDPR Count',1,200);
        //System.schedulebatch(new BatchGDPRMemberRequestCount(true,userList),'GDPR Count',1,200);
        ProcessGDPRCount.processGDPRCount('mohammed.ashwaq@care.com, ramaganesh.guttula@care.com');
        GDPRFailoverHandler gdpfoh = new GDPRFailoverHandler();
        Test.stopTest();
    }    
}