care/force-app/main/default/objects/CCC_API_Endpoint_Setting__mdt/CCC_API_Endpoint_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Used by Contract Composer for the various APIs the application is using.</description>
    <label>CCC API Endpoint Setting</label>
    <pluralLabel>CCC API Endpoint Settings</pluralLabel>
</CustomObject>

care/force-app/main/default/objects/CCC_API_Endpoint_Setting__mdt/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>The full URL to the end point. May contain placeholder tags {}, that can be replaced programmatically in code</description>
    <inlineHelpText>The full URL to the end point. May contain placeholder tags {}, that can be replaced programmatically in code</inlineHelpText>
    <label>URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/Composer_Service__c.object-meta.xml
<CustomObject>
    <description>Identifies the vertical and license level for a service provider</description>
    <label>Composer Service</label>
    <nameField>
        <displayFormat>CCS-{00}</displayFormat>
        <label>Composer Services Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Composer Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Composer_Service__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is this service active and available to be selected in the composer?</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/License_Level__c.field-meta.xml
<CustomField>
    <fullName>License_Level__c</fullName>
    <description>License level of the vertical being serviced, or Category</description>
    <label>License Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Centers</fullName>
            </value>
            <value>
                <fullName>Nanny Agencies</fullName>
            </value>
            <value>
                <fullName>FCCs</fullName>
            </value>
            <value>
                <fullName>Camps</fullName>
            </value>
            <value>
                <fullName>Activities</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Adult Day Care</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Flat Rate</fullName>
            </value>
            <value>
                <fullName>Camps &amp; Activities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Service_Specific_Fields__c.field-meta.xml
<CustomField>
    <fullName>Service_Specific_Fields__c</fullName>
    <description>Which fields on Opportunity Service Area should be displayed on the Vetting tab?  API names, comma seperated.</description>
    <label>Service Specific Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <description>Vertical name, or Category Group</description>
    <label>Vertical</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Childcare</fullName>
            </value>
            <value>
                <fullName>Childcare Flat Rate</fullName>
            </value>
            <value>
                <fullName>Recruiting Solutions</fullName>
            </value>
            <value>
                <fullName>Senior Care</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/Opportunity_Service_Area__c.object-meta.xml
<CustomObject>
    <description>The collection of postal codes for one service area inside a contract composer opportunity</description>
    <label>Opportunity Service Area</label>
    <nameField>
        <label>Display Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Service Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Age_Range__c.field-meta.xml
<CustomField>
    <fullName>Age_Range__c</fullName>
    <description>Age Range</description>
    <label>Age Range</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0-1 (infant)</fullName>
            </value>
            <value>
                <fullName>1-2 (toddler)</fullName>
            </value>
            <value>
                <fullName>3-4 (preschool)</fullName>
            </value>
            <value>
                <fullName>5+ (school age)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <description>Capacity</description>
    <label>Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email address for the location, optional</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Master opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Service Areas</relationshipLabel>
    <relationshipName>Opportunity_Service_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Phone</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

care/force-app/main/default/objects/Review_Reference__c/Review_Reference__c.object-meta.xml
<CustomObject>
    <description>Basic information for the CS team to acquire references.  Gathered typically through the Contract Composer</description>
    <label>Review Reference</label>
    <nameField>
        <displayFormat>RR-{0}</displayFormat>
        <label>Review Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Review_Reference__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Review References</relationshipLabel>
    <relationshipName>Review_References</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care/force-app/main/default/objects/Review_Reference__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

care/force-app/main/default/objects/Review_Reference__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>First Name</description>
    <label>First Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Review_Reference__c/fields/Galore_Review_uuid__c.field-meta.xml
<CustomField>
    <fullName>Galore_Review_uuid__c</fullName>
    <label>Galore Review uuid</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Review_Reference__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Last Name</description>
    <label>Last Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Review_Reference__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Optional lookup to the location referenced.</description>
    <label>Location</label>
    <referenceTo>Opportunity_Service_Area__c</referenceTo>
    <relationshipLabel>Review References</relationshipLabel>
    <relationshipName>Review_References</relationshipName>
    <type>Lookup</type>
</CustomField>

care/force-app/main/default/objects/Review_Reference__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Phone</description>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

care/force-app/main/default/classes/CCCReviewCont_Test.cls
/*****************************************************************************************
Created By: Alan Oshry
Email: alan.oshry@revelanttech.com
Created: 01/08/2021
Description: Test methods for CCCReviewController Apex class
Comments:

********************************************************************************************/
@isTest
private class CCCReviewCont_Test {
    private static CCCReviewController.ServerResponse response;

    @testSetup static void setup() {

        // Create Composer Service records
        CCCTestDataFactory.createComposerServiceRecords();

        // Create Account
        CCCTestDataFactory.createAccount('Test Account');

        // Retrieve our new Account
        Account accountRecord = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];

        // Assign a Galore Id for API calls
        accountRecord.Galore_Business_Id__c = 'XYZ';
        update accountRecord;


        // Retrieve our active Senior Care, Housing Composer Service record to assign to the Opportunity
        Composer_Service__c composerServiceRecord = [SELECT Id FROM Composer_Service__c WHERE Vertical__c = 'Senior Care' AND License_Level__c = 'Housing' AND Active__c = TRUE LIMIT 1];
        composerServiceRecord.Service_Specific_Fields__c = 'Age_Range__c,Capacity__c';
        update composerServiceRecord;

        // Create Opportunity
        CCCTestDataFactory.createOpportunity_SalesOrigination(accountRecord.Id, composerServiceRecord.Id);

        // Retrieve our new Opportunity
        Opportunity opportunitySORecord = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity - Sales Origination' LIMIT 1];

        // Create Opportunity Service Area records
        CCCTestDataFactory.createOpportunityServiceAreas(opportunitySORecord.Id);

        // Create Account Reviews
        List<Review_Reference__c> reviewRecords = new List<Review_Reference__c>();
        List<Opportunity_Service_Area__c> locationRecords = (List<Opportunity_Service_Area__c>) CCCQuery.get('Opportunity_Service_Area__c').equals('Opportunity__c', opportunitySORecord.Id).all();

        for (Opportunity_Service_Area__c locationRecord: locationRecords) {
            reviewRecords.add(new Review_Reference__c(
                Account__c = accountRecord.Id,
                Email__c = 'test@test.com',
                First_Name__c = 'First Name',
                Last_Name__c = 'Last Name',
                Phone__c = '1111111111',
                Location__c = locationRecord.Id
            ));
        }

        insert reviewRecords;

        // Create Sales Origination Rep user for testing
        CCCTestDataFactory.createSalesOriginationRepUser();
    }

    @isTest static void test_getReviewData_Fail_RootExceptionThrown() {
        User u = [SELECT Id FROM User WHERE UserName = 'test_so_profile@caredotcom.com'];

        CCCUtils.UnitTestFlags flags = new CCCUtils.UnitTestFlags();
        flags.throwRootExceptionFail = true;

        Opportunity opportunityRecord = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity - Sales Origination' LIMIT 1];

        Test.startTest();
        System.runAs(u) {
            response = CCCReviewController.getReviewData(opportunityRecord.Id, flags);
        }
        Test.stopTest();

        System.assertEquals(true, response.hasErrors, 'hasErrors should be true');
        System.assert(response.message.endsWith('Throw Root Exception Unit Test.'), 'Expected message to end with: Throw Root Exception Unit Test.');
    }

    @isTest static void test_getReviewData_Fail_EmptyOpportunityId() {
        User u = [SELECT Id FROM User WHERE UserName = 'test_so_profile@caredotcom.com'];


        Test.startTest();
        System.runAs(u) {
            response = CCCReviewController.getReviewData(null);
        }
        Test.stopTest();

        System.assertEquals(true, response.hasErrors, 'hasErrors should be true');
        System.assert(response.message.endsWith('Empty opportunityId parameter passed.'), 'Expected message to end with: Empty opportunityId parameter passed.');
    }

    @isTest static void test_getReviewData_Pass() {
        User u = [SELECT Id FROM User WHERE UserName = 'test_so_profile@caredotcom.com'];

        Opportunity opportunityRecord = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity - Sales Origination' LIMIT 1];

        Test.startTest();
        System.runAs(u) {
            response = CCCReviewController.getReviewData(opportunityRecord.Id);
        }
        Test.stopTest();

        System.assertEquals(false, response.hasErrors, 'response has error:' + response.message);
        System.assertEquals(null, response.message, 'response has error:' + response.message);
        System.assertEquals(3,response.locationRecords.size(), 'locationRecords list should be of size 3');
        System.assertEquals(3,response.reviewRecords.size(), 'reviewRecords list should be of size 3');
    }

    @isTest static void test_saveReviewRecord_Fail_EmptyReviewRecord() {
        User u = [SELECT Id FROM User WHERE UserName = 'test_so_profile@caredotcom.com'];


        Test.startTest();
        System.runAs(u) {
            response = CCCReviewController.saveReviewRecord(null, null);
        }
        Test.stopTest();

        System.assertEquals(true, response.hasErrors, 'hasErrors should be true');
        System.assert(response.message.endsWith('Empty reviewRecord parameter passed.'), 'Expected message to end with: Empty reviewRecord parameter passed.');
    }

    @isTest static void test_saveReviewRecord_Fail_RootExceptionThrown() {
        User u = [SELECT Id FROM User WHERE UserName = 'test_so_profile@caredotcom.com'];

        CCCUtils.UnitTestFlags flags = new CCCUtils.UnitTestFlags();
        flags.throwRootExceptionFail = true;

        Opportunity opportunityRecord = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity - Sales Origination' LIMIT 1];

        Test.startTest();
        System.runAs(u) {
            response = CCCReviewController.saveReviewRecord(new Review_Reference__c(), null, flags);
        }
        Test.stopTest();

        System.assertEquals(true, response.hasErrors, 'hasErrors should be true');
        System.assert(response.message.endsWith('Throw Root Exception Unit Test.'), 'Expected message to end with: Throw Root Exception Unit Test.');
    }

    @isTest static void test_saveReviewRecord_Pass_APIUpdate() {
        final String REVIEW_ID = '844f93d1-4922-404e-b5ab-c8bcca89ad9c';

        CCCReviewController.ServerResponse response2;

        User u = [SELECT Id FROM User WHERE UserName = 'test_so_profile@caredotcom.com'];

        Opportunity opportunityRecord = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity - Sales Origination' LIMIT 1];

        // Retrieve our new Account
        Account accountRecord = [SELECT Id, Galore_Business_Id__c FROM Account WHERE Name = 'Test Account' LIMIT 1];

        Opportunity_Service_Area__c locationRecord = (Opportunity_Service_Area__c) CCCQuery.get('Opportunity_Service_Area__c').equals('Opportunity__c', opportunityRecord.Id).one();

        Review_Reference__c reviewRecord = new Review_Reference__c();
        reviewRecord.Account__c = accountRecord.Id;
        reviewRecord.Email__c = 'test@test.com';
        reviewRecord.First_Name__c = 'First Name';
        reviewRecord.Last_Name__c = 'Last Name';
        reviewRecord.Phone__c = '1111111111';
        reviewRecord.Location__c = locationRecord.Id;
        reviewRecord.Galore_Review_uuid__c = REVIEW_ID;

        // Get API Setting - Update Review
        CCC_API_Endpoint_Setting__mdt apiSetting = (CCC_API_Endpoint_Setting__mdt) CCCQuery.get('CCC_API_Endpoint_Setting__mdt').equals('DeveloperName', 'Update_Review').one();
        String endpointURL = apiSetting.URL__c.replace(':uuid', REVIEW_ID);

        // Mock Response - Update Review
        CCCAPIRespUpdateReview.ServerResponse updateReviewResponse = new CCCAPIRespUpdateReview.ServerResponse();
        updateReviewResponse.review = new CCCAPIRespUpdateReview.ReviewObject();
        updateReviewResponse.review.uuid = REVIEW_ID;
        updateReviewResponse.review.first_name = 'test';
        updateReviewResponse.review.last_name = 'test';
        updateReviewResponse.review.email = 'test@example.com';
        updateReviewResponse.review.phone = '8005551234';
        updateReviewResponse.review.location_name = 'test';

        CCCMockCallouts mock = new CCCMockCallouts();
        mock.add(endpointURL, JSON.serialize(updateReviewResponse), 200, 'Success');


        Test.startTest();
        System.runAs(u) {

            Test.setMock(HttpCalloutMock.class, mock.getMockCallout());

            response = CCCReviewController.saveReviewRecord(reviewRecord, accountRecord.Galore_Business_Id__c);

            response2 = CCCReviewController.getReviewData(opportunityRecord.Id);
        }
        Test.stopTest();

        System.assertEquals(false, response.hasErrors, 'response has error:' + response.message);
        System.assertEquals(null, response.message, 'response has error:' + response.message);

        System.assertEquals(false, response2.hasErrors, 'response has error:' + response2.message);
        System.assertEquals(null, response2.message, 'response has error:' + response2.message);
        System.assertEquals(4, response2.reviewRecords.size(), 'reviewRecords list should be of size 4');
    }

    @isTest static void test_saveReviewRecord_Pass_APIAdd() {
        final String REVIEW_ID = '844f93d1-4922-404e-b5ab-c8bcca89ad9c';

        CCCReviewController.ServerResponse response2;

        User u = [SELECT Id FROM User WHERE UserName = 'test_so_profile@caredotcom.com'];

        Opportunity opportunityRecord = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity - Sales Origination' LIMIT 1];

        // Retrieve our new Account
        Account accountRecord = [SELECT Id, Galore_Business_Id__c FROM Account WHERE Name = 'Test Account' LIMIT 1];

        Opportunity_Service_Area__c locationRecord = (Opportunity_Service_Area__c) CCCQuery.get('Opportunity_Service_Area__c').equals('Opportunity__c', opportunityRecord.Id).one();

        Review_Reference__c reviewRecord = new Review_Reference__c();
        reviewRecord.Account__c = accountRecord.Id;
        reviewRecord.Email__c = 'test@test.com';
        reviewRecord.First_Name__c = 'First Name';
        reviewRecord.Last_Name__c = 'Last Name';
        reviewRecord.Phone__c = '1111111111';
        reviewRecord.Location__c = locationRecord.Id;

        // Get API Setting - Update Review
        CCC_API_Endpoint_Setting__mdt apiSetting = (CCC_API_Endpoint_Setting__mdt) CCCQuery.get('CCC_API_Endpoint_Setting__mdt').equals('DeveloperName', 'Create_Review').one();
        String endpointURL = apiSetting.URL__c;

        // Mock Response - Update Review
        CCCAPIRespUpdateReview.ServerResponse updateReviewResponse = new CCCAPIRespUpdateReview.ServerResponse();
        updateReviewResponse.review = new CCCAPIRespUpdateReview.ReviewObject();
        updateReviewResponse.review.uuid = REVIEW_ID;
        updateReviewResponse.review.first_name = 'test';
        updateReviewResponse.review.last_name = 'test';
        updateReviewResponse.review.email = 'test@example.com';
        updateReviewResponse.review.phone = '8005551234';
        updateReviewResponse.review.location_name = 'test';

        CCCMockCallouts mock = new CCCMockCallouts();
        mock.add(endpointURL, JSON.serialize(updateReviewResponse), 200, 'Success');


        Test.startTest();
        System.runAs(u) {

            Test.setMock(HttpCalloutMock.class, mock.getMockCallout());

            response = CCCReviewController.saveReviewRecord(reviewRecord, accountRecord.Galore_Business_Id__c);

            response2 = CCCReviewController.getReviewData(opportunityRecord.Id);
        }
        Test.stopTest();

        System.assertEquals(false, response.hasErrors, 'response has error:' + response.message);
        System.assertEquals(null, response.message, 'response has error:' + response.message);

        System.assertEquals(false, response2.hasErrors, 'response has error:' + response2.message);
        System.assertEquals(null, response2.message, 'response has error:' + response2.message);
        System.assertEquals(4, response2.reviewRecords.size(), 'reviewRecords list should be of size 4');
    }

}