care/force-app/main/default/objects/Opportunity_Service_Area__c/Opportunity_Service_Area__c.object-meta.xml
<CustomObject>
    <description>The collection of postal codes for one service area inside a contract composer opportunity</description>
    <label>Opportunity Service Area</label>
    <nameField>
        <label>Display Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Service Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email address for the location, optional</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Master opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Service Areas</relationshipLabel>
    <relationshipName>Opportunity_Service_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Phone</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

care/force-app/main/default/objects/Review_Reference__c/Review_Reference__c.object-meta.xml
<CustomObject>
    <description>Basic information for the CS team to acquire references.  Gathered typically through the Contract Composer</description>
    <label>Review Reference</label>
    <nameField>
        <displayFormat>RR-{0}</displayFormat>
        <label>Review Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Review_Reference__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Review References</relationshipLabel>
    <relationshipName>Review_References</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care/force-app/main/default/objects/Review_Reference__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

care/force-app/main/default/objects/Review_Reference__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>First Name</description>
    <label>First Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Review_Reference__c/fields/Galore_Review_uuid__c.field-meta.xml
<CustomField>
    <fullName>Galore_Review_uuid__c</fullName>
    <label>Galore Review uuid</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Review_Reference__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Last Name</description>
    <label>Last Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Review_Reference__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Optional lookup to the location referenced.</description>
    <label>Location</label>
    <referenceTo>Opportunity_Service_Area__c</referenceTo>
    <relationshipLabel>Review References</relationshipLabel>
    <relationshipName>Review_References</relationshipName>
    <type>Lookup</type>
</CustomField>

care/force-app/main/default/objects/Review_Reference__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Phone</description>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

care/force-app/main/default/classes/CCCReviewController.cls
/****************************************************************************
Created By: Alan Oshry
Email: alan.oshry@revelanttech.com
Created: 01/07/2021
Description: Apex controller for CCCReviewModule lightning component.
Changes:

*****************************************************************************/
public without sharing class CCCReviewController {
    static private String CLASS_NAME = 'CCCReviewController';

    public class ServerResponse extends CCCServerResponse {
        @AuraEnabled public List<Opportunity_Service_Area__c> locationRecords { get; set; }
        @AuraEnabled public List<Review_Reference__c> reviewRecords { get; set; }
        @AuraEnabled public Opportunity opportunityRecord { get; set; }

        public ServerResponse() {
            super();
            this.locationRecords = new List<Opportunity_Service_Area__c>();
            this.reviewRecords = new List<Review_Reference__c>();
        }
    }

    /**
    * @description Retrieves the Reference Review record for the Opportunity's related Account
    * @param opportunityId (String) - The Opportunity record Id
    * @return (ServerResponse)
    */
    @AuraEnabled public static ServerResponse getReviewData(String opportunityId) { return getReviewData(opportunityId, new CCCUtils.UnitTestFlags()); }

    @TestVisible private static ServerResponse getReviewData(String opportunityId, CCCUtils.UnitTestFlags flags) {
        final String METHOD_NAME = 'getReviewData';

        ServerResponse response = new ServerResponse();

        try {

            if (flags.throwRootExceptionFail) throw new CCCUtils.CCCException('Throw Root Exception Unit Test.');

            if (opportunityId == null) throw new CCCException('Empty opportunityId parameter passed.');

            // Get Opportunity record
            response.opportunityRecord = (Opportunity) CCCQuery.get('Opportunity').field('Account.Galore_Business_Id__c').equalsId(opportunityId).one();

            // Get Location records
            response.locationRecords = (List<Opportunity_Service_Area__c>) CCCQuery.get('Opportunity_Service_Area__c').equals('Opportunity__c', opportunityId).all();

            // Get Review records
            response.reviewRecords = (List<Review_Reference__c>) CCCQuery.get('Review_Reference__c').field('Location__r.Name').equals('Account__c', response.opportunityRecord.AccountId).all();

        } catch (Exception e) { return (ServerResponse) CCCUtils.setErrorResponse(CLASS_NAME, METHOD_NAME, e, (CCCServerResponse) response); }

        return response;
    }


    /**
    * @description Saves an Review record
    * @param reviewRecord (Review_Reference__c) - The Review_Reference__c record to save
    * @param businessId (String) - The Business Id for the Account
    * @return (ServerResponse)
    */
    @AuraEnabled public static ServerResponse saveReviewRecord(Review_Reference__c reviewRecord, String businessId) { return saveReviewRecord(reviewRecord, businessId, new CCCUtils.UnitTestFlags()); }

    @TestVisible private static ServerResponse saveReviewRecord(Review_Reference__c reviewRecord, String businessId, CCCUtils.UnitTestFlags flags) {
        final String METHOD_NAME = 'saveReviewRecord';
        ServerResponse response = new ServerResponse();

        try {

            if (flags.throwRootExceptionFail) throw new CCCUtils.CCCException('Throw Root Exception Unit Test.');
            if (reviewRecord == null) throw new CCCException('Empty reviewRecord parameter passed.');

            if (String.isNotBlank(businessId)) {
                // First update/create review in Galore
                // If this fails then we won't update the review in Salesforce
                reviewRecord = upsertGaloreReview(reviewRecord, businessId);
            }

            upsert reviewRecord;

        } catch (Exception e) { return (ServerResponse) CCCUtils.setErrorResponse(CLASS_NAME, METHOD_NAME, e, (CCCServerResponse) response); }

        return response;
    }


    private static Review_Reference__c upsertGaloreReview(Review_Reference__c reviewRecord, String businessId) {
        if (String.isNotBlank(reviewRecord.Galore_Review_uuid__c)) {

            CCCAPIReqUpdateReview request = new CCCAPIReqUpdateReview();
            request.review = new CCCAPIReqUpdateReview.ReviewObject();
            request.review.first_name = reviewRecord.First_Name__c;
            request.review.last_name = reviewRecord.Last_Name__c;
            request.review.email = reviewRecord.Email__c;
            request.review.phone = reviewRecord.Phone__c;
            request.review.location_name = reviewRecord.Location__r.Name;

            // Callout to Galore to update review
            Map<String, String> customParameters = new Map<String, String>();
            customParameters.put('uuid', reviewRecord.Galore_Review_uuid__c);
            CCCAPIRespUpdateReview.ServerResponse rCalloutMaster = (CCCAPIRespUpdateReview.ServerResponse) CCCCalloutMaster.updateReview(request, customParameters);
            if (rCalloutMaster.hasErrors) throw new CCCException(rCalloutMaster.message);

        } else {

            CCCAPIReqCreateReview request = new CCCAPIReqCreateReview();
            request.review = new CCCAPIReqCreateReview.ReviewObject();
            request.review.business_id = businessId;
            request.review.first_name = reviewRecord.First_Name__c;
            request.review.last_name = reviewRecord.Last_Name__c;
            request.review.email = reviewRecord.Email__c;
            request.review.phone = reviewRecord.Phone__c;
            request.review.location_name = reviewRecord.Location__r.Name;

            // Callout to Galore to create review
            CCCAPIRespCreateReview.ServerResponse rCalloutMaster = (CCCAPIRespCreateReview.ServerResponse) CCCCalloutMaster.createReview(request);
            if (rCalloutMaster.hasErrors) throw new CCCException(rCalloutMaster.message);

            // Update uuid on review record
            reviewRecord.Galore_Review_uuid__c = rCalloutMaster.review.uuid;
        }

        return reviewRecord;
    }
}