care/force-app/main/default/objects/Sterling_Country_Setting__mdt/Sterling_Country_Setting__mdt.object-meta.xml
<CustomObject>
    <description>This object stores country specific settings for each Sterling server..  This includes login &amp; registration URLs used in the Help Center.</description>
    <label>Sterling Country Setting</label>
    <pluralLabel>Sterling Country Settings</pluralLabel>
</CustomObject>

care/force-app/main/default/objects/Sterling_Country_Setting__mdt/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <inlineHelpText>Sterling Country Code.</inlineHelpText>
    <label>Country Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Sterling_Country_Setting__mdt/fields/Locale__c.field-meta.xml
<CustomField>
    <fullName>Locale__c</fullName>
    <label>Locale</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

care/force-app/main/default/classes/SetLocaleAndCountryInCase.cls
public class SetLocaleAndCountryInCase 
{

    public static void main (Case c){
    String caseOrigin=c.Origin;
     if(caseOrigin!=null && caseOrigin.contains(' - Privacy'))
            caseOrigin=caseOrigin.remove(' - Privacy');
 
     if(caseOrigin!=null && caseOrigin.contains(' - Covid'))
            caseOrigin=caseOrigin.remove(' - Covid');
            
     if(caseOrigin!=null && caseOrigin.contains(' - Web'))  
            caseOrigin=caseOrigin.remove(' - Web'); 
        
     if(caseOrigin!=null && caseOrigin.contains(' - Imprint'))
            caseOrigin=caseOrigin.remove(' - Imprint');
 
       /*
        if (c.Origin != null && c.Origin.left(5).ToLowerCase() == 'email'){ // should apply to email origins only
            Sterling_Country_Setting__mdt s = CountryLocaleMapHelper.getSettingByCaseOrigin(c.Origin);
            */
            
            if (caseOrigin != null && caseOrigin.left(5).ToLowerCase() == 'email'){ // should apply to email origins only
            Sterling_Country_Setting__mdt s = CountryLocaleMapHelper.getSettingByCaseOrigin(caseOrigin);
            
            if (s != null){
                if (s.Country_Code__c != 'us'){ // exclude US for now because US doesn't have full multilanguage support
                    c.Member_Locale__c = s.Locale__c;
                    c.Member_Country__c = s.Country_Code__c;
                }
            }
        }
    } 
}