care/force-app/main/default/objects/Sterling_Country_Setting__mdt/Sterling_Country_Setting__mdt.object-meta.xml
<CustomObject>
    <description>This object stores country specific settings for each Sterling server..  This includes login &amp; registration URLs used in the Help Center.</description>
    <label>Sterling Country Setting</label>
    <pluralLabel>Sterling Country Settings</pluralLabel>
</CustomObject>

care/force-app/main/default/objects/Sterling_Country_Setting__mdt/fields/Apply_to_Jobs__c.field-meta.xml
<CustomField>
    <fullName>Apply_to_Jobs__c</fullName>
    <label>Apply to Jobs</label>
    <type>Url</type>
</CustomField>

care/force-app/main/default/objects/Sterling_Country_Setting__mdt/fields/Case_Origin__c.field-meta.xml
<CustomField>
    <fullName>Case_Origin__c</fullName>
    <label>Case Origin</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

care/force-app/main/default/objects/Sterling_Country_Setting__mdt/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <inlineHelpText>Sterling Country Code.</inlineHelpText>
    <label>Country Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Sterling_Country_Setting__mdt/fields/Join_Now__c.field-meta.xml
<CustomField>
    <fullName>Join_Now__c</fullName>
    <label>Join Now</label>
    <type>Url</type>
</CustomField>

care/force-app/main/default/objects/Sterling_Country_Setting__mdt/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>Danish</fullName>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
            <value>
                <fullName>Finnish</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Norwegian</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Swedish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Sterling_Country_Setting__mdt/fields/Locale__c.field-meta.xml
<CustomField>
    <fullName>Locale__c</fullName>
    <label>Locale</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

care/force-app/main/default/objects/Sterling_Country_Setting__mdt/fields/Login__c.field-meta.xml
<CustomField>
    <fullName>Login__c</fullName>
    <inlineHelpText>The URL of the Login Page for the given locale.</inlineHelpText>
    <label>Login</label>
    <type>Url</type>
</CustomField>

care/force-app/main/default/objects/Sterling_Country_Setting__mdt/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Sterling_Country_Setting__mdt/fields/Production_URL_Root__c.field-meta.xml
<CustomField>
    <fullName>Production_URL_Root__c</fullName>
    <description>The root of the URL to hit the production servers for a given country.</description>
    <label>Production URL Root</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Sterling_Country_Setting__mdt/fields/QA_Email__c.field-meta.xml
<CustomField>
    <fullName>QA_Email__c</fullName>
    <label>QA Email</label>
    <type>Email</type>
</CustomField>

care/force-app/main/default/objects/Sterling_Country_Setting__mdt/fields/Staging_URL_Root__c.field-meta.xml
<CustomField>
    <fullName>Staging_URL_Root__c</fullName>
    <label>Staging URL Root</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Sterling_Country_Setting__mdt/fields/Upgrade__c.field-meta.xml
<CustomField>
    <fullName>Upgrade__c</fullName>
    <label>Upgrade</label>
    <type>Url</type>
</CustomField>

care/force-app/main/default/objects/Sterling_Country_Setting__mdt/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <description>The user names to access the staging server.</description>
    <label>User Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/classes/CountryLocaleMapHelper.cls
public class CountryLocaleMapHelper {
	/* This class should be used to access the Sterling Country Settings Map. 
	 * The class keeps a copy of the map & helper methods by which to access specific records
    
	*/

    public static List<Sterling_Country_Setting__mdt> CountryLocaleMap = [SELECT Country_Code__c, Case_Origin__c, Language__c, Locale__c, Production_URL_Root__c,Staging_URL_Root__c,User_Name__c,Password__c,QA_Email__c,Login__c,Upgrade__c,Join_Now__c,Apply_to_Jobs__c  FROM Sterling_Country_Setting__mdt];

    public static Sterling_Country_Setting__mdt getSettingByCaseOrigin(String CaseOrigin){
        for (Sterling_Country_Setting__mdt s : CountryLocaleMap){
			if (s.Case_Origin__c == CaseOrigin) return s;
        }
		return null;        
    }
    
    @AuraEnabled(cacheable=true)
    public static Sterling_Country_Setting__mdt getSettingByLocale(String locale){
        for (Sterling_Country_Setting__mdt s : CountryLocaleMap){
			if (s.Locale__c == locale) return s;
        }
		return null;        
    }
    
    public static Sterling_Country_Setting__mdt getSettingByCountry(String CountryCode){
		// multiple countries are alloweed in the table, but their records are interchangeable, so we return the first one we find
        for (Sterling_Country_Setting__mdt s : CountryLocaleMap){
			if (s.Country_Code__c == CountryCode) return s;
        }
		return null;        
    }

    public static String getLanguageFromLocale(String Locale){
        for (Sterling_Country_Setting__mdt s : CountryLocaleMap){
            if (s.Locale__c == Locale) return s.Language__c;
        }
        return null;
    }

    public static String getCaseOriginFromLocale(String Locale){
        for (Sterling_Country_Setting__mdt sc: CountryLocaleMap){
            if (sc.Locale__c == Locale) return sc.Case_Origin__c;
        }
        return null;
    }

    public static String getQAEmail(String Locale){
        for (Sterling_Country_Setting__mdt sc: CountryLocaleMap){
            if (sc.Locale__c == Locale) return sc.QA_Email__c;
        }
        return null;
        
    }

}