care/force-app/main/default/objects/Sterling_Country_Setting__mdt/Sterling_Country_Setting__mdt.object-meta.xml
<CustomObject>
    <description>This object stores country specific settings for each Sterling server..  This includes login &amp; registration URLs used in the Help Center.</description>
    <label>Sterling Country Setting</label>
    <pluralLabel>Sterling Country Settings</pluralLabel>
</CustomObject>

care/force-app/main/default/objects/Sterling_Country_Setting__mdt/fields/Case_Origin__c.field-meta.xml
<CustomField>
    <fullName>Case_Origin__c</fullName>
    <label>Case Origin</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

care/force-app/main/default/objects/Sterling_Country_Setting__mdt/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <inlineHelpText>Sterling Country Code.</inlineHelpText>
    <label>Country Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Sterling_Country_Setting__mdt/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>Danish</fullName>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
            <value>
                <fullName>Finnish</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Norwegian</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Swedish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Sterling_Country_Setting__mdt/fields/Locale__c.field-meta.xml
<CustomField>
    <fullName>Locale__c</fullName>
    <label>Locale</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

care/force-app/main/default/objects/Sterling_Country_Setting__mdt/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Sterling_Country_Setting__mdt/fields/Production_URL_Root__c.field-meta.xml
<CustomField>
    <fullName>Production_URL_Root__c</fullName>
    <description>The root of the URL to hit the production servers for a given country.</description>
    <label>Production URL Root</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Sterling_Country_Setting__mdt/fields/QA_Email__c.field-meta.xml
<CustomField>
    <fullName>QA_Email__c</fullName>
    <label>QA Email</label>
    <type>Email</type>
</CustomField>

care/force-app/main/default/objects/Sterling_Country_Setting__mdt/fields/Staging_URL_Root__c.field-meta.xml
<CustomField>
    <fullName>Staging_URL_Root__c</fullName>
    <label>Staging URL Root</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Sterling_Country_Setting__mdt/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <description>The user names to access the staging server.</description>
    <label>User Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/classes/Test_CountryLocaleMapHelper.cls
//Created By: Mohammed Ashwaq
//Test class for CountryLocaleMapHelper
//Created Date: 10/11/2020
@isTest
private class Test_CountryLocaleMapHelper {
    Public static String  csOrigin='Email - AU';
    Public static String  countryCode='AU';
    Public static string locale = 'en_AU';
    static testMethod void CountryLocaleMapHelperTest () {
        Test.startTest();
        List<Sterling_Country_Setting__mdt> CountryLocaleMap = [SELECT Country_Code__c, Case_Origin__c, Language__c, Locale__c, Production_URL_Root__c,Staging_URL_Root__c,User_Name__c,Password__c,QA_Email__c FROM Sterling_Country_Setting__mdt];
        CountryLocaleMapHelper.getSettingByCaseOrigin(csOrigin);
        CountryLocaleMapHelper.getSettingByCaseOrigin(null);
        CountryLocaleMapHelper.getSettingByCountry(countryCode);
        CountryLocaleMapHelper.getSettingByCountry(null);
        CountryLocaleMapHelper.getLanguageFromLocale(locale);
        CountryLocaleMapHelper.getLanguageFromLocale(null);
        CountryLocaleMapHelper.getCaseOriginFromLocale(locale);
        CountryLocaleMapHelper.getCaseOriginFromLocale(null);
        CountryLocaleMapHelper.getQAEmail(locale);
        CountryLocaleMapHelper.getQAEmail(null);
        CountryLocaleMapHelper.getSettingByLocale(locale);
        CountryLocaleMapHelper.getSettingByLocale(null);
        Test.stopTest();
    }
}