care/force-app/main/default/objects/CCC_Global_Setting__mdt/CCC_Global_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Global Settings used by Contract Composer Lightning Components and related code.</description>
    <label>CCC Global Setting</label>
    <pluralLabel>CCC Global Settings</pluralLabel>
</CustomObject>

care/force-app/main/default/objects/CCC_Global_Setting__mdt/fields/Admin_Additional_Location_Platform_Fee__c.field-meta.xml
<CustomField>
    <fullName>Admin_Additional_Location_Platform_Fee__c</fullName>
    <label>Admin Additional Location Platform Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

care/force-app/main/default/objects/CCC_Global_Setting__mdt/fields/Admin_Initial_Platform_Fee__c.field-meta.xml
<CustomField>
    <fullName>Admin_Initial_Platform_Fee__c</fullName>
    <label>Admin Initial Platform Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/Composer_Service__c.object-meta.xml
<CustomObject>
    <description>Identifies the vertical and license level for a service provider</description>
    <label>Composer Service</label>
    <nameField>
        <displayFormat>CCS-{00}</displayFormat>
        <label>Composer Services Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Composer Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Composer_Service__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is this service active and available to be selected in the composer?</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Base_Points__c.field-meta.xml
<CustomField>
    <fullName>Base_Points__c</fullName>
    <description>Base Points to be used in Contract Composer for compensation calculation</description>
    <label>Base Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Bonus_Points__c.field-meta.xml
<CustomField>
    <fullName>Bonus_Points__c</fullName>
    <description>Bonus Points</description>
    <label>Bonus Points</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Extra_Location_Base_Cap__c.field-meta.xml
<CustomField>
    <fullName>Extra_Location_Base_Cap__c</fullName>
    <description>The maximum number of locations that can be added before additional base points are no longer tallied</description>
    <label>Extra Location Base Cap</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Extra_Location_Base_Points__c.field-meta.xml
<CustomField>
    <fullName>Extra_Location_Base_Points__c</fullName>
    <description>Extra base points earned for each location beyond the first</description>
    <label>Extra Location Base Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Extra_Location_Bonus_Points__c.field-meta.xml
<CustomField>
    <fullName>Extra_Location_Bonus_Points__c</fullName>
    <description>Extra Location Bonus Points earned for each location beyond the first</description>
    <label>Extra Location Bonus Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/License_Level__c.field-meta.xml
<CustomField>
    <fullName>License_Level__c</fullName>
    <description>License level of the vertical being serviced, or Category</description>
    <label>License Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Centers</fullName>
            </value>
            <value>
                <fullName>Nanny Agencies</fullName>
            </value>
            <value>
                <fullName>FCCs</fullName>
            </value>
            <value>
                <fullName>Camps</fullName>
            </value>
            <value>
                <fullName>Activities</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Adult Day Care</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Flat Rate</fullName>
            </value>
            <value>
                <fullName>Camps &amp; Activities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Tier_1_Amount__c.field-meta.xml
<CustomField>
    <fullName>Tier_1_Amount__c</fullName>
    <description>Tier 1 Amount</description>
    <label>Tier 1 Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Tuition_Discount_Bonus_Points__c.field-meta.xml
<CustomField>
    <fullName>Tuition_Discount_Bonus_Points__c</fullName>
    <description>The number of bonus points given to the sales rep if a tuition discount is added to the location.</description>
    <label>Tuition Discount Bonus Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <description>Vertical name, or Category Group</description>
    <label>Vertical</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Childcare</fullName>
            </value>
            <value>
                <fullName>Childcare Flat Rate</fullName>
            </value>
            <value>
                <fullName>Recruiting Solutions</fullName>
            </value>
            <value>
                <fullName>Senior Care</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Opportunity_Location_Service__c/Opportunity_Location_Service__c.object-meta.xml
<CustomObject>
    <description>Tracks extra services associated with a location for Contract Composer</description>
    <label>Opportunity Location Service</label>
    <nameField>
        <displayFormat>OLS-{0}</displayFormat>
        <label>Opportunity Location Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Location Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Opportunity_Location_Service__c/fields/Advertising_Spend__c.field-meta.xml
<CustomField>
    <fullName>Advertising_Spend__c</fullName>
    <defaultValue>300</defaultValue>
    <description>Advertising Spend</description>
    <label>Advertising Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Location_Service__c/fields/Composer_Service__c.field-meta.xml
<CustomField>
    <fullName>Composer_Service__c</fullName>
    <description>Composer Service</description>
    <label>Composer Service</label>
    <referenceTo>Composer_Service__c</referenceTo>
    <relationshipLabel>Opportunity Location Services</relationshipLabel>
    <relationshipName>Opportunity_Location_Services</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Location_Service__c/fields/Opportunity_Service_Area__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Service_Area__c</fullName>
    <description>Opportunity Service Area</description>
    <label>Opportunity Service Area</label>
    <referenceTo>Opportunity_Service_Area__c</referenceTo>
    <relationshipLabel>Opportunity Location Services</relationshipLabel>
    <relationshipName>Opportunity_Location_Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Location_Service__c/fields/Pricing_Tier__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Tier__c</fullName>
    <defaultValue>&quot;Tier 1&quot;</defaultValue>
    <description>Pricing Tier</description>
    <label>Pricing Tier</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Pricing_Tier</valueSetName>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/Opportunity_Service_Area__c.object-meta.xml
<CustomObject>
    <description>The collection of postal codes for one service area inside a contract composer opportunity</description>
    <label>Opportunity Service Area</label>
    <nameField>
        <label>Display Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Service Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Advertising_Spend__c.field-meta.xml
<CustomField>
    <fullName>Advertising_Spend__c</fullName>
    <defaultValue>300</defaultValue>
    <description>Amount being spent on advertising</description>
    <label>Advertising Spend</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Master opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Service Areas</relationshipLabel>
    <relationshipName>Opportunity_Service_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Pricing_Tier__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Tier__c</fullName>
    <description>Pricing Tier</description>
    <label>Pricing Tier</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Pricing_Tier</valueSetName>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Tuition_Discount_Text__c.field-meta.xml
<CustomField>
    <fullName>Tuition_Discount_Text__c</fullName>
    <description>Tuition Discount Text for this location</description>
    <label>Tuition Discount Text</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/globalValueSets/Pricing_Tier.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Tier 1</fullName>
        <default>true</default>
        <label>Tier 1</label>
    </customValue>
    <customValue>
        <fullName>Tier 2</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 3</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 4</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 5</fullName>
    </customValue>
    <customValue>
        <fullName>Custom</fullName>
    </customValue>
    <masterLabel>Pricing Tier</masterLabel>
</GlobalValueSet>

care/force-app/main/default/classes/CCCScoreboardController.cls
/****************************************************************************
Created By: Alan Oshry
Email: alan.oshry@revelanttech.com
Created: 09/18/2020
Description: Provides methods to calculate and retrieve Scoreboard Metrics
Changes:

*****************************************************************************/
public without sharing class CCCScoreboardController {
    static private final String CLASS_NAME = 'CCCScoreboardController';

    public class ServerResponse extends CCCServerResponse {
        @AuraEnabled public Decimal advertisingBudgetTotalAmount { get; set; }
        @AuraEnabled public Decimal agreementTotalAmount { get; set; }
        @AuraEnabled public Integer numLocations { get; set; }
        @AuraEnabled public Integer ofLocations { get; set; }
        @AuraEnabled public Decimal initialPlatformFee { get; set; }
        @AuraEnabled public Decimal additionalLocationPlatformFee { get; set; }
        @AuraEnabled public Decimal platformFeeWaived { get; set; }
        @AuraEnabled public Decimal totalPlatformFee { get; set; }

        // SO RecordType fields
        @AuraEnabled public Decimal basePoints { get; set; }
        @AuraEnabled public Decimal bonusPoints { get; set; }

        public ServerResponse() {
            super();
            this.advertisingBudgetTotalAmount = 0.00;
            this.agreementTotalAmount = 0.00;
            this.basePoints = null;
            this.bonusPoints = null;
            this.numLocations = 0;
            this.initialPlatformFee = 0.00;
            this.additionalLocationPlatformFee = 0.00;
            this.platformFeeWaived = 0.00;
            this.totalPlatformFee = 0.00;
        }
    }


    /**
    * @description Calculates and returns Scoreboard Metrics
    * @param recordId (String) - The Id of the Opportunity record that is being viewed
    * @param forcePointsRecalculate (String) - A boolean indicator if Points need to be recalculated
    * @return String (JSON) - Serialized Server Response object
    */
    @AuraEnabled public static ServerResponse getScoreboardData(String recordId, Boolean forcePointsRecalculate) { return getScoreboardData(recordId, forcePointsRecalculate, new CCCUtils.UnitTestFlags()); }

    @TestVisible private static ServerResponse getScoreboardData(String recordId, Boolean forcePointsRecalculate, CCCUtils.UnitTestFlags flags) {
        final String METHOD_NAME = 'getScoreboardData';

        CCCUtils.ServerResponse rUtils;
        CCC_Global_Setting__mdt globalSettings;
        Decimal activeWebAgreementPrice = 0;
        Opportunity opportunityRecord;
        Account accountRecord;
        ServerResponse response = new ServerResponse();
        String recordType;

        try {
            // ContractComposerLog.logDebug(CLASS_NAME, METHOD_NAME, 'Start Method');

            if (flags.throwRootExceptionFail) throw new CCCUtils.CCCException('Throw Root Exception Unit Test.');

            if (recordId == null) throw new CCCException('Empty recordId parameter passed.');

            // Recalculate Points info later, even if the values exist on the Opp
            if (forcePointsRecalculate == null) forcePointsRecalculate = false;

            // Get Opportunity info
            opportunityRecord = (Opportunity) CCCQuery.get('Opportunity').add('RecordType').add('Composer_Service__c').equalsId(recordId).one();

            // Get related account
            accountRecord = (Account) CCCQuery.get('Account').equalsId(opportunityRecord.AccountId).one();

            // Get Locations
            Map<String, sObject> locationRecordMap = CCCQuery.get('Opportunity_Service_Area__c').equals('Opportunity__c', recordId).toMap();
            List<Opportunity_Service_Area__c> locationRecords = (List<Opportunity_Service_Area__c>) locationRecordMap.values();
            //resetLocationRecordsAdSpend(locationRecords);

            // Get Location Service records
            List<Opportunity_Location_Service__c> locationServiceRecords = (List<Opportunity_Location_Service__c>)
                CCCQuery.get('Opportunity_Location_Service__c')
                        .includes('Opportunity_Service_Area__c', locationRecordMap.keySet())
                        .all();

            /*****************************************
            * Begin Number of Opportunity Service Area Calculations
            *****************************************/
            response.numLocations = locationRecords.size();
            response.ofLocations = Integer.valueOf(accountRecord.of_locations__c); // total locations on the account (for display only)

            // Gather Category Group count for Agreement Price, default to 1 for Agreement Price calculations if none have been selected so far.
            // Ad Budget - Sum of the Opportunity Service Area - Advertising Spend
            for (Opportunity_Service_Area__c locationRecord : locationRecords) {
                response.advertisingBudgetTotalAmount += locationRecord.Advertising_Spend__c;
            }

            for (Opportunity_Location_Service__c locationServiceRecord : locationServiceRecords) {
                response.advertisingBudgetTotalAmount += locationServiceRecord.Advertising_Spend__c;
            }


            /*****************************************
            * Begin Platform Fee Calculations
            *****************************************/

            // Get Global Custom Metadata settings
            globalSettings = (CCC_Global_Setting__mdt) CCCQuery.get('CCC_Global_Setting__mdt').equals('DeveloperName', 'Default').one();

            // Fees
            response.initialPlatformFee = globalSettings.Admin_Initial_Platform_Fee__c;
            response.additionalLocationPlatformFee = globalSettings.Admin_Additional_Location_Platform_Fee__c * (response.numLocations > 0 ? response.numLocations -1 : 0);
            response.totalPlatformFee = response.initialPlatformFee + response.additionalLocationPlatformFee;
            response.platformFeeWaived = opportunityRecord.Platform_Fee_Waived__c;

            /*****************************************
            * Begin Agreement Price Calculations
            *****************************************/
            response.agreementTotalAmount = response.advertisingBudgetTotalAmount + response.totalPlatformFee;


            // ********************************/
            // Calculate Discounts
            // ********************************/


            // TBD


            // Agreement Price cannot be less than 0
            if (response.agreementTotalAmount < 0) response.agreementTotalAmount = 0;


            /*****************************************
            * Begin Base Points Calculations
            *****************************************/
            if (CCCUtils.getOpportunityRecordTypeCategory(opportunityRecord, globalSettings) == 'SO') {
                response.basePoints = opportunityRecord.Base_Points__c;
                response.bonusPoints = opportunityRecord.Bonus_Points__c;

                // Base/Bonus points are saved to the Opportunity during "Publish Agreement". Usually we would not recalculate these if they are not null on the Opp
                // however, we would need to recalculate in certain situations, like when Publishing the agreement again
                if (forcePointsRecalculate || (response.basePoints == null && response.bonusPoints == null)) {
                    response.basePoints = calculateBasePoints(opportunityRecord.Composer_Service__r, response.numLocations);
                    response.bonusPoints = calculateBonusPoints(opportunityRecord, globalSettings, locationRecords, locationServiceRecords);
                }
            }

        } catch (Exception e) { return (ServerResponse) CCCUtils.setErrorResponse(CLASS_NAME, METHOD_NAME, e, (CCCServerResponse) response); }

        // ContractComposerLog.logDebug(CLASS_NAME, METHOD_NAME, 'End Method');

        return response;
    }
    
    private static void resetLocationRecordsAdSpend(List<Opportunity_Service_Area__c> locationRecords){
       Opportunity opportunityRecord = [SELECT Composer_Service__r.Tier_1_Amount__c, Composer_Service__r.Vertical__c
                                        FROM Opportunity 
                                        WHERE Id = :locationRecords[0].Opportunity__c];
        
        for(Opportunity_Service_Area__c each : locationRecords){
            each.Advertising_Spend__c = opportunityRecord.Composer_Service__r.Tier_1_Amount__c;
            each.Pricing_Tier__c = 'Tier 1';
        }
            
        update locationRecords;
    }

    private static Integer calculateBasePoints(Composer_Service__c composerServiceRecord, Integer locationCount) {
        Integer basePoints = 0;

        // Add Base Points for Composer Service record related to the Opportunity
        if (composerServiceRecord != null) {
            Integer composerServiceBasePoints = composerServiceRecord.Base_Points__c == null ? 0 : Integer.valueOf(composerServiceRecord.Base_Points__c);
            basePoints += composerServiceBasePoints;

            // Add to base points for each extra location beyond the first location
            if (locationCount > 1) {
                Integer extraLocationCount = locationCount - 1;
                Integer extraLocationBasePoints = composerServiceRecord.Extra_Location_Base_Points__c == null ? 0 : Integer.valueOf(composerServiceRecord.Extra_Location_Base_Points__c);

                // Cap the number of extra locations to Extra_Location_Base_Cap__c
                Integer extraLocationBaseCap = composerServiceRecord.Extra_Location_Base_Cap__c == null ? 0 : Integer.valueOf(composerServiceRecord.Extra_Location_Base_Cap__c);
                if (extraLocationBaseCap > 0 && extraLocationCount > extraLocationBaseCap) {
                    extraLocationCount = extraLocationBaseCap;
                }

                basePoints += (extraLocationCount * extraLocationBasePoints);
            }
        }

        return basePoints;
    }

    private static Integer calculateBonusPoints(Opportunity opportunityRecord, CCC_Global_Setting__mdt globalSettings, List<Opportunity_Service_Area__c> locationRecords, List<Opportunity_Location_Service__c> locationServiceRecords) {
        Integer bonusPoints = 0;

        Composer_Service__c composerServiceRecord = opportunityRecord.Composer_Service__r;

        // Calculate bonus points for each location for the primary service
        // Get starting bonus points from the Composer_Service__c related to the Opportunity
        if (composerServiceRecord != null) {
            Integer composerServiceBonusPoints = composerServiceRecord.Bonus_Points__c == null ? 0 : Integer.valueOf(composerServiceRecord.Bonus_Points__c);
            bonusPoints += composerServiceBonusPoints;


            // Add to bonus points for each extra location beyond the first location
            if (locationRecords != null && locationRecords.size() > 1) {
                Integer extraLocationCount = locationRecords.size() - 1;
                Integer extraLocationBonusPoints = composerServiceRecord.Extra_Location_Bonus_Points__c == null ? 0 : Integer.valueOf(composerServiceRecord.Extra_Location_Bonus_Points__c);

                bonusPoints += (extraLocationCount * extraLocationBonusPoints);
            }

            // Add to bonus points for each location based on the location's pricing tier
            if (locationRecords != null) {
                for (Opportunity_Service_Area__c locationRecord : locationRecords) {
                    String bonusFieldName = locationRecord.Pricing_Tier__c.replace(' ', '_') + '_Bonus_Points__c';
                    Integer bonusPointsValue = Integer.valueOf(composerServiceRecord.get(bonusFieldName));
                    bonusPoints += (bonusPointsValue != null) ? bonusPointsValue : 0;
                }
            
                // Add bonus points for each location that has a tuition discount code if spend > $400
                Integer tuitionDiscountBonusPoints = composerServiceRecord.Tuition_Discount_Bonus_Points__c != null ? Integer.valueOf(composerServiceRecord.Tuition_Discount_Bonus_Points__c) : 4;
                for (Opportunity_Service_Area__c locationRecord : locationRecords) {
                    if (String.isNotBlank(locationRecord.Tuition_Discount_Text__c) && locationRecord.Advertising_Spend__c != null && (locationRecord.Advertising_Spend__c >= 400 || composerServiceRecord.Vertical__c.contains('Flat Rate'))) {
                        bonusPoints += tuitionDiscountBonusPoints;
                    }
                }
            }

            // Add to bonus points for each location Service based on the location Service's pricing tier
            if (locationServiceRecords != null) {
                Map<String, sObject> composerServiceMap = CCCQuery.get('Composer_Service__c').equals('Active__c', true).order('Vertical__c ASC, License_Level__c ASC').toMap();
                for (Opportunity_Location_Service__c locationServiceRecord : locationServiceRecords) {
                    // Get the Composer_Service__c related to the location service record
                    Composer_Service__c compServRec = (Composer_Service__c) composerServiceMap.get(locationServiceRecord.Composer_Service__c);
    
                    String bonusFieldName = locationServiceRecord.Pricing_Tier__c.replace(' ', '_') + '_Bonus_Points__c';
                    Integer bonusPointsValue = Integer.valueOf(compServRec.get(bonusFieldName));
                    bonusPoints += (bonusPointsValue != null) ? bonusPointsValue : 0;
                }
            }

        }

        return bonusPoints;
    }

}