care/force-app/main/default/objects/CCC_Global_Setting__mdt/CCC_Global_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Global Settings used by Contract Composer Lightning Components and related code.</description>
    <label>CCC Global Setting</label>
    <pluralLabel>CCC Global Settings</pluralLabel>
</CustomObject>

care/force-app/main/default/objects/CCC_Global_Setting__mdt/fields/Enable_Additional_Services__c.field-meta.xml
<CustomField>
    <fullName>Enable_Additional_Services__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enables the ability to add Additional Services to a location</description>
    <label>Enable Additional Services</label>
    <type>Checkbox</type>
</CustomField>

care/force-app/main/default/objects/CCC_Location_Base_Point__mdt/CCC_Location_Base_Point__mdt.object-meta.xml
<CustomObject>
    <label>CCC Location Base Point Setting</label>
    <pluralLabel>CCC Location Base Points</pluralLabel>
</CustomObject>

care/force-app/main/default/objects/CCC_Location_Base_Point__mdt/fields/Location_Number__c.field-meta.xml
<CustomField>
    <fullName>Location_Number__c</fullName>
    <label>Location Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

care/force-app/main/default/objects/CCC_MapBox_Setting__mdt/CCC_MapBox_Setting__mdt.object-meta.xml
<CustomObject>
    <label>CCC MapBox Setting</label>
    <pluralLabel>CCC MapBox Settings</pluralLabel>
</CustomObject>

care/force-app/main/default/objects/CCC_MapBox_Setting__mdt/fields/MapBox_API_Key__c.field-meta.xml
<CustomField>
    <fullName>MapBox_API_Key__c</fullName>
    <label>MapBox API Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/Composer_Service__c.object-meta.xml
<CustomObject>
    <description>Identifies the vertical and license level for a service provider</description>
    <label>Composer Service</label>
    <nameField>
        <displayFormat>CCS-{00}</displayFormat>
        <label>Composer Services Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Composer Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Composer_Service__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is this service active and available to be selected in the composer?</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/License_Level__c.field-meta.xml
<CustomField>
    <fullName>License_Level__c</fullName>
    <description>License level of the vertical being serviced, or Category</description>
    <label>License Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Centers</fullName>
            </value>
            <value>
                <fullName>Nanny Agencies</fullName>
            </value>
            <value>
                <fullName>FCCs</fullName>
            </value>
            <value>
                <fullName>Camps</fullName>
            </value>
            <value>
                <fullName>Activities</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Adult Day Care</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Flat Rate</fullName>
            </value>
            <value>
                <fullName>Camps &amp; Activities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Tier_1_Amount__c.field-meta.xml
<CustomField>
    <fullName>Tier_1_Amount__c</fullName>
    <description>Tier 1 Amount</description>
    <label>Tier 1 Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Tier_2_Amount__c.field-meta.xml
<CustomField>
    <fullName>Tier_2_Amount__c</fullName>
    <description>Tier 2 Amount</description>
    <label>Tier 2 Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <description>Vertical name, or Category Group</description>
    <label>Vertical</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Childcare</fullName>
            </value>
            <value>
                <fullName>Childcare Flat Rate</fullName>
            </value>
            <value>
                <fullName>Recruiting Solutions</fullName>
            </value>
            <value>
                <fullName>Senior Care</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Opportunity_Location_Service__c/Opportunity_Location_Service__c.object-meta.xml
<CustomObject>
    <description>Tracks extra services associated with a location for Contract Composer</description>
    <label>Opportunity Location Service</label>
    <nameField>
        <displayFormat>OLS-{0}</displayFormat>
        <label>Opportunity Location Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Location Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Opportunity_Location_Service__c/fields/Advertising_Spend__c.field-meta.xml
<CustomField>
    <fullName>Advertising_Spend__c</fullName>
    <defaultValue>300</defaultValue>
    <description>Advertising Spend</description>
    <label>Advertising Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Location_Service__c/fields/Composer_Service__c.field-meta.xml
<CustomField>
    <fullName>Composer_Service__c</fullName>
    <description>Composer Service</description>
    <label>Composer Service</label>
    <referenceTo>Composer_Service__c</referenceTo>
    <relationshipLabel>Opportunity Location Services</relationshipLabel>
    <relationshipName>Opportunity_Location_Services</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Location_Service__c/fields/Opportunity_Service_Area__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Service_Area__c</fullName>
    <description>Opportunity Service Area</description>
    <label>Opportunity Service Area</label>
    <referenceTo>Opportunity_Service_Area__c</referenceTo>
    <relationshipLabel>Opportunity Location Services</relationshipLabel>
    <relationshipName>Opportunity_Location_Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/Opportunity_Service_Area__c.object-meta.xml
<CustomObject>
    <description>The collection of postal codes for one service area inside a contract composer opportunity</description>
    <label>Opportunity Service Area</label>
    <nameField>
        <label>Display Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Service Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Advertising_Spend__c.field-meta.xml
<CustomField>
    <fullName>Advertising_Spend__c</fullName>
    <defaultValue>300</defaultValue>
    <description>Amount being spent on advertising</description>
    <label>Advertising Spend</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Display City</description>
    <label>Display City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Master opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Service Areas</relationshipLabel>
    <relationshipName>Opportunity_Service_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>Display Postal Code</description>
    <label>Display Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Registered_Entity_City__c.field-meta.xml
<CustomField>
    <fullName>Registered_Entity_City__c</fullName>
    <description>Registered Entity City</description>
    <label>Registered Entity City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Registered_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Registered_Entity_Name__c</fullName>
    <description>Registered Entity Name</description>
    <label>Registered Entity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Registered_Entity_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Registered_Entity_Postal_Code__c</fullName>
    <description>Registered Entity Postal Code</description>
    <label>Registered Entity Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Registered_Entity_State__c.field-meta.xml
<CustomField>
    <fullName>Registered_Entity_State__c</fullName>
    <description>Registered Entity State</description>
    <label>Registered Entity State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Registered_Entity_Street__c.field-meta.xml
<CustomField>
    <fullName>Registered_Entity_Street__c</fullName>
    <description>Registered Entity Street</description>
    <label>Registered Entity Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Display State</description>
    <label>Display State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Display Street</description>
    <label>Display Street</label>
    <type>TextArea</type>
</CustomField>

care/force-app/main/default/globalValueSets/States.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alabama</fullName>
    </customValue>
    <customValue>
        <fullName>Alaska</fullName>
    </customValue>
    <customValue>
        <fullName>Arizona</fullName>
    </customValue>
    <customValue>
        <fullName>Arkansas</fullName>
    </customValue>
    <customValue>
        <fullName>California</fullName>
    </customValue>
    <customValue>
        <fullName>Colorado</fullName>
    </customValue>
    <customValue>
        <fullName>Connecticut</fullName>
    </customValue>
    <customValue>
        <fullName>Delaware</fullName>
    </customValue>
    <customValue>
        <fullName>District of Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>Florida</fullName>
    </customValue>
    <customValue>
        <fullName>Georgia</fullName>
    </customValue>
    <customValue>
        <fullName>Hawaii</fullName>
    </customValue>
    <customValue>
        <fullName>Idaho</fullName>
    </customValue>
    <customValue>
        <fullName>Illinois</fullName>
    </customValue>
    <customValue>
        <fullName>Indiana</fullName>
    </customValue>
    <customValue>
        <fullName>Iowa</fullName>
    </customValue>
    <customValue>
        <fullName>Kansas</fullName>
    </customValue>
    <customValue>
        <fullName>Kentucky</fullName>
    </customValue>
    <customValue>
        <fullName>Louisiana</fullName>
    </customValue>
    <customValue>
        <fullName>Maine</fullName>
    </customValue>
    <customValue>
        <fullName>Maryland</fullName>
    </customValue>
    <customValue>
        <fullName>Massachusetts</fullName>
    </customValue>
    <customValue>
        <fullName>Michigan</fullName>
    </customValue>
    <customValue>
        <fullName>Minnesota</fullName>
    </customValue>
    <customValue>
        <fullName>Mississippi</fullName>
    </customValue>
    <customValue>
        <fullName>Missouri</fullName>
    </customValue>
    <customValue>
        <fullName>Montana</fullName>
    </customValue>
    <customValue>
        <fullName>Nebraska</fullName>
    </customValue>
    <customValue>
        <fullName>Nevada</fullName>
    </customValue>
    <customValue>
        <fullName>New Hampshire</fullName>
    </customValue>
    <masterLabel>States</masterLabel>
</GlobalValueSet>

care/force-app/main/default/classes/CCCLocationController.cls
/****************************************************************************
Created By: John Wrightsman
Email: john.wrightsman@revelanttech.com
Created: 11/06/2020
Description: Apex controller for CCCLocationModule lightning component.
Changes:

*****************************************************************************/
public without sharing class CCCLocationController {
    static private String CLASS_NAME = 'CCCLocationController';

    public class ServerResponse extends CCCServerResponse {
        @AuraEnabled public Opportunity opportunityRecord { get; set; }
        @AuraEnabled public Account accountRecord { get; set; }
        @AuraEnabled public List<Opportunity_Service_Area__c> locationRecords { get; set; }
        @AuraEnabled public Opportunity_Service_Area__c locationRecord { get; set; }
        @AuraEnabled public List<Composer_Service__c> composerServiceRecords { get; set; }
        @AuraEnabled public List<Opportunity_Location_Service__c> locationServiceRecords { get; set; }
        @AuraEnabled public String primaryServiceVerticalName { get; set; }
        @AuraEnabled public String mapBoxApiKey { get; set; }
        @AuraEnabled public Decimal maxLocations { get; set; }
        @AuraEnabled public List<Decimal> coordinates { get; set; }
        @AuraEnabled public List<String> provinceOptions { get; set; }
        @AuraEnabled public Boolean enableAdditionalServices { get; set; }
        @AuraEnabled public List<CCC_State_Abbreviation_Map__mdt> stateAbbreviations { get; set; }

        public ServerResponse() {
            super();
            this.locationRecords = new List<Opportunity_Service_Area__c>();
            this.composerServiceRecords = new List<Composer_Service__c>();
            this.stateAbbreviations = new List<CCC_State_Abbreviation_Map__mdt>();
            this.maxLocations = 9999999;
        }
    }


    /**
    * @description Retrieves the Service Area data for an Opportunity
    * @param opportunityId (String) - The Opportunity record Id
    * @return (ServerResponse)
    */
    @AuraEnabled public static ServerResponse getLocationData(String opportunityId) { return getLocationData(opportunityId, new CCCUtils.UnitTestFlags()); }

    @TestVisible private static ServerResponse getLocationData(String opportunityId, CCCUtils.UnitTestFlags flags) {
        final String METHOD_NAME = 'getLocationData';

        ServerResponse response = new ServerResponse();

        try {

            if (flags.throwRootExceptionFail) throw new CCCUtils.CCCException('Throw Root Exception Unit Test.');

            if (opportunityId == null) throw new CCCException('Empty opportunityId parameter passed.');

            CCC_Global_Setting__mdt globalSettings = (CCC_Global_Setting__mdt) CCCQuery.get('CCC_Global_Setting__mdt').equals('DeveloperName', 'Default').one();

            // Get Opportunity_Service_Area__c records
            response.locationRecords = (List<Opportunity_Service_Area__c>) CCCQuery.get('Opportunity_Service_Area__c').equals('Opportunity__c', opportunityId).all();

            response.opportunityRecord = (Opportunity) CCCQuery.get('Opportunity').field('Composer_Service__r.Vertical__c, Composer_Service__r.License_Level__c').equalsId(opportunityId).one();

            response.accountRecord = (Account) CCCQuery.get('Account').equalsId(response.opportunityRecord.AccountId).one();

            // Get the primary service's vertical name
            response.primaryServiceVerticalName = response.opportunityRecord.Composer_Service__r.Vertical__c;

            // Get all possible active Composer Service records except for the one selected as the primary service on the opportunity
            if (response.opportunityRecord.Composer_Service__c != null) {
                response.composerServiceRecords = (List<Composer_Service__c>)
                    CCCQuery.get('Composer_Service__c')
                            .equals('Active__c', true)
                            .notEquals('Id', response.opportunityRecord.Composer_Service__c)
                            .order('License_Level__c ASC')
                            .all();
            }

            // Get all the Opportunity_Location_Service__c records for the location record ids on this opportunity
            List<String> locationRecordIds = new List<String>();
            for (Opportunity_Service_Area__c locationRecord : response.locationRecords) {
                locationRecordIds.add(locationRecord.Id);
            }
            response.locationServiceRecords = (List<Opportunity_Location_Service__c>) CCCQuery.get('Opportunity_Location_Service__c').includes('Opportunity_Service_Area__c', locationRecordIds).all();

            // Get MapBox api key from custom metadata setting
            response.mapBoxApiKey = ((CCC_MapBox_Setting__mdt) CCCQuery.get('CCC_MapBox_Setting__mdt').one()).MapBox_API_Key__c;

            // Get max locations allowed from custom metadata setting
            response.maxLocations = ((CCC_Location_Base_Point__mdt) CCCQuery.get('CCC_Location_Base_Point__mdt').one()).Location_Number__c;

            // Get all state options
            response.provinceOptions = CCCUtils.getLocationProvinceOptions();

            // Get State Abbreviation metadata
            response.stateAbbreviations = (List<CCC_State_Abbreviation_Map__mdt>) CCCQuery.get('CCC_State_Abbreviation_Map__mdt').all();

            // Get Enable Additional Services metadata setting
            response.enableAdditionalServices = globalSettings.Enable_Additional_Services__c;

        } catch (Exception e) { return (ServerResponse) CCCUtils.setErrorResponse(CLASS_NAME, METHOD_NAME, e, (CCCServerResponse) response); }

        return response;
    }


    /**
    * @description Returns an Opportunity Service Area and it's associated postal codes
    * @param locationRecordId (String) - The Opportunity Service Area record Id
    * @return (ServerResponse)
    */
    @AuraEnabled public static ServerResponse getLocationRecord(String locationRecordId) { return getLocationRecord(locationRecordId, new CCCUtils.UnitTestFlags()); }

    @TestVisible private static ServerResponse getLocationRecord(String locationRecordId, CCCUtils.UnitTestFlags flags) {
        final String METHOD_NAME = 'getLocationRecord';

        ServerResponse response = new ServerResponse();

        try {

            if (flags.throwRootExceptionFail) throw new CCCUtils.CCCException('Throw Root Exception Unit Test.');

            if (locationRecordId == null) throw new CCCException('Empty locationRecordId parameter passed.');

            response.locationRecord = (Opportunity_Service_Area__c) CCCQuery.get('Opportunity_Service_Area__c').equalsId(locationRecordId).one();

        } catch (Exception e) { return (ServerResponse) CCCUtils.setErrorResponse(CLASS_NAME, METHOD_NAME, e, (CCCServerResponse) response); }

        return response;
    }


    /**
    * @description Saves an Opportunity_Service_Area__c and optionally copies the Service Specific Fields to all other locations
    *              on the Opportunity
    * @param locationRecord (Opportunity_Service_Area__c) - The Opportunity Service Area wrapper record
    * @param copyServiceSpecificFields (Boolean) - Indicates to copy this the Service Specific fields to all the other locations on the Opportunity
    * @return (ServerResponse)
    */
    @AuraEnabled public static ServerResponse saveLocationRecord(Opportunity_Service_Area__c locationRecord, Boolean copyServiceSpecificFields, List<String> selectedComposerServiceRecordIds) { return saveLocationRecord(locationRecord, copyServiceSpecificFields, selectedComposerServiceRecordIds, new CCCUtils.UnitTestFlags()); }

    @TestVisible private static ServerResponse saveLocationRecord(Opportunity_Service_Area__c locationRecord, Boolean copyServiceSpecificFields, List<String> selectedComposerServiceRecordIds, CCCUtils.UnitTestFlags flags) {
        final String METHOD_NAME = 'saveLocationRecord';
        ServerResponse response = new ServerResponse();

        try {

            if (flags.throwRootExceptionFail) throw new CCCUtils.CCCException('Throw Root Exception Unit Test.');

            if (locationRecord == null) throw new CCCException('Empty locationRecord parameter passed.');
            if (copyServiceSpecificFields == null) throw new CCCException('Empty copyServiceSpecificFields parameter passed.');

            // Populate the Registered Entity fields from the name/address fields
            // if this is a new location
            if (locationRecord.Id == null) {

                // Populate the Registered Entity fields from the name/address fields
                locationRecord.Registered_Entity_Name__c = locationRecord.Name;
                locationRecord.Registered_Entity_City__c = locationRecord.City__c;
                locationRecord.Registered_Entity_State__c = locationRecord.State__c;
                locationRecord.Registered_Entity_Street__c = locationRecord.Street__c;
                locationRecord.Registered_Entity_Postal_Code__c = locationRecord.Postal_Code__c;

                // Update the location's default advertising spend based on the current composer service on the opportunity
                Opportunity opportunityRecord = [SELECT Composer_Service__r.Tier_1_Amount__c, Composer_Service__r.Vertical__c,
                                                        Composer_Service__r.Tier_2_Amount__c
                                                 FROM Opportunity 
                                                 WHERE Id = :locationRecord.Opportunity__c];
                
                locationRecord.Advertising_Spend__c =  opportunityRecord.Composer_Service__r.Tier_1_Amount__c;
                locationRecord.Pricing_Tier__c = 'Tier 1';

                if(opportunityRecord.Composer_Service__r.Vertical__c.toLowerCase().contains('flat rate')){
                    locationRecord.Advertising_Spend__c =  opportunityRecord.Composer_Service__r.Tier_2_Amount__c;
                    locationRecord.Pricing_Tier__c = 'Tier 2';
                }
            }

            upsert locationRecord;

            if (copyServiceSpecificFields) {
                copyServiceSpecificFields(locationRecord);
            }

            if (selectedComposerServiceRecordIds != null) {
                updateLocationServices(locationRecord.Id, selectedComposerServiceRecordIds);
            }

        } catch (Exception e) { return (ServerResponse) CCCUtils.setErrorResponse(CLASS_NAME, METHOD_NAME, e, (CCCServerResponse) response); }

        return response;
    }


    /**
    * @description Deletes an Opportunity_Service_Area__c record
    * @param locationRecordId (String) - The Opportunity Service Area Id
    * @return (ServerResponse)
    */
    @AuraEnabled public static ServerResponse deleteLocationRecord(String locationRecordId) { return deleteLocationRecord(locationRecordId, new CCCUtils.UnitTestFlags()); }

    @TestVisible private static ServerResponse deleteLocationRecord(String locationRecordId, CCCUtils.UnitTestFlags flags) {
        final String METHOD_NAME = 'deleteLocationRecord';
        ServerResponse response = new ServerResponse();

        try {

            if (flags.throwRootExceptionFail) throw new CCCUtils.CCCException('Throw Root Exception Unit Test.');

            if (locationRecordId == null) throw new CCCException('Empty locationRecordId parameter passed.');

            delete new Opportunity_Service_Area__c(Id = locationRecordId);

        } catch (Exception e) { return (ServerResponse) CCCUtils.setErrorResponse(CLASS_NAME, METHOD_NAME, e, (CCCServerResponse) response); }

        return response;
    }


    @TestVisible private static void updateLocationServices(String locationRecordId, List<String> selectedComposerServiceRecordIds) {
        // Delete any Opportunity_Location_Service__c records related to the location if the Composer_Service__c
        // is not in the selectedComposerServiceRecordIds list
        List<Opportunity_Location_Service__c> locationServiceRecordsToDelete = (List<Opportunity_Location_Service__c>)
            CCCQuery.get('Opportunity_Location_Service__c')
                    .equals('Opportunity_Service_Area__c', locationRecordId)
                    .notIncludes('Composer_Service__c', selectedComposerServiceRecordIds)
                    .all();

        delete locationServiceRecordsToDelete;



        // Insert a new Opportunity_Location_Service__c for any new composer service ids selected
        List<Opportunity_Location_Service__c> newLocationServiceRecords = new List<Opportunity_Location_Service__c>();

        Map<String, sObject> locationServiceRecordsMap =
            CCCQuery.get('Opportunity_Location_Service__c')
                    .equals('Opportunity_Service_Area__c', locationRecordId)
                    .toMap('Composer_Service__c');

        for (String composerServiceRecordId : selectedComposerServiceRecordIds) {
            if (!locationServiceRecordsMap.containsKey(composerServiceRecordId)) {
                newLocationServiceRecords.add(new Opportunity_Location_Service__c(
                    Opportunity_Service_Area__c = locationRecordId,
                    Composer_Service__c = composerServiceRecordId
                ));
            }
        }

        insert newLocationServiceRecords;

    }


    /**
    * @description Finds the geolocation coordinates for an address
    * @param search (String) - The address search string to pass to the MapBox geocoding API
    * @return (ServerResponse)
    */
    @AuraEnabled public static ServerResponse findGeolocation(String search) { return findGeolocation(search, new CCCUtils.UnitTestFlags()); }

    @TestVisible private static ServerResponse findGeolocation(String search, CCCUtils.UnitTestFlags flags) {
        final String METHOD_NAME = 'findGeolocation';

        ServerResponse response = new ServerResponse();

        try {

            if (flags.throwRootExceptionFail) throw new CCCUtils.CCCException('Throw Root Exception Unit Test.');

            if (search == null) throw new CCCException('Empty search parameter passed.');

            CCCAPIRespMapBoxGeocoding.ServerResponse apiResponse = CCCCalloutMaster.getMapBoxGeocodingResults(search);
            if (apiResponse.features != null && apiResponse.features.size() > 0) {
                List<Decimal> coordinates;

                // Find first 'Point' feature and use its coordinates
                for (CCCAPIRespMapBoxGeocoding.FeatureData feature : apiResponse.features) {
                    if (feature.geometry != null) {
                        if (feature.geometry.type.equalsIgnoreCase('Point')) {
                            coordinates = feature.geometry.coordinates;
                            break;
                        }
                    }
                }

                if (coordinates != null) {
                    response.coordinates = coordinates;
                }
            }

            if (response.coordinates == null) throw new CCCException('Unable to find coordinates for this location\'s address');

        } catch (Exception e) { return (ServerResponse) CCCUtils.setErrorResponse(CLASS_NAME, METHOD_NAME, e, (CCCServerResponse) response); }

        return response;
    }


    /**
    * @description Copies the values in the Service Specific Fields from one location to all other locations on the related Opportunity
    * @param locationRecord (Opportunity_Service_Area__c) - The Opportunity Service Area
    * @return void
    */
    @TestVisible private static void copyServiceSpecificFields(Opportunity_Service_Area__c locationRecord) { copyServiceSpecificFields(locationRecord, new CCCUtils.UnitTestFlags()); }

    @TestVisible private static void copyServiceSpecificFields(Opportunity_Service_Area__c locationRecord, CCCUtils.UnitTestFlags flags) {
        final String METHOD_NAME = 'copyServiceSpecificFields';

        if (flags.throwRootExceptionFail) throw new CCCUtils.CCCException('Throw Root Exception Unit Test.');

        if (locationRecord == null) throw new CCCException('Empty locationRecord parameter passed.');

        // Get original location record, all location records
        locationRecord = (Opportunity_Service_Area__c) CCCQuery.get('Opportunity_Service_Area__c').equalsId(locationRecord.Id).one();
        String opportunityId = locationRecord.Opportunity__c;
        List<Opportunity_Service_Area__c> locationRecords = (List<Opportunity_Service_Area__c>) CCCQuery.get('Opportunity_Service_Area__c').equals('Opportunity__c', opportunityId).all();

        // Get the Opportunity so we can get the related Composer Service which has the service specific fields
        Opportunity oppty = (Opportunity) CCCQuery.get('Opportunity').equalsId(opportunityId).one();

        // Build list of Service Specific field names
        List<String> fields = new List<String>();
        if (oppty.Composer_Service__c != null) {
            // Get the Service Specific fields from the Composer Service
            Composer_Service__c cs = (Composer_Service__c) CCCQuery.get('Composer_Service__c').equalsId(oppty.Composer_Service__c).one();
            if (cs.Service_Specific_Fields__c != null) {
                for (String field : cs.Service_Specific_Fields__c.split(',')) {
                    fields.add(field.trim());
                }
            }
        }

        // Loop through location records and copy service specific
        // field values from main location
        for (Opportunity_Service_Area__c loc : locationRecords) {
            if (loc.Id != locationRecord.Id) {
                for (String field : fields) {
                    loc.put(field, locationRecord.get(field));
                }
            }
        }

        update locationRecords;
    }

}