care/force-app/main/default/objects/Privacy_Audit_Log__c/Privacy_Audit_Log__c.object-meta.xml
<CustomObject>
    <label>Privacy Audit Log</label>
    <nameField>
        <displayFormat>PAL-{0000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Privacy Audit Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Privacy_Audit_Log__c/fields/CSR_Email__c.field-meta.xml
<CustomField>
    <fullName>CSR_Email__c</fullName>
    <inlineHelpText>The email address of the CSR Rep who submitted the CSR Web Form.</inlineHelpText>
    <label>CSR Email</label>
    <type>Email</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Audit_Log__c/fields/CSR_Name__c.field-meta.xml
<CustomField>
    <fullName>CSR_Name__c</fullName>
    <inlineHelpText>The name of the CSR Rep who submitted the CSR Web Form.</inlineHelpText>
    <label>CSR Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Audit_Log__c/fields/Fail_Decline_Reason__c.field-meta.xml
<CustomField>
    <fullName>Fail_Decline_Reason__c</fullName>
    <label>Fail/Decline Reason</label>
    <type>TextArea</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Audit_Log__c/fields/Fulfillment_Date__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Date__c</fullName>
    <label>Fulfillment Date</label>
    <type>Date</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Audit_Log__c/fields/Fulfillment_Date_Rationale__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Date_Rationale__c</fullName>
    <inlineHelpText>The field reflect which use case was used to determine the Fulfillment Date.  It will be used to send different notifications to users.</inlineHelpText>
    <label>Fulfillment Date Rationale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Privacy_Request_Fulfillment_Date_Rationa</valueSetName>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Privacy_Audit_Log__c/fields/PR_Name__c.field-meta.xml
<CustomField>
    <fullName>PR_Name__c</fullName>
    <externalId>true</externalId>
    <label>PR Name</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

care/force-app/main/default/objects/Privacy_Audit_Log__c/fields/Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Date__c</fullName>
    <label>Request Date</label>
    <type>DateTime</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Audit_Log__c/fields/Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Privacy_Request_Status</valueSetName>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Privacy_Audit_Log__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Privacy_Request_Types</valueSetName>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Privacy_Audit_Log__c/fields/Requestor_Email__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Email__c</fullName>
    <label>Requestor Email</label>
    <type>Email</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Audit_Log__c/fields/Requestor_Name__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Name__c</fullName>
    <label>Requestor Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Audit_Log__c/fields/Requestor_Relationship_to_Member__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Relationship_to_Member__c</fullName>
    <label>Requestor Relationship to Member</label>
    <type>TextArea</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Audit_Log__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Privacy_Request_Source_Systems</valueSetName>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Privacy_Audit_Log__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State/Province</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Audit_Log__c/fields/Universal_Member_Id__c.field-meta.xml
<CustomField>
    <fullName>Universal_Member_Id__c</fullName>
    <description>The Member Id of the User.  This field is intended to handle member ids from the US &amp; International Platforms.</description>
    <label>Universal Member Id</label>
    <length>23</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/Privacy_Request__c.object-meta.xml
<CustomObject>
    <description>This object tracks requests</description>
    <label>Privacy Request</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Privacy Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Privacy Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Privacy_Request__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <inlineHelpText>The Address of the member for whom the request pertains to.</inlineHelpText>
    <label>Address</label>
    <type>TextArea</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/CSR_Email__c.field-meta.xml
<CustomField>
    <fullName>CSR_Email__c</fullName>
    <inlineHelpText>The email address of the CSR Rep who submitted the CSR Web Form.</inlineHelpText>
    <label>CSR Email</label>
    <type>Email</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/CSR_Name__c.field-meta.xml
<CustomField>
    <fullName>CSR_Name__c</fullName>
    <inlineHelpText>The name of the CSR Rep who submitted the CSR Web Form.</inlineHelpText>
    <label>CSR Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <inlineHelpText>The Email of the member to whom the request pertains to.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Fail_Decline_Reason__c.field-meta.xml
<CustomField>
    <fullName>Fail_Decline_Reason__c</fullName>
    <inlineHelpText>The field where we can specify more context about a Request Status.</inlineHelpText>
    <label>Fail/Decline Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Fulfillment_Date__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Date__c</fullName>
    <inlineHelpText>The date when the platforms expect to fulfill the request. Used to coordinate among the platforms &amp; either platform may change this value. When the request is fulfilled, Salesforce will automatically set this field to the date to the current date.</inlineHelpText>
    <label>Fulfillment Date</label>
    <type>Date</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Fulfillment_Date_Rationale__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Date_Rationale__c</fullName>
    <inlineHelpText>The field reflect which use case was used to determine the Fulfillment Date.  It will be used to send different notifications to users.</inlineHelpText>
    <label>Fulfillment Date Rationale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Privacy_Request_Fulfillment_Date_Rationa</valueSetName>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <inlineHelpText>The name of the member the request pertains to.</inlineHelpText>
    <label>Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Date__c</fullName>
    <inlineHelpText>The Date/Time when the member originally made the request.</inlineHelpText>
    <label>Request Date</label>
    <type>DateTime</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Privacy_Request_Status</valueSetName>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Privacy_Request_Types</valueSetName>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Requestor_Email__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Email__c</fullName>
    <inlineHelpText>This field is used if the request is being made by someone other than the member.</inlineHelpText>
    <label>Requestor Email</label>
    <type>Email</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Requestor_Name__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Name__c</fullName>
    <inlineHelpText>This field is used if the request is being made by someone other than the member.</inlineHelpText>
    <label>Requestor Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Requestor_Relationship_to_Member__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Relationship_to_Member__c</fullName>
    <inlineHelpText>This field is used if the request is being made by someone other than the member.</inlineHelpText>
    <label>Requestor Relationship to Member</label>
    <type>TextArea</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Privacy_Request_Source_Systems</valueSetName>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State/Province</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Universal_Member_Id__c.field-meta.xml
<CustomField>
    <fullName>Universal_Member_Id__c</fullName>
    <inlineHelpText>The Member Id of the User.  This field is intended to handle member ids from the US &amp; International Platforms.</inlineHelpText>
    <label>Universal Member Id</label>
    <length>23</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/globalValueSets/Privacy_Request_Fulfillment_Date_Rationa.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Downgrading Premium</fullName>
    </customValue>
    <customValue>
        <fullName>Recently Cleared Safety Case</fullName>
    </customValue>
    <description>The field reflect which use case was used to determine the Fulfillment Date.  It will be used to send different notifications to users.</description>
    <masterLabel>Privacy Request Fulfillment Date Rationa</masterLabel>
</GlobalValueSet>

care/force-app/main/default/globalValueSets/Privacy_Request_Source_Systems.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Intl Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Galore</fullName>
    </customValue>
    <customValue>
        <fullName>HomePay</fullName>
    </customValue>
    <masterLabel>Privacy Request Source Systems</masterLabel>
</GlobalValueSet>

care/force-app/main/default/globalValueSets/Privacy_Request_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Requested</fullName>
        <default>true</default>
        <label>Requested</label>
    </customValue>
    <customValue>
        <fullName>Completed - Failed - Verification Failure</fullName>
    </customValue>
    <customValue>
        <fullName>Completed - Declined - Remote Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Completed - Declined - Salesforce Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Request Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Pending - Soft Decline - Salesforce Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Queued - Remote Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Queued - Salesforce Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Retrying - Remote Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Completed - Success</fullName>
    </customValue>
    <customValue>
        <fullName>Safety/Fraud Case</fullName>
    </customValue>
    <customValue>
        <fullName>Error - Salesforce Platform</fullName>
    </customValue>
    <masterLabel>Privacy Request Status</masterLabel>
</GlobalValueSet>

care/force-app/main/default/globalValueSets/Privacy_Request_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Data Categories</fullName>
    </customValue>
    <customValue>
        <fullName>Access Data</fullName>
    </customValue>
    <customValue>
        <fullName>Delete Data</fullName>
    </customValue>
    <masterLabel>Privacy Request Types</masterLabel>
</GlobalValueSet>

care/force-app/main/default/classes/PrivacyAuditLogController.cls
public class PrivacyAuditLogController {

    static public void addLogs(List<Privacy_Request__c> requests){
		List<Privacy_Audit_Log__c> logsToInsert = new List<Privacy_Audit_Log__c>();

        for (Privacy_Request__c request : requests){
            Privacy_Audit_Log__c log = new Privacy_Audit_Log__c();
            log.PR_Name__c = request.Id;
            log.Name__c = request.Name__c;
            log.Email__c = request.Email__c;
            log.Request_Date__c	= request.Request_Date__c;
            log.Fulfillment_Date__c	= request.Fulfillment_Date__c;
            log.State_Province__c = request.State_Province__c;
            log.Country__c = request.Country__c;
            log.Request_Status__c = request.Request_Status__c;
            log.Fail_Decline_Reason__c = request.Fail_Decline_Reason__c;
            log.Request_Type__c	= request.Request_Type__c;
            log.Source_System__c = request.Source_System__c;
            log.Requestor_Name__c = request.Requestor_Name__c;
            log.Requestor_Email__c = request.Requestor_Email__c;
            log.Requestor_Relationship_to_Member__c = request.Requestor_Relationship_to_Member__c;
			// Update 2020-01-14: Add Phase 2 fields
            log.CSR_Name__c = request.CSR_Name__c;
			log.CSR_Email__c = request.CSR_Email__c;
            log.Fulfillment_Date_Rationale__c = request.Fulfillment_Date_Rationale__c;
            log.Universal_Member_Id__c=request.Universal_Member_Id__c;
            logsToInsert.add(log);
        }
        insert logsToInsert;
        
    }

    static public void updateLogs(List<Privacy_Request__c> requests, List<Privacy_Request__c> oldRequests, Map<id,Privacy_Request__c> newMap,Map<id,Privacy_Request__c> oldMap){
		List<Privacy_Audit_Log__c> logsToUpdate = new List<Privacy_Audit_Log__c>();

        for (Privacy_Request__c request : requests){
            Privacy_Audit_Log__c log = new Privacy_Audit_Log__c();
            log.PR_Name__c = request.id;
            if (request.Name__c != oldMap.get(request.id).Name__c) log.Name__c = request.Name__c;
            if (request.Email__c != oldMap.get(request.id).Email__c) log.Email__c = request.Email__c;
            if (request.Request_Date__c != oldMap.get(request.id).Request_Date__c) log.Request_Date__c = request.Request_Date__c;
            if (request.Request_Status__c != oldMap.get(request.id).Request_Status__c) log.Request_Status__c = request.Request_Status__c;
            if (request.Fulfillment_Date__c != oldMap.get(request.id).Fulfillment_Date__c) log.Fulfillment_Date__c = request.Fulfillment_Date__c;
            if (request.State_Province__c != oldMap.get(request.id).State_Province__c) log.State_Province__c = request.State_Province__c;
            if (request.Country__c != oldMap.get(request.id).Country__c) log.Country__c = request.Country__c;
            if (request.Fail_Decline_Reason__c != oldMap.get(request.id).Fail_Decline_Reason__c) log.Fail_Decline_Reason__c = request.Fail_Decline_Reason__c;
            if (request.Request_Type__c != oldMap.get(request.id).Request_Type__c) log.Request_Type__c = request.Request_Type__c;
            if (request.Source_System__c != oldMap.get(request.id).Source_System__c) log.Source_System__c = request.Source_System__c;
            if (request.Requestor_Name__c != oldMap.get(request.id).Requestor_Name__c) log.Requestor_Name__c = request.Requestor_Name__c;
            if (request.Requestor_Email__c != oldMap.get(request.id).Requestor_Email__c) log.Requestor_Email__c = request.Requestor_Email__c;
            if (request.Requestor_Relationship_to_Member__c != oldMap.get(request.id).Requestor_Relationship_to_Member__c) log.Requestor_Relationship_to_Member__c = request.Requestor_Relationship_to_Member__c;
			// Update 2020-01-14: Add Phase 2 fields
            if (request.CSR_Name__c != oldMap.get(request.id).CSR_Name__c) log.CSR_Name__c = request.CSR_Name__c;
            if (request.CSR_Email__c != oldMap.get(request.id).CSR_Email__c) log.CSR_Email__c = request.CSR_Email__c;
            if (request.Fulfillment_Date_Rationale__c != oldMap.get(request.id).Fulfillment_Date_Rationale__c) log.Fulfillment_Date_Rationale__c = request.Fulfillment_Date_Rationale__c;
           // if (request.Universal_Member_Id__c != oldMap.get(request.id).Universal_Member_Id__c) log.Universal_Member_Id__c = request.Universal_Member_Id__c;
            if (request.Universal_Member_Id__c != '') log.Universal_Member_Id__c = request.Universal_Member_Id__c;
            logsToUpdate.add(log);
        }
        Database.upsert(logsToUpdate, Privacy_Audit_Log__c.Fields.PR_Name__c);
        
    }

    
 /*
  * This code handles asynchronous triggers
  * 
    static public void handleChangeEvent(List<Privacy_Request__ChangeEvent> requests){
		List<Privacy_Request__ChangeEvent> logsToInsert = new List<Privacy_Request__ChangeEvent>();
		List<Privacy_Request__ChangeEvent> logsToUpdate = new List<Privacy_Request__ChangeEvent>();

        for (Privacy_Request__ChangeEvent request : requests){
	        EventBus.ChangeEventHeader header = request.ChangeEventHeader;
            if (header.changetype == 'CREATE'){
                logsToInsert.add(request);
            } else if (header.changetype == 'UPDATE'){
                logsToUpdate.add(request);
            }
        }
		addLogs(logsToInsert);
        updateLogs(logsToUpdate);
        
    }

    static public void addLogs(List<Privacy_Request__ChangeEvent> requests){
		List<Privacy_Audit_Log__c> logsToInsert = new List<Privacy_Audit_Log__c>();

        for (Privacy_Request__ChangeEvent request : requests){
            EventBus.ChangeEventHeader header = request.ChangeEventHeader;


            Privacy_Audit_Log__c log = new Privacy_Audit_Log__c();
            log.PR_Name__c = header.recordids[0];
            log.Name__c = request.Name__c;
            log.Email__c = request.Email__c;
            log.Request_Date__c	= request.Request_Date__c;
            log.Fulfillment_Date__c	= request.Fulfillment_Date__c;
            log.Address__c = request.Address__c;
            log.Request_Status__c = request.Request_Status__c;
            log.Fail_Decline_Reason__c = request.Fail_Decline_Reason__c;
            log.Request_Type__c	= request.Request_Type__c;
            log.Source_System__c = request.Source_System__c;
            log.Requestor_Name__c = request.Requestor_Name__c;
            log.Requestor_Email__c = request.Requestor_Email__c;
            log.Requestor_Relationship_to_Member__c = request.Requestor_Relationship_to_Member__c;
			logsToInsert.add(log);
        }
        insert logsToInsert;
    }
    
    static public void updateLogs(List<Privacy_Request__ChangeEvent> requests){
		List<Privacy_Audit_Log__c> logsToUpdate = new List<Privacy_Audit_Log__c>();

        for (Privacy_Request__ChangeEvent request : requests){
            Privacy_Audit_Log__c log = new Privacy_Audit_Log__c();

            EventBus.ChangeEventHeader header = request.ChangeEventHeader;
            log.PR_Name__c = header.recordids[0];
            for (String field : header.changedfields){
                switch on field {
                    when 'Name__c' {log.Name__c = (String) request.get(field); }	
                    when 'Email__c' {log.Email__c = (String) request.get(field); }	
                    when 'Request_Date__c' {log.Request_Date__c = (DateTime) request.get(field); }	
                    when 'Request_Status__c' {log.Request_Status__c = (String) request.get(field); }	
                    when 'Fulfillment_Date__c' {log.Fulfillment_Date__c = (Date) request.get(field); }	
                    when 'Address__c' {log.Address__c = (String) request.get(field); }	
                    when 'Fail_Decline_Reason__c' {log.Fail_Decline_Reason__c = (String) request.get(field); }	
                    when 'Source_System__c' {log.Source_System__c = (String) request.get(field); }	
                    when 'Requestor_Name__c' {log.Requestor_Name__c = (String) request.get(field); }	
                    when 'Requestor_Email__c' {log.Requestor_Email__c = (String) request.get(field); }	
                    when 'Requestor_Relationship_to_Member__c' {log.Requestor_Relationship_to_Member__c = (String) request.get(field); }	
                }
                
            }
            logsToUpdate.add(log);
        }
        Database.upsert(logsToUpdate, Privacy_Audit_Log__c.Fields.PR_Name__c);
        
    }
*/

}