care/force-app/main/default/objects/Platform_Servicing_Setting__mdt/Platform_Servicing_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Configuration to store token across the org</description>
    <label>Platform Servicing Setting</label>
    <pluralLabel>Platform Servicing Setting</pluralLabel>
</CustomObject>

care/force-app/main/default/objects/Platform_Servicing_Setting__mdt/fields/Is_Staging__c.field-meta.xml
<CustomField>
    <fullName>Is_Staging__c</fullName>
    <defaultValue>false</defaultValue>
    <description>if checked the configuration runs for staging</description>
    <label>Is Staging</label>
    <type>Checkbox</type>
</CustomField>

care/force-app/main/default/objects/Platform_Servicing_Setting__mdt/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
                <default>true</default>
                <label>US</label>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Platform_Servicing_Setting__mdt/fields/Production_Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Production_Access_Token__c</fullName>
    <label>Production Access Token</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Platform_Servicing_Setting__mdt/fields/Production_API_Key__c.field-meta.xml
<CustomField>
    <fullName>Production_API_Key__c</fullName>
    <label>Production API Key</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Platform_Servicing_Setting__mdt/fields/Staging_Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Staging_Access_Token__c</fullName>
    <label>Staging Access Token</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Platform_Servicing_Setting__mdt/fields/Staging_API_Key__c.field-meta.xml
<CustomField>
    <fullName>Staging_API_Key__c</fullName>
    <label>Staging API Key</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/classes/PlatformServicing_Setting.cls
/*
** _________________________________________________________________________________
** Created by:    Mohammed Ashwaq
** Developer:     Mohammed Ashwaq[mohammed.ashwaq@care.com]
** Modified Date:  30.10.2020
** =================================================================================
** Description: 
**             Utility Class which access Sterling Service integration data
** _______________________________________________________________________________
*/
public class PlatformServicing_Setting {
    
    private static List<Platform_Servicing_Setting__mdt> platformservices = [SELECT Platform__c,
                                                                              Staging_API_Key__c,
                                                                              Production_Access_Token__c,
                                                                              Production_API_Key__c,
                                                                              Staging_Access_Token__c,
																			  Is_Staging__c, Description__c
                                                                  			  FROM Platform_Servicing_Setting__mdt]; 

	
    public static Platform_Servicing_Setting__mdt  getSetting(String Platform){
        for (Platform_Servicing_Setting__mdt anyPlatform : platformservices){
            if (anyPlatform.Platform__c == Platform) return anyPlatform;
        }
        return null;
    }
    
    public static String getProductionAccessToken(String Platform){
        String ProductionAccessToken = (getSetting(Platform).Production_Access_Token__c != null) ? getSetting(Platform).Production_Access_Token__c : '';
        return ProductionAccessToken;
    }

    public static String getStagingAccessToken(String Platform){
        String StagingAccessToken = (getSetting(Platform).Staging_Access_Token__c != null) ? getSetting(Platform).Staging_Access_Token__c : '';
        return StagingAccessToken;
    }
    
    public static String getProductionAPIKey(String Platform){
        String ProductionAPIKey = (getSetting(Platform).Production_API_Key__c != null) ? getSetting(Platform).Production_API_Key__c : '';
        return ProductionAPIKey;
    }
    
    public static String getStagingAPIKey(String Platform){
        String StagingAPIKey = (getSetting(Platform).Staging_API_Key__c != null) ? getSetting(Platform).Staging_API_Key__c : '';
        return StagingAPIKey;
    }
        
    public static Boolean isStagingEnabled(String Platform){
        Boolean isStaging = getSetting(Platform).Is_Staging__c;
        return isStaging;
    }
    
}