care/force-app/main/default/objects/GDPR_Settings__mdt/GDPR_Settings__mdt.object-meta.xml
<CustomObject>
    <label>GDPR Settings</label>
    <pluralLabel>GDPR Settings</pluralLabel>
</CustomObject>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Data_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Data_Batch_Size__c</fullName>
    <description>This specifies the batch size of RTBF/Retention Data</description>
    <inlineHelpText>Enter RTBF/Retention Data Batch Size</inlineHelpText>
    <label>Data Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Feed_Data_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Feed_Data_Batch_Size__c</fullName>
    <description>This specifies the batch size of RTBF/Retention Feed Data</description>
    <inlineHelpText>Enter RTBF/Retention Feed Data Batch Size</inlineHelpText>
    <label>Feed Data Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/History_Data_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>History_Data_Batch_Size__c</fullName>
    <description>This specifies the batch size of RTBF/Retention History Data</description>
    <inlineHelpText>Enter RTBF/Retention History Data Batch Size</inlineHelpText>
    <label>History Data Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Override_Account_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Override_Account_Record_Type__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean flag, upon checking this, Skips Account Record Type validation while anonymyzing account.</description>
    <inlineHelpText>Check to override Account Record Type validation.</inlineHelpText>
    <label>Override Account Record Type</label>
    <type>Checkbox</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Override_Employer_Program__c.field-meta.xml
<CustomField>
    <fullName>Override_Employer_Program__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean flag, upon checking this, Skips Employer Program validation while anonymizing account.</description>
    <inlineHelpText>Check to override Employer Program validation.</inlineHelpText>
    <label>Override Employer Program</label>
    <type>Checkbox</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Override_Premium__c.field-meta.xml
<CustomField>
    <fullName>Override_Premium__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean flag, upon checking this, Skips Premium validation while anonymyzing account.</description>
    <inlineHelpText>Check to override premium validation.</inlineHelpText>
    <label>Override Premium</label>
    <type>Checkbox</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Override_Safety_Case__c.field-meta.xml
<CustomField>
    <fullName>Override_Safety_Case__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean flag, upon checking this, Skips Safety Case validation while anonymyzing account.</description>
    <inlineHelpText>Check to override Safety Case validation.</inlineHelpText>
    <label>Override Safety Case</label>
    <type>Checkbox</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/RTBF_Retention__c.field-meta.xml
<CustomField>
    <fullName>RTBF_Retention__c</fullName>
    <description>Provide option to choose the process type is RTBF or Retention</description>
    <inlineHelpText>Choose RTBF or Retention process and provide the corresponding validation on/off checks  like Safety Case/Premium/Employer Program/Record Type.</inlineHelpText>
    <label>RTBF/Retention</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RTBF</fullName>
                <default>true</default>
                <label>RTBF</label>
            </value>
            <value>
                <fullName>Retention</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Schedule_Mode__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Mode__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked when GDPR in Schedule run mode</description>
    <inlineHelpText>Check to GDPR in Schedule Mode</inlineHelpText>
    <label>Schedule Mode</label>
    <type>Checkbox</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Status_To_Process__c.field-meta.xml
<CustomField>
    <fullName>Status_To_Process__c</fullName>
    <description>Mention GDPR Status to process. Ex:- Use &apos;Test&apos; for testing phase</description>
    <inlineHelpText>Mention GDPR Status to process. Ex:- Use &apos;Test&apos; for testing phase</inlineHelpText>
    <label>Status To Process</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Time_To_Schedule_SSMMHH__c.field-meta.xml
<CustomField>
    <fullName>Time_To_Schedule_SSMMHH__c</fullName>
    <description>Enter GDPR schedule time in SSMMHH format</description>
    <inlineHelpText>Enter GDPR schedule time in SSMMHH format</inlineHelpText>
    <label>Time To Schedule(SSMMHH)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/classes/BatchGDPRFeedProcess.cls
global class BatchGDPRFeedProcess implements Schedulable, Database.Batchable<SObject>,Database.stateful {
    global String query;
    public boolean isTestingContext=false;
    String runState;
    List<id> caseList;
    GDPR_Settings__mdt rtbfSettings;
    global BatchGDPRFeedProcess() {
        //this.isTestingContext=isTestingContext;
    }
    global BatchGDPRFeedProcess(boolean isTestingContext,List<id> caseList) {
        this.caseList=caseList;
        this.isTestingContext=isTestingContext;
        rtbfSettings=[select id,DeveloperName,MasterLabel,Data_Batch_Size__c,Feed_Data_Batch_Size__c,History_Data_Batch_Size__c,Override_Account_Record_Type__c,Override_Employer_Program__c,Override_Premium__c,Override_Safety_Case__c,RTBF_Retention__c,Schedule_Mode__c,Status_To_Process__c,Time_To_Schedule_SSMMHH__c from GDPR_Settings__mdt where RTBF_Retention__c='RTBF'];
    }
    global Database.QueryLocator start(Database.BatchableContext bc){
        query =  'SELECT ID,PARENTID FROM caseFeed WHERE parentId=:caseList';
        if(isTestingContext)
        {
            query =  'SELECT ID,PARENTID FROM caseFeed WHERE parentId=:caseList LIMIT 200';
        }
        System.debug('GDPR Feed Query firing is ===>:'+query);
        return Database.getQueryLocator(query);
    }
    /**
    * Schedulable method, execute the schedule apex job
    */
    global void execute(SchedulableContext sc) {
        Database.executeBatch(this,Integer.valueOf(rtbfSettings.Feed_Data_Batch_Size__c));
    }
    global void execute(Database.BatchableContext bc, List<CaseFeed> caseFeedList)
    {
        if(caseFeedList.size()>0) {
            delete caseFeedList;Database.emptyRecycleBin(caseFeedList); 
        } 
    }
    global void finish(Database.BatchableContext bc){
        String day=String.valueOf(Datetime.now().day()); 
        String month=String.valueOf(Datetime.now().month()); 
        String year=String.valueOf(Datetime.now().year()); 
        String hour = String.valueOf(Datetime.now().hour()); 
        String min = String.valueOf(Datetime.now().minute()<=58?Datetime.now().minute()+1:Datetime.now().minute()); 
        String ss = String.valueOf(Datetime.now().second() ); 
        BatchGDPRHistoryProcess batchObj=new BatchGDPRHistoryProcess(false,caseList);
        String nextFireTime = ss + ' ' + min + ' ' + hour + ' ' + day+ ' ' + month+' ' + '?  ' + year; 
        List<CronTrigger> cronObj=[SELECT CronExpression,CronJobDetailId,EndTime,Id,LastModifiedById,NextFireTime,OwnerId,PreviousFireTime,StartTime,State FROM CronTrigger where CronJobDetail.name='Process GDPR History Data'];
        if(cronObj.size()>0)
            System.abortJob(cronObj[0].id);
        cronObj=[SELECT CronExpression,CronJobDetailId,EndTime,Id,LastModifiedById,NextFireTime,OwnerId,PreviousFireTime,StartTime,State FROM CronTrigger where CronJobDetail.name='Process GDPR History Data'];
        if(cronObj.size()==0)
            system.schedule('Process GDPR History Data',nextFireTime,batchObj); 
        /*
        Map<id,CaseFeed> caseFeedMap=new Map<id,CaseFeed>([SELECT ID,PARENTID FROM caseFeed WHERE parentId=:secondTimeFeedList]);
        Map<id,CaseHistory> caseHistoryMap=new Map<id,CaseHistory>([SELECT ID,CASEID FROM caseHistory WHERE caseId=:secondTimeFeedList]);
        System.debug('caseFeedMap.size()=====>:After Process 1'+caseFeedMap.size());
        if(caseFeedMap.size()>0)       delete caseFeedMap.values();
        System.debug('caseHistoryMap.size()=====>:After Process  1'+caseHistoryMap.size());
        if(caseHistoryMap.size()>0) delete caseHistoryMap.values();
        */
    }
}