care/force-app/main/default/objects/GDPR_Settings__mdt/GDPR_Settings__mdt.object-meta.xml
<CustomObject>
    <label>GDPR Settings</label>
    <pluralLabel>GDPR Settings</pluralLabel>
</CustomObject>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Data_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Data_Batch_Size__c</fullName>
    <description>This specifies the batch size of RTBF/Retention Data</description>
    <inlineHelpText>Enter RTBF/Retention Data Batch Size</inlineHelpText>
    <label>Data Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Feed_Data_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Feed_Data_Batch_Size__c</fullName>
    <description>This specifies the batch size of RTBF/Retention Feed Data</description>
    <inlineHelpText>Enter RTBF/Retention Feed Data Batch Size</inlineHelpText>
    <label>Feed Data Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/History_Data_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>History_Data_Batch_Size__c</fullName>
    <description>This specifies the batch size of RTBF/Retention History Data</description>
    <inlineHelpText>Enter RTBF/Retention History Data Batch Size</inlineHelpText>
    <label>History Data Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Override_Account_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Override_Account_Record_Type__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean flag, upon checking this, Skips Account Record Type validation while anonymyzing account.</description>
    <inlineHelpText>Check to override Account Record Type validation.</inlineHelpText>
    <label>Override Account Record Type</label>
    <type>Checkbox</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Override_Employer_Program__c.field-meta.xml
<CustomField>
    <fullName>Override_Employer_Program__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean flag, upon checking this, Skips Employer Program validation while anonymizing account.</description>
    <inlineHelpText>Check to override Employer Program validation.</inlineHelpText>
    <label>Override Employer Program</label>
    <type>Checkbox</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Override_Premium__c.field-meta.xml
<CustomField>
    <fullName>Override_Premium__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean flag, upon checking this, Skips Premium validation while anonymyzing account.</description>
    <inlineHelpText>Check to override premium validation.</inlineHelpText>
    <label>Override Premium</label>
    <type>Checkbox</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Override_Safety_Case__c.field-meta.xml
<CustomField>
    <fullName>Override_Safety_Case__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean flag, upon checking this, Skips Safety Case validation while anonymyzing account.</description>
    <inlineHelpText>Check to override Safety Case validation.</inlineHelpText>
    <label>Override Safety Case</label>
    <type>Checkbox</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Process_RTBF_Retention_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Process_RTBF_Retention_Request_Type__c</fullName>
    <description>Choose request type as either RTBF/Retention in Request Data.</description>
    <inlineHelpText>Choose request type as either RTBF/Retention in Request Data.</inlineHelpText>
    <label>Process RTBF/Retention Request Type?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RTBF</fullName>
                <default>true</default>
                <label>RTBF</label>
            </value>
            <value>
                <fullName>Retention</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/RTBF_Retention__c.field-meta.xml
<CustomField>
    <fullName>RTBF_Retention__c</fullName>
    <description>Provide option to choose the process type is RTBF or Retention</description>
    <inlineHelpText>Choose RTBF or Retention process and provide the corresponding validation on/off checks  like Safety Case/Premium/Employer Program/Record Type.</inlineHelpText>
    <label>RTBF/Retention</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RTBF</fullName>
                <default>true</default>
                <label>RTBF</label>
            </value>
            <value>
                <fullName>Retention</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Schedule_Mode__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Mode__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked when GDPR in Schedule run mode</description>
    <inlineHelpText>Check to GDPR in Schedule Mode</inlineHelpText>
    <label>Schedule Mode</label>
    <type>Checkbox</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Status_To_Process__c.field-meta.xml
<CustomField>
    <fullName>Status_To_Process__c</fullName>
    <description>Mention GDPR Status to process. Ex:- Use &apos;Test&apos; for testing phase</description>
    <inlineHelpText>Mention GDPR Status to process. Ex:- Use &apos;Test&apos; for testing phase</inlineHelpText>
    <label>Status To Process</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Time_To_Schedule_SSMMHH__c.field-meta.xml
<CustomField>
    <fullName>Time_To_Schedule_SSMMHH__c</fullName>
    <description>Enter GDPR schedule time in SSMMHH format</description>
    <inlineHelpText>Enter GDPR schedule time in SSMMHH format</inlineHelpText>
    <label>Time To Schedule(SSMMHH)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Request_Data__c/Request_Data__c.object-meta.xml
<CustomObject>
    <description>This objects holds the GDPR member data,it&apos;s status and other key information</description>
    <label>Request Data</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}-{000000}</displayFormat>
        <label>Request Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Request_Data__c/fields/Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>18 Character Account Id of Accounts being flagged for RTBF/Retention Process</description>
    <inlineHelpText>18 Character Account Id of Accounts being flagged for RTBF/Retention Process</inlineHelpText>
    <label>Account ID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Request Data</relationshipLabel>
    <relationshipName>Request_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

care/force-app/main/default/objects/Request_Data__c/fields/Global_Member_ID__c.field-meta.xml
<CustomField>
    <fullName>Global_Member_ID__c</fullName>
    <description>Unique identifier of  Sterling platform account</description>
    <label>Global Member ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Request_Data__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <description>Tells whether the request is RTBF or Retention</description>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RTBF</fullName>
            </value>
            <value>
                <fullName>Retention</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>RTBF Fail - Invalid Record Type</fullName>
            </value>
            <value>
                <fullName>RTBF Fail - Employer Program</fullName>
            </value>
            <value>
                <fullName>RTBF Fail - Safety Case</fullName>
            </value>
            <value>
                <fullName>RTBF Fail - Premium</fullName>
            </value>
            <value>
                <fullName>RTBF Fix</fullName>
            </value>
            <value>
                <fullName>RTBF Override</fullName>
            </value>
            <value>
                <fullName>RTBF Complete</fullName>
            </value>
            <value>
                <fullName>RTBF Do Not Process</fullName>
            </value>
            <value>
                <fullName>RTBF Anonymize</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Request_Data__c/fields/Response_Date__c.field-meta.xml
<CustomField>
    <fullName>Response_Date__c</fullName>
    <description>Date specifies the day when the ananymization process is completed.</description>
    <label>Response Date</label>
    <type>Date</type>
</CustomField>

care/force-app/main/default/objects/Request_Data__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field is used to hold the status of delete request.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Safety Case</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Invalid Record Type</fullName>
            </value>
            <value>
                <fullName>Employer Program</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>RTBF Fail - Invalid Record Type</fullName>
            </value>
            <value>
                <fullName>RTBF Fail - Employer Program</fullName>
            </value>
            <value>
                <fullName>RTBF Fail - Safety Case</fullName>
            </value>
            <value>
                <fullName>RTBF Fail - Premium</fullName>
            </value>
            <value>
                <fullName>RTBF Fix</fullName>
            </value>
            <value>
                <fullName>RTBF Override</fullName>
            </value>
            <value>
                <fullName>RTBF Complete</fullName>
            </value>
            <value>
                <fullName>RTBF Do Not Process</fullName>
            </value>
            <value>
                <fullName>RTBF Anonymize</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Request_Data__c/fields/Validation_Status__c.field-meta.xml
<CustomField>
    <fullName>Validation_Status__c</fullName>
    <description>Specifies the validations status of a particular GDPR account.</description>
    <label>Validation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Safety Case</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Invalid Record Type</fullName>
            </value>
            <value>
                <fullName>Employer Program</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/classes/Test_BatchGDPRAccFeedHistoryDelProcess.cls
//Last Modified by : Mohamme Ashwaq
//Last modified Date: 10/12/2020
@isTest(SeeAllData=false)
private class Test_BatchGDPRAccFeedHistoryDelProcess{
    Public static String intlCall = Schema.getGlobalDescribe().get('Case').getDescribe().getRecordTypeInfosByName().get('International Call Center').getRecordTypeId();
    Public static String intlEmail = Schema.getGlobalDescribe().get('Case').getDescribe().getRecordTypeInfosByName().get('International Email').getRecordTypeId();
    Public static String intlSafety = Schema.getGlobalDescribe().get('Case').getDescribe().getRecordTypeInfosByName().get('International Safety Alert').getRecordTypeId();
    Public static String intlSocial = Schema.getGlobalDescribe().get('Case').getDescribe().getRecordTypeInfosByName().get('Social Media International').getRecordTypeId();
    Public static String intlSeeker = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('International Seeker').getRecordTypeId();
    Public static String intlProvider= Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('International Provider').getRecordTypeId();
    @isTest(SeeAllData=false)
    static void test1() 
    {
        Test.startTest();
        //BatchGDPRAccHistoryDelProcess.dummyCoverageMethod();
        Account a=new Account(lastname='Test',Gdpr_request__c='RTBF',recordtypeid=intlSeeker,Global_Member_Id__c='12345678');
        Account a1=new Account(lastname='Test',Gdpr_request__c='RTBF',recordtypeid=intlProvider,Global_Member_Id__c='123456789');
        insert new List<Account>{a,a1};
        a.lastname='Test1';
        update new List<Account>{a,a1};
        AccountHistory ah=new AccountHistory(accountid=a.id);
        //insert ah;
        Request_Data__c  gdprObj=new Request_Data__c (Status__c='New',Request_Type__c='RTBF',Global_Member_Id__c='12345678');
        Request_Data__c  gdprObj1=new Request_Data__c (Status__c='New',Request_Type__c='RTBF',Global_Member_Id__c='123456789');
        upsert new List<Request_Data__c>{gdprObj,gdprObj1};
        system.debug('Request Data query==================>:'+[SELECT Account_ID__c,Request_Type__c,Global_Member_ID__c,Id,Name,Response_Date__c,Status__c,Validation_Status__c FROM Request_Data__c ]);
        String day=String.valueOf(Datetime.now().day()); 
        String month=String.valueOf(Datetime.now().month()); 
        String year=String.valueOf(Datetime.now().year()); 
        String hour = String.valueOf(Datetime.now().hour()); 
        String min = String.valueOf(Datetime.now().minute()<=58?Datetime.now().minute()+1:Datetime.now().minute()); 
        String ss = String.valueOf(Datetime.now().second()); 
        String nextFireTime = ss + ' ' + min + ' ' + hour + ' ' + day+ ' ' + month+' ' + '?  ' + year; 
        List<Id> caseFeedList;
        GDPR_Settings__mdt rtbfSettings=[select id,DeveloperName,Process_RTBF_Retention_Request_Type__c,MasterLabel,Data_Batch_Size__c,Feed_Data_Batch_Size__c,History_Data_Batch_Size__c,Override_Account_Record_Type__c,Override_Employer_Program__c,Override_Premium__c,Override_Safety_Case__c,RTBF_Retention__c,Schedule_Mode__c,Status_To_Process__c,Time_To_Schedule_SSMMHH__c from GDPR_Settings__mdt where RTBF_Retention__c='RTBF'];
        List<Request_Data__c> gdprList=new List<Request_Data__c>{gdprObj,gdprObj1};
        BatchGDPRAccHistoryDelProcess btchF = new BatchGDPRAccHistoryDelProcess();        
        Database.executeBatch(new BatchGDPRAccHistoryDelProcess(true));
        Test.stopTest();
    }
    @isTest(SeeAllData=false)
    static void test2() 
    {
        Test.startTest();
        Account a=new Account(lastname='Test',Gdpr_request__c='RTBF',recordtypeid=intlSeeker,Global_Member_Id__c='12345678');
        Account a1=new Account(lastname='Test',Gdpr_request__c='RTBF',recordtypeid=intlSeeker,Global_Member_Id__c='123456789');
        insert new List<Account>{a,a1};
        a.lastname='Test1';
        update new List<Account>{a,a1};
        System.debug('Acc Query:'+[SELECT Account_ID__c,Request_Type__c,Global_Member_ID__c,Id,Name,Response_Date__c,Status__c,Validation_Status__c FROM Request_Data__c where Status__c='New' and Request_Type__c='RTBF' LIMIT 200]);
        AccountHistory ah=new AccountHistory(accountid=a.id);
        //insert ah;
        Request_Data__c  gdprObj=new Request_Data__c (Status__c='New',Request_Type__c='RTBF',Global_Member_Id__c='12345678');
        Request_Data__c  gdprObj1=new Request_Data__c (Status__c='New',Request_Type__c='RTBF',Global_Member_Id__c='123456789');
        upsert new List<Request_Data__c>{gdprObj,gdprObj1};
        system.debug('Request Data query==================>:'+[SELECT Account_ID__c,Request_Type__c,Global_Member_ID__c,Id,Name,Response_Date__c,Status__c,Validation_Status__c FROM Request_Data__c ]);
        String day=String.valueOf(Datetime.now().day()); 
        String month=String.valueOf(Datetime.now().month()); 
        String year=String.valueOf(Datetime.now().year()); 
        String hour = String.valueOf(Datetime.now().hour()); 
        String min = String.valueOf(Datetime.now().minute()<=58?Datetime.now().minute()+1:Datetime.now().minute()); 
        String ss = String.valueOf(Datetime.now().second()); 
        String nextFireTime = ss + ' ' + min + ' ' + hour + ' ' + day+ ' ' + month+' ' + '?  ' + year; 
        List<Id> caseFeedList;
        GDPR_Settings__mdt rtbfSettings=[select id,DeveloperName,Process_RTBF_Retention_Request_Type__c,MasterLabel,Data_Batch_Size__c,Feed_Data_Batch_Size__c,History_Data_Batch_Size__c,Override_Account_Record_Type__c,Override_Employer_Program__c,Override_Premium__c,Override_Safety_Case__c,RTBF_Retention__c,Schedule_Mode__c,Status_To_Process__c,Time_To_Schedule_SSMMHH__c from GDPR_Settings__mdt where RTBF_Retention__c='RTBF'];
        List<Request_Data__c> gdprList=new List<Request_Data__c>{gdprObj,gdprObj1};
        BatchGDPRAccHistoryDelProcess btchF = new BatchGDPRAccHistoryDelProcess();
        Database.executeBatch(new BatchGDPRAccHistoryDelProcess(true));
        Test.stopTest();
    }
    @isTest(SeeAllData=false)
    static void test3() 
    {
        Test.startTest();
        Account a=new Account(lastname='Test',Gdpr_request__c='RTBF',recordtypeid=intlSeeker,Global_Member_Id__c='12345678');
        Account a1=new Account(lastname='Test',Gdpr_request__c='RTBF',recordtypeid=intlSeeker,Global_Member_Id__c='123456789');
        insert new List<Account>{a,a1};
        a.lastname='Test1';
        update new List<Account>{a,a1};
        System.debug('Acc Query:'+[SELECT Account_ID__c,Request_Type__c,Global_Member_ID__c,Id,Name,Response_Date__c,Status__c,Validation_Status__c FROM Request_Data__c where Status__c='New' and Request_Type__c='RTBF' LIMIT 200]);
        AccountHistory ah=new AccountHistory(accountid=a.id);
        //insert ah;
        Request_Data__c  gdprObj=new Request_Data__c (Status__c='New',Request_Type__c='RTBF',Global_Member_Id__c='12345678');
        Request_Data__c  gdprObj1=new Request_Data__c (Status__c='New',Request_Type__c='RTBF',Global_Member_Id__c='123456789');
        upsert new List<Request_Data__c>{gdprObj,gdprObj1};
        system.debug('Request Data query==================>:'+[SELECT Account_ID__c,Request_Type__c,Global_Member_ID__c,Id,Name,Response_Date__c,Status__c,Validation_Status__c FROM Request_Data__c ]);
        String day=String.valueOf(Datetime.now().day()); 
        String month=String.valueOf(Datetime.now().month()); 
        String year=String.valueOf(Datetime.now().year()); 
        String hour = String.valueOf(Datetime.now().hour()); 
        String min = String.valueOf(Datetime.now().minute()<=58?Datetime.now().minute()+1:Datetime.now().minute()); 
        String ss = String.valueOf(Datetime.now().second()); 
        String nextFireTime = ss + ' ' + min + ' ' + hour + ' ' + day+ ' ' + month+' ' + '?  ' + year; 
        List<Id> caseFeedList;
        GDPR_Settings__mdt rtbfSettings=[select id,DeveloperName,Process_RTBF_Retention_Request_Type__c,MasterLabel,Data_Batch_Size__c,Feed_Data_Batch_Size__c,History_Data_Batch_Size__c,Override_Account_Record_Type__c,Override_Employer_Program__c,Override_Premium__c,Override_Safety_Case__c,RTBF_Retention__c,Schedule_Mode__c,Status_To_Process__c,Time_To_Schedule_SSMMHH__c from GDPR_Settings__mdt where RTBF_Retention__c='RTBF'];
        List<Request_Data__c> gdprList=new List<Request_Data__c>{gdprObj,gdprObj1};
        System.schedule('Process GdprHistory Schedule','0 0 23 * * ?',new BatchGDPRAccHistoryDelProcess(true));
        Test.stopTest();
    }
    @isTest(SeeAllData=false)
    static void test4() 
    {
        Test.startTest();
        Account a=new Account(lastname='Test',Gdpr_request__c='RTBF',recordtypeid=intlSeeker,Global_Member_Id__c='12345678');
        Account a1=new Account(lastname='Test',Gdpr_request__c='RTBF',recordtypeid=intlSeeker,Global_Member_Id__c='123456789');
        insert new List<Account>{a,a1};
        a.lastname='Test1';
        update new List<Account>{a,a1};
        System.debug('Acc Query:'+[SELECT Account_ID__c,Request_Type__c,Global_Member_ID__c,Id,Name,Response_Date__c,Status__c,Validation_Status__c FROM Request_Data__c where Status__c='New' and Request_Type__c='RTBF' LIMIT 200]);
        AccountHistory ah=new AccountHistory(accountid=a.id);
        //insert ah;
        //Request_Data__c  gdprObj=new Request_Data__c (Request_Type__c='RTBF',Status__c='New',Global_Member_Id__c='12345678');
        //System.assert(gdprObj.Global_Member_Id__c==a.Global_Member_Id__c);
        Request_Data__c  gdprObj=new Request_Data__c (Status__c='New',Request_Type__c='RTBF',Global_Member_Id__c='12345678');
        Request_Data__c  gdprObj1=new Request_Data__c (Status__c='New',Request_Type__c='RTBF',Global_Member_Id__c='123456789');
        upsert new List<Request_Data__c>{gdprObj,gdprObj1};
        system.debug('Request Data query==================>:'+[SELECT Account_ID__c,Request_Type__c,Global_Member_ID__c,Id,Name,Response_Date__c,Status__c,Validation_Status__c FROM Request_Data__c ]);
        String day=String.valueOf(Datetime.now().day()); 
        String month=String.valueOf(Datetime.now().month()); 
        String year=String.valueOf(Datetime.now().year()); 
        String hour = String.valueOf(Datetime.now().hour()); 
        String min = String.valueOf(Datetime.now().minute()<=58?Datetime.now().minute()+1:Datetime.now().minute()); 
        String ss = String.valueOf(Datetime.now().second()); 
        String nextFireTime = ss + ' ' + min + ' ' + hour + ' ' + day+ ' ' + month+' ' + '?  ' + year; 
        List<Id> caseFeedList;
        GDPR_Settings__mdt rtbfSettings=[select id,DeveloperName,Process_RTBF_Retention_Request_Type__c,MasterLabel,Data_Batch_Size__c,Feed_Data_Batch_Size__c,History_Data_Batch_Size__c,Override_Account_Record_Type__c,Override_Employer_Program__c,Override_Premium__c,Override_Safety_Case__c,RTBF_Retention__c,Schedule_Mode__c,Status_To_Process__c,Time_To_Schedule_SSMMHH__c from GDPR_Settings__mdt where RTBF_Retention__c='RTBF'];
        List<Request_Data__c> gdprList=new List<Request_Data__c>{gdprObj,gdprObj1};
        System.schedule('Process GdprFeed Schedule','0 0 23 * * ?',new BatchGDPRAccHistoryDelProcess(true));
        Test.stopTest();
    }
    @isTest(SeeAllData=false)
    static void test6() 
    {
        Test.startTest();
        Account a=new Account(lastname='Test',Gdpr_request__c='RTBF',recordtypeid=intlSeeker,Global_Member_Id__c='12345678');
        Account a1=new Account(lastname='Test',Gdpr_request__c='RTBF',recordtypeid=intlProvider,Global_Member_Id__c='123456789');
        insert new List<Account>{a,a1};
        a.lastname='Test1';
        update new List<Account>{a,a1};
        System.debug('Acc Query:'+[SELECT Account_ID__c,Request_Type__c,Global_Member_ID__c,Id,Name,Response_Date__c,Status__c,Validation_Status__c FROM Request_Data__c where Status__c='New' and Request_Type__c='RTBF' LIMIT 200]);
        AccountHistory ah=new AccountHistory(accountid=a.id);
        //insert ah;
        Request_Data__c  gdprObj=new Request_Data__c (Status__c='New',Request_Type__c='RTBF',Global_Member_Id__c='12345678');
        Request_Data__c  gdprObj1=new Request_Data__c (Status__c='New',Request_Type__c='RTBF',Global_Member_Id__c='123456789');
        upsert new List<Request_Data__c>{gdprObj,gdprObj1};
        system.debug('Request Data query==================>:'+[SELECT Account_ID__c,Request_Type__c,Global_Member_ID__c,Id,Name,Response_Date__c,Status__c,Validation_Status__c FROM Request_Data__c ]);
        Case c1=new Case(accountid=a.id,Recordtypeid=intlEmail);
        Case c2=new Case(accountid=a.id,Recordtypeid=intlEmail);
        Case c3=new Case(accountid=a.id,Recordtypeid=intlEmail);
        Case c4=new Case(accountid=a.id,Recordtypeid=intlEmail);
        Case c5=new Case(accountid=a.id,Recordtypeid=intlSafety);
        Case c6=new Case(accountid=a.id,Recordtypeid=intlSafety);
        insert new List<case>{c1,c2,c3,c4,c5,c6};
        Attachment att1 = new Attachment(parentid=a.id,name='Att1',body=Blob.valueOf('Test Body')); 
        Attachment att2 = new Attachment(parentid=c1.id,name='Att2',body=Blob.valueOf('Test Body')); 
        Attachment att3 = new Attachment(parentid=a.id,name='Att1',body=Blob.valueOf('Test Body1')); 
        Attachment att4 = new Attachment(parentid=c1.id,name='Att2',body=Blob.valueOf('Test Body1')); 
        insert new List<Attachment>{att1,att2,att3,att4}; 
        String day=String.valueOf(Datetime.now().day()); 
        String month=String.valueOf(Datetime.now().month()); 
        String year=String.valueOf(Datetime.now().year()); 
        String hour = String.valueOf(Datetime.now().hour()); 
        String min = String.valueOf(Datetime.now().minute()<=58?Datetime.now().minute()+1:Datetime.now().minute()); 
        String ss = String.valueOf(Datetime.now().second()); 
        String nextFireTime = ss + ' ' + min + ' ' + hour + ' ' + day+ ' ' + month+' ' + '?  ' + year; 
        //BatchGDPRMemberRequest batchObj=new BatchGDPRMemberRequest(true,'anonymize','New');
        //Database.executeBatch(batchObj,20);
        List<Id> caseFeedList;
        GDPR_Settings__mdt rtbfSettings=[select id,DeveloperName,Process_RTBF_Retention_Request_Type__c,MasterLabel,Data_Batch_Size__c,Feed_Data_Batch_Size__c,History_Data_Batch_Size__c,Override_Account_Record_Type__c,Override_Employer_Program__c,Override_Premium__c,Override_Safety_Case__c,RTBF_Retention__c,Schedule_Mode__c,Status_To_Process__c,Time_To_Schedule_SSMMHH__c from GDPR_Settings__mdt where RTBF_Retention__c='RTBF'];
        List<Request_Data__c> gdprList=new List<Request_Data__c>{gdprObj,gdprObj1};
        //ProcessMemberGDPRequest.ProcessMemberGDPRequestData(gdprList,'anonymize',caseFeedList,rtbfSettings);
            //Database.executeBatch(new BatchGDPRAccHistoryDelProcess(true));
            //public static void ProcessMemberGDPRequestData(List<Request_Data__c > gdpReqListParam,String runStateStr,List<id> secondTimeFeedListParam,GDPR_Settings__mdt rtbfSettingsParam)
            //system.schedule('Process GDPR Data',nextFireTime,batchObj); 
            //Database.executeBatch(new BatchGDPRMemberRequestCount(true));
            //List<User> userList=[select id,firstname,lastname,email,name,username from user where email in ('sridhar.neeli@care.com')];
            //System.schedulebatch(new BatchGDPRMemberRequestCount(false,userList),'GDPR Count',1,200);
            //ProcessGDPRCount.processGDPRCount('sridhar.neeli@care.com,raju.cherukuri@care.com');
            //ProcessGDPRData.processGDPRInfo('anonymize');
            Test.stopTest();
    }
    @isTest(SeeAllData=false)
    static void test7() 
    {
        Test.startTest();
        Account a=new Account(lastname='Test',Gdpr_request__c='RTBF',recordtypeid=intlSeeker,Global_Member_Id__c='12345678');
        Account a1=new Account(lastname='Test',Gdpr_request__c='RTBF',recordtypeid=intlSeeker,Global_Member_Id__c='123456789');
        insert new List<Account>{a,a1};
        a.lastname='Test1';
        update new List<Account>{a,a1};
        System.debug('Acc Query:'+[SELECT Account_ID__c,Request_Type__c,Global_Member_ID__c,Id,Name,Response_Date__c,Status__c,Validation_Status__c FROM Request_Data__c where Status__c='New' and Request_Type__c='RTBF' LIMIT 200]);
        AccountHistory ah=new AccountHistory(accountid=a.id);
        Request_Data__c  gdprObj=new Request_Data__c (Status__c='New',Request_Type__c='RTBF',Global_Member_Id__c='12345678');
        Request_Data__c  gdprObj1=new Request_Data__c (Status__c='New',Request_Type__c='RTBF',Global_Member_Id__c='123456789');
        upsert new List<Request_Data__c>{gdprObj,gdprObj1};
        system.debug('Request Data query==================>:'+[SELECT Account_ID__c,Request_Type__c,Global_Member_ID__c,Id,Name,Response_Date__c,Status__c,Validation_Status__c FROM Request_Data__c ]);
        Case c1=new Case(accountid=a.id,Recordtypeid=intlEmail);
        Case c2=new Case(accountid=a.id,Recordtypeid=intlEmail);
        Case c3=new Case(accountid=a.id,Recordtypeid=intlEmail);
        Case c4=new Case(accountid=a.id,Recordtypeid=intlEmail);
        Case c5=new Case(accountid=a.id,Recordtypeid=intlSafety);
        Case c6=new Case(accountid=a.id,Recordtypeid=intlSafety);
        insert new List<case>{c1,c2,c3,c4,c5,c6};
        Attachment att1 = new Attachment(parentid=a.id,name='Att1',body=Blob.valueOf('Test Body')); 
        Attachment att2 = new Attachment(parentid=c1.id,name='Att2',body=Blob.valueOf('Test Body')); 
        Attachment att3 = new Attachment(parentid=a.id,name='Att1',body=Blob.valueOf('Test Body1')); 
        Attachment att4 = new Attachment(parentid=c1.id,name='Att2',body=Blob.valueOf('Test Body1')); 
        insert new List<Attachment>{att1,att2,att3,att4}; 
        String day=String.valueOf(Datetime.now().day()); 
        String month=String.valueOf(Datetime.now().month()); 
        String year=String.valueOf(Datetime.now().year()); 
        String hour = String.valueOf(Datetime.now().hour()); 
        String min = String.valueOf(Datetime.now().minute()<=58?Datetime.now().minute()+1:Datetime.now().minute()); 
        String ss = String.valueOf(Datetime.now().second()); 
        String nextFireTime = ss + ' ' + min + ' ' + hour + ' ' + day+ ' ' + month+' ' + '?  ' + year; 
        BatchGDPRMemberRequest batchObj=new BatchGDPRMemberRequest(true,'anonymize','New');
        Database.executeBatch(batchObj,20);
        List<Id> caseFeedList;
        GDPR_Settings__mdt rtbfSettings=[select id,DeveloperName,Process_RTBF_Retention_Request_Type__c,MasterLabel,Data_Batch_Size__c,Feed_Data_Batch_Size__c,History_Data_Batch_Size__c,Override_Account_Record_Type__c,Override_Employer_Program__c,Override_Premium__c,Override_Safety_Case__c,RTBF_Retention__c,Schedule_Mode__c,Status_To_Process__c,Time_To_Schedule_SSMMHH__c from GDPR_Settings__mdt where RTBF_Retention__c='RTBF'];
        List<Request_Data__c> gdprList=new List<Request_Data__c>{gdprObj,gdprObj1};
        Database.executeBatch(new BatchGDPRAccHistoryDelProcess(true));
        Test.stopTest();
    }
    @isTest(SeeAllData=false)
    static void test8() 
    {
        Test.startTest();
        Account a=new Account(lastname='Test',Gdpr_request__c='RTBF',recordtypeid=intlSeeker,Global_Member_Id__c='12345678');
        Account a1=new Account(lastname='Test',Gdpr_request__c='RTBF',recordtypeid=intlSeeker,Global_Member_Id__c='123456789');
        insert new List<Account>{a,a1};
        a.lastname='Test1';
        update new List<Account>{a,a1};
        System.debug('Acc Query:'+[SELECT Account_ID__c,Request_Type__c,Global_Member_ID__c,Id,Name,Response_Date__c,Status__c,Validation_Status__c FROM Request_Data__c where Status__c='New' and Request_Type__c='RTBF' LIMIT 200]);
        AccountHistory ah=new AccountHistory(accountid=a.id);
        //insert ah;
        //Request_Data__c  gdprObj=new Request_Data__c (Request_Type__c='RTBF',Status__c='New',Global_Member_Id__c='12345678');
        //System.assert(gdprObj.Global_Member_Id__c==a.Global_Member_Id__c);
        Request_Data__c  gdprObj=new Request_Data__c (Status__c='New',Request_Type__c='RTBF',Global_Member_Id__c='12345678');
        Request_Data__c  gdprObj1=new Request_Data__c (Status__c='New',Request_Type__c='RTBF',Global_Member_Id__c='123456789');
        upsert new List<Request_Data__c>{gdprObj,gdprObj1};
        system.debug('Request Data query==================>:'+[SELECT Account_ID__c,Request_Type__c,Global_Member_ID__c,Id,Name,Response_Date__c,Status__c,Validation_Status__c FROM Request_Data__c ]);
        Case c1=new Case(accountid=a.id,Recordtypeid=intlEmail);
        Case c2=new Case(accountid=a.id,Recordtypeid=intlEmail);
        Case c3=new Case(accountid=a.id,Recordtypeid=intlEmail);
        Case c4=new Case(accountid=a.id,Recordtypeid=intlEmail);
        Case c5=new Case(accountid=a.id,Recordtypeid=intlSafety);
        Case c6=new Case(accountid=a.id,Recordtypeid=intlSafety);
        insert new List<case>{c1,c2,c3,c4,c5,c6};
        Attachment att1 = new Attachment(parentid=a.id,name='Att1',body=Blob.valueOf('Test Body')); 
        Attachment att2 = new Attachment(parentid=c1.id,name='Att2',body=Blob.valueOf('Test Body')); 
        Attachment att3 = new Attachment(parentid=a.id,name='Att1',body=Blob.valueOf('Test Body1')); 
        Attachment att4 = new Attachment(parentid=c1.id,name='Att2',body=Blob.valueOf('Test Body1')); 
        insert new List<Attachment>{att1,att2,att3,att4}; 
        String day=String.valueOf(Datetime.now().day()); 
        String month=String.valueOf(Datetime.now().month()); 
        String year=String.valueOf(Datetime.now().year()); 
        String hour = String.valueOf(Datetime.now().hour()); 
        String min = String.valueOf(Datetime.now().minute()<=58?Datetime.now().minute()+1:Datetime.now().minute()); 
        String ss = String.valueOf(Datetime.now().second()); 
        String nextFireTime = ss + ' ' + min + ' ' + hour + ' ' + day+ ' ' + month+' ' + '?  ' + year; 
        //BatchGDPRMemberRequest batchObj=new BatchGDPRMemberRequest(true,'anonymize','New');
        //Database.executeBatch(batchObj,20);
        List<Id> caseFeedList;
        GDPR_Settings__mdt rtbfSettings=[select id,DeveloperName,Process_RTBF_Retention_Request_Type__c,MasterLabel,Data_Batch_Size__c,Feed_Data_Batch_Size__c,History_Data_Batch_Size__c,Override_Account_Record_Type__c,Override_Employer_Program__c,Override_Premium__c,Override_Safety_Case__c,RTBF_Retention__c,Schedule_Mode__c,Status_To_Process__c,Time_To_Schedule_SSMMHH__c from GDPR_Settings__mdt where RTBF_Retention__c='RTBF'];
        List<Request_Data__c> gdprList=new List<Request_Data__c>{gdprObj,gdprObj1};
        System.schedule('Process GdprHistory Schedule','0 0 23 * * ?',new BatchGDPRAccHistoryDelProcess(true));
        Test.stopTest();
    }
    @isTest(SeeAllData=false)
    static void test9() 
    {
        Test.startTest();
        Account a=new Account(lastname='Test',Gdpr_request__c='RTBF',recordtypeid=intlSeeker,Global_Member_Id__c='12345678');
        Account a1=new Account(lastname='Test',Gdpr_request__c='RTBF',recordtypeid=intlSeeker,Global_Member_Id__c='123456789');
        insert new List<Account>{a,a1};
        a.lastname='Test1';
        update new List<Account>{a,a1};
        System.debug('Acc Query:'+[SELECT Account_ID__c,Request_Type__c,Global_Member_ID__c,Id,Name,Response_Date__c,Status__c,Validation_Status__c FROM Request_Data__c where Status__c='New' and Request_Type__c='RTBF' LIMIT 200]);
        AccountHistory ah=new AccountHistory(accountid=a.id);
        //insert ah;
        //Request_Data__c  gdprObj=new Request_Data__c (Request_Type__c='RTBF',Status__c='New',Global_Member_Id__c='12345678');
        //System.assert(gdprObj.Global_Member_Id__c==a.Global_Member_Id__c);
        Request_Data__c  gdprObj=new Request_Data__c (Status__c='New',Request_Type__c='RTBF',Global_Member_Id__c='12345678');
        Request_Data__c  gdprObj1=new Request_Data__c (Status__c='New',Request_Type__c='RTBF',Global_Member_Id__c='123456789');
        upsert new List<Request_Data__c>{gdprObj,gdprObj1};
            
        Case c1=new Case(accountid=a.id,Recordtypeid=intlEmail);
        Case c2=new Case(accountid=a.id,Recordtypeid=intlEmail);
        Case c3=new Case(accountid=a.id,Recordtypeid=intlEmail);
        Case c4=new Case(accountid=a.id,Recordtypeid=intlEmail);
        Case c5=new Case(accountid=a.id,Recordtypeid=intlSafety);
        Case c6=new Case(accountid=a.id,Recordtypeid=intlSafety);
        insert new List<case>{c1,c2,c3,c4,c5,c6};
        
        Attachment att1 = new Attachment(parentid=a.id,name='Att1',body=Blob.valueOf('Test Body')); 
        Attachment att2 = new Attachment(parentid=c1.id,name='Att2',body=Blob.valueOf('Test Body')); 
        Attachment att3 = new Attachment(parentid=a.id,name='Att1',body=Blob.valueOf('Test Body1')); 
        Attachment att4 = new Attachment(parentid=c1.id,name='Att2',body=Blob.valueOf('Test Body1')); 
        insert new List<Attachment>{att1,att2,att3,att4}; 
        
        String day=String.valueOf(Datetime.now().day()); 
        String month=String.valueOf(Datetime.now().month()); 
        String year=String.valueOf(Datetime.now().year()); 
        String hour = String.valueOf(Datetime.now().hour()); 
        String min = String.valueOf(Datetime.now().minute()<=58?Datetime.now().minute()+1:Datetime.now().minute()); 
        String ss = String.valueOf(Datetime.now().second()); 
        String nextFireTime = ss + ' ' + min + ' ' + hour + ' ' + day+ ' ' + month+' ' + '?  ' + year; 
        List<Id> caseFeedList;
        GDPR_Settings__mdt rtbfSettings=[select id,DeveloperName,Process_RTBF_Retention_Request_Type__c,MasterLabel,Data_Batch_Size__c,Feed_Data_Batch_Size__c,History_Data_Batch_Size__c,Override_Account_Record_Type__c,Override_Employer_Program__c,Override_Premium__c,Override_Safety_Case__c,RTBF_Retention__c,Schedule_Mode__c,Status_To_Process__c,Time_To_Schedule_SSMMHH__c from GDPR_Settings__mdt where RTBF_Retention__c='RTBF'];
        List<Request_Data__c> gdprList=new List<Request_Data__c>{gdprObj,gdprObj1};
        System.schedule('Process GdprFeed Schedule','0 0 23 * * ?',new BatchGDPRAccHistoryDelProcess(true));
        Test.stopTest();
    }
}