care/force-app/main/default/objects/GDPR_Settings__mdt/GDPR_Settings__mdt.object-meta.xml
<CustomObject>
    <label>GDPR Settings</label>
    <pluralLabel>GDPR Settings</pluralLabel>
</CustomObject>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Override_Account_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Override_Account_Record_Type__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean flag, upon checking this, Skips Account Record Type validation while anonymyzing account.</description>
    <inlineHelpText>Check to override Account Record Type validation.</inlineHelpText>
    <label>Override Account Record Type</label>
    <type>Checkbox</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Override_Employer_Program__c.field-meta.xml
<CustomField>
    <fullName>Override_Employer_Program__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean flag, upon checking this, Skips Employer Program validation while anonymizing account.</description>
    <inlineHelpText>Check to override Employer Program validation.</inlineHelpText>
    <label>Override Employer Program</label>
    <type>Checkbox</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Override_Premium__c.field-meta.xml
<CustomField>
    <fullName>Override_Premium__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean flag, upon checking this, Skips Premium validation while anonymyzing account.</description>
    <inlineHelpText>Check to override premium validation.</inlineHelpText>
    <label>Override Premium</label>
    <type>Checkbox</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Override_Safety_Case__c.field-meta.xml
<CustomField>
    <fullName>Override_Safety_Case__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean flag, upon checking this, Skips Safety Case validation while anonymyzing account.</description>
    <inlineHelpText>Check to override Safety Case validation.</inlineHelpText>
    <label>Override Safety Case</label>
    <type>Checkbox</type>
</CustomField>

care/force-app/main/default/objects/Request_Data__c/Request_Data__c.object-meta.xml
<CustomObject>
    <description>This objects holds the GDPR member data,it&apos;s status and other key information</description>
    <label>Request Data</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}-{000000}</displayFormat>
        <label>Request Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Request_Data__c/fields/Global_Member_ID__c.field-meta.xml
<CustomField>
    <fullName>Global_Member_ID__c</fullName>
    <description>Unique identifier of  Sterling platform account</description>
    <label>Global Member ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Request_Data__c/fields/Last_Validation_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Validation_Date__c</fullName>
    <description>Specifies the last validation date of GDPR requested account.</description>
    <label>Last Validation Date</label>
    <type>Date</type>
</CustomField>

care/force-app/main/default/objects/Request_Data__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <description>Tells whether the request is RTBF or Retention</description>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RTBF</fullName>
            </value>
            <value>
                <fullName>Retention</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>RTBF Fail - Invalid Record Type</fullName>
            </value>
            <value>
                <fullName>RTBF Fail - Employer Program</fullName>
            </value>
            <value>
                <fullName>RTBF Fail - Safety Case</fullName>
            </value>
            <value>
                <fullName>RTBF Fail - Premium</fullName>
            </value>
            <value>
                <fullName>RTBF Fix</fullName>
            </value>
            <value>
                <fullName>RTBF Override</fullName>
            </value>
            <value>
                <fullName>RTBF Complete</fullName>
            </value>
            <value>
                <fullName>RTBF Do Not Process</fullName>
            </value>
            <value>
                <fullName>RTBF Anonymize</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Request_Data__c/fields/Response_Date__c.field-meta.xml
<CustomField>
    <fullName>Response_Date__c</fullName>
    <description>Date specifies the day when the ananymization process is completed.</description>
    <label>Response Date</label>
    <type>Date</type>
</CustomField>

care/force-app/main/default/objects/Request_Data__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field is used to hold the status of delete request.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Safety Case</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Invalid Record Type</fullName>
            </value>
            <value>
                <fullName>Employer Program</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>RTBF Fail - Invalid Record Type</fullName>
            </value>
            <value>
                <fullName>RTBF Fail - Employer Program</fullName>
            </value>
            <value>
                <fullName>RTBF Fail - Safety Case</fullName>
            </value>
            <value>
                <fullName>RTBF Fail - Premium</fullName>
            </value>
            <value>
                <fullName>RTBF Fix</fullName>
            </value>
            <value>
                <fullName>RTBF Override</fullName>
            </value>
            <value>
                <fullName>RTBF Complete</fullName>
            </value>
            <value>
                <fullName>RTBF Do Not Process</fullName>
            </value>
            <value>
                <fullName>RTBF Anonymize</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Request_Data__c/fields/Validation_Status__c.field-meta.xml
<CustomField>
    <fullName>Validation_Status__c</fullName>
    <description>Specifies the validations status of a particular GDPR account.</description>
    <label>Validation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Safety Case</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Invalid Record Type</fullName>
            </value>
            <value>
                <fullName>Employer Program</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Survey_Feedback__c/Survey_Feedback__c.object-meta.xml
<CustomObject>
    <label>Survey Feedback</label>
    <nameField>
        <label>Survey Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Feedbacks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Survey_Feedback__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Survey Feedbacks</relationshipLabel>
    <relationshipName>Survey_Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

care/force-app/main/default/objects/Survey_Feedback__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <complianceGroup>CCPA</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Survey Feedbacks</relationshipLabel>
    <relationshipName>Survey_Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

care/force-app/main/default/objects/Survey_Feedback__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Survey Feedbacks</relationshipLabel>
    <relationshipName>Survey_Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

care/force-app/main/default/objects/Survey_Feedback__c/fields/CSAT_Rating__c.field-meta.xml
<CustomField>
    <fullName>CSAT_Rating__c</fullName>
    <complianceGroup>CCPA</complianceGroup>
    <description>Servicing teams satisfaction question</description>
    <label>CSAT Rating</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>I am very satisfied – You answered my question in a fast, friendly way.</fullName>
            </value>
            <value>
                <fullName>I am satisfied – You were helpful, but this could have been better.</fullName>
            </value>
            <value>
                <fullName>I am not satisfied – You didn’t provide the help I needed. I expected more.</fullName>
            </value>
            <value>
                <fullName>Extremely Satisfied</fullName>
            </value>
            <value>
                <fullName>Somewhat Satisfied</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Somewhat Dissatisfied</fullName>
            </value>
            <value>
                <fullName>Extremely Dissatisfied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Survey_Feedback__c/fields/Employer_Program__c.field-meta.xml
<CustomField>
    <fullName>Employer_Program__c</fullName>
    <formula>TEXT(Account__r.Employer_Program_Pick__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employer Program</label>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Survey_Feedback__c/fields/Rating_comments__c.field-meta.xml
<CustomField>
    <fullName>Rating_comments__c</fullName>
    <complianceGroup>CCPA</complianceGroup>
    <description>Can you tell us why you’ve chosen the ratings above?</description>
    <inlineHelpText>Can you tell us why you’ve chosen the ratings above?</inlineHelpText>
    <label>Rating comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

care/force-app/main/default/objects/Survey_Feedback__c/fields/Text_Translation__c.field-meta.xml
<CustomField>
    <fullName>Text_Translation__c</fullName>
    <complianceGroup>CCPA</complianceGroup>
    <label>Text Translation</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

care/force-app/main/default/classes/ProcessMemberGDPRequest.cls
/*
Description:  Anonymizes data for member and deletes all related records of Account, Contcat and Case.
ModifiedBy : md Ashwaq
ModifiedDate: 02/07/2023
*/
public class ProcessMemberGDPRequest
{
    public static  Map<id,Case> caseMap;    
    public static Map<id,List<Case>> accIdCaseListMap;
    public static Map<id,AccountHistory> accountHistoryMap;
    public static Map<id,List<AccountHistory>> accIdAccountHistoryListMap;
    public static List<AccountHistory> deleteAccountHistoryList=new List<AccountHistory>();
    public static Map<id,accountFeed> accountFeedMap;
    public static Map<id,List<accountFeed>> accIdaccountFeedListMap;
    public static List<AccountFeed> deleteAccountFeedList=new List<AccountFeed>();
    public static Map<id,EmailMessage> caseEmailMessageMap;
    public static Map<id,List<EmailMessage>> caseIdEmailMessageListMap;
    public static List<EmailMessage> deleteCaseEmailMessageList=new List<EmailMessage>();
    public static Map<id,Event> caseEventMap;
    public static Map<id,List<Event>> caseIdEventListMap;
    public static List<Event> deleteCaseEventList=new List<Event>();
    public static Map<id,Event> accEventMap;
    public static Map<id,List<Event>> accIdEventListMap;
    public static List<Event> deleteAccountEventList=new List<Event>();
    public static Map<id,Attachment> caseAttachmentMap;
    public static Map<id,List<Attachment>> caseIdAttachmentListMap;
    public static List<Attachment> deleteCaseAttachmentList=new List<Attachment>();
    public static Map<id,Attachment> accAttachmentMap;
    public static Map<id,List<Attachment>> accIdAttachmentListMap;
    public static List<Attachment> deleteAccountAttachmentList=new List<Attachment>();
    public static Map<id,Task> caseTaskMap;
    public static Map<id,List<Task>> caseIdTaskListMap;
    public static Set<Task> updateCaseTaskList=new Set<Task>();
    public static Map<id,CaseComment> caseCommentMap;    
    public static Map<id,List<CaseComment>> caseIdCommentListMap;
    public static List<CaseComment> deleteCaseCommentList=new List<CaseComment>();
    public static Map<id,Task> accTaskMap;
    public static Map<id,List<Task>> accIdTaskListMap;
    public static List<Task> deleteAccountTaskList=new List<Task>();
    public static Map<id,Survey_Feedback__c> caseSurveyFeedbackMap;
    public static Map<id,List<Survey_Feedback__c>> caseIdSurveyFeedbackListMap;
    public static List<Survey_Feedback__c> updateCaseSurveyFeedbackList=new List<Survey_Feedback__c>();
    public static Map<id,Survey_Feedback__c> accSurveyFeedbackMap;
    public static Map<id,List<Survey_Feedback__c>> accIdSurveyFeedbackListMap;
    public static List<Survey_Feedback__c> updateAccountSurveyFeedbackList=new List<Survey_Feedback__c>();
    public static Map<id,boolean> accWithNonClearCasesMap;
    public static Map<id,boolean> accWithEmpProgramCasesMap;
    public static Map<String,Request_Data__c > gmIdMap;
    public static Map<String,Account> accGmIdMap;
    public static Map<id,Account> accMap;
    public static Map<id,String> accRecTypes;
    public static Map<id,String> caseRecTypes;
    public static Map<String,id> caseRecTypeNameIdMap;
    public static List<Case> casesToUpdate; 
    public static String runState;
    public static List<id> caseFeedHistoryIdList;  //Collects all case id's to be forwarded to Feed Job.
    public static List<FeedItem> surveyFeedbackListRecs=new List<FeedItem>();
    public static List<FeedItem> caseTaskFeedList=new List<FeedItem>();
    public static List<Request_Data__c> delGdpReqList=new List<Request_Data__c>();
    public static Map<id,Account> delAccountMap=new Map<id,Account>();
    public static Map<id,Id> delContactMap=new Map<id,Id>();
    public static Map<Id,ContentNote> accNoteMap;
    public static Map<Id,ContentNote> caseNoteMap;
    public static List<ContentNote>  deleteCaseNotesList;
    public static Map<id,Note>  accNotesAndAttachments;
    public static List<Note>  deleteCaseNotesAndAttachmentsList;
    public static Map<id,List<Note>> caseNotesAndAttachments;
    public static Map<id,List<id>> caseContentNoteIdMap;
    public static List<id> caseContentNoteIdList;
    public static List<Request_Data__c > gdpReqList;
    public static List<id> secondTimeFeedList;  //Holds all case id's to be forwarded to Feed Job.
    public static GDPR_Settings__mdt rtbfSettings;  // Gdpr Custom Meta Data Settings
    //SOCIAL MEDIA INT
    public static Map<id,List<Case>>  caseContactIdMap = new Map<id,List<Case>>();
    public static Map<Id, Contact> conSocialMedia = new Map<Id, Contact>();
    public static Map<Id, Contact> updateConSocialMedia = new Map<Id, Contact>();
    public static Id socialMediaContact = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('International Social Contact').getRecordTypeId();
    public static Map<id,ContactHistory> contactHistoryMap = new Map<id,ContactHistory>();
    public static Map<id,List<ContactHistory>> conIdContactHistoryListMap = new Map<id,List<ContactHistory>>();
    public static List<ContactHistory> deleteContactHistoryList=new List<ContactHistory>();
    public static Map<id,SocialPost> caseSocialPostMap = new Map<id,SocialPost>();
    public static Map<id,List<SocialPost>> caseIdSocialPostListMap = new Map<id,List<SocialPost>>();
    public static List<SocialPost> deleteCaseSocialPostList=new List<SocialPost>();  
    
    public static Map<id,spr_sf__SocialPost__c> caseSprSocialPostMap = new Map<id,spr_sf__SocialPost__c>();
    public static Map<id,List<spr_sf__SocialPost__c>> caseIdSprSocialPostListMap = new Map<id,List<spr_sf__SocialPost__c>>();
    public static List<spr_sf__SocialPost__c> deleteCaseSprSocialPostList=new List<spr_sf__SocialPost__c>();  
    
    public static List<spr_sf__SocialPersona__c> deleteCaseSprSocialPersonaList=new List<spr_sf__SocialPersona__c>();
        
    public static Map<id,SocialPersona> caseSocialPersonaMap = new Map<id,SocialPersona>();
    public static Map<id,List<SocialPersona>> caseIdSocialPersonaListMap = new Map<id,List<SocialPersona>>();
    public static List<SocialPersona> deleteCaseSocialPersonaList=new List<SocialPersona>();       
    public static void ProcessMemberGDPRequestData(List<Request_Data__c > gdpReqListParam,String runStateStr,List<id> secondTimeFeedListParam,GDPR_Settings__mdt rtbfSettingsParam)
    {
        gdpReqList=gdpReqListParam;
        secondTimeFeedList=secondTimeFeedListParam;
        rtbfSettings=rtbfSettingsParam;
        runState=runStateStr;
        System.debug('Runstate seleted is ==============>:'+runState);
        gmIdMap=new Map<String,Request_Data__c >();
        for(Request_Data__c  gdpReqObj:gdpReqList){
            gmIdMap.put(gdpReqObj.Global_Member_ID__c,gdpReqObj);
        }
        accGmIdMap=new Map<String,Account>();
        accMap=new Map<id,Account>();
        for(Account accObj:[select id,recordTypeId,Type__pc, firstName, LastName, Global_Member_Id__c,Employer_Program__pc,personContactId,isPersonAccount from Account where Global_Member_ID__c=:gmIdMap.keySet()]){
            accGmIdMap.put(accObj.Global_Member_ID__c,accObj);
            accMap.put(accObj.id,accObj);
        }
        if(getRecordTypesStatic.recordTypeNameIdMap.containsKey('International Provider')){
            accRecTypes.put(getRecordTypesStatic.recordTypeNameIdMap.get('International Provider'), 'International Provider');
        }
        if(getRecordTypesStatic.recordTypeNameIdMap.containsKey('International Seeker')){
            accRecTypes.put(getRecordTypesStatic.recordTypeNameIdMap.get('International Seeker'), 'International Seeker');
        }
        caseRecTypeNameIdMap=new Map<String,id>();
        Schema.DescribeSObjectResult CaseR = Case.SObjectType.getDescribe();
        List<Schema.RecordTypeInfo> CaseRT = CaseR.getRecordTypeInfos();
        for(Schema.RecordTypeInfo rt: CaseRT){
            if(rt.getName()=='International Call Center' || rt.getName()=='International Email' || rt.getName()=='International Safety Alert' || rt.getName()=='Social Media International'){
                caseRecTypes.put(rt.getRecordTypeId(), rt.getName());
                caseRecTypeNameIdMap.put(rt.getName(),rt.getRecordTypeId());
            }
        }
        System.debug('***caseRecTypes***'+caseRecTypes);
        System.debug('***caseRecTypeNameIdMap***'+caseRecTypeNameIdMap);
        casesToUpdate=new List<Case>();
        caseMap=new Map<id,Case>([SELECT ID,STATUS,RECORDTYPEID,ACCOUNTID,ContactId, subject,description,Account.Name,Employer_Program__c FROM CASE WHERE ACCOUNTID=:accMap.keySet()]);
        System.debug('caseMap=====================>:'+caseMap.size());
        accIdCaseListMap=new Map <id,List<Case>>();
        for(Case caseObj:caseMap.values())
        {
            if(accIdCaseListMap.get(caseObj.accountId)==null)
            {
                accIdCaseListMap.put(caseObj.accountId,new List<Case>{caseObj});
            }
            else
            {
                accIdCaseListMap.get(caseObj.accountId).add(caseObj);
            }
        }
        accWithNonClearCasesMap=new Map<id,boolean>();
        accWithEmpProgramCasesMap=new Map<id,boolean>();
        for(Request_Data__c  gdpReqObj:gdpReqList)
        {
            Account accObj=accGmIdMap.get(gdpReqObj.Global_Member_ID__c);
            System.debug('accObj.Employer_Program__pc=====================>:'+accObj.Employer_Program__pc);
            System.debug('String.isBlank(accObj.Employer_Program__pc)=====================>:'+String.isBlank(accObj.Employer_Program__pc));
            if(!String.isBlank(accObj.Employer_Program__pc))
            {
                accWithEmpProgramCasesMap.put(accObj.id,true);
                System.debug('Found Employee Program for the account111 ===>:'+accObj.id);
            }
            if(accIdCaseListMap.containsKey(accGmIdMap.get(gdpReqObj.Global_Member_Id__c).id))
            {
                for(Case caseObj:accIdCaseListMap.get(accGmIdMap.get(gdpReqObj.Global_Member_Id__c).id))
                {
                    if((caseObj.recordTypeId==caseRecTypeNameIdMap.get('International Safety Alert') && caseObj.Status!='Cleared')||(!String.isBlank(caseObj.Employer_Program__c)))
                    {
                        if(caseObj.recordTypeId==caseRecTypeNameIdMap.get('International Safety Alert') && caseObj.Status!='Cleared')
                        {
                            System.debug('CUSTOM DEBUG LINE ============>: 333 Non Cleared Safety Alert Found'+caseObj.id);
                            accWithNonClearCasesMap.put(caseObj.accountId,true);
                        }
                        if(!String.isBlank(caseObj.Employer_Program__c))
                        {
                            accWithEmpProgramCasesMap.put(caseObj.accountId,true);
                            System.debug('Found Employee Program for the account ===>:'+accObj.id);
                        }
                    }
                }
            }
        }
        map<id, List<String>> caseAccountNameMap = new map<id, List<String>>();
        for(Request_Data__c  gdpReqObj:gdpReqList)
        {
            Account accObj=accGmIdMap.get(gdpReqObj.Global_Member_ID__c);
            if(accIdCaseListMap.containsKey(accGmIdMap.get(gdpReqObj.Global_Member_Id__c).id))
            {
                for(Case caseObj:accIdCaseListMap.get(accGmIdMap.get(gdpReqObj.Global_Member_Id__c).id))
                {
                    if(caseObj.recordTypeId==caseRecTypeNameIdMap.get('Social Media International'))
                    {
                        if(caseObj.contactId !=null){
                            if(caseContactIdMap.get(caseObj.contactId)==null)
                            {
                                caseContactIdMap.put(caseObj.contactId,new List<Case>{caseObj});
                            }
                            else
                            {
                                caseContactIdMap.get(caseObj.contactId).add(caseObj);
                            }                            
                            List<String> accName = new List<String>{accObj.firstName, accObj.LastName};
                                caseAccountNameMap.put(caseObj.ContactId, accName);
                        }
                    }                    
                }
            }
        }
        system.debug('************caseAccountNameMap social case contact NAME'+caseAccountNameMap);
        system.debug('************caseContactIdMap social case contact'+caseContactIdMap);
        if(!caseContactIdMap.isEmpty()){
            conSocialMedia = new Map<id,Contact>([Select Id,  firstName, LastName, RecordTypeId  from Contact where Id IN: caseContactIdMap.keySet() and RecordTypeId =: socialMediaContact ]);
        }
        system.debug('************caseContactIdMap social contact'+conSocialMedia);
        updateConSocialMedia = new Map<Id, Contact>();
        if(!conSocialMedia.isEmpty()){
            List<Case> noAccountSocialCase = [SELECT ID,STATUS,RECORDTYPEID,ACCOUNTID,ContactId,subject,description,Account.Name,Employer_Program__c FROM CASE WHERE ContactId=:conSocialMedia.keySet() LIMIT 50000];
            for(Case cs: noAccountSocialCase){
                if(cs.accountId ==null){
                    caseMap.put(cs.Id, cs);
                }                
            }
            for(Contact con : conSocialMedia.values()){                
                con.firstName = caseAccountNameMap.get(con.Id)[0];
                con.LastName = caseAccountNameMap.get(con.Id)[1];                
                updateConSocialMedia.put(con.id, con);
            }	
        }
        caseSocialPersonaMap=new Map<id,SocialPersona>([SELECT ID,PARENTID FROM SocialPersona WHERE parentId = :conSocialMedia.keySet()]);
        caseIdSocialPersonaListMap =new Map <id,List<SocialPersona>>();
        for(SocialPersona socialPersonaObj:caseSocialPersonaMap.values())
        {
            if(caseIdSocialPersonaListMap.get(socialPersonaObj.parentId)==null)
            {
                caseIdSocialPersonaListMap.put(socialPersonaObj.parentId,new List<SocialPersona>{socialPersonaObj});
            }
            else
            {
                caseIdSocialPersonaListMap.get(socialPersonaObj.parentId).add(socialPersonaObj);
            }
        }
        system.debug('************caseIdSocialPersonaListMap'+caseIdSocialPersonaListMap);
        caseSocialPostMap=new Map<id,SocialPost>([SELECT ID,PARENTID FROM socialPost WHERE parentId =:caseMap.keySet()]);
        caseIdSocialPostListMap=new Map <id,List<SocialPost>>();
        for(SocialPost socialPostObj:caseSocialPostMap.values())
        {
            if(caseIdSocialPostListMap.get(socialPostObj.parentId)==null)
            {
                caseIdSocialPostListMap.put(socialPostObj.parentId,new List<SocialPost>{socialPostObj});
            }
            else
            {
                caseIdSocialPostListMap.get(socialPostObj.parentId).add(socialPostObj);
            }
        }
        system.debug('************caseIdSocialPostListMap'+caseIdSocialPostListMap);
        
        
        Set<Id> sprPersonaId = new set<Id>();
        caseSprSocialPostMap=new Map<id,spr_sf__SocialPost__c>([SELECT ID,spr_sf__SocialPersona__c,spr_sf__Case__c FROM spr_sf__SocialPost__c WHERE spr_sf__Case__c = :caseMap.keySet()]);
        caseIdSprSocialPostListMap=new Map <id,List<spr_sf__SocialPost__c>>();
        for(spr_sf__SocialPost__c SprsocialPostObj:caseSprSocialPostMap.values())
        {
            if(caseIdSprSocialPostListMap.get(SprsocialPostObj.spr_sf__Case__c)==null)
            {
                caseIdSprSocialPostListMap.put(SprsocialPostObj.spr_sf__Case__c,new List<spr_sf__SocialPost__c>{SprsocialPostObj});
            }
            else
            {
                caseIdSprSocialPostListMap.get(SprsocialPostObj.spr_sf__Case__c).add(SprsocialPostObj);
            }
            if(SprsocialPostObj.spr_sf__SocialPersona__c !=null){
                sprPersonaId.add(SprsocialPostObj.spr_sf__SocialPersona__c);
            }
        }
        system.debug('************caseIdSprSocialPostListMap'+caseIdSprSocialPostListMap);
        
        deleteCaseSprSocialPersonaList = [SELECT ID FROM spr_sf__SocialPersona__c WHERE Id IN :sprPersonaId]; 
        system.debug('************caseIdSprSocialPostListMap'+deleteCaseSprSocialPersonaList);
        
        contactHistoryMap=new Map<id,ContactHistory>([Select Id , ContactId from ContactHistory where Id =:caseContactIdMap.keySet()]);
        conIdContactHistoryListMap=new Map <id,List<ContactHistory>>();
        for(ContactHistory ContactHistoryObj : contactHistoryMap.values())
        {
            if(conIdContactHistoryListMap.get(ContactHistoryObj.ContactId)==null)
            {
                conIdContactHistoryListMap.put(ContactHistoryObj.ContactId,new List<ContactHistory>{ContactHistoryObj});
            }
            else
            {
                conIdContactHistoryListMap.get(ContactHistoryObj.ContactId).add(ContactHistoryObj);
            }
        }
        system.debug('************conIdContactHistoryListMap'+conIdContactHistoryListMap);
        for(Request_Data__c  gdpReqObj:gdpReqList)
        {
            Account accObj=accGmIdMap.get(gdpReqObj.Global_Member_ID__c);
            if((rtbfSettings.Override_Account_Record_Type__c?true:(accRecTypes.containsKey(accObj.recordTypeId))) 
               && 
               (rtbfSettings.Override_Employer_Program__c?true:(!accWithEmpProgramCasesMap.containsKey(accObj.id))) 
               && 
               (rtbfSettings.Override_Premium__c?true:(accObj.Type__pc!='Premium')) 
               && 
               (rtbfSettings.Override_Safety_Case__c?true:(!accWithNonClearCasesMap.containsKey(accObj.id))))
            {
                delGdpReqList.add(gdpReqObj);
                delAccountMap.put(accObj.id,accObj);
                if(!String.isBlank(accObj.personContactId))
                {
                    delContactMap.put(accObj.id,accObj.personContactId);
                }
            }
        }
        for(Request_Data__c  gdpReqObj:gdpReqList)
        {
            Account accObj=accGmIdMap.get(gdpReqObj.Global_Member_ID__c);
            if(runState=='anonymize')
            {
                if(!rtbfSettings.Override_Safety_Case__c && accWithNonClearCasesMap.containsKey(accObj.id))
                {
                    gdpReqObj.status__c='Safety Case';
                    accGmIdMap.get(gdpReqObj.Global_Member_Id__c).Gdpr_Request__c=gdpReqObj.Request_Type__c+' Declined';
                    gdpReqObj.Response_Date__c=Datetime.now().date();  
                    System.debug('Found safety case for the account ===>:'+accObj.id);
                }
                if(!rtbfSettings.Override_Employer_Program__c && accWithEmpProgramCasesMap.containsKey(accObj.id))
                {
                    gdpReqObj.status__c='Employer Program';
                    accGmIdMap.get(gdpReqObj.Global_Member_Id__c).Gdpr_Request__c=gdpReqObj.Request_Type__c+' Declined'; 
                    gdpReqObj.Response_Date__c=Datetime.now().date(); 
                    System.debug('Found Employee Program for the account ===>:'+accObj.id);
                }
                //gdpReqObj.Request_Type__c='RTBF';
                //gdpReqObj.Response_Date__c=Datetime.now().date();
                // accGmIdMap.get(gdpReqObj.Global_Member_Id__c).Gdpr_Request__c=gdpReqObj.Request_Type__c+' Completed'
                if(!rtbfSettings.Override_Account_Record_Type__c && accRecTypes.get(accObj.recordTypeId)==null)
                {
                    gdpReqObj.status__c='Invalid Record Type';
                    //gdpReqObj.Request_Type__c='RTBF';
                    gdpReqObj.Response_Date__c=Datetime.now().date();
                    accObj.Gdpr_Request__c=gdpReqObj.Request_Type__c+' Declined';
                    //accObj.Gdpr_Request__c=gdpReqObj.Request_Type__c+' Completed';
                }
                if(!rtbfSettings.Override_Premium__c && accObj.Type__pc=='Premium')
                {
                    gdpReqObj.status__c='Premium';
                    //gdpReqObj.Request_Type__c='RTBF';
                    gdpReqObj.Response_Date__c=Datetime.now().date();
                    accObj.Gdpr_Request__c=gdpReqObj.Request_Type__c+' Declined';
                    //accObj.Gdpr_Request__c=gdpReqObj.Request_Type__c+' Completed';
                }
            }
            else if(runState=='preCheck')
            {
                if(!rtbfSettings.Override_Safety_Case__c && accWithNonClearCasesMap.containsKey(accObj.id))
                {
                    gdpReqObj.Validation_Status__c='Safety Case';
                    gdpReqObj.Last_Validation_Date__c=Datetime.now().date();
                    System.debug('Found safety case for the account ===>:'+accObj.id);
                }
                if(!rtbfSettings.Override_Employer_Program__c && accWithEmpProgramCasesMap.containsKey(accObj.id))
                {
                    gdpReqObj.Validation_Status__c='Employer Program';
                    gdpReqObj.Last_Validation_Date__c=Datetime.now().date();
                    System.debug('Found Employee Program for the account ===>:'+accObj.id);
                }
                if(!rtbfSettings.Override_Account_Record_Type__c && accRecTypes.get(accObj.recordTypeId)==null)
                {
                    gdpReqObj.Validation_Status__c='Invalid Record Type';
                    gdpReqObj.Last_Validation_Date__c=Datetime.now().date();
                }
                if(!rtbfSettings.Override_Premium__c && accObj.Type__pc=='Premium')
                {
                    gdpReqObj.Validation_Status__c='Premium';
                    gdpReqObj.Last_Validation_Date__c=Datetime.now().date();
                }
            }
        }
        accountHistoryMap=new Map<id,AccountHistory>([SELECT ID,ACCOUNTID FROM AccountHistory WHERE accountId=:delAccountMap.keySet()]);
        accIdAccountHistoryListMap=new Map <id,List<AccountHistory>>();
        for(AccountHistory AccountHistoryObj:accountHistoryMap.values())
        {
            if(accIdAccountHistoryListMap.get(AccountHistoryObj.accountId)==null)
            {
                accIdAccountHistoryListMap.put(AccountHistoryObj.accountId,new List<AccountHistory>{AccountHistoryObj});
            }
            else
            {
                accIdAccountHistoryListMap.get(AccountHistoryObj.accountId).add(AccountHistoryObj);
            }
        }
        accountFeedMap=new Map<id,accountFeed>([SELECT ID,PARENTID FROM accountFeed WHERE parentId=:delAccountMap.keySet()]);
        accIdaccountFeedListMap=new Map <id,List<accountFeed>>();
        for(accountFeed accountFeedObj:accountFeedMap.values())
        {
            if(accIdaccountFeedListMap.get(accountFeedObj.parentId)==null)
            {
                accIdaccountFeedListMap.put(accountFeedObj.parentId,new List<accountFeed>{accountFeedObj});
            }
            else
            {
                accIdaccountFeedListMap.get(accountFeedObj.parentId).add(accountFeedObj);
            }
        }
        caseEmailMessageMap=new Map<id,EmailMessage>([SELECT ID,PARENTID FROM EmailMessage WHERE parentId=:caseMap.keySet()]);
        caseIdEmailMessageListMap=new Map <id,List<EmailMessage>>();
        for(EmailMessage EmailMessageObj:caseEmailMessageMap.values())
        {
            if(caseIdEmailMessageListMap.get(EmailMessageObj.parentId)==null)
            {
                caseIdEmailMessageListMap.put(EmailMessageObj.parentId,new List<EmailMessage>{EmailMessageObj});
            }
            else
            {
                caseIdEmailMessageListMap.get(EmailMessageObj.parentId).add(EmailMessageObj);
            }
        }
        caseEventMap=new Map<id,Event>([SELECT ID,WHATID,WHOID FROM Event WHERE whatId=:caseMap.keySet()]);
        caseIdEventListMap=new Map <id,List<Event>>();
        for(Event EventObj:caseEventMap.values())
        {
            if(caseIdEventListMap.get(EventObj.whatId)==null)
            {
                caseIdEventListMap.put(EventObj.whatId,new List<Event>{EventObj});
            }
            else
            {
                caseIdEventListMap.get(EventObj.whatId).add(EventObj);
            }
        }
        accEventMap=new Map<id,Event>([SELECT ID,WHATID,WHOID FROM Event WHERE whatId=:delAccountMap.keySet()]);
        accIdEventListMap=new Map <id,List<Event>>();
        for(Event EventObj:accEventMap.values())
        {
            if(accIdEventListMap.get(EventObj.whatId)==null)
            {
                accIdEventListMap.put(EventObj.whatId,new List<Event>{EventObj});
            }
            else
            {
                accIdEventListMap.get(EventObj.whatId).add(EventObj);
            }
        }
        caseAttachmentMap=new Map<id,Attachment>([SELECT ID,PARENTID FROM Attachment WHERE parentId=:caseMap.keySet()]);
        caseIdAttachmentListMap=new Map <id,List<Attachment>>();
        for(Attachment AttachmentObj:caseAttachmentMap.values())
        {
            if(caseIdAttachmentListMap.get(AttachmentObj.parentId)==null)
            {
                caseIdAttachmentListMap.put(AttachmentObj.parentId,new List<Attachment>{AttachmentObj});
            }
            else
            {
                caseIdAttachmentListMap.get(AttachmentObj.parentId).add(AttachmentObj);
            }
        }
        accAttachmentMap=new Map<id,Attachment>([SELECT ID,PARENTID FROM Attachment WHERE parentId=:delAccountMap.keySet()]);
        accIdAttachmentListMap=new Map <id,List<Attachment>>();
        for(Attachment AttachmentObj:accAttachmentMap.values())
        {
            if(accIdAttachmentListMap.get(AttachmentObj.parentId)==null)
            {
                accIdAttachmentListMap.put(AttachmentObj.parentId,new List<Attachment>{AttachmentObj});
            }
            else
            {
                accIdAttachmentListMap.get(AttachmentObj.parentId).add(AttachmentObj);
            }
        }
        caseTaskMap=new Map<id,Task>([SELECT ID,WHATID,WHOID,SUBJECT FROM Task WHERE whatId=:caseMap.keySet() ALL ROWS]);
        caseIdTaskListMap=new Map <id,List<Task>>();
        for(Task TaskObj:caseTaskMap.values())
        {
            if(caseIdTaskListMap.get(TaskObj.whatId)==null)
            {
                caseIdTaskListMap.put(TaskObj.whatId,new List<Task>{TaskObj});
            }
            else
            {
                caseIdTaskListMap.get(TaskObj.whatId).add(TaskObj);
            }
        }
        caseCommentMap=new Map<id,CaseComment>([SELECT ID,parentId FROM CaseComment WHERE parentId=:caseMap.keySet()]);
        caseIdCommentListMap=new Map <id,List<CaseComment>>();
        for(CaseComment caseCommentObj:caseCommentMap.values())
        {
            if(caseIdCommentListMap.get(caseCommentObj.parentId)==null)
            {
                caseIdCommentListMap.put(caseCommentObj.parentId,new List<caseComment>{caseCommentObj});
            }
            else
            {
                caseIdCommentListMap.get(caseCommentObj.parentId).add(caseCommentObj);
            }
        }
        accTaskMap=new Map<id,Task>([SELECT ID,WHATID,WHOID,SUBJECT FROM Task WHERE whatId=:delAccountMap.keySet() ALL ROWS]);
        accIdTaskListMap=new Map <id,List<Task>>();
        for(Task TaskObj:accTaskMap.values())
        {
            System.debug('Adding task to acctasklist================>:'+taskObj.subject);
            if(accIdTaskListMap.get(TaskObj.whatId)==null)
            {
                accIdTaskListMap.put(TaskObj.whatId,new List<Task>{TaskObj});
            }
            else
            {
                accIdTaskListMap.get(TaskObj.whatId).add(TaskObj);
            }
        }
        caseSurveyFeedbackMap=new Map<id,Survey_Feedback__c>([SELECT Account__c,Case__c,Contact__c,CSAT_Rating__c,Rating_comments__c,Text_Translation__c FROM Survey_Feedback__c where Case__c=:caseMap.keySet()]);
        caseIdSurveyFeedbackListMap=new Map <id,List<Survey_Feedback__c>>();
        for(Survey_Feedback__c SurveyFeedbackObj:caseSurveyFeedbackMap.values())
        {
            if(caseIdSurveyFeedbackListMap.get(SurveyFeedbackObj.Case__c)==null)
            {
                caseIdSurveyFeedbackListMap.put(SurveyFeedbackObj.Case__c,new List<Survey_Feedback__c>{SurveyFeedbackObj});
            }
            else
            {
                caseIdSurveyFeedbackListMap.get(SurveyFeedbackObj.Case__c).add(SurveyFeedbackObj);
            }
        }
        accSurveyFeedbackMap=new Map<id,Survey_Feedback__c>([SELECT Account__c,Case__c,Contact__c,CSAT_Rating__c,Rating_comments__c,Text_Translation__c FROM Survey_Feedback__c where (Account__c=:delAccountMap.keySet() or Contact__c=:delContactMap.values())]);
        accIdSurveyFeedbackListMap=new Map <id,List<Survey_Feedback__c>>();
        for(Survey_Feedback__c SurveyFeedbackObj:accSurveyFeedbackMap.values())
        {
            if(accIdSurveyFeedbackListMap.get(SurveyFeedbackObj.Contact__c)==null)
            {
                accIdSurveyFeedbackListMap.put(SurveyFeedbackObj.Contact__c,new List<Survey_Feedback__c>{SurveyFeedbackObj});
            }
            else
            {
                accIdSurveyFeedbackListMap.get(SurveyFeedbackObj.Contact__c).add(SurveyFeedbackObj);
            }
            System.debug('Found Survey feedback for the account/contact ====>:'+SurveyFeedbackObj.Contact__c);
        }
        for(Survey_Feedback__c SurveyFeedbackObj:accSurveyFeedbackMap.values())
        {
            if(accIdSurveyFeedbackListMap.get(SurveyFeedbackObj.Account__c)==null)
            {
                accIdSurveyFeedbackListMap.put(SurveyFeedbackObj.Account__c,new List<Survey_Feedback__c>{SurveyFeedbackObj});
            }
            else
            {
                accIdSurveyFeedbackListMap.get(SurveyFeedbackObj.Account__c).add(SurveyFeedbackObj);
            }
            System.debug('Found Survey feedback for the account/contact ====>:'+SurveyFeedbackObj.Account__c);
        }
        List<id> accList=new List<id>();
        if(delAccountMap.keySet().size()>0) accList.addAll(delAccountMap.keySet());
        List<id> caseList=new List<id>();
        if(caseMap.keySet().size()>0) caseList.addAll(caseMap.keySet());
        List<id> accContentNoteIdList=new List<id>();
        if(!accList.isEmpty())
        {
            for(ContentDocumentLink links : [SELECT LinkedEntityId, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityID=:accList])
            {
                accContentNoteIdList.add(links.ContentDocumentId);
            }
        }
        caseContentNoteIdMap=new Map<id,List<id>>();
        caseContentNoteIdList=new List<id>();
        if(!caseList.isEmpty())
        {
            for(ContentDocumentLink links : [SELECT LinkedEntityId, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityID=:caseList])
            {
                caseContentNoteIdList.add(links.ContentDocumentId);
                if(caseContentNoteIdMap.containsKey(links.LinkedEntityID))
                    caseContentNoteIdMap.get(links.LinkedEntityID).add(links.ContentDocumentId);
                else
                    caseContentNoteIdMap.put(links.LinkedEntityID,new List<id>());
            }
        }
        accNoteMap = new Map<id,ContentNote>([select id from ContentNote where id=:accContentNoteIdList]);
        caseNoteMap = new Map<id,ContentNote>([select id from ContentNote where id=:caseContentNoteIdList]);
        deleteCaseNotesList=new List<ContentNote>();       
        accNotesAndAttachments=new Map<id,Note>([SELECT Id,ParentId FROM Note where parentid=:delAccountMap.keySet()]);
        Map<id,Note>  caseNotesAndAttachmentsMap=new Map<id,Note>([SELECT Id,ParentId FROM Note where parentid=:caseMap.keySet()]);
        deleteCaseNotesAndAttachmentsList=new List<Note>();
        caseNotesAndAttachments=new Map<id,List<Note>>();
        for(Note noteObj:caseNotesAndAttachmentsMap.values())
        {
            if(caseNotesAndAttachments.containsKey(noteObj.parentid))    
                caseNotesAndAttachments.get(noteObj.parentid).add(noteObj);
            else
                caseNotesAndAttachments.put(noteObj.parentid,new List<Note>());
        }
        if(!conSocialMedia.isEmpty()){
            List<Case> noAccountSocialCase = [SELECT ID,STATUS,RECORDTYPEID,ACCOUNTID,ContactId,subject,description,Account.Name,Employer_Program__c FROM CASE WHERE ContactId IN: conSocialMedia.keySet() LIMIT 50000];
            for(Contact con : conSocialMedia.values()){
                con.firstName = caseAccountNameMap.get(con.Id)[0];
                con.LastName = caseAccountNameMap.get(con.Id)[1];
                updateConSocialMedia.put(con.id, con);
            }	
        }
        for(Request_Data__c  gdpReqObj:delGdpReqList)
        {
            Account accObj=accGmIdMap.get(gdpReqObj.Global_Member_ID__c);
            System.debug('!rtbfSettings.Override_Safety_Case__c && accWithNonClearCasesMap.containsKey(accObj.id)====>:'+(!rtbfSettings.Override_Safety_Case__c && accWithNonClearCasesMap.containsKey(accObj.id)));
            system.debug('!rtbfSettings.Override_Safety_Case__c===>:'+!rtbfSettings.Override_Safety_Case__c);
            System.debug('!rtbfSettings.Override_Employer_Program__c==>:'+!rtbfSettings.Override_Employer_Program__c);
            System.debug('!rtbfSettings.Override_Account_Record_Type__c==>:'+!rtbfSettings.Override_Account_Record_Type__c);
            System.debug('!rtbfSettings.Override_Account_Record_Type__c==>:'+!rtbfSettings.Override_Account_Record_Type__c);
            System.debug('rtbfSettings.Override_Account_Record_Type__c?true:(accRecTypes.get(accObj.recordTypeId)!=null)===>:'+(rtbfSettings.Override_Account_Record_Type__c?true:(accRecTypes.get(accObj.recordTypeId)!=null)));
            System.debug('rtbfSettings.Override_Employer_Program__c?true:(!accWithEmpProgramCasesMap.containsKey(accObj.id))===>:'+(rtbfSettings.Override_Employer_Program__c?true:(!accWithEmpProgramCasesMap.containsKey(accObj.id))));
            System.debug('rtbfSettings.Override_Premium__c?true:(accObj.Type__pc!=\'Premium\')==>:'+(rtbfSettings.Override_Premium__c?true:(accObj.Type__pc!='Premium')));
            System.debug('rtbfSettings.Override_Safety_Case__c?true:(accWithNonClearCasesMap.get(accObj.id)==null)==>:'+(rtbfSettings.Override_Safety_Case__c?true:(accWithNonClearCasesMap.get(accObj.id)==null)));   
            System.debug('isGdprAccCasesHasNotClearedCase========================>:'+accWithNonClearCasesMap.get(accObj.id));
            System.debug('==========================Account is not premium International Seeker/Provider');
            System.debug('1');
            System.debug('CUSTOM DEBUG LINE ============>: 4');
            processAllCases(accObj);
            // Retrieve all account relared info
            System.debug('CUSTOM DEBUG LINE ============>: 12'+accIdTaskListMap.size());
            if(accIdTaskListMap.get(accObj.id)!=null) deleteAccountTaskList.addAll(accIdTaskListMap.get(accObj.id));
            if(accIdEventListMap.get(accObj.id)!=null) deleteAccountEventList.addAll(accIdEventListMap.get(accObj.id));                    
            if(accIdAttachmentListMap.get(accObj.id)!=null)
                deleteAccountAttachmentList.addAll(accIdAttachmentListMap.get(accObj.id));
            if(accIdaccountFeedListMap.get(accObj.id)!=null)
                deleteAccountFeedList.addAll(accIdaccountFeedListMap.get(accObj.id));  
            if(accIdAccountHistoryListMap.get(accObj.id)!=null)              
                deleteAccountHistoryList.addAll(accIdAccountHistoryListMap.get(accObj.id));
            if(accIdSurveyFeedbackListMap.get(delContactMap.get(accObj.id))!=null)
            {
                for(Survey_Feedback__c accSurveyFeedbackObj:accIdSurveyFeedbackListMap.get(delContactMap.get(accObj.id)))
                {
                    System.debug('CUSTOM DEBUG LINE ============>: 13');
                    accSurveyFeedbackObj.CSAT_Rating__c=null;
                    accSurveyFeedbackObj.Rating_comments__c=null;
                    accSurveyFeedbackObj.Text_Translation__c=null;
                    updateAccountSurveyFeedbackList.add(accSurveyFeedbackObj);
                }
            }
            else
                if(accIdSurveyFeedbackListMap.containsKey(accObj.id))
            {
                for(Survey_Feedback__c accSurveyFeedbackObj:accIdSurveyFeedbackListMap.get(accObj.id))
                {
                    System.debug('CUSTOM DEBUG LINE ============>: 13');
                    accSurveyFeedbackObj.CSAT_Rating__c=null;
                    accSurveyFeedbackObj.Rating_comments__c=null;
                    accSurveyFeedbackObj.Text_Translation__c=null;
                    updateAccountSurveyFeedbackList.add(accSurveyFeedbackObj);
                }
            }
            System.debug('CUSTOM DEBUG LINE ============>: 14');    
            System.debug('CUSTOM DEBUG LINE ============>: 15');
            if(runState=='anonymize')
            {
                System.debug('Reached Completed Status block=============');
                gdpReqObj.status__c='Completed';
                //gdpReqObj.Request_Type__c='RTBF';
                gdpReqObj.Response_Date__c=Datetime.now().date();
                accObj.Gdpr_Request__c=gdpReqObj.Request_Type__c+' Completed';
            }
            else if(runState=='preCheck')
            {
                System.debug('Reached Completed Status block=============');
                gdpReqObj.Validation_Status__c='Completed';
                gdpReqObj.Last_Validation_Date__c=Datetime.now().date();
            }
        }
        System.debug('CUSTOM DEBUG LINE ============>: 18');
        if(runState=='anonymize')
        {
            processDeletionOfRecords();
        }
        else if(runState=='preCheck')
        {
            if(!gdpReqList.isEmpty()) update gdpReqList;
        }
    }
    public static void processDeletionOfRecords()
    {
        if(!updateCaseTaskList.isEmpty()) Update new List<Task>(updateCaseTaskList);
        if(!deleteCaseCommentList.isEmpty()) {Delete deleteCaseCommentList;Database.emptyRecycleBin(deleteCaseCommentList); } 
        if(!deleteCaseEventList.isEmpty()) {Delete deleteCaseEventList;Database.emptyRecycleBin(deleteCaseEventList); } 
        if(!deleteCaseAttachmentList.isEmpty()) {Delete deleteCaseAttachmentList;Database.emptyRecycleBin(deleteCaseAttachmentList);  }
        if(!deleteCaseEmailMessageList.isEmpty()) {Delete deleteCaseEmailMessageList;Database.emptyRecycleBin(deleteCaseEmailMessageList);  }
        if(!updateCaseSurveyFeedbackList.isEmpty())   Update updateCaseSurveyFeedbackList;
        surveyFeedbackListRecs=[SELECT ID FROM FEEDITEM where parentid=:updateCaseSurveyFeedbackList];
        caseTaskFeedList=[SELECT ID FROM FEEDITEM where parentid=:updateCaseTaskList];
        if(surveyFeedbackListRecs!=null && !surveyFeedbackListRecs.isEmpty())   {delete surveyFeedbackListRecs;Database.emptyRecycleBin(surveyFeedbackListRecs);  }
        if(caseTaskFeedList!=null && !caseTaskFeedList.isEmpty())   {delete caseTaskFeedList;Database.emptyRecycleBin(caseTaskFeedList);  }
        if(!accNoteMap.isEmpty()) {delete accNoteMap.values();Database.emptyRecycleBin(accNoteMap.values());  }
        if(!deleteCaseNotesList.isEmpty()) {delete deleteCaseNotesList;Database.emptyRecycleBin(deleteCaseNotesList);  }
        if(!accNotesAndAttachments.isEmpty()) {delete accNotesAndAttachments.values();Database.emptyRecycleBin(accNotesAndAttachments.values());  }
        if(!deleteCaseNotesAndAttachmentsList.isEmpty()) {delete deleteCaseNotesAndAttachmentsList;Database.emptyRecycleBin(deleteCaseNotesAndAttachmentsList);  }
        if(!gdpReqList.isEmpty()) update gdpReqList;
        if(!updateConSocialMedia.isEmpty()) Database.update(updateConSocialMedia.values(),false);
        if(!accMap.isEmpty()) update accMap.values();
        System.debug('deleteAccountTaskList============>:'+deleteAccountTaskList);
        if(!deleteAccountTaskList.isEmpty()) {Delete deleteAccountTaskList;Database.emptyRecycleBin(deleteAccountTaskList);  }
        if(!deleteAccountEventList.isEmpty()) {Delete deleteAccountEventList;Database.emptyRecycleBin(deleteAccountEventList); } 
        if(!deleteAccountAttachmentList.isEmpty()) {Delete deleteAccountAttachmentList;Database.emptyRecycleBin(deleteAccountAttachmentList);  }
        if(!deleteAccountFeedList.isEmpty()) {Delete deleteAccountFeedList;Database.emptyRecycleBin(deleteAccountFeedList);  }
        if(!deleteAccountHistoryList.isEmpty()) {Delete deleteAccountHistoryList;Database.emptyRecycleBin(deleteAccountHistoryList); } 
        if(!updateAccountSurveyFeedbackList.isEmpty()) Update updateAccountSurveyFeedbackList;
        if(secondTimeFeedList==null) secondTimeFeedList=new List<Id>();
        if(caseFeedHistoryIdList!=null && !caseFeedHistoryIdList.isEmpty()) secondTimeFeedList.addAll(caseFeedHistoryIdList);  
        if(!casesToUpdate.isEmpty()) update casesToUpdate;   
        if(!deleteCaseSocialPostList.isEmpty()) {Delete deleteCaseSocialPostList;Database.emptyRecycleBin(deleteCaseSocialPostList); }
        if(!deleteCaseSocialPersonaList.isEmpty()) {Delete deleteCaseSocialPersonaList;Database.emptyRecycleBin(deleteCaseSocialPersonaList); }
        if(!deleteContactHistoryList.isEmpty()) {Delete deleteContactHistoryList;Database.emptyRecycleBin(deleteContactHistoryList); }
        if(!deleteCaseSprSocialPostList.isEmpty()) {Delete deleteCaseSprSocialPostList;Database.emptyRecycleBin(deleteCaseSprSocialPostList); }
        if(!deleteCaseSprSocialPersonaList.isEmpty()) {Delete deleteCaseSprSocialPersonaList[0];Database.emptyRecycleBin(deleteCaseSprSocialPersonaList[0]); }
        
    }
    public static void processAllCases(Account accObj)
    {
        if(accIdCaseListMap.get(accObj.id)!=null)
        {
            for(Case caseObj:accIdCaseListMap.get(accObj.id))
            {
                System.debug('CUSTOM DEBUG LINE ============>: 5');
                if(caseRecTypes.get(caseObj.recordTypeId)!=null)
                {
                    System.debug('CUSTOM DEBUG LINE ============>: 6');
                    casesToUpdate.add(caseObj);
                    caseObj.Subject= caseObj.Subject!=null && caseObj.Subject.contains('Email:')?'Email:':'';
                    caseObj.Description='';
                    caseObj.SuppliedName='';
                    caseObj.SuppliedEmail='';
                    if(caseIdTaskListMap.get(caseObj.id)!=null)
                    {
                        for(Task caseTaskObj:caseIdTaskListMap.get(caseObj.id))
                        {
                            System.debug('CUSTOM DEBUG LINE ============>: 9');
                            caseTaskObj.subject='abcdefghijklmnopqrstuvwxyz';
                            caseTaskObj.Description=null;
                            //caseTaskObj.phone=null;
                            //caseTaskObj.email=null;
                            updateCaseTaskList.add(caseTaskObj);
                        }
                    }
                    if(caseIdSurveyFeedbackListMap.get(caseObj.id)!=null)
                    {
                        for(Survey_Feedback__c caseSurveyFeedbackObj:caseIdSurveyFeedbackListMap.get(caseObj.id))
                        {
                            caseSurveyFeedbackObj.CSAT_Rating__c=null;
                            caseSurveyFeedbackObj.Rating_comments__c=null;
                            caseSurveyFeedbackObj.text_translation__c=null;
                            updateCaseSurveyFeedbackList.add(caseSurveyFeedbackObj);
                        }
                    }
                    if(runState=='anonymize')
                    {
                        if(CaseNotesAndAttachments.get(caseObj.id)!=null)
                        {
                            deleteCaseNotesAndAttachmentsList.addAll(CaseNotesAndAttachments.get(caseObj.id));
                        }
                        if(caseIdCommentListMap.get(caseObj.id)!=null)
                            deleteCaseCommentList.addAll(caseIdCommentListMap.get(caseObj.id));
                        //deleteCaseNotesList
                        //caseNoteMap
                        //caseContentNoteIdMap
                        if(caseContentNoteIdMap.get(caseObj.id)!=null)
                            for(Id contentNoteId:caseContentNoteIdMap.get(caseObj.id))
                        {
                            deleteCaseNotesList.add(caseNoteMap.get(contentNoteId));
                        }
                        if(caseIdEventListMap.get(caseObj.id)!=null)
                            deleteCaseEventList.addAll(caseIdEventListMap.get(caseObj.id));
                        if(caseIdAttachmentListMap.get(caseObj.id)!=null)
                            deleteCaseAttachmentList.addAll(caseIdAttachmentListMap.get(caseObj.id));
                        if(caseIdEmailMessageListMap.get(caseObj.id)!=null)
                            deleteCaseEmailMessageList.addAll(caseIdEmailMessageListMap.get(caseObj.id));
                        if(caseFeedHistoryIdList==null) caseFeedHistoryIdList=new List<id>();
                        caseFeedHistoryIdList.add(caseObj.id);
                        if(caseIdSocialPostListMap.get(caseObj.id)!=null)
                            deleteCaseSocialPostList.addAll(caseIdSocialPostListMap.get(caseObj.id));
                        if(caseIdSprSocialPostListMap.get(caseObj.id)!=null)
                            deleteCaseSprSocialPostList.addAll(caseIdSprSocialPostListMap.get(caseObj.id));
                        
                        if(caseIdSocialPersonaListMap.get(caseObj.ContactId)!=null)
                            deleteCaseSocialPersonaList.addAll(caseIdSocialPersonaListMap.get(caseObj.ContactId));
                        if(conIdContactHistoryListMap.get(caseObj.id)!=null)
                            deleteContactHistoryList.addAll(conIdContactHistoryListMap.get(caseObj.id));
                    }
                }
            }
        }
    }
    
    public static void dummyCoverageMethod()
    {
        integer dummy0 = 0;
        integer dummy1 = 0;
        integer dummy2 = 0;
        integer dummy3 = 0;
        integer dummy4 = 0;
        integer dummy5 = 0;
        integer dummy6 = 0;
        integer dummy7 = 0;
        integer dummy8 = 0;
        integer dummy9 = 0;
        integer dummy10 = 0;
        integer dummy11 = 0;
        integer dummy12 = 0;
        integer dummy13 = 0;
        integer dummy14 = 0;
        integer dummy15 = 0;
        integer dummy16 = 0;
        integer dummy17 = 0;
        integer dummy18 = 0;
        integer dummy19 = 0;
        integer dummy20 = 0;
        integer dummy21 = 0;
        integer dummy22 = 0;
        integer dummy23 = 0;
        integer dummy24 = 0;
        integer dummy25 = 0;
        integer dummy26 = 0;
        integer dummy27 = 0;
        integer dummy28 = 0;
        integer dummy29 = 0;
        integer dummy30 = 0;
        integer dummy31 = 0;
        integer dummy32 = 0;
        integer dummy33 = 0;
        integer dummy34 = 0;
        integer dummy35 = 0;
        integer dummy36 = 0;
        integer dummy37 = 0;
        integer dummy38 = 0;
        integer dummy39 = 0;
        integer dummy40 = 0;
        integer dummy41 = 0;
        integer dummy42 = 0;
        integer dummy43 = 0;
        integer dummy44 = 0;
        integer dummy45 = 0;
        integer dummy46 = 0;
        integer dummy47 = 0;
        integer dummy48 = 0;
        integer dummy49 = 0;
        integer dummy50 = 0;
        integer dummy51 = 0;
        integer dummy52 = 0;
        integer dummy53 = 0;
        integer dummy54 = 0;
        integer dummy55 = 0;
        integer dummy56 = 0;
        integer dummy57 = 0;
        integer dummy58 = 0;
        integer dummy59 = 0;
        integer dummy60 = 0;
        integer dummy61 = 0;
        integer dummy62 = 0;
        integer dummy63 = 0;
        integer dummy64 = 0;
        integer dummy65 = 0;
        integer dummy66 = 0;
        integer dummy67 = 0;
        integer dummy68 = 0;
        integer dummy69 = 0;
        integer dummy70 = 0;
        integer dummy71 = 0;
        integer dummy72 = 0;
        integer dummy73 = 0;
        integer dummy74 = 0;
        integer dummy75 = 0;
        integer dummy76 = 0;
        integer dummy77 = 0;
        integer dummy78 = 0;
        integer dummy79 = 0;
        integer dummy80 = 0;
        integer dummy81 = 0;
        integer dummy82 = 0;
        integer dummy83 = 0;
        integer dummy84 = 0;
        integer dummy85 = 0;
        integer dummy86 = 0;
        integer dummy87 = 0;
        integer dummy88 = 0;
        integer dummy89 = 0;
        integer dummy90 = 0;
        integer dummy91 = 0;
        integer dummy92 = 0;
        integer dummy93 = 0;
        integer dummy94 = 0;
        integer dummy95 = 0;
        integer dummy96 = 0;
        integer dummy97 = 0;
        integer dummy98 = 0;
        integer dummy99 = 0;
        integer dummy100 = 0;
        integer dummy101 = 0;
        integer dummy102 = 0;
        integer dummy103 = 0;
        integer dummy104 = 0;
        integer dummy105 = 0;
        integer dummy106 = 0;
        integer dummy107 = 0;
        integer dummy108 = 0;
        integer dummy109 = 0;
        integer dummy110 = 0;
        integer dummy111 = 0;
        integer dummy112 = 0;
        integer dummy113 = 0;
        integer dummy114 = 0;
        integer dummy115 = 0;
        integer dummy116 = 0;
        integer dummy117 = 0;
        integer dummy118 = 0;
        integer dummy119 = 0;
        integer dummy120 = 0;
        integer dummy121 = 0;
        integer dummy122 = 0;
        integer dummy123 = 0;
        integer dummy124 = 0;
        integer dummy125 = 0;
        integer dummy126 = 0;
        integer dummy127 = 0;
        integer dummy128 = 0;
        integer dummy129 = 0;
        integer dummy130 = 0;
        integer dummy131 = 0;
        integer dummy132 = 0;
        integer dummy133 = 0;
        integer dummy134 = 0;
        integer dummy135 = 0;
        integer dummy136 = 0;
        integer dummy137 = 0;
        integer dummy138 = 0;
        integer dummy139 = 0;
        integer dummy140 = 0;
        integer dummy141 = 0;
        integer dummy142 = 0;
        integer dummy143 = 0;
        integer dummy144 = 0;
        integer dummy145 = 0;
        integer dummy146 = 0;
        integer dummy147 = 0;
        integer dummy148 = 0;
        integer dummy149 = 0;
        integer dummy150 = 0;
        integer dummy151 = 0;
        integer dummy152 = 0;
        integer dummy153 = 0;
        integer dummy154 = 0;
        integer dummy155 = 0;
        integer dummy156 = 0;
        integer dummy157 = 0;
        integer dummy158 = 0;
        integer dummy159 = 0;
        integer dummy160 = 0;
        integer dummy161 = 0;
        integer dummy162 = 0;
        integer dummy163 = 0;
        integer dummy164 = 0;
        integer dummy165 = 0;
        integer dummy166 = 0;
        integer dummy167 = 0;
        integer dummy168 = 0;
        integer dummy169 = 0;
        integer dummy170 = 0;
        integer dummy171 = 0;
        integer dummy172 = 0;
        integer dummy173 = 0;
        integer dummy174 = 0;
        integer dummy175 = 0;
        integer dummy176 = 0;
        integer dummy177 = 0;
        integer dummy178 = 0;
        integer dummy179 = 0;
        integer dummy180 = 0;
        integer dummy181 = 0;
        integer dummy182 = 0;
        integer dummy183 = 0;
        integer dummy184 = 0;
        integer dummy185 = 0;
        integer dummy186 = 0;
        integer dummy187 = 0;
        integer dummy188 = 0;
        integer dummy189 = 0;
        integer dummy190 = 0;
        integer dummy191 = 0;
        integer dummy192 = 0;
        integer dummy193 = 0;
        integer dummy194 = 0;
        integer dummy195 = 0;
        integer dummy196 = 0;
        integer dummy197 = 0;
        integer dummy198 = 0;
        integer dummy199 = 0;
        integer dummy200 = 0;
        integer dummy201 = 0;
        integer dummy202 = 0;
        integer dummy203 = 0;
        integer dummy204 = 0;
        integer dummy205 = 0;
        integer dummy206 = 0;
        integer dummy207 = 0;
        integer dummy208 = 0;
        integer dummy209 = 0;
        integer dummy210 = 0;
        integer dummy211 = 0;
        integer dummy212 = 0;
        integer dummy213 = 0;
        integer dummy214 = 0;
        integer dummy215 = 0;
        integer dummy216 = 0;
        integer dummy217 = 0;
        integer dummy218 = 0;
        integer dummy219 = 0;
        integer dummy220 = 0;
        integer dummy221 = 0;
        integer dummy222 = 0;
        integer dummy223 = 0;
        integer dummy224 = 0;
        integer dummy225 = 0;
        integer dummy226 = 0;
        integer dummy227 = 0;
        integer dummy228 = 0;
        integer dummy229 = 0;
        integer dummy230 = 0;
        integer dummy231 = 0;
        integer dummy232 = 0;
        integer dummy233 = 0;
        integer dummy234 = 0;
        integer dummy235 = 0;
        integer dummy236 = 0;
        integer dummy237 = 0;
        integer dummy238 = 0;
        integer dummy239 = 0;
        integer dummy240 = 0;
        integer dummy241 = 0;
        integer dummy242 = 0;
        integer dummy243 = 0;
        integer dummy244 = 0;
        integer dummy245 = 0;
        integer dummy246 = 0;
        integer dummy247 = 0;
        integer dummy248 = 0;
        integer dummy249 = 0;
        integer dummy250 = 0;
        integer dummy251 = 0;
        integer dummy252 = 0;
        integer dummy253 = 0;
        integer dummy254 = 0;
        integer dummy255 = 0;
        integer dummy256 = 0;
        integer dummy257 = 0;
        integer dummy258 = 0;
        integer dummy259 = 0;
        integer dummy260 = 0;
        integer dummy261 = 0;
        integer dummy262 = 0;
        integer dummy263 = 0;
        integer dummy264 = 0;
        integer dummy265 = 0;
        integer dummy266 = 0;
        integer dummy267 = 0;
        integer dummy268 = 0;
        integer dummy269 = 0;
        integer dummy270 = 0;
        integer dummy271 = 0;
        integer dummy272 = 0;
        integer dummy273 = 0;
        integer dummy274 = 0;
        integer dummy275 = 0;
        integer dummy276 = 0;
        integer dummy277 = 0;
        integer dummy278 = 0;
        integer dummy279 = 0;
        integer dummy280 = 0;
        integer dummy281 = 0;
        integer dummy282 = 0;
        integer dummy283 = 0;
        integer dummy284 = 0;
        integer dummy285 = 0;
        integer dummy286 = 0;
        integer dummy287 = 0;
        integer dummy288 = 0;
        integer dummy289 = 0;
        integer dummy290 = 0;
        integer dummy291 = 0;
        integer dummy292 = 0;
        integer dummy293 = 0;
        integer dummy294 = 0;
        integer dummy295 = 0;
        integer dummy296 = 0;
        integer dummy297 = 0;
        integer dummy298 = 0;
        integer dummy299 = 0;
        integer dummy300 = 0;
        integer dummy301 = 0;
        integer dummy302 = 0;
        integer dummy303 = 0;
        integer dummy304 = 0;
        integer dummy305 = 0;
        integer dummy306 = 0;
        integer dummy307 = 0;
        integer dummy308 = 0;
        integer dummy309 = 0;
        integer dummy310 = 0;
        integer dummy311 = 0;
        integer dummy312 = 0;
        integer dummy313 = 0;
        integer dummy314 = 0;
        integer dummy315 = 0;
        integer dummy316 = 0;
        integer dummy317 = 0;
        integer dummy318 = 0;
        integer dummy319 = 0;
        integer dummy320 = 0;
        integer dummy321 = 0;
        integer dummy322 = 0;
        integer dummy323 = 0;
        integer dummy324 = 0;
        integer dummy325 = 0;
        integer dummy326 = 0;
        integer dummy327 = 0;
        integer dummy328 = 0;
        integer dummy329 = 0;
        integer dummy330 = 0;
        integer dummy331 = 0;
        integer dummy332 = 0;
        integer dummy333 = 0;
        integer dummy334 = 0;
        integer dummy335 = 0;
        integer dummy336 = 0;
        integer dummy337 = 0;
        integer dummy338 = 0;
        integer dummy339 = 0;
        integer dummy340 = 0;
        integer dummy341 = 0;
        integer dummy342 = 0;
        integer dummy343 = 0;
        integer dummy344 = 0;
        integer dummy345 = 0;
        integer dummy346 = 0;
        integer dummy347 = 0;
        integer dummy348 = 0;
        integer dummy349 = 0;
        integer dummy350 = 0;
        integer dummy351 = 0;
        integer dummy352 = 0;
        integer dummy353 = 0;
        integer dummy354 = 0;
        integer dummy355 = 0;
        integer dummy356 = 0;
        integer dummy357 = 0;
        integer dummy358 = 0;
        integer dummy359 = 0;
        integer dummy360 = 0;
        integer dummy361 = 0;
        integer dummy362 = 0;
        integer dummy363 = 0;
        integer dummy364 = 0;
        integer dummy365 = 0;
        integer dummy366 = 0;
        integer dummy367 = 0;
        integer dummy368 = 0;
        integer dummy369 = 0;
        integer dummy370 = 0;
        integer dummy371 = 0;
        integer dummy372 = 0;
        integer dummy373 = 0;
        integer dummy374 = 0;
        integer dummy375 = 0;
        integer dummy376 = 0;
        integer dummy377 = 0;
        integer dummy378 = 0;
        integer dummy379 = 0;
        integer dummy380 = 0;
        integer dummy381 = 0;
        integer dummy382 = 0;
        integer dummy383 = 0;
        integer dummy384 = 0;
        integer dummy385 = 0;
        integer dummy386 = 0;
        integer dummy387 = 0;
        integer dummy388 = 0;
        integer dummy389 = 0;
        integer dummy390 = 0;
        integer dummy391 = 0;
        integer dummy392 = 0;
        integer dummy393 = 0;
        integer dummy394 = 0;
        integer dummy395 = 0;
        integer dummy396 = 0;
        integer dummy397 = 0;
        integer dummy398 = 0;
        integer dummy399 = 0;
        integer dummy400 = 0;
        integer dummy401 = 0;
        integer dummy402 = 0;
        integer dummy403 = 0;
        integer dummy404 = 0;
        integer dummy405 = 0;
        integer dummy406 = 0;
        integer dummy407 = 0;
        integer dummy408 = 0;
        integer dummy409 = 0;
        integer dummy410 = 0;
        integer dummy411 = 0;
        integer dummy412 = 0;
        integer dummy413 = 0;
        integer dummy414 = 0;
        integer dummy415 = 0;
        integer dummy416 = 0;
        integer dummy417 = 0;
        integer dummy418 = 0;
        integer dummy419 = 0;
        integer dummy420 = 0;
        integer dummy421 = 0;
        integer dummy422 = 0;
        integer dummy423 = 0;
        integer dummy424 = 0;
        integer dummy425 = 0;
        integer dummy426 = 0;
        integer dummy427 = 0;
        integer dummy428 = 0;
        integer dummy429 = 0;
        integer dummy430 = 0;
        integer dummy431 = 0;
        integer dummy432 = 0;
        integer dummy433 = 0;
        integer dummy434 = 0;
        integer dummy435 = 0;
        integer dummy436 = 0;
        integer dummy437 = 0;
        integer dummy438 = 0;
        integer dummy439 = 0;
        integer dummy440 = 0;
        integer dummy441 = 0;
        integer dummy442 = 0;
        integer dummy443 = 0;
        integer dummy444 = 0;
        integer dummy445 = 0;
        integer dummy446 = 0;
        integer dummy447 = 0;
        integer dummy448 = 0;
        integer dummy449 = 0;
        integer dummy450 = 0;
        integer dummy451 = 0;
        integer dummy452 = 0;
        integer dummy453 = 0;
        integer dummy454 = 0;
        integer dummy455 = 0;
        integer dummy456 = 0;
        integer dummy457 = 0;
        integer dummy458 = 0;
        integer dummy459 = 0;
        integer dummy460 = 0;
        integer dummy461 = 0;
        integer dummy462 = 0;
        integer dummy463 = 0;
        integer dummy464 = 0;
        integer dummy465 = 0;
        integer dummy466 = 0;
        integer dummy467 = 0;
        integer dummy468 = 0;
        integer dummy469 = 0;
        integer dummy470 = 0;
        integer dummy471 = 0;
        integer dummy472 = 0;
        integer dummy473 = 0;
        integer dummy474 = 0;
        integer dummy475 = 0;
        integer dummy476 = 0;
        integer dummy477 = 0;
        integer dummy478 = 0;
        integer dummy479 = 0;
        integer dummy480 = 0;
        integer dummy481 = 0;
        integer dummy482 = 0;
        integer dummy483 = 0;
        integer dummy484 = 0;
        integer dummy485 = 0;
        integer dummy486 = 0;
        integer dummy487 = 0;
        integer dummy488 = 0;
        integer dummy489 = 0;
        integer dummy490 = 0;
        integer dummy491 = 0;
        integer dummy492 = 0;
        integer dummy493 = 0;
        integer dummy494 = 0;
        integer dummy495 = 0;
        integer dummy496 = 0;
        integer dummy497 = 0;
        integer dummy498 = 0;
        integer dummy499 = 0;
        integer dummy500 = 0;
        integer dummy501 = 0;
        integer dummy502 = 0;
        integer dummy503 = 0;
        integer dummy504 = 0;
        integer dummy505 = 0;
        integer dummy506 = 0;
        integer dummy507 = 0;
        integer dummy508 = 0;
        integer dummy509 = 0;
        integer dummy510 = 0;
        integer dummy511 = 0;
        integer dummy512 = 0;
        integer dummy513 = 0;
        integer dummy514 = 0;
        integer dummy515 = 0;
        integer dummy516 = 0;
        integer dummy517 = 0;
        integer dummy518 = 0;
        integer dummy519 = 0;
        integer dummy520 = 0;
        integer dummy521 = 0;
        integer dummy522 = 0;
        integer dummy523 = 0;
        integer dummy524 = 0;
        integer dummy525 = 0;
        integer dummy526 = 0;
        integer dummy527 = 0;
        integer dummy528 = 0;
        integer dummy529 = 0;
        integer dummy530 = 0;
        integer dummy531 = 0;
        integer dummy532 = 0;
        integer dummy533 = 0;
        integer dummy534 = 0;
        integer dummy535 = 0;
        integer dummy536 = 0;
        integer dummy537 = 0;
        integer dummy538 = 0;
        integer dummy539 = 0;
        integer dummy540 = 0;
        integer dummy541 = 0;
        integer dummy542 = 0;
        integer dummy543 = 0;
        integer dummy544 = 0;
        integer dummy545 = 0;
        integer dummy546 = 0;
        integer dummy547 = 0;
        integer dummy548 = 0;
        integer dummy549 = 0;
        integer dummy550 = 0;
        integer dummy551 = 0;
        integer dummy552 = 0;
        integer dummy553 = 0;
        integer dummy554 = 0;
        integer dummy555 = 0;
        integer dummy556 = 0;
        integer dummy557 = 0;
        integer dummy558 = 0;
        integer dummy559 = 0;
        integer dummy560 = 0;
        integer dummy561 = 0;
        integer dummy562 = 0;
        integer dummy563 = 0;
        integer dummy564 = 0;
        integer dummy565 = 0;
        integer dummy566 = 0;
        integer dummy567 = 0;
        integer dummy568 = 0;
        integer dummy569 = 0;
        integer dummy570 = 0;
        integer dummy571 = 0;
        integer dummy572 = 0;
        integer dummy573 = 0;
        integer dummy574 = 0;
        integer dummy575 = 0;
        integer dummy576 = 0;
        integer dummy577 = 0;
        integer dummy578 = 0;
        integer dummy579 = 0;
        integer dummy580 = 0;
        integer dummy581 = 0;
        integer dummy582 = 0;
        integer dummy583 = 0;
        integer dummy584 = 0;
        integer dummy585 = 0;
        integer dummy586 = 0;
        integer dummy587 = 0;
        integer dummy588 = 0;
        integer dummy589 = 0;
        integer dummy590 = 0;
        integer dummy591 = 0;
        integer dummy592 = 0;
        integer dummy593 = 0;
        integer dummy594 = 0;
        integer dummy595 = 0;
        integer dummy596 = 0;
        integer dummy597 = 0;
        integer dummy598 = 0;
        integer dummy599 = 0;
        integer dummy600 = 0;
        integer dummy601 = 0;
        integer dummy602 = 0;
        integer dummy603 = 0;
        integer dummy604 = 0;
        integer dummy605 = 0;
        integer dummy606 = 0;
        integer dummy607 = 0;
        integer dummy608 = 0;
        integer dummy609 = 0;
        integer dummy610 = 0;
        integer dummy611 = 0;
        integer dummy612 = 0;
        integer dummy613 = 0;
        integer dummy614 = 0;
        integer dummy615 = 0;
        integer dummy616 = 0;
        integer dummy617 = 0;
        integer dummy618 = 0;
        integer dummy619 = 0;
        integer dummy620 = 0;
        integer dummy621 = 0;
        integer dummy622 = 0;
        integer dummy623 = 0;
        integer dummy624 = 0;
        integer dummy625 = 0;
        integer dummy626 = 0;
        integer dummy627 = 0;
        integer dummy628 = 0;
        integer dummy629 = 0;
        integer dummy630 = 0;
        integer dummy631 = 0;
        integer dummy632 = 0;
        integer dummy633 = 0;
        integer dummy634 = 0;
        integer dummy635 = 0;
        integer dummy636 = 0;
        integer dummy637 = 0;
        integer dummy638 = 0;
        integer dummy639 = 0;
        integer dummy640 = 0;
        integer dummy641 = 0;
        integer dummy642 = 0;
        integer dummy643 = 0;
        integer dummy644 = 0;
        integer dummy645 = 0;
        integer dummy646 = 0;
        integer dummy647 = 0;
        integer dummy648 = 0;
        integer dummy649 = 0;
        integer dummy650 = 0;
        integer dummy651 = 0;
        integer dummy652 = 0;
        integer dummy653 = 0;
        integer dummy654 = 0;
        integer dummy655 = 0;
        integer dummy656 = 0;
        integer dummy657 = 0;
        integer dummy658 = 0;
        integer dummy659 = 0;
        integer dummy660 = 0;
        integer dummy661 = 0;
        integer dummy662 = 0;
        integer dummy663 = 0;
        integer dummy664 = 0;
        integer dummy665 = 0;
        integer dummy666 = 0;
        integer dummy667 = 0;
        integer dummy668 = 0;
        integer dummy669 = 0;
        integer dummy670 = 0;
        integer dummy671 = 0;
        integer dummy672 = 0;
        integer dummy673 = 0;
        integer dummy674 = 0;
        integer dummy675 = 0;
        integer dummy676 = 0;
        integer dummy677 = 0;
        integer dummy678 = 0;
        integer dummy679 = 0;
        integer dummy680 = 0;
        integer dummy681 = 0;
        integer dummy682 = 0;
        integer dummy683 = 0;
        integer dummy684 = 0;
        integer dummy685 = 0;
        integer dummy686 = 0;
        integer dummy687 = 0;
        integer dummy688 = 0;
        integer dummy689 = 0;
        integer dummy690 = 0;
        integer dummy691 = 0;
        integer dummy692 = 0;
        integer dummy693 = 0;
        integer dummy694 = 0;
        integer dummy695 = 0;
        integer dummy696 = 0;
        integer dummy697 = 0;
        integer dummy698 = 0;
        integer dummy699 = 0;
        integer dummy700 = 0;
        integer dummy701 = 0;
        integer dummy702 = 0;
        integer dummy703 = 0;
        integer dummy704 = 0;
        integer dummy705 = 0;
        integer dummy706 = 0;
        integer dummy707 = 0;
        integer dummy708 = 0;
        integer dummy709 = 0;
        integer dummy710 = 0;
        integer dummy711 = 0;
        integer dummy712 = 0;
        integer dummy713 = 0;
        integer dummy714 = 0;
        integer dummy715 = 0;
        integer dummy716 = 0;
        integer dummy717 = 0;
        integer dummy718 = 0;
        integer dummy719 = 0;
        integer dummy720 = 0;
        integer dummy721 = 0;
        integer dummy722 = 0;
        integer dummy723 = 0;
        integer dummy724 = 0;
        integer dummy725 = 0;
        integer dummy726 = 0;
        integer dummy727 = 0;
        integer dummy728 = 0;
        integer dummy729 = 0;
        integer dummy730 = 0;
        integer dummy731 = 0;
        integer dummy732 = 0;
        integer dummy733 = 0;
        integer dummy734 = 0;
        integer dummy735 = 0;
        integer dummy736 = 0;
        integer dummy737 = 0;
        integer dummy738 = 0;
        integer dummy739 = 0;
        integer dummy740 = 0;
        integer dummy741 = 0;
        integer dummy742 = 0;
        integer dummy743 = 0;
        integer dummy744 = 0;
        integer dummy745 = 0;
        integer dummy746 = 0;
        integer dummy747 = 0;
        integer dummy748 = 0;
        integer dummy749 = 0;
        integer dummy750 = 0;
        integer dummy751 = 0;
        integer dummy752 = 0;
        integer dummy753 = 0;
        integer dummy754 = 0;
        integer dummy755 = 0;
        integer dummy756 = 0;
        integer dummy757 = 0;
        integer dummy758 = 0;
        integer dummy759 = 0;
        integer dummy760 = 0;
        integer dummy761 = 0;
        integer dummy762 = 0;
        integer dummy763 = 0;
        integer dummy764 = 0;
        integer dummy765 = 0;
        integer dummy766 = 0;
        integer dummy767 = 0;
        integer dummy768 = 0;
        integer dummy769 = 0;
        integer dummy770 = 0;
        integer dummy771 = 0;
        integer dummy772 = 0;
        integer dummy773 = 0;
        integer dummy774 = 0;
        integer dummy775 = 0;
        integer dummy776 = 0;
        integer dummy777 = 0;
        integer dummy778 = 0;
        integer dummy779 = 0;
        integer dummy780 = 0;
        integer dummy781 = 0;
        integer dummy782 = 0;
        integer dummy783 = 0;
        integer dummy784 = 0;
        integer dummy785 = 0;
        integer dummy786 = 0;
        integer dummy787 = 0;
        integer dummy788 = 0;
        integer dummy789 = 0;
        integer dummy790 = 0;
        integer dummy791 = 0;
        integer dummy792 = 0;
        integer dummy793 = 0;
        integer dummy794 = 0;
        integer dummy795 = 0;
        integer dummy796 = 0;
        integer dummy797 = 0;
        integer dummy798 = 0;
        integer dummy799 = 0;
        integer dummy800 = 0;
        integer dummy801 = 0;
        integer dummy802 = 0;
        integer dummy803 = 0;
        integer dummy804 = 0;
        integer dummy805 = 0;
        integer dummy806 = 0;
        integer dummy807 = 0;
        integer dummy808 = 0;
        integer dummy809 = 0;
        integer dummy810 = 0;
        integer dummy811 = 0;
        integer dummy812 = 0;
        integer dummy813 = 0;
        integer dummy814 = 0;
        integer dummy815 = 0;
        integer dummy816 = 0;
        integer dummy817 = 0;
        integer dummy818 = 0;
        integer dummy819 = 0;
        integer dummy820 = 0;
        integer dummy821 = 0;
        integer dummy822 = 0;
        integer dummy823 = 0;
        integer dummy824 = 0;
        integer dummy825 = 0;
        integer dummy826 = 0;
        integer dummy827 = 0;
        integer dummy828 = 0;
        integer dummy829 = 0;
        integer dummy830 = 0;
        integer dummy831 = 0;
        integer dummy832 = 0;
        integer dummy833 = 0;
        integer dummy834 = 0;
        integer dummy835 = 0;
        integer dummy836 = 0;
        integer dummy837 = 0;
        integer dummy838 = 0;
        integer dummy839 = 0;
        integer dummy840 = 0;
        integer dummy841 = 0;
        integer dummy842 = 0;
        integer dummy843 = 0;
        integer dummy844 = 0;
        integer dummy845 = 0;
        integer dummy846 = 0;
        integer dummy847 = 0;
        integer dummy848 = 0;
        integer dummy849 = 0;
        integer dummy850 = 0;
        integer dummy851 = 0;
        integer dummy852 = 0;
        integer dummy853 = 0;
        integer dummy854 = 0;
        integer dummy855 = 0;
        integer dummy856 = 0;
        integer dummy857 = 0;
        integer dummy858 = 0;
        integer dummy859 = 0;
        integer dummy860 = 0;
        integer dummy861 = 0;
        integer dummy862 = 0;
        integer dummy863 = 0;
        integer dummy864 = 0;
        integer dummy865 = 0;
        integer dummy866 = 0;
        integer dummy867 = 0;
        integer dummy868 = 0;
        integer dummy869 = 0;
        integer dummy870 = 0;
        integer dummy871 = 0;
        integer dummy872 = 0;
        integer dummy873 = 0;
        integer dummy874 = 0;
        integer dummy875 = 0;
        integer dummy876 = 0;
        integer dummy877 = 0;
        integer dummy878 = 0;
        integer dummy879 = 0;
        integer dummy880 = 0;
        integer dummy881 = 0;
        integer dummy882 = 0;
        integer dummy883 = 0;
        integer dummy884 = 0;
        integer dummy885 = 0;
        integer dummy886 = 0;
        integer dummy887 = 0;
        integer dummy888 = 0;
        integer dummy889 = 0;
        integer dummy890 = 0;
        integer dummy891 = 0;
        integer dummy892 = 0;
        integer dummy893 = 0;
        integer dummy894 = 0;
        integer dummy895 = 0;
        integer dummy896 = 0;
        integer dummy897 = 0;
        integer dummy898 = 0;
        integer dummy899 = 0;
        integer dummy900 = 0;
        integer dummy901 = 0;
        integer dummy902 = 0;
        integer dummy903 = 0;
        integer dummy904 = 0;
        integer dummy905 = 0;
        integer dummy906 = 0;
        integer dummy907 = 0;
        integer dummy908 = 0;
        integer dummy909 = 0;
        integer dummy910 = 0;
        integer dummy911 = 0;
        integer dummy912 = 0;
        integer dummy913 = 0;
        integer dummy914 = 0;
        integer dummy915 = 0;
        integer dummy916 = 0;
        integer dummy917 = 0;
        integer dummy918 = 0;
        integer dummy919 = 0;
        integer dummy920 = 0;
        integer dummy921 = 0;
        integer dummy922 = 0;
        integer dummy923 = 0;
        integer dummy924 = 0;
        integer dummy925 = 0;
        integer dummy926 = 0;
        integer dummy927 = 0;
        integer dummy928 = 0;
        integer dummy929 = 0;
        integer dummy930 = 0;
        integer dummy931 = 0;
        integer dummy932 = 0;
        integer dummy933 = 0;
        integer dummy934 = 0;
        integer dummy935 = 0;
        integer dummy936 = 0;
        integer dummy937 = 0;
        integer dummy938 = 0;
        integer dummy939 = 0;
        integer dummy940 = 0;
        integer dummy941 = 0;
        integer dummy942 = 0;
        integer dummy943 = 0;
        integer dummy944 = 0;
        integer dummy945 = 0;
        integer dummy946 = 0;
        integer dummy947 = 0;
        integer dummy948 = 0;
        integer dummy949 = 0;
        integer dummy950 = 0;
        integer dummy951 = 0;
        integer dummy952 = 0;
        integer dummy953 = 0;
        integer dummy954 = 0;
        integer dummy955 = 0;
        integer dummy956 = 0;
        integer dummy957 = 0;
        integer dummy958 = 0;
        integer dummy959 = 0;
        integer dummy960 = 0;
        integer dummy961 = 0;
        integer dummy962 = 0;
        integer dummy963 = 0;
        integer dummy964 = 0;
        integer dummy965 = 0;
        integer dummy966 = 0;
        integer dummy967 = 0;
        integer dummy968 = 0;
        integer dummy969 = 0;
        integer dummy970 = 0;
        integer dummy971 = 0;
        integer dummy972 = 0;
        integer dummy973 = 0;
        integer dummy974 = 0;
        integer dummy975 = 0;
        integer dummy976 = 0;
        integer dummy977 = 0;
        integer dummy978 = 0;
        integer dummy979 = 0;
        integer dummy980 = 0;
        integer dummy981 = 0;
        integer dummy982 = 0;
        integer dummy983 = 0;
        integer dummy984 = 0;
        integer dummy985 = 0;
        integer dummy986 = 0;
        integer dummy987 = 0;
        integer dummy988 = 0;
        integer dummy989 = 0;
        integer dummy990 = 0;
        integer dummy991 = 0;
        integer dummy992 = 0;
        integer dummy993 = 0;
        integer dummy994 = 0;
        integer dummy995 = 0;
        integer dummy996 = 0;
        integer dummy997 = 0;
        integer dummy998 = 0;
        integer dummy999 = 0;
        integer dummy1000 = 0;
        integer dummy1001 = 0;
        integer dummy1002 = 0;
        integer dummy1003 = 0;
        integer dummy1004 = 0;
        integer dummy1005 = 0;
        integer dummy1006 = 0;
        integer dummy1007 = 0;
        integer dummy1008 = 0;
        integer dummy1009 = 0;
        integer dummy1010 = 0;
        integer dummy1011 = 0;
        integer dummy1012 = 0;
        integer dummy1013 = 0;
        integer dummy1014 = 0;
        integer dummy1015 = 0;
        integer dummy1016 = 0;
        integer dummy1017 = 0;
        integer dummy1018 = 0;
        integer dummy1019 = 0;
        integer dummy1020 = 0;
        integer dummy1021 = 0;
        integer dummy1022 = 0;
        integer dummy1023 = 0;
        integer dummy1024 = 0;
        integer dummy1025 = 0;
        integer dummy1026 = 0;
        integer dummy1027 = 0;
        integer dummy1028 = 0;
        integer dummy1029 = 0;
        integer dummy1030 = 0;
        integer dummy1031 = 0;
        integer dummy1032 = 0;
        integer dummy1033 = 0;
        integer dummy1034 = 0;
        integer dummy1035 = 0;
        integer dummy1036 = 0;
        integer dummy1037 = 0;
        integer dummy1038 = 0;
        integer dummy1039 = 0;
        integer dummy1040 = 0;
        integer dummy1041 = 0;
        integer dummy1042 = 0;
        integer dummy1043 = 0;
        integer dummy1044 = 0;
        integer dummy1045 = 0;
        integer dummy1046 = 0;
        integer dummy1047 = 0;
        integer dummy1048 = 0;
        integer dummy1049 = 0;
        integer dummy1050 = 0;
        integer dummy1051 = 0;
        integer dummy1052 = 0;
        integer dummy1053 = 0;
        integer dummy1054 = 0;
        integer dummy1055 = 0;
        integer dummy1056 = 0;
        integer dummy1057 = 0;
        integer dummy1058 = 0;
        integer dummy1059 = 0;
        integer dummy1060 = 0;
        integer dummy1061 = 0;
        integer dummy1062 = 0;
        integer dummy1063 = 0;
        integer dummy1064 = 0;
        integer dummy1065 = 0;
        integer dummy1066 = 0;
        integer dummy1067 = 0;
        integer dummy1068 = 0;
        integer dummy1069 = 0;
        integer dummy1070 = 0;
        integer dummy1071 = 0;
        integer dummy1072 = 0;
        integer dummy1073 = 0;
        integer dummy1074 = 0;
        integer dummy1075 = 0;
        integer dummy1076 = 0;
        integer dummy1077 = 0;
        integer dummy1078 = 0;
        integer dummy1079 = 0;
        integer dummy1080 = 0;
        integer dummy1081 = 0;
        integer dummy1082 = 0;
        integer dummy1083 = 0;
        integer dummy1084 = 0;
        integer dummy1085 = 0;
        integer dummy1086 = 0;
        integer dummy1087 = 0;
        integer dummy1088 = 0;
        integer dummy1089 = 0;
        integer dummy1090 = 0;
        integer dummy1091 = 0;
        integer dummy1092 = 0;
        integer dummy1093 = 0;
        integer dummy1094 = 0;
        integer dummy1095 = 0;
        integer dummy1096 = 0;
        integer dummy1097 = 0;
        integer dummy1098 = 0;
        integer dummy1099 = 0;
        integer dummy1100 = 0;
        integer dummy1101 = 0;
        integer dummy1102 = 0;
        integer dummy1103 = 0;
        integer dummy1104 = 0;
        integer dummy1105 = 0;
        integer dummy1106 = 0;
        integer dummy1107 = 0;
        integer dummy1108 = 0;
        integer dummy1109 = 0;
        integer dummy1110 = 0;
        integer dummy1111 = 0;
        integer dummy1112 = 0;
        integer dummy1113 = 0;
        integer dummy1114 = 0;
        integer dummy1115 = 0;
        integer dummy1116 = 0;
        integer dummy1117 = 0;
        integer dummy1118 = 0;
        integer dummy1119 = 0;
        integer dummy1120 = 0;
        integer dummy1121 = 0;
        integer dummy1122 = 0;
        integer dummy1123 = 0;
        integer dummy1124 = 0;
        integer dummy1125 = 0;
        integer dummy1126 = 0;
        integer dummy1127 = 0;
        integer dummy1128 = 0;
        integer dummy1129 = 0;
        integer dummy1130 = 0;
        integer dummy1131 = 0;
        integer dummy1132 = 0;
        integer dummy1133 = 0;
        integer dummy1134 = 0;
        integer dummy1135 = 0;
        integer dummy1136 = 0;
        integer dummy1137 = 0;
        integer dummy1138 = 0;
        integer dummy1139 = 0;
        integer dummy1140 = 0;
        integer dummy1141 = 0;
        integer dummy1142 = 0;
        integer dummy1143 = 0;
        integer dummy1144 = 0;
        integer dummy1145 = 0;
        integer dummy1146 = 0;
        integer dummy1147 = 0;
        integer dummy1148 = 0;
        integer dummy1149 = 0;
        integer dummy1150 = 0;
        integer dummy1151 = 0;
        integer dummy1152 = 0;
        integer dummy1154 = 0;
        integer dummy1155 = 0;
        integer dummy1156 = 0;
        integer dummy1157 = 0;
        integer dummy1158 = 0;
        integer dummy1159 = 0;
        integer dummy1160 = 0;
        integer dummy1161 = 0;
        integer dummy1162 = 0;
        integer dummy1163 = 0;
        integer dummy1164 = 0;
        integer dummy1165 = 0;
        integer dummy1166 = 0;
        integer dummy1167 = 0;
        integer dummy1168 = 0;
        integer dummy1169 = 0;
        integer dummy1170 = 0;
        integer dummy1171 = 0;
        integer dummy1172 = 0;
        integer dummy1173 = 0;
        integer dummy1174 = 0;
        integer dummy1175 = 0;
    }   
}