care/force-app/main/default/objects/GDPR_Settings__mdt/GDPR_Settings__mdt.object-meta.xml
<CustomObject>
    <label>GDPR Settings</label>
    <pluralLabel>GDPR Settings</pluralLabel>
</CustomObject>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Data_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Data_Batch_Size__c</fullName>
    <description>This specifies the batch size of RTBF/Retention Data</description>
    <inlineHelpText>Enter RTBF/Retention Data Batch Size</inlineHelpText>
    <label>Data Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Feed_Data_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Feed_Data_Batch_Size__c</fullName>
    <description>This specifies the batch size of RTBF/Retention Feed Data</description>
    <inlineHelpText>Enter RTBF/Retention Feed Data Batch Size</inlineHelpText>
    <label>Feed Data Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/History_Data_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>History_Data_Batch_Size__c</fullName>
    <description>This specifies the batch size of RTBF/Retention History Data</description>
    <inlineHelpText>Enter RTBF/Retention History Data Batch Size</inlineHelpText>
    <label>History Data Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Override_Account_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Override_Account_Record_Type__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean flag, upon checking this, Skips Account Record Type validation while anonymyzing account.</description>
    <inlineHelpText>Check to override Account Record Type validation.</inlineHelpText>
    <label>Override Account Record Type</label>
    <type>Checkbox</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Override_Employer_Program__c.field-meta.xml
<CustomField>
    <fullName>Override_Employer_Program__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean flag, upon checking this, Skips Employer Program validation while anonymizing account.</description>
    <inlineHelpText>Check to override Employer Program validation.</inlineHelpText>
    <label>Override Employer Program</label>
    <type>Checkbox</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Override_Premium__c.field-meta.xml
<CustomField>
    <fullName>Override_Premium__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean flag, upon checking this, Skips Premium validation while anonymyzing account.</description>
    <inlineHelpText>Check to override premium validation.</inlineHelpText>
    <label>Override Premium</label>
    <type>Checkbox</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Override_Safety_Case__c.field-meta.xml
<CustomField>
    <fullName>Override_Safety_Case__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean flag, upon checking this, Skips Safety Case validation while anonymyzing account.</description>
    <inlineHelpText>Check to override Safety Case validation.</inlineHelpText>
    <label>Override Safety Case</label>
    <type>Checkbox</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Process_RTBF_Retention_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Process_RTBF_Retention_Request_Type__c</fullName>
    <description>Choose request type as either RTBF/Retention in Request Data.</description>
    <inlineHelpText>Choose request type as either RTBF/Retention in Request Data.</inlineHelpText>
    <label>Process RTBF/Retention Request Type?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RTBF</fullName>
                <default>true</default>
                <label>RTBF</label>
            </value>
            <value>
                <fullName>Retention</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/RTBF_Retention__c.field-meta.xml
<CustomField>
    <fullName>RTBF_Retention__c</fullName>
    <description>Provide option to choose the process type is RTBF or Retention</description>
    <inlineHelpText>Choose RTBF or Retention process and provide the corresponding validation on/off checks  like Safety Case/Premium/Employer Program/Record Type.</inlineHelpText>
    <label>RTBF/Retention</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RTBF</fullName>
                <default>true</default>
                <label>RTBF</label>
            </value>
            <value>
                <fullName>Retention</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Schedule_Mode__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Mode__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked when GDPR in Schedule run mode</description>
    <inlineHelpText>Check to GDPR in Schedule Mode</inlineHelpText>
    <label>Schedule Mode</label>
    <type>Checkbox</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Status_To_Process__c.field-meta.xml
<CustomField>
    <fullName>Status_To_Process__c</fullName>
    <description>Mention GDPR Status to process. Ex:- Use &apos;Test&apos; for testing phase</description>
    <inlineHelpText>Mention GDPR Status to process. Ex:- Use &apos;Test&apos; for testing phase</inlineHelpText>
    <label>Status To Process</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/GDPR_Settings__mdt/fields/Time_To_Schedule_SSMMHH__c.field-meta.xml
<CustomField>
    <fullName>Time_To_Schedule_SSMMHH__c</fullName>
    <description>Enter GDPR schedule time in SSMMHH format</description>
    <inlineHelpText>Enter GDPR schedule time in SSMMHH format</inlineHelpText>
    <label>Time To Schedule(SSMMHH)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Request_Data__c/Request_Data__c.object-meta.xml
<CustomObject>
    <description>This objects holds the GDPR member data,it&apos;s status and other key information</description>
    <label>Request Data</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}-{000000}</displayFormat>
        <label>Request Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Request_Data__c/fields/Global_Member_ID__c.field-meta.xml
<CustomField>
    <fullName>Global_Member_ID__c</fullName>
    <description>Unique identifier of  Sterling platform account</description>
    <label>Global Member ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Request_Data__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <description>Tells whether the request is RTBF or Retention</description>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RTBF</fullName>
            </value>
            <value>
                <fullName>Retention</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>RTBF Fail - Invalid Record Type</fullName>
            </value>
            <value>
                <fullName>RTBF Fail - Employer Program</fullName>
            </value>
            <value>
                <fullName>RTBF Fail - Safety Case</fullName>
            </value>
            <value>
                <fullName>RTBF Fail - Premium</fullName>
            </value>
            <value>
                <fullName>RTBF Fix</fullName>
            </value>
            <value>
                <fullName>RTBF Override</fullName>
            </value>
            <value>
                <fullName>RTBF Complete</fullName>
            </value>
            <value>
                <fullName>RTBF Do Not Process</fullName>
            </value>
            <value>
                <fullName>RTBF Anonymize</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Request_Data__c/fields/Response_Date__c.field-meta.xml
<CustomField>
    <fullName>Response_Date__c</fullName>
    <description>Date specifies the day when the ananymization process is completed.</description>
    <label>Response Date</label>
    <type>Date</type>
</CustomField>

care/force-app/main/default/objects/Request_Data__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field is used to hold the status of delete request.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Safety Case</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Invalid Record Type</fullName>
            </value>
            <value>
                <fullName>Employer Program</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>RTBF Fail - Invalid Record Type</fullName>
            </value>
            <value>
                <fullName>RTBF Fail - Employer Program</fullName>
            </value>
            <value>
                <fullName>RTBF Fail - Safety Case</fullName>
            </value>
            <value>
                <fullName>RTBF Fail - Premium</fullName>
            </value>
            <value>
                <fullName>RTBF Fix</fullName>
            </value>
            <value>
                <fullName>RTBF Override</fullName>
            </value>
            <value>
                <fullName>RTBF Complete</fullName>
            </value>
            <value>
                <fullName>RTBF Do Not Process</fullName>
            </value>
            <value>
                <fullName>RTBF Anonymize</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/classes/Test_BatchGDPRAccFeedHistDelProcessSADT.cls
//Modified by By: Mohammed Ashwaq
//Modified Date: 10/11/2020
//Test class for: BatchGDPRAccFeedHistDelProcess
@isTest(SeeAllData = true)
private class Test_BatchGDPRAccFeedHistDelProcessSADT {
    Public static String intlPvdr = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('International Provider').getRecordTypeId();
    Public static String intlSeeker = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('International Seeker').getRecordTypeId();
    Public static String day = String.valueOf(Datetime.now().day());
    Public static String month = String.valueOf(Datetime.now().month());
    Public static String year = String.valueOf(Datetime.now().year());
    Public static String hour = String.valueOf(Datetime.now().hour());
    Public static String min = String.valueOf(Datetime.now().minute() <= 58 ? Datetime.now().minute() + 1 : Datetime.now().minute());
    Public static String ss = String.valueOf(Datetime.now().second());
    Public static String nextFireTime = ss + ' ' + min + ' ' + hour + ' ' + day + ' ' + month + ' ' + '?  ' + year;
    @isTest(SeeAllData = true)
    static void test5() {
        Test.startTest();
        Account a = new Account(lastname = 'Test', Gdpr_request__c = 'RTBF Anonymize', recordtypeid = intlSeeker, Global_Member_Id__c = '123456781');
        Account a1 = new Account(lastname = 'Test', Gdpr_request__c = 'RTBF Anonymize', recordtypeid = intlSeeker, Global_Member_Id__c = '1234567891');
        insert new List < Account > {a,a1};
        a.lastname = 'Test1';
        update new List < Account > {a,a1};
        AccountHistory ah = new AccountHistory(accountid = a.id);
        Request_Data__c gdprObj = new Request_Data__c(Status__c = 'New', Request_Type__c = 'RTBF Anonymize', Global_Member_Id__c = '123456781');
        Request_Data__c gdprObj1 = new Request_Data__c(Status__c = 'New', Request_Type__c = 'RTBF Anonymize', Global_Member_Id__c = '1234567891');
        upsert new List < Request_Data__c > { gdprObj, gdprObj1};
        List < Id > caseFeedList;
        GDPR_Settings__mdt rtbfSettings = [select id, DeveloperName, Process_RTBF_Retention_Request_Type__c, MasterLabel, Data_Batch_Size__c, Feed_Data_Batch_Size__c, History_Data_Batch_Size__c, Override_Account_Record_Type__c, Override_Employer_Program__c, Override_Premium__c, Override_Safety_Case__c, RTBF_Retention__c, Schedule_Mode__c, Status_To_Process__c, Time_To_Schedule_SSMMHH__c from GDPR_Settings__mdt where RTBF_Retention__c = 'RTBF'];
        List < Request_Data__c > gdprList = new List < Request_Data__c > {gdprObj, gdprObj1};
        BatchGDPRAccFeedDelProcess btch = new BatchGDPRAccFeedDelProcess();
        //Database.executeBatch(new BatchGDPRAccHistoryDelProcess(true));
        List<CronTrigger> cronObj=[SELECT id FROM CronTrigger where CronJobDetail.name='Process GdprHistory Schedule'];
        if(cronObj.size()>0){
            System.abortJob(cronObj[0].id);
        }
        else{
            System.schedule('Process GdprHistory Schedule', nextFireTime, new BatchGDPRAccFeedDelProcess(true));
        }
        Test.stopTest();
    }
    @isTest(SeeAllData = true)
    static void test4() {
        Test.startTest();
        Account a = new Account(lastname = 'Test', Gdpr_request__c = 'Retention', recordtypeid = intlSeeker, Global_Member_Id__c = '12345678', Type__pc = 'Premium');
        insert a;
        a.lastname = 'Test1';
        update a;
        AccountHistory ah = new AccountHistory(accountid = a.id);
        //insert ah;
        Request_Data__c gdprObj = new Request_Data__c(Request_Type__c = 'Retention', Status__c = 'New', Global_Member_Id__c = '12345678');
        System.assert(gdprObj.Global_Member_Id__c == a.Global_Member_Id__c);
        upsert gdprObj;
        Test.stopTest();
    }
    @isTest(SeeAllData = true)
    static void test3() {
        Test.startTest();
        Account a = new Account(lastname = 'Test', Gdpr_request__c = 'RTBF Override', recordtypeid = intlSeeker, Global_Member_Id__c = '12345678', Type__pc = 'Premium');
        insert a;
        a.lastname = 'Test1';
        update a;
        AccountHistory ah = new AccountHistory(accountid = null);
        Request_Data__c gdprObj = new Request_Data__c(Request_Type__c = 'RTBF Fix', Status__c = 'New', Global_Member_Id__c = '12345678');
        System.assert(gdprObj.Global_Member_Id__c == a.Global_Member_Id__c);
        upsert gdprObj;
        gdprObj.Request_Type__c = 'RTBF Override';
        update gdprObj;
        Test.stopTest();
    }
    @isTest(SeeAllData = true)
    static void test2() {
        Test.startTest();
        Account a = new Account(lastname = 'Test', Gdpr_request__c = 'RTBF Do Not Process', recordtypeid = intlSeeker, Global_Member_Id__c = '12345678', Type__pc = 'Premium');
        insert a;
        a.lastname = 'Test1';
        update a;
        AccountHistory ah = new AccountHistory(accountid = a.id);
        //insert ah;
        Request_Data__c gdprObj = new Request_Data__c(Request_Type__c = 'RTBF Do Not Process', Status__c = 'New', Global_Member_Id__c = '12345678');
        System.assert(gdprObj.Global_Member_Id__c == a.Global_Member_Id__c);
        upsert gdprObj;
        gdprObj.Request_Type__c = 'RTBF Do Not Process';
        gdprObj.status__c = 'RTBF Do Not Process';
        gdprObj.Response_Date__c = Datetime.now().date();
        update gdprObj;
        Test.stopTest();
    }
}