care/force-app/main/default/objects/Infraction__c/Infraction__c.object-meta.xml
<CustomObject>
    <description>BUC Violations</description>
    <label>Infraction</label>
    <nameField>
        <label>Violation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Infractions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Infraction__c/fields/BUC_Center_Name__c.field-meta.xml
<CustomField>
    <fullName>BUC_Center_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Center Name</description>
    <inlineHelpText>Center Name</inlineHelpText>
    <label>Center Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>BUC Network Center, BUC Network Agency</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Infractions</relationshipLabel>
    <relationshipName>Infractions</relationshipName>
    <type>Lookup</type>
</CustomField>

care/force-app/main/default/objects/Infraction__c/fields/Vetting_Object__c.field-meta.xml
<CustomField>
    <fullName>Vetting_Object__c</fullName>
    <description>Vetting Object</description>
    <inlineHelpText>Vetting Object</inlineHelpText>
    <label>Vetting Object</label>
    <referenceTo>Vetting__c</referenceTo>
    <relationshipLabel>Infractions</relationshipLabel>
    <relationshipName>Infractions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care/force-app/main/default/objects/Infraction__c/fields/Violation_Date__c.field-meta.xml
<CustomField>
    <fullName>Violation_Date__c</fullName>
    <description>Violation Date</description>
    <inlineHelpText>Violation Date</inlineHelpText>
    <label>Violation Date</label>
    <type>Date</type>
</CustomField>

care/force-app/main/default/objects/Infraction__c/fields/Violation_Level__c.field-meta.xml
<CustomField>
    <fullName>Violation_Level__c</fullName>
    <description>Violation Level 
This is used in Account Score forumla  - the points associated with these levels are  (AF=21, C=7, SB=3, M=0, NC=0)</description>
    <inlineHelpText>Violation Level</inlineHelpText>
    <label>Violation Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automatic Fail</fullName>
            </value>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Sub-Critical</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Non-Critical</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Infraction__c/fields/Violation_Type__c.field-meta.xml
<CustomField>
    <fullName>Violation_Type__c</fullName>
    <description>Violation Type</description>
    <inlineHelpText>Violation Type</inlineHelpText>
    <label>Violation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Safety</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Supervision</fullName>
            </value>
            <value>
                <fullName>Nutrition</fullName>
            </value>
            <value>
                <fullName>Building and Maintenance</fullName>
            </value>
            <value>
                <fullName>No Violations</fullName>
            </value>
            <value>
                <fullName>No Inspection</fullName>
            </value>
            <value>
                <fullName>Corresponding Score</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <description>Reviews Escalations</description>
    <label>Review</label>
    <nameField>
        <label>Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Review__c/fields/BUC_Center_Name__c.field-meta.xml
<CustomField>
    <fullName>BUC_Center_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Center Name</description>
    <inlineHelpText>Center Name</inlineHelpText>
    <label>Center Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>BUC Network Center, BUC Network Agency</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews_Escalations</relationshipName>
    <type>Lookup</type>
</CustomField>

care/force-app/main/default/objects/Vetting__c/Vetting__c.object-meta.xml
<CustomObject>
    <description>Vetting</description>
    <label>Vetting</label>
    <nameField>
        <label>Vetting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vettings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Vetting__c/fields/BUC_Center_Name__c.field-meta.xml
<CustomField>
    <fullName>BUC_Center_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Center Name</description>
    <inlineHelpText>Center Name</inlineHelpText>
    <label>Business Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>BUC Network Agency, BUC Network Center, BUC Network Agency, Business Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vettings</relationshipLabel>
    <relationshipName>Vettings</relationshipName>
    <type>Lookup</type>
</CustomField>

care/force-app/main/default/classes/Test_BUC_VettingViolationReview.cls
@isTest(SeeAllData=false)
private class Test_BUC_VettingViolationReview{
    private static ID BUCNetAgencyRtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('BUC Network Agency').getRecordTypeId();
    private static ID BUCNetCenterRtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('BUC Network Center').getRecordTypeId();
    private static ID USBUCRtId = Schema.SObjectType.Vetting__c.getRecordTypeInfosByName().get('US BUC Network Vetting').getRecordTypeId();
@isTest(SeeAllData=false)
static void VettingRecordCountOnAccountTest() 
{
 //Map<Id, RecordType> recTypeIds = new Map<Id, RecordType>([Select Id, Name From RecordType where name IN ('BUC Network Agency', 'BUC Network Center')]);   
    Account a = new Account(Name='TestAccount1',recordTypeId=BUCNetCenterRtId);
    insert a;
    a.Vetting_Record_Count__c=0;
    update a;
    Vetting__c vetObj1=new Vetting__c(Name='Vetting Test',BUC_Center_Name__c=a.id, recordTypeId=USBUCRtId);
    insert vetObj1;
       // delete vetObj1;
        Vetting__c vetObj2=new Vetting__c(Name='Vetting Test',BUC_Center_Name__c=a.id, recordTypeId=USBUCRtId);
    insert vetObj2;
    //a.Vetting_Record_Count__c=-1;
    //update a;
    //delete vetObj2;
}
@isTest(SeeAllData=false)
static void ViolationRecordCountOnAccountTest1() 
{
 //Map<Id, RecordType> recTypeIds = new Map<Id, RecordType>([Select Id, Name From RecordType where name IN ('BUC Network Agency', 'BUC Network Center')]);   
    Account a = new Account(Name='TestAccount1',recordTypeId=BUCNetCenterRtId);
    insert a;
    ApexPages.StandardController stdController=new ApexPages.StandardController(a);
    UpdateViolationCountOnAccount uvcOnAccount=new UpdateViolationCountOnAccount(stdController);
    Vetting__c vetObj=new Vetting__c(Name='Vetting Test',BUC_Center_Name__c=a.id);
    insert vetObj;
    uvcOnAccount.UpdateViolationSumsOnAccount();
    //Violation Level => Automatic Fail,Critical,Sub-Critical,Medium,Non-Critical
    //Violation Type => Administration,Safety Health,Supervision,Nutrition,Building and Maintenance,No Violations
    Infraction__c violObj1=new Infraction__c(BUC_Center_Name__c=a.id,Vetting_Object__c=vetObj.id,Violation_Date__c=system.now().date(), Violation_Level__c='Automatic Fail',Violation_Type__c='Administration');
    insert violObj1;
    Infraction__c violObj2=new Infraction__c(BUC_Center_Name__c=a.id,Vetting_Object__c=vetObj.id,Violation_Date__c=system.now().date(), Violation_Level__c='Automatic Fail',Violation_Type__c='Administration');
    insert violObj2;
    delete violObj1;
    a.Violation_Records_Present__c=0;
    update a;
    delete violObj2;
}
@isTest(SeeAllData=false)
static void ReviewRecordCountOnAccountTest() 
{
 //Map<Id, RecordType> recTypeIds = new Map<Id, RecordType>([Select Id, Name From RecordType where name IN ('BUC Network Agency', 'BUC Network Center')]);   
    Account a = new Account(Name='TestAccount1',recordTypeId=BUCNetCenterRtId);
    insert a;
    Vetting__c vetObj=new Vetting__c(Name='Vetting Test',BUC_Center_Name__c=a.id);
    insert vetObj;
//Review__c reviewObj= new Review__c(Name='Violation Test',BUC_Center_Name__c=a.id,Vetting_Object__c=vetObj.id);
Review__c reviewObj1= new Review__c(Name='Violation Test',BUC_Center_Name__c=a.id);
insert reviewObj1;
Review__c reviewObj2= new Review__c(Name='Violation Test',BUC_Center_Name__c=a.id);
insert reviewObj2;
}
@isTest(SeeAllData=false)
static void UpdateViolationCountOnAccountTest() 
{
 //Map<Id, RecordType> recTypeIds = new Map<Id, RecordType>([Select Id, Name From RecordType where name IN ('BUC Network Agency', 'BUC Network Center')]);   
    Account a = new Account(Name='TestAccount1',recordTypeId=BUCNetCenterRtId);
    insert a;
    Vetting__c vetObj=new Vetting__c(Name='Vetting Test',BUC_Center_Name__c=a.id);
    insert vetObj;
   //Violation Level => Automatic Fail,Critical,Sub-Critical,Medium,Non-Critical
    //Vi olation Type => Administration,Safety Health,Supervision,Nutrition,Building and Maintenance,No Violations
    Infraction__c violObj1=new Infraction__c(BUC_Center_Name__c=a.id,Vetting_Object__c=vetObj.id,Violation_Date__c=system.now().date(), Violation_Level__c='Automatic Fail',Violation_Type__c='Administration');
    Infraction__c violObj2=new Infraction__c(BUC_Center_Name__c=a.id,Vetting_Object__c=vetObj.id,Violation_Date__c=system.now().date(), Violation_Level__c='Critical',Violation_Type__c='Administration');
    Infraction__c violObj3=new Infraction__c(BUC_Center_Name__c=a.id,Vetting_Object__c=vetObj.id,Violation_Date__c=system.now().date(), Violation_Level__c='Sub-Critical',Violation_Type__c='Administration');
    insert new List<Infraction__c>{violObj1,violObj2,violObj3};
//UpdateViolationCountOnAccount upObj=new UpdateViolationCountOnAccount();
     ApexPages.StandardController sc = new ApexPages.StandardController(a);
     UpdateViolationCountOnAccount upObj=new UpdateViolationCountOnAccount(sc);
    upObj.UpdateViolationSumsOnAccount();
}
/*
@isTest(SeeAllData=false)
static void BatchUpdateViolationCountsOnAllAccountsTest() 
{
 //Map<Id, RecordType> recTypeIds = new Map<Id, RecordType>([Select Id, Name From RecordType where name IN ('BUC Network Agency', 'BUC Network Center')]);   
 List<RecordType> recordTypeList=[select id,name from recordtype where name in ('BUC Network Agency','BUC Network Center')];
    Map<String,id> recMap=new Map<String,id>();
    for(RecordType recObj:recordTypeList)
    {
        recMap.put(recObj.name,recObj.id);
    }
    Account a = new Account(Name='TestAccount1',recordTypeId=recMap.get('BUC Network Center'));
    insert a;
    Vetting__c vetObj=new Vetting__c(Name='Vetting Test',BUC_Center_Name__c=a.id);
    insert vetObj;
   //Violation Level => Automatic Fail,Critical,Sub-Critical,Medium,Non-Critical
    //Vi olation Type => Administration,Safety Health,Supervision,Nutrition,Building and Maintenance,No Violations
    Infraction__c violObj1=new Infraction__c(BUC_Center_Name__c=a.id,Vetting_Object__c=vetObj.id,Violation_Date__c=system.now().date(), Violation_Level__c='Automatic Fail',Violation_Type__c='Administration');
    Infraction__c violObj2=new Infraction__c(BUC_Center_Name__c=a.id,Vetting_Object__c=vetObj.id,Violation_Date__c=system.now().date(), Violation_Level__c='Critical',Violation_Type__c='Administration');
    Infraction__c violObj3=new Infraction__c(BUC_Center_Name__c=a.id,Vetting_Object__c=vetObj.id,Violation_Date__c=system.now().date(), Violation_Level__c='Sub-Critical',Violation_Type__c='Administration');
    insert new List<Infraction__c>{violObj1,violObj2,violObj3};
    Test.startTest();
    Database.executeBatch(new BatchUpdateViolationCountsOnAllAccounts(true));    
    Test.stopTest();
}
*/
}