care/force-app/main/default/objects/Infraction__c/Infraction__c.object-meta.xml
<CustomObject>
    <description>BUC Violations</description>
    <label>Infraction</label>
    <nameField>
        <label>Violation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Infractions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Infraction__c/fields/BUC_Center_Name__c.field-meta.xml
<CustomField>
    <fullName>BUC_Center_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Center Name</description>
    <inlineHelpText>Center Name</inlineHelpText>
    <label>Center Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>BUC Network Center, BUC Network Agency</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Infractions</relationshipLabel>
    <relationshipName>Infractions</relationshipName>
    <type>Lookup</type>
</CustomField>

care/force-app/main/default/objects/Infraction__c/fields/Violation_Date__c.field-meta.xml
<CustomField>
    <fullName>Violation_Date__c</fullName>
    <description>Violation Date</description>
    <inlineHelpText>Violation Date</inlineHelpText>
    <label>Violation Date</label>
    <type>Date</type>
</CustomField>

care/force-app/main/default/objects/Infraction__c/fields/Violation_Level__c.field-meta.xml
<CustomField>
    <fullName>Violation_Level__c</fullName>
    <description>Violation Level 
This is used in Account Score forumla  - the points associated with these levels are  (AF=21, C=7, SB=3, M=0, NC=0)</description>
    <inlineHelpText>Violation Level</inlineHelpText>
    <label>Violation Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automatic Fail</fullName>
            </value>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Sub-Critical</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Non-Critical</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/classes/UpdateViolationCountOnAccount.cls
/*
** _________________________________________________________________________________
** Created by:    Sridhar Neeli
** Developer:     Sridhar Neeli, Developer [sridhar.neeli@nbostech.com]
** Created Date:  09.04.2017
** =================================================================================
** Description: 
                Refresh Violation Level count on account which happened in last 365 days.
** _______________________________________________________________________________
*/
global with sharing class UpdateViolationCountOnAccount{
public Account accountObj{get;set;}
public Id accountId{get;set;}
    public UpdateViolationCountOnAccount(ApexPages.StandardController stdController) {
        this.accountObj= (Account)stdController.getRecord();
        this.accountId=accountObj.id;
    }

//WebService static String UpdateViolationSumsOnAccount(Id accountId)
public void UpdateViolationSumsOnAccount()
    {
    try
    {
        if(accountObj!=null)
        {
            Integer automaticFailCount=database.countQuery('SELECT count()  FROM Infraction__c where BUC_Center_Name__c=:accountId and Violation_Level__c=\'Automatic Fail\' and Violation_Date__c = LAST_N_DAYS:365 LIMIT 50000');
            Integer critialCount=database.countQuery('SELECT count()  FROM Infraction__c where BUC_Center_Name__c=:accountId and Violation_Level__c=\'Critical\' and Violation_Date__c = LAST_N_DAYS:365 LIMIT 50000');
            Integer subCriticalCount=database.countQuery('SELECT count()  FROM Infraction__c where BUC_Center_Name__c=:accountId and Violation_Level__c=\'Sub-Critical\' and Violation_Date__c = LAST_N_DAYS:365 LIMIT 50000');
                 
            Account accObj=[select id,Sum_of_Automatic_Fail_Violations__c,Sum_of_Critical_Violations__c,Sum_of_Sub_Critical_Violations__c,Violation_Sum_Counted_Date__c from Account where id=:accountId];
            if(automaticFailCount>0)
            accObj.Sum_of_Automatic_Fail_Violations__c=automaticFailCount;
            else 
            accObj.Sum_of_Automatic_Fail_Violations__c = null;
            
            if(critialCount>0)
            accObj.Sum_of_Critical_Violations__c=critialCount;
            else 
             accObj.Sum_of_Critical_Violations__c=null;
             
            if(subCriticalCount>0)
            accObj.Sum_of_Sub_Critical_Violations__c=subCriticalCount;
            else 
            accObj.Sum_of_Sub_Critical_Violations__c=null;
            
            accObj.Violation_Sum_Counted_Date__c =System.now();
    
            update accObj;
            }

        }catch(Exception e){System.debug('An exception has occured while counting violation sums ==>:'+e.getMessage()); }
         //PageReference stdAccPage= new PageReference('/'+accountId);
        //stdAccPage.setRedirect(true);
        //return stdAccPage; 
    }
}