care/force-app/main/default/objects/Vetting__c/Vetting__c.object-meta.xml
<CustomObject>
    <description>Vetting</description>
    <label>Vetting</label>
    <nameField>
        <label>Vetting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vettings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Vetting__c/fields/BUC_Center_Name__c.field-meta.xml
<CustomField>
    <fullName>BUC_Center_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Center Name</description>
    <inlineHelpText>Center Name</inlineHelpText>
    <label>Business Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>BUC Network Agency, BUC Network Center, BUC Network Agency, Business Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vettings</relationshipLabel>
    <relationshipName>Vettings</relationshipName>
    <type>Lookup</type>
</CustomField>

care/force-app/main/default/objects/Vetting__c/fields/Business_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Name__c</fullName>
    <description>SFORCE-2848
Modify Vetting Custom Object</description>
    <label>Business Name:</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Vetting__c/fields/Overall_Score__c.field-meta.xml
<CustomField>
    <fullName>Overall_Score__c</fullName>
    <description>SFORCE-2883
Dev - Add Overall Score field to BUC Network Vetting and Vetting Related List</description>
    <inlineHelpText>Update the Overall Score on the Account and enter the updated value here.</inlineHelpText>
    <label>Overall Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care/force-app/main/default/classes/Test_AutoPopulateOverallScoreonVetting.cls
@isTest(SeeAllData=false)
public class Test_AutoPopulateOverallScoreonVetting {
    private static ID BUCNetAgencyRtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('BUC Network Agency').getRecordTypeId();
    private static ID BUCNetCenterRtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('BUC Network Center').getRecordTypeId();
    private static ID USBUCRtId = Schema.SObjectType.Vetting__c.getRecordTypeInfosByName().get('US BUC Network Vetting').getRecordTypeId();
    @isTest(SeeAllData=false)
    static void autoPopulateOverallScoretest() 
{
    Test.startTest();
    Account a = new Account(Name='TestAccount1',overall_score__c=79, recordTypeId=BUCNetCenterRtId);
    insert a;
    Account a1 = new Account(Name='TestAccount2',overall_score__c=79, recordTypeId=BUCNetAgencyRtId);
    insert a1;
    a.overall_score__c=82;
    update a;
    a1.overall_score__c=82;
    update a1;
    Vetting__c vetObj1=new Vetting__c(Name='Vetting Test',overall_score__c= 82, BUC_Center_Name__c=a.id, recordTypeId=USBUCRtId);
    insert vetObj1;
    Vetting__c vetObj2=new Vetting__c(Name='Vetting Test',overall_score__c= 82, BUC_Center_Name__c=a1.id, recordTypeId=USBUCRtId);
    insert vetObj2;
    Test.stopTest();
    list<Account> acc= [select id, overall_score__c from account limit 1];
    list<Vetting__c> vet = [select id, overall_score__c, Business_Name__c from Vetting__c where Business_Name__c=:a.id limit 1];
}
}