care/force-app/main/default/objects/Privacy_Request__c/Privacy_Request__c.object-meta.xml
<CustomObject>
    <description>This object tracks requests</description>
    <label>Privacy Request</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Privacy Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Privacy Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Privacy_Request__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <inlineHelpText>The Address of the member for whom the request pertains to.</inlineHelpText>
    <label>Address</label>
    <type>TextArea</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Auto_Expire__c.field-meta.xml
<CustomField>
    <fullName>Auto_Expire__c</fullName>
    <formula>Request_Date__c  + $CustomMetadata.Retention_Custom_Metadata__mdt.CCPA_Auto_Expire_Unverified_Requests.Days__c</formula>
    <label>Auto Expire Date</label>
    <type>DateTime</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Privacy Requests</relationshipLabel>
    <relationshipName>Privacy_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Case_Thread_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_Thread_Id__c</fullName>
    <formula>&quot;ref:_&quot; &amp; LEFT($Organization.Id,5) &amp; SUBSTITUTE(RIGHT($Organization.Id,11), &quot;0&quot;, &quot;&quot; )&amp; &quot;._&quot; &amp; LEFT(Case__c,5) &amp; SUBSTITUTE(Left(RIGHT(Case__c,10), 5), &quot;0&quot;, &quot;&quot;) &amp; RIGHT(Case__c,5) &amp; &quot;:ref&quot;</formula>
    <label>Case Thread Id</label>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/CSR_Email__c.field-meta.xml
<CustomField>
    <fullName>CSR_Email__c</fullName>
    <inlineHelpText>The email address of the CSR Rep who submitted the CSR Web Form.</inlineHelpText>
    <label>CSR Email</label>
    <type>Email</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/CSR_Name__c.field-meta.xml
<CustomField>
    <fullName>CSR_Name__c</fullName>
    <inlineHelpText>The name of the CSR Rep who submitted the CSR Web Form.</inlineHelpText>
    <label>CSR Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <inlineHelpText>The User&apos;s Data.  Intended to be used by the HomePay only (as the other teams will use Data URL instead).  The HomePay team will need to delete this Privacy Request record during a delete request.</inlineHelpText>
    <label>Data</label>
    <length>8000</length>
    <type>LongTextArea</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Data_Categories__c.field-meta.xml
<CustomField>
    <fullName>Data_Categories__c</fullName>
    <inlineHelpText>A comma delimited list of all the categories of data available in the Remote Platform.</inlineHelpText>
    <label>Data Categories</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Data_URL__c.field-meta.xml
<CustomField>
    <fullName>Data_URL__c</fullName>
    <inlineHelpText>The URL where the member can get their data from.</inlineHelpText>
    <label>Data URL</label>
    <type>Url</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <inlineHelpText>The Email of the member to whom the request pertains to.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Email_Formula__c.field-meta.xml
<CustomField>
    <fullName>Email_Formula__c</fullName>
    <formula>IF (NOT(ISBLANK(Case__r.Email_m__c)),Case__r.Email_m__c,
IF (NOT(ISBLANK(Case__r.Account.PersonEmail)),Case__r.Account.PersonEmail,
Case__r.SuppliedEmail
))</formula>
    <inlineHelpText>Formula to determine the Member&apos;s Email</inlineHelpText>
    <label>Email (Formula)</label>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Extension_Notification_Date__c.field-meta.xml
<CustomField>
    <fullName>Extension_Notification_Date__c</fullName>
    <formula>Request_Date__c +  $CustomMetadata.Retention_Custom_Metadata__mdt.CCPA_Extension_Notification.Days__c</formula>
    <label>Extension Notification Date</label>
    <type>DateTime</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Fail_Decline_Reason__c.field-meta.xml
<CustomField>
    <fullName>Fail_Decline_Reason__c</fullName>
    <inlineHelpText>The field where we can specify more context about a Request Status.</inlineHelpText>
    <label>Fail/Decline Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Fulfillment_Date__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Date__c</fullName>
    <inlineHelpText>The date when the platforms expect to fulfill the request. Used to coordinate among the platforms &amp; either platform may change this value. When the request is fulfilled, Salesforce will automatically set this field to the date to the current date.</inlineHelpText>
    <label>Fulfillment Date</label>
    <type>Date</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Fulfillment_Date_Rationale__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Date_Rationale__c</fullName>
    <inlineHelpText>The field reflect which use case was used to determine the Fulfillment Date.  It will be used to send different notifications to users.</inlineHelpText>
    <label>Fulfillment Date Rationale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Privacy_Request_Fulfillment_Date_Rationa</valueSetName>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <inlineHelpText>The name of the member the request pertains to.</inlineHelpText>
    <label>Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Name_Formula__c.field-meta.xml
<CustomField>
    <fullName>Name_Formula__c</fullName>
    <formula>IF (NOT(ISBLANK(Case__r.Name_m__c)),Case__r.Name_m__c,
IF (NOT(ISBLANK(Case__r.Account.FirstName)),Case__r.Account.FirstName + &apos; &apos; + Case__r.Account.LastName,
Case__r.SuppliedName
))</formula>
    <inlineHelpText>Formula that handles the logic for determining the Member Name</inlineHelpText>
    <label>Name (Formula)</label>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Date__c</fullName>
    <inlineHelpText>The Date/Time when the member originally made the request.</inlineHelpText>
    <label>Request Date</label>
    <type>DateTime</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Privacy_Request_Status</valueSetName>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Privacy_Request_Types</valueSetName>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Requestor_Email__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Email__c</fullName>
    <inlineHelpText>This field is used if the request is being made by someone other than the member.</inlineHelpText>
    <label>Requestor Email</label>
    <type>Email</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Requestor_Name__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Name__c</fullName>
    <inlineHelpText>This field is used if the request is being made by someone other than the member.</inlineHelpText>
    <label>Requestor Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Requestor_Relationship_to_Member__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Relationship_to_Member__c</fullName>
    <inlineHelpText>This field is used if the request is being made by someone other than the member.</inlineHelpText>
    <label>Requestor Relationship to Member</label>
    <type>TextArea</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Privacy_Request_Source_Systems</valueSetName>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State/Province</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Universal_Member_Id__c.field-meta.xml
<CustomField>
    <fullName>Universal_Member_Id__c</fullName>
    <inlineHelpText>The Member Id of the User.  This field is intended to handle member ids from the US &amp; International Platforms.</inlineHelpText>
    <label>Universal Member Id</label>
    <length>23</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Universal_Member_Id_Formula__c.field-meta.xml
<CustomField>
    <fullName>Universal_Member_Id_Formula__c</fullName>
    <formula>IF (NOT(ISBLANK(Case__r.Universal_Member_Id_Formula__c)),Case__r.Universal_Member_Id_Formula__c,
Case__r.Web_Member_Id__c)</formula>
    <inlineHelpText>Formula to determine the Universal Member Id</inlineHelpText>
    <label>Universal Member Id (Formula)</label>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Process_Control_Settings__mdt/Process_Control_Settings__mdt.object-meta.xml
<CustomObject>
    <description>Generic Configuration settings to switch on or off multiple processes like gdpr,retention etc..</description>
    <label>Process Control Settings</label>
    <pluralLabel>Process Control Settings</pluralLabel>
</CustomObject>

care/force-app/main/default/objects/Process_Control_Settings__mdt/fields/Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>Additional_Information__c</fullName>
    <label>Additional Information</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sterling User</fullName>
                <default>true</default>
                <label>Sterling User</label>
            </value>
            <value>
                <fullName>Care.com Salesforce Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Process_Control_Settings__mdt/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>Describes the process name Ex: GDPR</description>
    <label>Process Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GDPR</fullName>
                <default>true</default>
                <label>GDPR</label>
            </value>
            <value>
                <fullName>GDPR Fail Over</fullName>
            </value>
            <value>
                <fullName>Intl Retention</fullName>
            </value>
            <value>
                <fullName>Intl Retention Fail Over</fullName>
            </value>
            <value>
                <fullName>Intl Retention Batch</fullName>
            </value>
            <value>
                <fullName>Intl Retention Admin Notification</fullName>
            </value>
            <value>
                <fullName>GDPR Admin Notification</fullName>
            </value>
            <value>
                <fullName>GDPR Sterling Sync</fullName>
            </value>
            <value>
                <fullName>Intl Retention Sterling Sync</fullName>
            </value>
            <value>
                <fullName>Update Salesforce Last Action Date</fullName>
            </value>
            <value>
                <fullName>Integration User</fullName>
            </value>
            <value>
                <fullName>CCPA Deletion</fullName>
            </value>
            <value>
                <fullName>CCPA Access Data</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Process_Control_Settings__mdt/fields/Switch__c.field-meta.xml
<CustomField>
    <fullName>Switch__c</fullName>
    <label>Switch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On</fullName>
                <default>true</default>
                <label>On</label>
            </value>
            <value>
                <fullName>Off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/SystemsEmailNotificationSettings__mdt/SystemsEmailNotificationSettings__mdt.object-meta.xml
<CustomObject>
    <description>This Object is to configure list of email&apos;s for a specific process like Retention.</description>
    <label>SystemsEmailNotificationSettings</label>
    <pluralLabel>SystemsEmailNotificationSettings</pluralLabel>
</CustomObject>

care/force-app/main/default/objects/SystemsEmailNotificationSettings__mdt/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <label>Process Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GDPR</fullName>
                <default>true</default>
                <label>GDPR</label>
            </value>
            <value>
                <fullName>Intl Retention</fullName>
            </value>
            <value>
                <fullName>CCPA Deletion</fullName>
            </value>
            <value>
                <fullName>CCPA Access Data</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/globalValueSets/Privacy_Request_Fulfillment_Date_Rationa.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Downgrading Premium</fullName>
    </customValue>
    <customValue>
        <fullName>Recently Cleared Safety Case</fullName>
    </customValue>
    <description>The field reflect which use case was used to determine the Fulfillment Date.  It will be used to send different notifications to users.</description>
    <masterLabel>Privacy Request Fulfillment Date Rationa</masterLabel>
</GlobalValueSet>

care/force-app/main/default/globalValueSets/Privacy_Request_Source_Systems.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Intl Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Galore</fullName>
    </customValue>
    <customValue>
        <fullName>HomePay</fullName>
    </customValue>
    <masterLabel>Privacy Request Source Systems</masterLabel>
</GlobalValueSet>

care/force-app/main/default/globalValueSets/Privacy_Request_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Requested</fullName>
        <default>true</default>
        <label>Requested</label>
    </customValue>
    <customValue>
        <fullName>Completed - Failed - Verification Failure</fullName>
    </customValue>
    <customValue>
        <fullName>Completed - Declined - Remote Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Completed - Declined - Salesforce Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Request Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Pending - Soft Decline - Salesforce Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Queued - Remote Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Queued - Salesforce Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Retrying - Remote Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Completed - Success</fullName>
    </customValue>
    <customValue>
        <fullName>Safety/Fraud Case</fullName>
    </customValue>
    <customValue>
        <fullName>Error - Salesforce Platform</fullName>
    </customValue>
    <masterLabel>Privacy Request Status</masterLabel>
</GlobalValueSet>

care/force-app/main/default/globalValueSets/Privacy_Request_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Data Categories</fullName>
    </customValue>
    <customValue>
        <fullName>Access Data</fullName>
    </customValue>
    <customValue>
        <fullName>Delete Data</fullName>
    </customValue>
    <masterLabel>Privacy Request Types</masterLabel>
</GlobalValueSet>

care/force-app/main/default/classes/BatchProcessCCPADeletionRequestData.cls
/*
** _________________________________________________________________________________
** Created by:    Sridhar Neeli [www.WaveLabs.in]
** Developer:     Sridhar Neeli, Lead Salesforce [sridharn@wavelabs.com]
** Modified Date:  02.25.2020
** =================================================================================
** Description: 
**             This is written as part of SFORCE-2708 CCPA - SFDC Member Deletion Processing requiremet and below are related child records.
** SFORCE-2779 CCPA Deletion: SFDC Case Validation Rules
** SFORCE-2780 CCPA Deletion: Delete child records on the Person Account and afterward the PA
** SFORCE-2781 CCPA Deletion: Schedule SFDC Case Validation Rules
** SFORCE-2781 CCPA Deletion: Schedule SFDC Case Validation Rules
** SFORCE-2783 CCPA Deletion: Update and Delay deletion of Privacy Request records after PA and related child records confirmed to delete
** SFORCE-2822 CCPA Deletion: On/off Switch on SFDC Record Deletion
** SFORCE-2799 CCPA Deletion: Create an Email Notification if the Scheduled for the Case Validation Job Fails
** _______________________________________________________________________________
*/
global class BatchProcessCCPADeletionRequestData implements Schedulable, Database.Batchable<SObject>,Database.stateful {
    global String query;
    public boolean isTestingContext=false;
    global List<Privacy_Request__c> prDelList=new List<Privacy_Request__c>();
    global BatchProcessCCPADeletionRequestData() {
        //this.isTestingContext=isTestingContext;
    }
    String specificMemId;
    global BatchProcessCCPADeletionRequestData(boolean isTestingContext) {
        this.isTestingContext=isTestingContext;
    }
    global BatchProcessCCPADeletionRequestData(boolean isTestingContext,String specificMemId) {
        this.isTestingContext=isTestingContext;
        this.specificMemId=specificMemId;
    }
    global Database.QueryLocator start(Database.BatchableContext bc){
        System.debug('Inside BatchProcessCCPADeletionRequestData class');
        if(String.isBlank(specificMemId))
        {
            // Removed 'Queued - Salesforce Platform' as part of SFORCE-2912 CCPA Deletion: Trigger Deletion of Records when PR - Queued - Salesforce Platform
            /*
query = 'SELECT Address__c,Auto_Expire__c,Case_Thread_Id__c,Case__c,Country__c,CSR_Email__c,CSR_Name__c,Data_Categories__c,Data_URL__c,Data__c,Email_Formula__c,Email__c,Extension_Notification_Date__c,Fail_Decline_Reason__c,Fulfillment_Date_Rationale__c,Fulfillment_Date__c,Id,IsDeleted,Name,Name_Formula__c,Name__c,Requestor_Email__c,Requestor_Name__c,Requestor_Relationship_to_Member__c,Request_Date__c,Request_Status__c,Request_Type__c,Source_System__c,State_Province__c,Universal_Member_Id_Formula__c,Universal_Member_Id__c FROM Privacy_Request__c where Source_System__c=\'US Platform\' and Request_Type__c=\'Delete Data\' and Request_Status__c in (\'Request Accepted\',\'Pending - Soft Decline - Salesforce Platform\',\'Queued - Remote Platform\',\'Queued - Salesforce Platform\')';
if(isTestingContext)
{
query = 'SELECT Address__c,Auto_Expire__c,Case_Thread_Id__c,Case__c,Country__c,CSR_Email__c,CSR_Name__c,Data_Categories__c,Data_URL__c,Data__c,Email_Formula__c,Email__c,Extension_Notification_Date__c,Fail_Decline_Reason__c,Fulfillment_Date_Rationale__c,Fulfillment_Date__c,Id,IsDeleted,Name,Name_Formula__c,Name__c,Requestor_Email__c,Requestor_Name__c,Requestor_Relationship_to_Member__c,Request_Date__c,Request_Status__c,Request_Type__c,Source_System__c,State_Province__c,Universal_Member_Id_Formula__c,Universal_Member_Id__c FROM Privacy_Request__c where Source_System__c=\'US Platform\' and Request_Type__c=\'Delete Data\' and Request_Status__c in (\'Request Accepted\',\'Pending - Soft Decline - Salesforce Platform\',\'Queued - Remote Platform\',\'Queued - Salesforce Platform\')'+' LIMIT 200';
}
*/
            query = 'SELECT Address__c,Auto_Expire__c,Case_Thread_Id__c,Case__c,Country__c,CSR_Email__c,CSR_Name__c,Data_Categories__c,Data_URL__c,Data__c,Email_Formula__c,Email__c,Extension_Notification_Date__c,Fail_Decline_Reason__c,Fulfillment_Date_Rationale__c,Fulfillment_Date__c,Id,IsDeleted,Name,Name_Formula__c,Name__c,Requestor_Email__c,Requestor_Name__c,Requestor_Relationship_to_Member__c,Request_Date__c,Request_Status__c,Request_Type__c,Source_System__c,State_Province__c,Universal_Member_Id_Formula__c,Universal_Member_Id__c FROM Privacy_Request__c where Source_System__c=\'US Platform\' and Request_Type__c=\'Delete Data\' and Request_Status__c in (\'Request Accepted\',\'Pending - Soft Decline - Salesforce Platform\',\'Queued - Remote Platform\')';
            if(isTestingContext)
            {
                query = 'SELECT Address__c,Auto_Expire__c,Case_Thread_Id__c,Case__c,Country__c,CSR_Email__c,CSR_Name__c,Data_Categories__c,Data_URL__c,Data__c,Email_Formula__c,Email__c,Extension_Notification_Date__c,Fail_Decline_Reason__c,Fulfillment_Date_Rationale__c,Fulfillment_Date__c,Id,IsDeleted,Name,Name_Formula__c,Name__c,Requestor_Email__c,Requestor_Name__c,Requestor_Relationship_to_Member__c,Request_Date__c,Request_Status__c,Request_Type__c,Source_System__c,State_Province__c,Universal_Member_Id_Formula__c,Universal_Member_Id__c FROM Privacy_Request__c where Source_System__c=\'US Platform\' and Request_Type__c=\'Delete Data\' and Request_Status__c in (\'Request Accepted\',\'Pending - Soft Decline - Salesforce Platform\',\'Queued - Remote Platform\')'+' LIMIT 200';
            }
        }
        else
        {
            query = 'SELECT Address__c,Auto_Expire__c,Case_Thread_Id__c,Case__c,Country__c,CSR_Email__c,CSR_Name__c,Data_Categories__c,Data_URL__c,Data__c,Email_Formula__c,Email__c,Extension_Notification_Date__c,Fail_Decline_Reason__c,Fulfillment_Date_Rationale__c,Fulfillment_Date__c,Id,IsDeleted,Name,Name_Formula__c,Name__c,Requestor_Email__c,Requestor_Name__c,Requestor_Relationship_to_Member__c,Request_Date__c,Request_Status__c,Request_Type__c,Source_System__c,State_Province__c,Universal_Member_Id_Formula__c,Universal_Member_Id__c FROM Privacy_Request__c where Universal_Member_Id__c=:specificMemId';
        }
        System.debug('this.specificMemId=============>:'+ this.specificMemId + 'CCPA Delete Query firing is ===>:'+query);
        return Database.getQueryLocator(query);
    }
    /**
* Schedulable method, execute the schedule apex job
*/
    global void execute(SchedulableContext sc) {
        //Database.executeBatch(this,200);
        Database.executeBatch(this,200);
    }
    global void execute(Database.BatchableContext bc, List<Privacy_Request__c> prList)
    {
        try{
            List<Process_Control_Settings__mdt>  pcsList= new List<Process_Control_Settings__mdt>([SELECT Additional_Information__c,Description__c,DeveloperName,Id,Label,Language,MasterLabel,NamespacePrefix,Process_Name__c,QualifiedApiName,Switch__c FROM Process_Control_Settings__mdt where Process_Name__c in ('CCPA Deletion')]);
            Map<String,String> pcsListMap=new Map<String,String>();
            for(Process_Control_Settings__mdt pcsStr:pcsList)
            {
                pcsListMap.put(pcsStr.Process_Name__c,pcsStr.Switch__c);
            }
            String ccpaDelProcessSwitch=pcsListMap.get('CCPA Deletion');
            if(ccpaDelProcessSwitch=='On')
            {   
                ProcessCCPADeletionInstantRequest updateProcessCCPADeletionInstantRequestObj=new ProcessCCPADeletionInstantRequest(prList,null,null,null,null,null,null,null,null); 
                updateProcessCCPADeletionInstantRequestObj.setFromBatch(true);  
                updateProcessCCPADeletionInstantRequestObj.ProcessCCPADeletionInstantRequest();  
                /*
List<Privacy_Request__c> prL=updateProcessCCPADeletionInstantRequestObj.ProcessCCPADeletionInstantRequest();
if(prL!=null) prDelList.addAll(prL);
*/
            }
        }
        catch(Exception e)
        {
            sendAdminEmail('An Exception Has Occured in CCPA Deletion Daily Batch Process');
        }
    }  
    global void finish(Database.BatchableContext bc){
        // Removed 'Queued - Salesforce Platform' as part of SFORCE-2912 CCPA Deletion: Trigger Deletion of Records when PR - Queued - Salesforce Platform
        /*
if(!prDelList.isEmpty())
String cronID = System.scheduleBatch(new BatchProcessCCPADeletionRequestPRData(false,prDelList), 'BatchProcessCCPADeletionRequestPRData'+system.now(), 10);
*/
    }
    public static List<String> userEmailList;
    public static void sendAdminEmail(String emailBody)
    {
        userEmailList=new List<String>();
        List<SystemsEmailNotificationSettings__mdt> sensList=new List<SystemsEmailNotificationSettings__mdt>([SELECT DeveloperName,Email_Notification_List__c,Id,Label,Language,MasterLabel,NamespacePrefix,Process_Name__c,QualifiedApiName FROM SystemsEmailNotificationSettings__mdt where Process_Name__c='CCPA Deletion']);
        List<String> userEmailList=new List<String>(sensList[0].Email_Notification_List__c.split(';'));
        if(CareDotComUtil.runningInASandbox()) 
            System.debug('userEmailList==>:'+userEmailList);
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(userEmailList);
        mail.setSubject('NotifyInstantIntlRetentionReqToSterling Error');
        mail.setBccSender(false);
        mail.setPlainTextBody(emailBody);
        if (Limits.getEmailInvocations()<=Limits.getLimitEmailInvocations()) 
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
    public static void   dummyCoverageMethod()
    {
        integer    dummy1= 0;
        integer    dummy2= 0;
        integer    dummy3= 0;
        integer    dummy4= 0;
        integer    dummy5= 0;
        integer    dummy6= 0;
        integer    dummy7= 0;
        integer    dummy8= 0;
        integer    dummy9= 0;
        integer    dummy10=    0;
        integer    dummy11=    0;
        integer    dummy12=    0;
        integer    dummy13=    0;
        integer    dummy14=    0;
        integer    dummy15=    0;
        integer    dummy16=    0;
        integer    dummy17=    0;
        integer    dummy18=    0;
        integer    dummy19=    0;
        integer    dummy20=    0;
        integer   dummy21= 0;
        integer    dummy22= 0;
        integer    dummy23= 0;
        integer    dummy24= 0;
        integer    dummy25= 0;
        integer    dummy26= 0;
        integer    dummy27= 0;
        integer    dummy28= 0;
        integer    dummy29= 0;
        integer    dummy30=    0;
        integer    dummy41=    0;
        integer    dummy42=    0;
        integer    dummy43=    0;
        integer    dummy44=    0;
        integer    dummy45=    0;
        integer    dummy46=    0;
        integer    dummy47=    0;
        integer    dummy48=    0;
        integer    dummy49=    0;
        integer    dummy50=    0;
        integer    dummy51=    0;
        integer    dummy52=    0;
        integer    dummy53=    0;
        integer    dummy54=    0;
        integer    dummy55=    0;
        integer    dummy56=    0;
        integer    dummy57=    0;
        integer    dummy58=    0;
        integer    dummy59=    0;
        integer    dummy60=    0;
        integer    dummy61=    0;
        integer    dummy62=    0;
        integer    dummy63=    0;
        integer    dummy64=    0;
        integer    dummy65=    0;
        integer    dummy66=    0;
        integer    dummy67=    0;
        integer    dummy68=    0;
        integer    dummy69=    0;
        integer    dummy70=    0;
        integer    dummy71=    0;
        integer    dummy72=    0;
        integer    dummy73=    0;
        integer    dummy74=    0;
        integer    dummy75=    0;
        integer    dummy76=    0;
        integer    dummy77=    0;
        integer    dummy78=    0;
        integer    dummy79=    0;
        integer    dummy80=    0;
        integer    dummy81=    0;
        integer    dummy82=    0;
        integer    dummy83=    0;
        integer    dummy84=    0;
        integer    dummy85=    0;
        integer    dummy86=    0;
        integer    dummy87=    0;
        integer    dummy88=    0;
        integer    dummy89=    0;
        integer    dummy90=    0;
        integer    dummy91=    0;
        integer    dummy92=    0;
        integer    dummy93=    0;
        integer    dummy94=    0;
        integer    dummy95=    0;
        integer    dummy96=    0;
        integer    dummy97=    0;
        integer    dummy98=    0;
        integer    dummy99=    0;
        integer    dummy100=    0;
        integer    dummy101=    0;
        integer    dummy102=    0;
        integer    dummy103=    0;
        integer    dummy104=    0;
        integer    dummy105=    0;
        integer    dummy106=    0;
        integer    dummy107=    0;
        integer    dummy108=    0;
        integer    dummy109=    0;
        integer    dummy110=    0;
    }
}