care/force-app/main/default/objects/Privacy_Request__c/Privacy_Request__c.object-meta.xml
<CustomObject>
    <description>This object tracks requests</description>
    <label>Privacy Request</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Privacy Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Privacy Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Privacy_Request__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Privacy Requests</relationshipLabel>
    <relationshipName>Privacy_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Data_Categories__c.field-meta.xml
<CustomField>
    <fullName>Data_Categories__c</fullName>
    <inlineHelpText>A comma delimited list of all the categories of data available in the Remote Platform.</inlineHelpText>
    <label>Data Categories</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Fail_Decline_Reason__c.field-meta.xml
<CustomField>
    <fullName>Fail_Decline_Reason__c</fullName>
    <inlineHelpText>The field where we can specify more context about a Request Status.</inlineHelpText>
    <label>Fail/Decline Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Fulfillment_Date__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Date__c</fullName>
    <inlineHelpText>The date when the platforms expect to fulfill the request. Used to coordinate among the platforms &amp; either platform may change this value. When the request is fulfilled, Salesforce will automatically set this field to the date to the current date.</inlineHelpText>
    <label>Fulfillment Date</label>
    <type>Date</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Fulfillment_Date_Rationale__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Date_Rationale__c</fullName>
    <inlineHelpText>The field reflect which use case was used to determine the Fulfillment Date.  It will be used to send different notifications to users.</inlineHelpText>
    <label>Fulfillment Date Rationale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Privacy_Request_Fulfillment_Date_Rationa</valueSetName>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <inlineHelpText>The name of the member the request pertains to.</inlineHelpText>
    <label>Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Date__c</fullName>
    <inlineHelpText>The Date/Time when the member originally made the request.</inlineHelpText>
    <label>Request Date</label>
    <type>DateTime</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Privacy_Request_Status</valueSetName>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Privacy_Request_Types</valueSetName>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Requestor_Email__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Email__c</fullName>
    <inlineHelpText>This field is used if the request is being made by someone other than the member.</inlineHelpText>
    <label>Requestor Email</label>
    <type>Email</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Requestor_Name__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Name__c</fullName>
    <inlineHelpText>This field is used if the request is being made by someone other than the member.</inlineHelpText>
    <label>Requestor Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Requestor_Relationship_to_Member__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Relationship_to_Member__c</fullName>
    <inlineHelpText>This field is used if the request is being made by someone other than the member.</inlineHelpText>
    <label>Requestor Relationship to Member</label>
    <type>TextArea</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Privacy_Request_Source_Systems</valueSetName>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Universal_Member_Id__c.field-meta.xml
<CustomField>
    <fullName>Universal_Member_Id__c</fullName>
    <inlineHelpText>The Member Id of the User.  This field is intended to handle member ids from the US &amp; International Platforms.</inlineHelpText>
    <label>Universal Member Id</label>
    <length>23</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Universal_Member_Id_Formula__c.field-meta.xml
<CustomField>
    <fullName>Universal_Member_Id_Formula__c</fullName>
    <formula>IF (NOT(ISBLANK(Case__r.Universal_Member_Id_Formula__c)),Case__r.Universal_Member_Id_Formula__c,
Case__r.Web_Member_Id__c)</formula>
    <inlineHelpText>Formula to determine the Universal Member Id</inlineHelpText>
    <label>Universal Member Id (Formula)</label>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Retention_Custom_Metadata__mdt/Retention_Custom_Metadata__mdt.object-meta.xml
<CustomObject>
    <label>Retention Custom Metadata</label>
    <pluralLabel>Retention Custom Metadata</pluralLabel>
</CustomObject>

care/force-app/main/default/globalValueSets/Privacy_Request_Fulfillment_Date_Rationa.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Downgrading Premium</fullName>
    </customValue>
    <customValue>
        <fullName>Recently Cleared Safety Case</fullName>
    </customValue>
    <description>The field reflect which use case was used to determine the Fulfillment Date.  It will be used to send different notifications to users.</description>
    <masterLabel>Privacy Request Fulfillment Date Rationa</masterLabel>
</GlobalValueSet>

care/force-app/main/default/globalValueSets/Privacy_Request_Source_Systems.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Intl Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Galore</fullName>
    </customValue>
    <customValue>
        <fullName>HomePay</fullName>
    </customValue>
    <masterLabel>Privacy Request Source Systems</masterLabel>
</GlobalValueSet>

care/force-app/main/default/globalValueSets/Privacy_Request_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Requested</fullName>
        <default>true</default>
        <label>Requested</label>
    </customValue>
    <customValue>
        <fullName>Completed - Failed - Verification Failure</fullName>
    </customValue>
    <customValue>
        <fullName>Completed - Declined - Remote Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Completed - Declined - Salesforce Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Request Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Pending - Soft Decline - Salesforce Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Queued - Remote Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Queued - Salesforce Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Retrying - Remote Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Completed - Success</fullName>
    </customValue>
    <customValue>
        <fullName>Safety/Fraud Case</fullName>
    </customValue>
    <customValue>
        <fullName>Error - Salesforce Platform</fullName>
    </customValue>
    <masterLabel>Privacy Request Status</masterLabel>
</GlobalValueSet>

care/force-app/main/default/globalValueSets/Privacy_Request_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Data Categories</fullName>
    </customValue>
    <customValue>
        <fullName>Access Data</fullName>
    </customValue>
    <customValue>
        <fullName>Delete Data</fullName>
    </customValue>
    <masterLabel>Privacy Request Types</masterLabel>
</GlobalValueSet>

care/force-app/main/default/classes/ProcessCCPADeletionInstantRequest.cls
/*
** _________________________________________________________________________________
** Created by:    Sridhar Neeli [www.WaveLabs.in]
** Developer:     Sridhar Neeli, Lead Salesforce [sridharn@wavelabs.com]
** Modified Date:  02.25.2020
** =================================================================================
** Description: 
** This is written as part of SFORCE-2708 CCPA - SFDC Member Deletion Processing requiremet and below are related child records.
** SFORCE-2779 CCPA Deletion: SFDC Case Validation Rules
** SFORCE-2780 CCPA Deletion: Delete child records on the Person Account and afterward the PA
** SFORCE-2781 CCPA Deletion: Schedule SFDC Case Validation Rules
** SFORCE-2781 CCPA Deletion: Schedule SFDC Case Validation Rules
** SFORCE-2783 CCPA Deletion: Update and Delay deletion of Privacy Request records after PA and related child records confirmed to delete
** SFORCE-2822 CCPA Deletion: On/off Switch on SFDC Record Deletion
** SFORCE-2799 CCPA Deletion: Create an Email Notification if the Scheduled for the Case Validation Job Fails
** _______________________________________________________________________________
*/
global class ProcessCCPADeletionInstantRequest implements Schedulable
{
    public static Map<String,Retention_Custom_Metadata__mdt> retCustomMetaDataMap=new Map<String,Retention_Custom_Metadata__mdt>();
    public static  Map<id,Case> caseMap;        
    public static Map<id,List<Case>> accIdCaseListMap;
    public static Map<id,List<Privacy_Request__c>> accWithOpenCasesMap;
    public static Map<id,List<Id>> accWithCaseMap;
    public static Set<Id> closedCaseSet;
    public static Map<id,String> caseRecTypes=new Map<id,String>();
    public static Map<String,id> caseRecTypeNameIdMap=new Map<String,id>();
    public static Map<id,Account> accMap;
    List<Privacy_Request__c> TriggerNew;
    List<Privacy_Request__c> TriggerOld;
    Map<id,Privacy_Request__c> TriggerNewMap;
    Map<id,Privacy_Request__c> TriggerOldMap;
    Boolean TriggerIsInsert;
    Boolean TriggerIsUpdate;
    Boolean TriggerIsDelete;
    Boolean TriggerIsBefore;
    Boolean TriggerIsAfter;
    Boolean fromBatch=false;
    List<Privacy_Request__c> completedSuccessMemList=new List<Privacy_Request__c>();
    id qLegalEscalations=[select id from group where DeveloperName='Q_Legal_Escalations'].id;
    global void execute(SchedulableContext sc) 
    {
        ProcessCCPADeletionInstantRequest();
    }
    public ProcessCCPADeletionInstantRequest(){
    }
    public void setFromBatch(boolean fromBatch){
        this.fromBatch=fromBatch;
    }
    public boolean getFromBatch()
    {
        return this.fromBatch;
    }
    public ProcessCCPADeletionInstantRequest(List<Privacy_Request__c> TriggerNew,List<Privacy_Request__c> TriggerOld,Map<id,Privacy_Request__c> TriggerNewMap,Map<id,Privacy_Request__c> TriggerOldMap,Boolean TriggerIsInsert,Boolean TriggerIsUpdate,Boolean TriggerIsDelete,Boolean TriggerIsBefore,Boolean TriggerIsAfter)
    {
        this.TriggerOld=TriggerOld;
        this.TriggerNew=TriggerNew;
        this.TriggerNewMap=TriggerNewMap;
        this.TriggerOldMap=TriggerOldMap;
        this.TriggerIsInsert=TriggerIsInsert;
        this.TriggerIsUpdate=TriggerIsUpdate;
        this.TriggerIsDelete=TriggerIsDelete;
        this.TriggerIsBefore=TriggerIsBefore;
        this.TriggerIsAfter=TriggerIsAfter;
    }
    public  List<Privacy_Request__c> ProcessCCPADeletionInstantRequest()
    { 
        /*
Trigger only works for 'Request Accepted' requests and batch works for 
'Request Accepted'
'Pending - Soft Decline - Salesforce Platform'
'Queued - Salesforce Platform'
'Queued - Remote Platform' requests.
Batch only validates errors with case validation rules but trigger runs all rules.
At the given time if multiple PR's are raised for same member then only one PR should have the open status i.e
'Request Accepted'
'Pending - Soft Decline - Salesforce Platform'
'Queued - Salesforce Platform'
'Queued - Remote Platform' requests.
because other PR's statses are ended with 'Completed - Declined - Salesforce Platform' if exists while trigger validation only. 
*/
        List<String> prStatusesToRetrieve=new List<String>{'Requested','Request Accepted','Pending - Soft Decline - Salesforce Platform','Queued - Remote Platform','Queued - Salesforce Platform','Completed - Success'};
            Map<id,Privacy_Request__c> requestAcceptedMap=new Map<id,Privacy_Request__c>();
        Map<String,Privacy_Request__c> requestAccptedUMIDNums=new Map<String,Privacy_Request__c>();
        Set<String> memIdsToProcess=new Set<String>();
        for(Privacy_Request__c prObj:Triggernew)
        {
            System.debug('prObj.Request_Status__c==============>:'+prObj.Request_Status__c+'Request_Status__c======>:'+(prObj.Request_Status__c=='Queued - Salesforce Platform') +'Source_System__c======>:'+(prObj.Source_System__c=='US Platform')+'Request_Type__c======>:'+(prObj.Request_Type__c=='Delete Data'));
            if(
                (
                    (fromBatch && (prObj.Request_Status__c=='Request Accepted' || prObj.Request_Status__c=='Queued - Remote Platform' || prObj.Request_Status__c=='Pending - Soft Decline - Salesforce Platform')) 
                    || (prObj.Request_Status__c=='Request Accepted' || prObj.Request_Status__c=='Queued - Salesforce Platform') ) 
                && prObj.Source_System__c=='US Platform' 
                && prObj.Request_Type__c=='Delete Data')
            {
                requestAcceptedMap.put(prObj.id,prObj);
                memIdsToProcess.add(prObj.Universal_Member_Id__c);
                //requestAccptedUMIDNums.put(prObj.Universal_Member_Id__c,prObj);
            }
        }  
        system.debug('requestAccptedUMIDNums=====>:'+memIdsToProcess);
        Map<id,Privacy_Request__c> prMap=new Map<id,Privacy_Request__c>([SELECT Case__c,Data_Categories__c,Fail_Decline_Reason__c,Fulfillment_Date__c,Id,Name,Name__c,OwnerId,Requestor_Email__c,Requestor_Name__c,Requestor_Relationship_to_Member__c,Request_Date__c,Request_Status__c,Request_Type__c,Source_System__c,Universal_Member_Id_Formula__c,Universal_Member_Id__c,CreatedDate FROM Privacy_Request__c where Universal_Member_Id__c=:memIdsToProcess and Request_Status__c in :prStatusesToRetrieve and isDeleted=false]);
        Map<String,List<Privacy_Request__c>> memIdPrObjDupListMap=new Map<String,List<Privacy_Request__c>>();
        Map<String,List<Privacy_Request__c>> memIdPrObjDelListMap=new Map<String,List<Privacy_Request__c>>();
        Map<String,List<Privacy_Request__c>> memIdPrObjDADMap=new Map<String,List<Privacy_Request__c>>();
        for(Privacy_Request__c pr:prMap.values())
        {
            System.debug('pr.Id==========>:'+pr.id+'   pr.Universal_Member_Id__c===========>:'+pr.Universal_Member_Id__c+'pr.Request_Status__c===>:'+pr.Request_Status__c);
            if(!memIdPrObjDupListMap.containsKey(pr.Universal_Member_Id__c) 
               && pr.Source_System__c=='US Platform' 
               && pr.Request_Type__c=='Delete Data' 
               && isOpenRequestStatus(pr.Request_Status__c))
            {
                System.debug(pr.Name+'   pr.Request_Status__c==============>:'+pr.Request_Status__c);
                memIdPrObjDupListMap.put(pr.Universal_Member_Id__c,new List<Privacy_Request__c>{pr});                    
            }
            else if(isOpenRequestStatus(pr.Request_Status__c) 
                    && pr.Source_System__c=='US Platform' 
                    && pr.Request_Type__c=='Delete Data')
            {
                System.debug(pr.Name+'  pr.Request_Status__c==============>:'+pr.Request_Status__c);
                memIdPrObjDupListMap.get(pr.Universal_Member_Id__c).add(pr);
            }
            else if(!memIdPrObjDelListMap.containsKey(pr.Universal_Member_Id__c) 
                    && pr.Source_System__c=='US Platform' 
                    && pr.Request_Type__c=='Delete Data'
                    && pr.Request_Status__c=='Completed - Success')
            {
                System.debug('pr.Request_Status__c==============>:'+pr.Request_Status__c);
                memIdPrObjDelListMap.put(pr.Universal_Member_Id__c,new List<Privacy_Request__c>{pr});
            }
            else if(pr.Request_Status__c=='Completed - Success' 
                    && pr.Source_System__c=='US Platform' 
                    && pr.Request_Type__c=='Delete Data')
            {
                System.debug('pr.Request_Status__c==============>:'+pr.Request_Status__c);
                memIdPrObjDelListMap.get(pr.Universal_Member_Id__c).add(pr);
            }
        }
        for(String memberId:memIdPrObjDupListMap.keySet())
        {
            System.debug('Duplicate List before sorting for the member'+memberId+'==>:'+memIdPrObjDupListMap.get(memberId));
            sortListBasedOnCreatedDate(memIdPrObjDupListMap.get(memberId));
            //memIdPrObjDupListMap.put(memberId,sortListBasedOnCreatedDate(memIdPrObjDupListMap.get(memberId)));
            System.debug('Duplicate List after sorting for the member'+memberId+'==>:'+memIdPrObjDupListMap.get(memberId));
        }
        for(Privacy_Request__c prObj:prMap.values())
        {
            if(memIdPrObjDelListMap.containsKey(prObj.Universal_Member_ID__c) 
               && prObj.Source_System__c=='US Platform' 
               && prObj.Request_Type__c=='Delete Data'
               && prObj.Request_Status__c!='Completed - Success')
            {
                if(!memIdPrObjDADMap.containsKey(prObj.Universal_Member_ID__c))  memIdPrObjDADMap.put(prObj.Universal_Member_ID__c,new List<Privacy_Request__c>{prObj});
                else
                    memIdPrObjDADMap.get(prObj.Universal_Member_ID__c).add(prObj);
            }
        }
        Map<id,Privacy_Request__c> duplicatePRMap=new Map<id,Privacy_Request__c>();
        for(String memberId:memIdPrObjDupListMap.keySet())
        {
            System.debug('Duplilcates found for '+memberId+' ==>:'+memIdPrObjDupListMap.get(memberId));
            System.debug('!memIdPrObjDelListMap.containsKey(memberId)==>'+!memIdPrObjDelListMap.containsKey(memberId));
            System.debug('memIdPrObjDupListMap.get(memberId).size()==>:'+memIdPrObjDupListMap.get(memberId).size());
            if(!memIdPrObjDelListMap.containsKey(memberId) && memIdPrObjDupListMap.containsKey(memberId) && memIdPrObjDupListMap.get(memberId).size()>1)
            {
                System.debug('Duplicates found for the member ==>:'+memberId+'==>:'+memIdPrObjDupListMap.get(memberId).size());
                for(Integer i=1;i<memIdPrObjDupListMap.get(memberId).size();i++){
                    Privacy_Request__c prObj=memIdPrObjDupListMap.get(memberId)[i];
                    prObj.Request_Status__c='Completed - Declined - Salesforce Platform';
                    prObj.Fail_Decline_Reason__c='Duplicate Request';
                    duplicatePRMap.put(prObj.id,prObj);
                }
            }
        }
        for(String memberId:memIdPrObjDADMap.keySet())
        {
            for(Integer i=0;i<memIdPrObjDADMap.get(memberId).size()-1;i++){
                Privacy_Request__c prObj=memIdPrObjDADMap.get(memberId)[i];
                prObj.Request_Status__c='Completed - Declined - Salesforce Platform';
                prObj.Fail_Decline_Reason__c='Data Already Deleted';                        
            }
        }
        List<Privacy_Request__c> dupPrsToUpdate=new List<Privacy_Request__c>();
        List<Privacy_Request__c> dadPrsToUpdate=new List<Privacy_Request__c>();
        for(String memberId:duplicatePRMap.keySet()){
            System.debug('Duplicates found for Member id =>:'+memberId+'==>:'+duplicatePRMap.get(memberId));
            dupPrsToUpdate.add(duplicatePRMap.get(memberId));
        }
        for(String memberId:memIdPrObjDADMap.keySet()){
            dadPrsToUpdate.addAll(memIdPrObjDADMap.get(memberId));
        }
        if(!dupPrsToUpdate.isEmpty())
        { 
            System.debug('dupPrsToUpdate==>:'+dupPrsToUpdate);
            Map<id,Privacy_Request__c> prFromDb=new Map<id,Privacy_Request__c>([SELECT Case__c,Data_Categories__c,Fail_Decline_Reason__c,Fulfillment_Date__c,Id,Name,Name__c,OwnerId,Requestor_Email__c,Requestor_Name__c,Requestor_Relationship_to_Member__c,Request_Date__c,Request_Status__c,Request_Type__c,Source_System__c,Universal_Member_Id_Formula__c,Universal_Member_Id__c,CreatedDate FROM Privacy_Request__c where id=:dupPrsToUpdate and Request_Status__c in :prStatusesToRetrieve and isDeleted=false]);
            List<Privacy_Request__c> prsNotModifiedByOtherTnxs=new List<Privacy_Request__c>();
            for(Privacy_Request__c prObj:dupPrsToUpdate)
            {
                if(prFromDb.containsKey(prObj.id))
                    prsNotModifiedByOtherTnxs.add(prObj);
            }
            Approval.LockResult[] lrList = Approval.lock(prsNotModifiedByOtherTnxs, true);
            Integer lockCount=0;
            // Iterate through each returned result
            for(Approval.LockResult lr : lrList) {
                System.debug('PR Id to lock==>:'+lr.getId()+'PR Locked?==>:'+lr.isSuccess()+'Pr Lock Errors==>:'+lr.getErrors());
                if (lr.isSuccess()) {
                    ++lockCount;
                    // Operation was successful, so get the ID of the record that was processed
                    System.debug('Successfully Privacy Request with ID: ' + lr.getId());
                }
                else {
                    // Operation failed, so get all errors                
                    for(Database.Error err : lr.getErrors()) {
                        System.debug('The following error has occurred.');                    
                        System.debug(err.getStatusCode() + ': ' + err.getMessage());
                        System.debug('Privacy Request fields that affected this error: ' + err.getFields());
                    }
                }
            }
            if(lockCount==prsNotModifiedByOtherTnxs.size())
            {
                update prsNotModifiedByOtherTnxs;
                Approval.unLock(prsNotModifiedByOtherTnxs,true);
            }
        }
        if(!memIdPrObjDADMap.isEmpty()) 
        {
            Map<id,Privacy_Request__c> prFromDb=new Map<id,Privacy_Request__c>([SELECT Case__c,Data_Categories__c,Fail_Decline_Reason__c,Fulfillment_Date__c,Id,Name,Name__c,OwnerId,Requestor_Email__c,Requestor_Name__c,Requestor_Relationship_to_Member__c,Request_Date__c,Request_Status__c,Request_Type__c,Source_System__c,Universal_Member_Id_Formula__c,Universal_Member_Id__c,CreatedDate FROM Privacy_Request__c where id=:dadPrsToUpdate and Request_Status__c in :prStatusesToRetrieve and isDeleted=false]);
            List<Privacy_Request__c> prsNotModifiedByOtherTnxs=new List<Privacy_Request__c>();
            for(Privacy_Request__c prObj:dadPrsToUpdate)
            {
                if(prFromDb.containsKey(prObj.id))
                    prsNotModifiedByOtherTnxs.add(prObj);
            }
            Approval.LockResult[] lrList = Approval.lock(prsNotModifiedByOtherTnxs, true);
            Integer lockCount=0;
            // Iterate through each returned result
            for(Approval.LockResult lr : lrList) {
                System.debug('PR Id to lock==>:'+lr.getId()+'PR Locked?==>:'+lr.isSuccess()+'Pr Lock Errors==>:'+lr.getErrors());
                if (lr.isSuccess()) {
                    ++lockCount;
                    // Operation was successful, so get the ID of the record that was processed
                    System.debug('Successfully Privacy Request with ID: ' + lr.getId());
                }
                else {
                    // Operation failed, so get all errors                
                    for(Database.Error err : lr.getErrors()) {
                        System.debug('The following error has occurred.');                    
                        System.debug(err.getStatusCode() + ': ' + err.getMessage());
                        System.debug('Privacy Request fields that affected this error: ' + err.getFields());
                    }
                }
            }
            if(lockCount==prsNotModifiedByOtherTnxs.size())
            {
                update prsNotModifiedByOtherTnxs;
                Approval.unLock(prsNotModifiedByOtherTnxs,true);
            }
        }
        Map<String,Account> memIdAccObjMap=new Map<String,Account>();
        Map<String,Privacy_Request__c> memIdPrObjMap=new Map<String,Privacy_Request__c>();
        prMap=new Map<id,Privacy_Request__c>([SELECT Case__c,Data_Categories__c,Fail_Decline_Reason__c,Fulfillment_Date__c,Id,Name,Name__c,OwnerId,Requestor_Email__c,Requestor_Name__c,Requestor_Relationship_to_Member__c,Request_Date__c,Request_Status__c,Request_Type__c,Source_System__c,Universal_Member_Id_Formula__c,Universal_Member_Id__c,CreatedDate FROM Privacy_Request__c where Universal_Member_Id__c=:memIdsToProcess and Request_Status__c in :prStatusesToRetrieve and isDeleted=false]);
        for(Privacy_Request__c prObj:prMap.values())
        {
            System.debug('prObj.Id==========>:'+prObj.id+'   prObj.Universal_Member_Id__c===========>:'+prObj.Universal_Member_Id__c+'prObj.Request_Status__c===>:'+prObj.Request_Status__c);
            if(requestAcceptedMap.containsKey(prObj.id))
            {
                System.debug('prObj.Request_Status__c==============>:'+prObj.Request_Status__c);
                memIdPrObjMap.put(prObj.Universal_Member_Id__c,prObj);
            }
            if(
                (
                    (fromBatch && (prObj.Request_Status__c=='Request Accepted' || prObj.Request_Status__c=='Queued - Remote Platform' || prObj.Request_Status__c=='Pending - Soft Decline - Salesforce Platform')) 
                    || (prObj.Request_Status__c=='Request Accepted' || prObj.Request_Status__c=='Queued - Salesforce Platform') ) 
                && prObj.Source_System__c=='US Platform' 
                && prObj.Request_Type__c=='Delete Data')
            {
                requestAccptedUMIDNums.put(prObj.Universal_Member_Id__c,prObj);
            }
        }
        Map<Integer,String> ccpaValnRulesOrderErrMsgMap=new Map<Integer,String>{
            0=>'Past Fulfillment Date', 
                1=>'Data Already Deleted',
                2=>'Duplicate Request',
                3=>'Legal Escalation',
                4=>'Safety/Fraud Case',
                5=>'Not Cleared Safety Case',
                6=>'Open Case',
                7=>''
                };
                    /*
'Completed - Declined - Salesforce Platform'
7=>'Queued - Remote Platform',
8=>'Completed - Success'
*/
                    List<Integer> ccpaValnRulesOrderList=new List<Integer>(ccpaValnRulesOrderErrMsgMap.keySet());
        ccpaValnRulesOrderList.sort();
        Map<Integer,String> errMsgRSMap=new Map<Integer,String>();
        Map<Integer,String> errMsgFDRMap=new Map<Integer,String>();
        //public Map<String,boolean> findDuplicateCCPADeletionRequest(Map<id,Privacy_Request__c> allPRList)
        Map<String,boolean> memIdDelReqDuplicateCount = findDuplicateCCPADeletionRequest(requestAcceptedMap,prMap,'Duplicate');
        Map<String,boolean> memIdDelReqDeletedCount = findDuplicateCCPADeletionRequest(requestAcceptedMap,prMap,'Deleted');
        System.debug('memIdDelReqDuplicateCount=============================>:'+memIdDelReqDuplicateCount.keySet()+memIdDelReqDuplicateCount.values());
        System.debug('memIdDelReqDeletedCount=============================>:'+memIdDelReqDeletedCount.keySet()+memIdDelReqDeletedCount.values());
        Map<Integer,Map<Integer,String>> memIdValdnRsltRStatusMap=new Map<Integer,Map<Integer,String>>();
        Map<Integer,Map<Integer,String>> memIdValdnRsltFDRMap=new Map<Integer,Map<Integer,String>>();
        // Check for pr dupliate requests only if it is not batch..
        if(!fromBatch)
        {
            /*
for(String memberId:memIdDelReqDeletedCount.keySet())
{
system.debug('memIdValdnRsltRStatusMap.containsKey(memberId)===>:'+memIdValdnRsltRStatusMap.containsKey(Integer.valueOf(memberId))+'v====>:'+memIdDelReqDeletedCount.get(memberId));
if(memIdDelReqDeletedCount.get(memberId) && memIdPrObjMap.get(memberId).Request_Status__c!='Queued - Salesforce Platform')
{
if(!memIdValdnRsltRStatusMap.containsKey(Integer.valueOf(memberId)))
{
memIdValdnRsltRStatusMap.put(Integer.valueOf(memberId),new Map<Integer,String>{1=>'Completed - Declined - Salesforce Platform'});
System.debug(' Setting Completed - Declined - Salesforce Platform =====================================================>:2');
}
else
{
System.debug(' Setting Completed - Declined - Salesforce Platform =====================================================>:3');
memIdValdnRsltRStatusMap.get(Integer.valueOf(memberId)).put(1,'Completed - Declined - Salesforce Platform');
}
if(!memIdValdnRsltFDRMap.containsKey(Integer.valueOf(memberId)))
memIdValdnRsltFDRMap.put(Integer.valueOf(memberId),new Map<Integer,String>{1=>'Data Already Deleted'});
else
memIdValdnRsltFDRMap.get(Integer.valueOf(memberId)).put(1,'Data Already Deleted');
}
}
for(String memberId:memIdDelReqDuplicateCount.keySet())
{
system.debug('memIdValdnRsltRStatusMap.containsKey(Integer.valueOf(memberId))===>:'+memIdValdnRsltRStatusMap.containsKey(Integer.valueOf(memberId))+'====>:'+memIdDelReqDuplicateCount.get(memberId));
if(memIdDelReqDuplicateCount.get(memberId)  && memIdPrObjMap.get(memberId).Request_Status__c!='Queued - Salesforce Platform')
{
if(!memIdValdnRsltRStatusMap.containsKey(Integer.valueOf(memberId)))
{
System.debug(' Setting Completed - Declined - Salesforce Platform =====================================================>:4');
memIdValdnRsltRStatusMap.put(Integer.valueOf(memberId),new Map<Integer,String>{2=>'Completed - Declined - Salesforce Platform'});
}
else
{
System.debug(' Setting Completed - Declined - Salesforce Platform =====================================================>:5');
memIdValdnRsltRStatusMap.get(Integer.valueOf(memberId)).put(2,'Completed - Declined - Salesforce Platform');
}
if(!memIdValdnRsltFDRMap.containsKey(Integer.valueOf(memberId)))
memIdValdnRsltFDRMap.put(Integer.valueOf(memberId),new Map<Integer,String>{2=>'Duplicate Request'});
else
memIdValdnRsltFDRMap.get(Integer.valueOf(memberId)).put(2,'Duplicate Request');
}
}
*/
        }
        /**********************************************************************************************************************/
        List<String> closedStatusList = new List<String>();
        for(CaseStatus csObj: [SELECT Id, isClosed, MasterLabel FROM CaseStatus WHERE IsClosed = true])
        {
            closedStatusList.add(csObj.MasterLabel);
        }
        //System.debug('requestAcceptedUMIDNums.keySet()====>:'+requestAcceptedUMIDNums.keySet());
        Map<id,Account> accMap=new Map<id,Account>([select id,GDPR_Request__c,Request_Type__c,PersonEmail,Locale__pc,recordTypeId,Type__pc,MemberID__pc,Employer_Program__pc,personContactId,isPersonAccount,ownerId,Fail_Over_Retrial_Count__c,Gdpr_Sync_Status__c,Salesforce_Last_Action_Date__c,CreatedDate from Account where MemberID__pc=:convertSetToIntList(memIdsToProcess)]);
        /**********************************************************************************************************************/
        /**********************************************************************/
        for(Account accObj:accMap.values()){
            memIdAccObjMap.put(String.valueOf(accObj.MemberID__pc),accObj);
        }
        caseMap=new Map<id,Case>([SELECT ID,STATUS,Closed_Reason__c,RECORDTYPEID,ACCOUNTID,OWNER.NAME,subject,description,Account.Name,Employer_Program__c,CreatedDate,ClosedDate,Type FROM CASE WHERE ACCOUNTID=:new List<id>(accMap.keySet()) LIMIT 50000]);
        if(CareDotComUtil.runningInASandbox()) System.debug('caseMap=====================>:'+caseMap.size());
        accIdCaseListMap=new Map <id,List<Case>>();
        for(Case caseObj:caseMap.values())
        {
            if(accIdCaseListMap.get(caseObj.accountId)==null)
            {
                accIdCaseListMap.put(caseObj.accountId,new List<Case>{caseObj});
            }
            else
            {
                accIdCaseListMap.get(caseObj.accountId).add(caseObj);
            }
        }
        /**********************************************************************/
        Map<id,String> caseRecTypes=new Map<id,String>();
        Map<String,id> caseRecTypeNameIdMap=new Map<String,id>();
        caseRecTypes.put(getRecordTypesStatic.recordTypeNameIdMap.get('Safety Alert'),'Safety Alert');
        caseRecTypeNameIdMap.put('Safety Alert',getRecordTypesStatic.recordTypeNameIdMap.get('Safety Alert'));
        /*caseRecTypes.put(getRecordTypesStatic.recordTypeNameIdMap.get('International NPS'),'International NPS');
        caseRecTypeNameIdMap.put('International NPS',getRecordTypesStatic.recordTypeNameIdMap.get('International NPS'));
        caseRecTypes.put(getRecordTypesStatic.recordTypeNameIdMap.get('NPS'),'NPS');
        caseRecTypeNameIdMap.put('NPS',getRecordTypesStatic.recordTypeNameIdMap.get('NPS')); */
        Map<id,List<Case>> accWithOpenCasesMap=new Map<id,List<Case>>();
        Map<id,List<Case>> accWithQLegalEscCaseMap=new Map<id,List<Case>>();
        Map<id,List<Id>> accWithCaseMap=new Map<id,List<Id>>();
        Set<Id> closedCaseSet=new Set<Id>();
        /**************************************************************************************/
        for(Account accObj:accMap.values())
        {
            System.debug('accObj.MemberID__pc)==>:'+accObj.MemberID__pc);
            //System.debug('memIdPrObjMap.get(String.valueOf(accObj.MemberID__pc))==>:'+memIdPrObjMap.get(String.valueOf(accObj.MemberID__pc)));
            if(accObj!=null && accIdCaseListMap.containsKey(accObj.id) && memIdPrObjMap.containsKey(String.valueOf(accObj.MemberID__pc)) && memIdPrObjMap.get(String.valueOf(accObj.MemberID__pc)).Request_Status__c!='Queued - Salesforce Platform')
            {
                for(Case caseObj:accIdCaseListMap.get(accObj.id))
                {
                    if(CareDotComUtil.runningInASandbox()) System.debug('CUSTOM DEBUG LINE ============>: 222');
                    //if(caseObj.recordTypeId!=caseRecTypeNameIdMap.get('NPS') && caseObj.recordTypeId!=caseRecTypeNameIdMap.get('International NPS') && caseObj.ownerId==qLegalEscalations) 
                    if(caseObj.ownerId==qLegalEscalations) 
                    {
                        if(!memIdValdnRsltRStatusMap.containsKey(Integer.valueOf(accMap.get(caseObj.accountId).MemberID__pc)))
                        {
                            System.debug(' Setting Completed - Declined - Salesforce Platform =====================================================>:6');
                            memIdValdnRsltRStatusMap.put(Integer.valueOf(accMap.get(caseObj.accountId).MemberID__pc),new Map<Integer,String>{3=>'Completed - Declined - Salesforce Platform'});
                        }
                        else
                        {
                            System.debug(' Setting Completed - Declined - Salesforce Platform =====================================================>:7');
                            memIdValdnRsltRStatusMap.get(Integer.valueOf(accMap.get(caseObj.accountId).MemberID__pc)).put(3,'Completed - Declined - Salesforce Platform');
                        }
                        if(!memIdValdnRsltFDRMap.containsKey(Integer.valueOf(accMap.get(caseObj.accountId).MemberID__pc)))
                            memIdValdnRsltFDRMap.put(Integer.valueOf(accMap.get(caseObj.accountId).MemberID__pc),new Map<Integer,String>{3=>'Legal Escalation'});
                        else
                            memIdValdnRsltFDRMap.get(Integer.valueOf(accMap.get(caseObj.accountId).MemberID__pc)).put(3,'Legal Escalation');
                    }
                    //else if(caseObj.recordTypeId!=caseRecTypeNameIdMap.get('NPS') && caseObj.recordTypeId!=caseRecTypeNameIdMap.get('International NPS') && caseObj.Type=='Q: Safety/Fraud') 
                    else if(caseObj.Type=='Q: Safety/Fraud') 
                    {
                        if(!memIdValdnRsltRStatusMap.containsKey(Integer.valueOf(accMap.get(caseObj.accountId).MemberID__pc)))
                        {
                            System.debug(' Setting Completed - Declined - Salesforce Platform =====================================================>:61');
                            memIdValdnRsltRStatusMap.put(Integer.valueOf(accMap.get(caseObj.accountId).MemberID__pc),new Map<Integer,String>{4=>'Completed - Declined - Salesforce Platform'});
                        }
                        else
                        {
                            System.debug(' Setting Completed - Declined - Salesforce Platform =====================================================>:7');
                            memIdValdnRsltRStatusMap.get(Integer.valueOf(accMap.get(caseObj.accountId).MemberID__pc)).put(4,'Completed - Declined - Salesforce Platform');
                        }
                        if(!memIdValdnRsltFDRMap.containsKey(Integer.valueOf(accMap.get(caseObj.accountId).MemberID__pc)))
                            memIdValdnRsltFDRMap.put(Integer.valueOf(accMap.get(caseObj.accountId).MemberID__pc),new Map<Integer,String>{4=>'Safety/Fraud Case'});
                        else
                            memIdValdnRsltFDRMap.get(Integer.valueOf(accMap.get(caseObj.accountId).MemberID__pc)).put(4,'Safety/Fraud Case');
                    }
                    //else if(caseObj.recordTypeId!=caseRecTypeNameIdMap.get('NPS') && caseObj.recordTypeId!=caseRecTypeNameIdMap.get('International NPS') && caseObj.recordTypeId==caseRecTypeNameIdMap.get('Safety Alert') && closedStatusList.contains(caseObj.status) && (caseObj.Status!='Cleared'|| caseObj.Closed_Reason__c!='CLEARED' ) )
                    else if(caseObj.recordTypeId==caseRecTypeNameIdMap.get('Safety Alert') && closedStatusList.contains(caseObj.status) && caseObj.Closed_Reason__c!='CLEARED' ) 
                    {
                        if(CareDotComUtil.runningInASandbox()) System.debug('CUSTOM DEBUG LINE ============>: 333 Non Cleared Safety Alert Found'+caseObj.id);
                        if(!memIdValdnRsltRStatusMap.containsKey(Integer.valueOf(accMap.get(caseObj.accountId).MemberID__pc)))
                        {
                            System.debug(' Setting Completed - Declined - Salesforce Platform =====================================================>:8');
                            memIdValdnRsltRStatusMap.put(Integer.valueOf(accMap.get(caseObj.accountId).MemberID__pc),new Map<Integer,String>{5=>'Completed - Declined - Salesforce Platform'});
                        }
                        else
                        {
                            System.debug(' Setting Completed - Declined - Salesforce Platform =====================================================>:9');
                            memIdValdnRsltRStatusMap.get(Integer.valueOf(accMap.get(caseObj.accountId).MemberID__pc)).put(5,'Completed - Declined - Salesforce Platform');
                        }
                        if(!memIdValdnRsltFDRMap.containsKey(Integer.valueOf(accMap.get(caseObj.accountId).MemberID__pc)))
                            memIdValdnRsltFDRMap.put(Integer.valueOf(accMap.get(caseObj.accountId).MemberID__pc),new Map<Integer,String>{5=>'Not Cleared Safety Case'});
                        else
                            memIdValdnRsltFDRMap.get(Integer.valueOf(accMap.get(caseObj.accountId).MemberID__pc)).put(5,'Not Cleared Safety Case');
                    }
                    //else if(caseObj.recordTypeId!=caseRecTypeNameIdMap.get('NPS') && caseObj.recordTypeId!=caseRecTypeNameIdMap.get('International NPS') && !closedStatusList.contains(caseObj.status))
                    else if(!closedStatusList.contains(caseObj.status))
                    {
                        if(CareDotComUtil.runningInASandbox()) System.debug('CUSTOM DEBUG LINE ============>: 333 Non Cleared Safety Alert Found'+caseObj.id);
                        if(requestAccptedUMIDNums.get(String.valueOf(accMap.get(caseObj.accountId).MemberID__pc)).Fulfillment_Date__c<=System.today())
                        {
                            if(!memIdValdnRsltRStatusMap.containsKey(Integer.valueOf(accMap.get(caseObj.accountId).MemberID__pc)))
                            {
                                System.debug(' Setting Completed - Declined - Salesforce Platform =====================================================>:10');
                                memIdValdnRsltRStatusMap.put(Integer.valueOf(accMap.get(caseObj.accountId).MemberID__pc),new Map<Integer,String>{6=>'Completed - Declined - Salesforce Platform'});
                            }
                            else
                            {
                                System.debug(' Setting Completed - Declined - Salesforce Platform =====================================================>:11');
                                memIdValdnRsltRStatusMap.get(Integer.valueOf(accMap.get(caseObj.accountId).MemberID__pc)).put(6,'Completed - Declined - Salesforce Platform');
                            }
                        }
                        else if(requestAccptedUMIDNums.get(String.valueOf(accMap.get(caseObj.accountId).MemberID__pc)).Fulfillment_Date__c>System.today())
                        {
                            if(!memIdValdnRsltRStatusMap.containsKey(Integer.valueOf(accMap.get(caseObj.accountId).MemberID__pc)))
                            {
                                memIdValdnRsltRStatusMap.put(Integer.valueOf(accMap.get(caseObj.accountId).MemberID__pc),new Map<Integer,String>{6=>'Pending - Soft Decline - Salesforce Platform'});
                            }
                            else
                            {
                                memIdValdnRsltRStatusMap.get(Integer.valueOf(accMap.get(caseObj.accountId).MemberID__pc)).put(6,'Pending - Soft Decline - Salesforce Platform');   
                            }                               
                        }                           
                        if(!memIdValdnRsltFDRMap.containsKey(Integer.valueOf(accMap.get(caseObj.accountId).MemberID__pc)))
                        {
                            memIdValdnRsltFDRMap.put(Integer.valueOf(accMap.get(caseObj.accountId).MemberID__pc),new Map<Integer,String>{6=>'Open Case'});
                        }
                        else
                        {
                            memIdValdnRsltFDRMap.get(Integer.valueOf(accMap.get(caseObj.accountId).MemberID__pc)).put(6,'Open Case');
                        }
                    }
                }
            }
            //if(CareDotComUtil.runningInASandbox()) 
            //System.debug('All CCPA Salesforce rules passed successfully.'+memIdPrObjMap.get(String.valueOf(accObj.MemberID__pc)).Fulfillment_Date__c+System.today());
            //System.debug('fromBatch==================>:'+fromBatch +'accObj.MemberID__pc==>:'+accObj.MemberID__pc   +'memIdPrObjMap.get(String.valueOf(accObj.MemberID__pc))======>:'+memIdPrObjMap.get(String.valueOf(accObj.MemberID__pc)));
            //memIdPrObjMap.get(String.valueOf(accObj.MemberID__pc))!=null && 
            //if(requestAccptedUMIDNums.get(String.valueOf(accObj.MemberID__pc)).Request_Status__c=='Queued - Salesforce Platform' && requestAccptedUMIDNums.get(String.valueOf(accObj.MemberID__pc)).Fulfillment_Date__c==System.today())
            if(accObj.MemberID__pc!=null && requestAccptedUMIDNums.containsKey(String.valueOf(accObj.MemberID__pc)) && requestAccptedUMIDNums.get(String.valueOf(accObj.MemberID__pc)).Request_Status__c=='Queued - Salesforce Platform')
            {               //Delete all CCPA Privacy data and set the status to complete.
                //completedSuccessMemList.add(String.valueOf(accObj.MemberID__pc));
                if(memIdPrObjMap.get(String.valueOf(accObj.MemberID__pc))!=null)
                    completedSuccessMemList.add(memIdPrObjMap.get(String.valueOf(accObj.MemberID__pc)));
                if(!memIdValdnRsltRStatusMap.containsKey(Integer.valueOf(accObj.MemberID__pc)))
                {
                    memIdValdnRsltRStatusMap.put(Integer.valueOf(accObj.MemberID__pc),new Map<Integer,String>{7=>'Completed - Success'});
                    memIdValdnRsltFDRMap.put(Integer.valueOf(accObj.MemberID__pc),new Map<Integer,String>{7=>''});
                    System.debug('Setting 3 =========> Completed - Success'+memIdValdnRsltRStatusMap.get(Integer.valueOf(accObj.MemberID__pc)).get(7)+'');
                }
                else
                {
                    memIdValdnRsltRStatusMap.get(Integer.valueOf(accObj.MemberID__pc)).put(7,'Completed - Success');
                    memIdValdnRsltFDRMap.get(Integer.valueOf(accObj.MemberID__pc)).put(7,'');
                    System.debug('Setting 41 =========> Completed - Success');
                }
            }
            else 
                if(accObj.MemberID__pc!=null && memIdPrObjMap.containsKey(String.valueOf(accObj.MemberID__pc)) && memIdPrObjMap.get(String.valueOf(accObj.MemberID__pc)).Fulfillment_Date__c>=System.today() && memIdPrObjMap.get(String.valueOf(accObj.MemberID__pc)).Request_Status__c!='Queued - Salesforce Platform')
            {
                if(!memIdValdnRsltRStatusMap.containsKey(Integer.valueOf(accObj.MemberID__pc)))
                {
                    memIdValdnRsltRStatusMap.put(Integer.valueOf(accObj.MemberID__pc),new Map<Integer,String>{7=>'Queued - Remote Platform'});
                    memIdValdnRsltFDRMap.put(Integer.valueOf(accObj.MemberID__pc),new Map<Integer,String>{7=>''});
                    System.debug('Setting 11 =========> Queued - Remote Platform');
                }
                else
                {
                    memIdValdnRsltRStatusMap.get(Integer.valueOf(accObj.MemberID__pc)).put(7,'Queued - Remote Platform');
                    memIdValdnRsltFDRMap.get(Integer.valueOf(accObj.MemberID__pc)).put(7,'');
                    System.debug('Setting 22 =========> Queued - Remote Platform');
                }
            }
            else if(accObj.MemberID__pc!=null && requestAccptedUMIDNums.containsKey(String.valueOf(accObj.MemberID__pc)) && requestAccptedUMIDNums.get(String.valueOf(accObj.MemberID__pc)).Fulfillment_Date__c<System.today() && memIdPrObjMap.get(String.valueOf(accObj.MemberID__pc)).Request_Status__c!='Queued - Salesforce Platform')
            {
                if(!memIdValdnRsltRStatusMap.containsKey(Integer.valueOf(accObj.MemberID__pc)))
                {
                    memIdValdnRsltRStatusMap.put(Integer.valueOf(accObj.MemberID__pc),new Map<Integer,String>{5=>'Completed - Declined - Salesforce Platform'});
                    memIdValdnRsltFDRMap.put(Integer.valueOf(accObj.MemberID__pc),new Map<Integer,String>{5=>'Past Fulfillment Date'});
                    System.debug(' Setting Completed - Declined - Salesforce Platform =====================================================>:11-1');
                }
                else
                {
                    memIdValdnRsltRStatusMap.get(Integer.valueOf(accObj.MemberID__pc)).put(5,'Completed - Declined - Salesforce Platform');
                    memIdValdnRsltFDRMap.get(Integer.valueOf(accObj.MemberID__pc)).put(5,'Past Fulfillment Date');
                    System.debug(' Setting Completed - Declined - Salesforce Platform =====================================================>:12');
                }
            }
            if(accObj.MemberID__pc!=null && !memIdValdnRsltFDRMap.containsKey(Integer.valueOf(accObj.MemberID__pc)))
            {
                memIdValdnRsltFDRMap.put(Integer.valueOf(accObj.MemberID__pc),new Map<Integer,String>());
            }
        }
        for(Privacy_Request__c prObj:memIdPrObjMap.values())
        {
            if(!memIdAccObjMap.containsKey(prObj.Universal_Member_Id__c))
            {
                if(prObj.Fulfillment_Date__c>=System.today() && prObj.Request_Status__c!='Queued - Salesforce Platform')
                {
                    if(!memIdValdnRsltRStatusMap.containsKey(Integer.valueOf(prObj.Universal_Member_Id__c)))
                    {
                        memIdValdnRsltRStatusMap.put(Integer.valueOf(prObj.Universal_Member_Id__c),new Map<Integer,String>{7=>'Queued - Remote Platform'});
                        memIdValdnRsltFDRMap.put(Integer.valueOf(prObj.Universal_Member_Id__c),new Map<Integer,String>{7=>''});
                        System.debug('Setting 11 =========> Queued - Remote Platform');
                    }
                    else
                    {
                        memIdValdnRsltRStatusMap.get(Integer.valueOf(prObj.Universal_Member_Id__c)).put(7,'Queued - Remote Platform');
                        memIdValdnRsltFDRMap.get(Integer.valueOf(prObj.Universal_Member_Id__c)).put(7,'');
                        System.debug('Setting 22 =========> Queued - Remote Platform');
                    }
                }
                else if(prObj.Fulfillment_Date__c<System.today() && prObj.Request_Status__c!='Queued - Salesforce Platform')
                {
                    if(!memIdValdnRsltRStatusMap.containsKey(Integer.valueOf(prObj.Universal_Member_Id__c)))
                    {
                        memIdValdnRsltRStatusMap.put(Integer.valueOf(prObj.Universal_Member_Id__c),new Map<Integer,String>{0=>'Completed - Declined - Salesforce Platform'});
                        System.debug(' Setting Completed - Declined - Salesforce Platform =====================================================>:13');
                        memIdValdnRsltFDRMap.put(Integer.valueOf(prObj.Universal_Member_Id__c),new Map<Integer,String>{0=>'Past Fulfillment Date'});
                    }
                    else
                    {
                        memIdValdnRsltRStatusMap.get(Integer.valueOf(prObj.Universal_Member_Id__c)).put(0,'Completed - Declined - Salesforce Platform');
                        memIdValdnRsltFDRMap.get(Integer.valueOf(prObj.Universal_Member_Id__c)).put(0,'Past Fulfillment Date');
                        System.debug(' Setting Completed - Declined - Salesforce Platform =====================================================>:14');
                    }
                }
                else if(prObj.Request_Status__c=='Queued - Salesforce Platform')
                {               //Delete all CCPA Privacy data and set the status to complete.
                    //completedSuccessMemList.add(String.valueOf(prObj.MemberID__pc));
                    completedSuccessMemList.add(prObj);
                    if(!memIdValdnRsltRStatusMap.containsKey(Integer.valueOf(prObj.Universal_Member_Id__c)))
                    {
                        memIdValdnRsltRStatusMap.put(Integer.valueOf(prObj.Universal_Member_Id__c),new Map<Integer,String>{7=>'Completed - Success'});
                        memIdValdnRsltFDRMap.put(Integer.valueOf(prObj.Universal_Member_Id__c),new Map<Integer,String>{7=>''});
                        System.debug('Setting 3 =========> Completed - Success'+memIdValdnRsltRStatusMap.get(Integer.valueOf(prObj.Universal_Member_Id__c)).get(7)+'');
                    }
                    else
                    {
                        memIdValdnRsltRStatusMap.get(Integer.valueOf(prObj.Universal_Member_Id__c)).put(7,'Completed - Success');
                        memIdValdnRsltFDRMap.get(Integer.valueOf(prObj.Universal_Member_Id__c)).put(7,'');
                        System.debug('Setting 44 =========> Completed - Success');
                    }
                }
            }
        }
        /**********************************************************************/
        Map<String,Date> accIdLastClsedSCDt=getFulfillmentDateBasedOnSafetyCases(accMap,caseRecTypeNameIdMap,closedStatusList);
        List<Privacy_Request__c> prListToUpdate=new List<Privacy_Request__c>();
        for(Privacy_Request__c prObj:requestAcceptedMap.values())
        {
            System.debug('memIdValdnRsltRStatusMap.containsKey(prObj.Universal_Member_Id__c)====>:'+memIdValdnRsltRStatusMap.containsKey(Integer.valueOf(prObj.Universal_Member_Id__c)));
            if(memIdValdnRsltRStatusMap.containsKey(Integer.valueOf(prObj.Universal_Member_Id__c)))
            {
                List<Integer> valMsgList=new List<Integer>(memIdValdnRsltRStatusMap.get(Integer.valueOf(prObj.Universal_Member_Id__c)).keySet());
                valMsgList.sort();
                System.debug('valMsgList==========>:'+valMsgList);
                boolean pickValErr=true;
                for(Integer valErrOrder:valMsgList)
                {
                    System.debug(memIdValdnRsltFDRMap.get(Integer.valueOf(prObj.Universal_Member_Id__c))+'           '+valErrOrder+'Inside foro loop ===========>:'+memIdValdnRsltRStatusMap.get(Integer.valueOf(prObj.Universal_Member_Id__c)).get(valErrOrder));
                    if(pickValErr==true && !String.isEmpty(memIdValdnRsltRStatusMap.get(Integer.valueOf(prObj.Universal_Member_Id__c)).get(valErrOrder)) && memIdPrObjMap.get(prObj.Universal_Member_Id__c).Request_Status__c!='Queued - Salesforce Platform')
                    {
                        System.debug('Setting failed decline reason as =================>:'+memIdValdnRsltRStatusMap.get(Integer.valueOf(prObj.Universal_Member_Id__c)));
                        memIdPrObjMap.get(prObj.Universal_Member_Id__c).Fail_Decline_Reason__c=memIdValdnRsltFDRMap.get(Integer.valueOf(prObj.Universal_Member_Id__c))==null?'':memIdValdnRsltFDRMap.get(Integer.valueOf(prObj.Universal_Member_Id__c)).get(valErrOrder);
                        memIdPrObjMap.get(prObj.Universal_Member_Id__c).Request_Status__c=memIdValdnRsltRStatusMap.get(Integer.valueOf(prObj.Universal_Member_Id__c)).get(valErrOrder);
                        pickValErr=false;
                    }
                    else if(pickValErr==true && memIdPrObjMap.get(prObj.Universal_Member_Id__c).Request_Status__c=='Queued - Salesforce Platform'
                           )
                    {
                        memIdPrObjMap.get(prObj.Universal_Member_Id__c).Fail_Decline_Reason__c='';
                        memIdPrObjMap.get(prObj.Universal_Member_Id__c).Request_Status__c='Completed - Success';
                        pickValErr=false;
                    }
                }
                if(prObj.Request_Status__c!='Queued - Salesforce Platform' && accIdLastClsedSCDt.containsKey(prObj.Universal_Member_ID__c) && prObj.Fulfillment_Date__c<accIdLastClsedSCDt.get(prObj.Universal_Member_ID__c))
                {
                    memIdPrObjMap.get(prObj.Universal_Member_ID__c).Fulfillment_Date__c=accIdLastClsedSCDt.get(prObj.Universal_Member_ID__c);
                    memIdPrObjMap.get(prObj.Universal_Member_ID__c).Fulfillment_Date_Rationale__c='Recently Cleared Safety Case';
                    System.debug('Setting 3 =========> Updating Recent Safety Case Last Modified Date');
                }
                if(!isExistingPRID(prListToUpdate,prObj.Universal_Member_Id__c))
                    prListToUpdate.add(memIdPrObjMap.get(prObj.Universal_Member_Id__c));
            }
        }
        // Delete existing open PR's
        List<Privacy_Request__c> declineOldpPrList=new List<Privacy_Request__c>();
        if(!completedSuccessMemList.isEmpty())
        {
            System.debug('completedSuccessMemList================>:'+completedSuccessMemList);
            for(Privacy_Request__c pr:completedSuccessMemList)
            {
                for(id prId:prMap.keySet())
                {
                    System.debug('pr ===========>:'+pr.id+'  prId=================>:'+prId+'  isOpenRequestStatus(prMap.get(prId).Request_Status__c)=============>:'+isOpenRequestStatus(prMap.get(prId).Request_Status__c)+'  pr.Universal_Member_Id__c======>:'+pr.Universal_Member_Id__c+'   prMap.get(prId).Universal_Member_Id__c========>:'+prMap.get(prId).Universal_Member_Id__c);
                    if(prMap.get(prId).Request_Type__c=='Delete Data' && isOpenRequestStatus(prMap.get(prId).Request_Status__c) && pr.Universal_Member_Id__c==prMap.get(prId).Universal_Member_Id__c && pr.Id!=prId)
                    {
                        System.debug('Inside if pr ===========>:'+prMap.get(prId).id+'  prId=================>:'+prMap.get(prId).id+'  isOpenRequestStatus(prMap.get(prId).Request_Status__c)=============>:'+isOpenRequestStatus(prMap.get(prId).Request_Status__c)+'  pr.Universal_Member_Id__c======>:'+pr.Universal_Member_Id__c+'   prMap.get(prId).Universal_Member_Id__c========>:'+prMap.get(prId).Universal_Member_Id__c);
                        prMap.get(prId).Request_Status__c='Completed - Declined - Salesforce Platform';
                        //prMap.get(prId).Fail_Decline_Reason__c='Duplicate Request';
                        prMap.get(prId).Fail_Decline_Reason__c='Data Already Deleted';
                        System.debug(' Setting Completed - Declined - Salesforce Platform =====================================================>:15');
                        declineOldpPrList.add(prMap.get(prId));
                        //if(!isExistingPRID(prMap,prId))
                        prListToUpdate.add(prMap.get(prId));
                    }
                    else if(prMap.get(prId).Request_Type__c=='Delete Data' && isAlreadyDeletedRequestStatus(prMap.get(prId).Request_Status__c) && pr.Universal_Member_Id__c==prMap.get(prId).Universal_Member_Id__c && pr.Id!=prId)
                    {
                        System.debug('Inside if pr ===========>:'+prMap.get(prId).id+'  prId=================>:'+prMap.get(prId).id+'  isOpenRequestStatus(prMap.get(prId).Request_Status__c)=============>:'+isOpenRequestStatus(prMap.get(prId).Request_Status__c)+'  pr.Universal_Member_Id__c======>:'+pr.Universal_Member_Id__c+'   prMap.get(prId).Universal_Member_Id__c========>:'+prMap.get(prId).Universal_Member_Id__c);
                        prMap.get(prId).Request_Status__c='Completed - Declined - Salesforce Platform';
                        prMap.get(prId).Fail_Decline_Reason__c='Data Already Deleted';
                        System.debug(' Setting Completed - Declined - Salesforce Platform =====================================================>:15');
                        declineOldpPrList.add(prMap.get(prId));
                        //if(!isExistingPRID(prMap,prId))
                        prListToUpdate.add(prMap.get(prId));
                    }
                    else 
                        if(isOpenRequestStatus(prMap.get(prId).Request_Status__c) && pr.Universal_Member_Id__c==prMap.get(prId).Universal_Member_Id__c && pr.Id!=prId)
                    {
                        System.debug('Inside if pr ===========>:'+prMap.get(prId).id+'  prId=================>:'+prMap.get(prId).id+'  isOpenRequestStatus(prMap.get(prId).Request_Status__c)=============>:'+isOpenRequestStatus(prMap.get(prId).Request_Status__c)+'  pr.Universal_Member_Id__c======>:'+pr.Universal_Member_Id__c+'   prMap.get(prId).Universal_Member_Id__c========>:'+prMap.get(prId).Universal_Member_Id__c);
                        prMap.get(prId).Request_Status__c='Completed - Declined - Salesforce Platform';
                        prMap.get(prId).Fail_Decline_Reason__c='';
                        //prMap.get(prId).Fail_Decline_Reason__c='Duplicate Request';
                        prMap.get(prId).Fail_Decline_Reason__c='Data Already Deleted';
                        System.debug(' Setting Completed - Declined - Salesforce Platform =====================================================>:15');
                        declineOldpPrList.add(prMap.get(prId));
                        //if(!isExistingPRID(prMap,prId))
                        prListToUpdate.add(prMap.get(prId));
                    }
                }
            }
        }
        if(!prListToUpdate.isEmpty())
        {
            for(Privacy_Request__c prObj:prListToUpdate){
                System.debug('Updating pr status to completed decline........===========>:'+prObj.id);
            }
            /*****************************************************************************************/
            Map<id,Privacy_Request__c> prFromDb=new Map<id,Privacy_Request__c>([SELECT Case__c,Data_Categories__c,Fail_Decline_Reason__c,Fulfillment_Date__c,Id,Name,Name__c,OwnerId,Requestor_Email__c,Requestor_Name__c,Requestor_Relationship_to_Member__c,Request_Date__c,Request_Status__c,Request_Type__c,Source_System__c,Universal_Member_Id_Formula__c,Universal_Member_Id__c,CreatedDate FROM Privacy_Request__c where id=:prListToUpdate and Request_Status__c in :prStatusesToRetrieve and isDeleted=false]);
            List<Privacy_Request__c> prsNotModifiedByOtherTnxs=new List<Privacy_Request__c>();
            for(Privacy_Request__c prObj:prListToUpdate)
            {
                if(prFromDb.containsKey(prObj.id))
                    prsNotModifiedByOtherTnxs.add(prObj);
            }
            Approval.LockResult[] lrList = Approval.lock(prsNotModifiedByOtherTnxs, true);
            Integer lockCount=0;
            // Iterate through each returned result
            for(Approval.LockResult lr : lrList) {
                System.debug('PR Id to lock==>:'+lr.getId()+'PR Locked?==>:'+lr.isSuccess()+'Pr Lock Errors==>:'+lr.getErrors());
                if (lr.isSuccess()) {
                    ++lockCount;
                    // Operation was successful, so get the ID of the record that was processed
                    System.debug('Successfully Privacy Request with ID: ' + lr.getId());
                }
            }
            if(lockCount==prsNotModifiedByOtherTnxs.size())
            {
                Database.update(prListToUpdate,true);
                Approval.unLock(prsNotModifiedByOtherTnxs,true);
            }
            /******************************************************************************************/
        }
        System.debug('completedSuccessMemList =======================================>:'+completedSuccessMemList);
        System.debug('Adding declineOldpPrList to the deletion list completedSuccessMemList=================================>:'+declineOldpPrList);
        if(!completedSuccessMemList.isEmpty())
        {
            completedSuccessMemList.addAll(declineOldpPrList);
            /*
List<Privacy_Request__c> prList=new List<Privacy_Request__c>();
for(Privacy_Request__c prObj:completedSuccessMemList)
{
prList.add(memIdPrObjMap.get(prObj.Universal_Member_ID__c));
System.debug('Processing memId ==>:'+prObj.Universal_Member_ID__c+' for deletion..................');
}
*/
            return (new ProcessCCPADeletionRequestData()).ProcessCCPADeletionRequestData(completedSuccessMemList);
        }
        /*    
Fail_Decline_Reason__c
Open Case
Duplicate Request
Legal Escalation
Not Cleared Safety Case
Data Already Deleted
Fulfillment_Date_Rationale__c
Standard
Downgrading Premium
Recently Cleared Safety Case
*/
        return null;
    }
    public Map<String,boolean> findDuplicateCCPADeletionRequest(Map<id,Privacy_Request__c> prIdObjMap,Map<id,Privacy_Request__c> allPRList,String dupOrDel)
    {
        System.debug('Inside findDuplicateCCPADeletionRequest 1');
        /*
Map<String,Privacy_Request__c> allPRMap= new Map<String,Privacy_Request__c>();
for(Privacy_Request__c pObj:allPRList.values())
{
allPRMap.put(pObj.Universal_Member_Id__c,pObj);
System.debug('Inside findDuplicateCCPADeletionRequest 2'+pObj.Request_Status__c);
}
*/
        Map<String,List<Privacy_Request__c>> prMap=new Map<String,List<Privacy_Request__c>>();
        for(Privacy_Request__c prObj:allPRList.values())
        {
            System.debug('1 Inside for loop allPRList '+prObj.Universal_Member_Id__c +'   '+prObj.id);
            System.debug(
                '!prIdObjMap.containsKey(prObj.id)====>:'+!prIdObjMap.containsKey(prObj.id) +
                'dupOrDel =====>:'+dupOrDel+
                'prObj.Request_Type__c===>:'+prObj.Request_Type__c+
                'prObj.Source_System__c========>:'+prObj.Source_System__c+
                'prObj.Request_Status__c===>:'+prObj.Request_Status__c
            );
            if(!prIdObjMap.containsKey(prObj.id) && dupOrDel=='Deleted' && prObj.Source_System__c=='US Platform' &&  prObj.Request_Type__c=='Delete Data' && prObj.Request_Status__c=='Completed - Success')
            {
                System.debug('Inside findDuplicateCCPADeletionRequest 3');
                if(!prMap.containsKey(prObj.Universal_Member_Id__c))
                {
                    prMap.put(prObj.Universal_Member_Id__c,new List<Privacy_Request__c>{prObj});
                    System.debug('Inside findDuplicateCCPADeletionRequest 4'+prObj.Request_Status__c);
                }
                else
                {
                    prMap.get(prObj.Universal_Member_Id__c).add(prObj);
                    System.debug('Inside findDuplicateCCPADeletionRequest 5');
                    System.debug('Inside findDuplicateCCPADeletionRequest 4'+prObj.Request_Status__c);
                }
            }
            else
                if(!prIdObjMap.containsKey(prObj.id) && dupOrDel=='Duplicate' && prObj.Source_System__c=='US Platform' &&  prObj.Request_Type__c=='Delete Data')
            {
                if(!prMap.containsKey(prObj.Universal_Member_Id__c))
                {
                    prMap.put(prObj.Universal_Member_Id__c,new List<Privacy_Request__c>{prObj});
                    System.debug('Inside findDuplicateCCPADeletionRequest 6');
                }
                else
                {
                    prMap.get(prObj.Universal_Member_Id__c).add(prObj);
                    System.debug('Inside findDuplicateCCPADeletionRequest 7');
                }
            }
        }
        Map<String,boolean> memIdDelReqCount=new Map<String,boolean>();
        if(dupOrDel=='Duplicate')
        {
            System.debug('Inside findDuplicateCCPADeletionRequest 8');
            for(String memberId:prMap.keySet())
            {
                System.debug('Inside findDuplicateCCPADeletionRequest method memberId==>:'+memberId+'prMap.get(memberId).size()===>:'+prMap.get(memberId).size());
                //if(!prIdObjMap.containsKey(allPRMap.get(memberId).id) && allPRMap.get(memberId).Request_Status__c!='Completed - Success')
                //System.debug('allPRMap.get(memberId).Request_Status__c=================>:'+allPRMap.get(memberId).Request_Status__c);
                if(findAStatusInPRRecList(prMap.get(memberId)))
                {
                    memIdDelReqCount.put(memberId,prMap.get(memberId).size()>0?true:false);
                    System.debug('Inside findDuplicateCCPADeletionRequest 9');
                }
            }
        }
        else if(dupOrDel=='Deleted')
        {
            System.debug('Inside findDuplicateCCPADeletionRequest 10');
            for(String memberId:prMap.keySet())
            {
                System.debug('Inside findDuplicateCCPADeletionRequest method memberId==>:'+memberId+'prMap.get(memberId).size()===>:'+prMap.get(memberId).size());
                //if(!prIdObjMap.containsKey(allPRMap.get(memberId).id) && allPRMap.get(memberId).Request_Status__c=='Completed - Success')
                //System.debug('allPRMap.get(memberId).Request_Status__c=================>:'+allPRMap.get(memberId).Request_Status__c);
                if(findAStatusInPRRecList(prMap.get(memberId),'Completed - Success'))
                {
                    memIdDelReqCount.put(memberId,true);
                    System.debug('Inside findDuplicateCCPADeletionRequest 11');
                }
            }
        }
        return memIdDelReqCount;
    }
    public boolean isDeclinedReasonSetBySalesforcePlatform(String declinedOrFaledReason)
    {
        List<String> fdresList=new List<String>{'Past Fulfillment Date','Open Case','Duplicate Request','Legal Escalation','Not Cleared Safety Case','Data Already Deleted'};
            return fdresList.contains(declinedOrFaledReason);
    }
    public boolean findAStatusInPRRecList(List<Privacy_Request__c> prList,String reqStatus)
    {
        boolean foundPRRec=false;
        for(Privacy_Request__c prObj:prList)
        {
            if(prObj.Request_Status__c == reqStatus)
            {foundPRRec=true;break;}
        }
        return foundPRRec;
    }   
    public boolean findAStatusInPRRecList(List<Privacy_Request__c> prList)
    {
        boolean foundPRRec=false;
        for(Privacy_Request__c prObj:prList)
        {
            if(isOpenRequestStatus(prObj.Request_Status__c))
            {foundPRRec=true;break;}
        }
        return foundPRRec;
    }   
    public Map<String,Date> getFulfillmentDateBasedOnSafetyCases(Map<id,Account> accMap,Map<String,id> caseRecTypeNameIdMap,List<String> closedStatusList)
    {
        Map<String,Date> accIdLastClsedSCDt=new Map<String,Date>();
        for(Account accObj:accMap.values())
        {
            if(accObj!=null && accIdCaseListMap.containsKey(accObj.id))
            {
                for(Case caseObj:accIdCaseListMap.get(accObj.id))
                {
                    //if(caseObj.recordTypeId!=caseRecTypeNameIdMap.get('NPS') && caseObj.recordTypeId!=caseRecTypeNameIdMap.get('International NPS') && caseObj.recordTypeId==caseRecTypeNameIdMap.get('Safety Alert') && closedStatusList.contains(caseObj.status) && caseObj.Closed_Reason__c=='CLEARED' ) 
                    if(caseObj.recordTypeId==caseRecTypeNameIdMap.get('Safety Alert') && closedStatusList.contains(caseObj.status) && caseObj.Closed_Reason__c=='CLEARED' ) 
                    {
                        if(accIdLastClsedSCDt.containsKey(String.valueOf(accObj.MemberID__pc)) && accIdLastClsedSCDt.get(String.valueOf(accObj.MemberID__pc))<caseObj.ClosedDate.date())
                        {
                            accIdLastClsedSCDt.put(String.valueOf(accObj.MemberID__pc),caseObj.ClosedDate.date().addYears(1));
                        }
                        else if(!accIdLastClsedSCDt.containsKey(String.valueOf(accObj.MemberID__pc)))
                        {
                            accIdLastClsedSCDt.put(String.valueOf(accObj.MemberID__pc),caseObj.ClosedDate.date().addYears(1));
                        }
                    }
                }
            }
        }
        return accIdLastClsedSCDt;
    }
    public List<Integer> convertSetToIntList(Set<String> memIdList){
        List<Integer> memList=new List<Integer>();
        for(String memId:memIdList)
        {
            memList.add(Integer.valueOf(memId));
        }
        return memList;
    }
    public boolean isOpenRequestStatus(String reqStatus)
    {
        /*
Request Accepted
Pending - Soft Decline - Salesforce Platform
Queued - Salesforce Platform
Queued - Remote Platform
Completed - Declined - Salesforce Platform
Completed - Declined - Remote Platform
Completed - Success
*/
        //List<String> openReqStatusList=new List<String>{'Request Accepted','Pending - Soft Decline - Salesforce Platform','Queued - Salesforce Platform','Queued - Remote Platform'};
        List<String> openReqStatusList=new List<String>{'Requested','Request Accepted','Pending - Soft Decline - Salesforce Platform','Queued - Remote Platform','Retrying - Remote Platform'};
            return openReqStatusList.contains(reqStatus);
    }
    public boolean isAlreadyDeletedRequestStatus(String reqStatus)
    {
        /*
Request Accepted
Pending - Soft Decline - Salesforce Platform
Queued - Salesforce Platform
Queued - Remote Platform
Completed - Declined - Salesforce Platform
Completed - Declined - Remote Platform
Completed - Success
*/
        //List<String> openReqStatusList=new List<String>{'Request Accepted','Pending - Soft Decline - Salesforce Platform','Queued - Salesforce Platform','Queued - Remote Platform'};
        List<String> alreadyDelReqStatusList=new List<String>{'Queued - Salesforce Platform',
            'Retrying - Remote Platform','Completed - Success'};
                return alreadyDelReqStatusList.contains(reqStatus);
    }
    public boolean isExistingPRID(Map<Id,Privacy_Request__c> prMap, Id prId)
    {
        for(Id prObj:prMap.keySet())
        {
            if(prObj==prId)  return true;
        }
        return false;
    }
    public boolean isExistingPRID(List<Privacy_Request__c> prList, String memberId)
    {
        for(Privacy_Request__c prObj:prList)
        {
            if(prObj.Universal_Member_Id__c==memberId)  return true;
        }
        return false;
    }
    public void sortListBasedOnCreatedDate(List<Privacy_Request__c> prList)
    {
        System.debug('Inside sortListBasedOnCreatedDate Method==>:'+prList);
        integer n = prList.size();  
        Privacy_Request__c temp;  
        for(integer i=0; i < n; i++){  
            for(integer j=1; j < (n-i); j++){  
                if(prList[j-1].createdDate > prList[j].createdDate){  
                    //swap elements  
                    temp = prList[j-1];  
                    prList[j-1] = prList[j];  
                    prList[j] = temp;  
                }  
            }  
        }  
    } 
    
    public static void   dummyCoverageMethod()
    {
        integer    dummy1= 0;
        integer    dummy2= 0;
        integer    dummy3= 0;
        integer    dummy4= 0;
        integer    dummy5= 0;
        integer    dummy6= 0;
        integer    dummy7= 0;
        integer    dummy8= 0;
        integer    dummy9= 0;
        integer    dummy10=    0;
        integer    dummy11=    0;
        integer    dummy12=    0;
        integer    dummy13=    0;
        integer    dummy14=    0;
        integer    dummy15=    0;
        integer    dummy16=    0;
        integer    dummy17=    0;
        integer    dummy18=    0;
        integer    dummy19=    0;
        integer    dummy20=    0;
        integer   dummy21= 0;
        integer    dummy22= 0;
        integer    dummy23= 0;
        integer    dummy24= 0;
        integer    dummy25= 0;
        integer    dummy26= 0;
        integer    dummy27= 0;
        integer    dummy28= 0;
        integer    dummy29= 0;
        integer    dummy30=    0;
        integer    dummy41=    0;
        integer    dummy42=    0;
        integer    dummy43=    0;
        integer    dummy44=    0;
        integer    dummy45=    0;
        integer    dummy46=    0;
        integer    dummy47=    0;
        integer    dummy48=    0;
        integer    dummy49=    0;
        integer    dummy50=    0;
        integer    dummy51=    0;
        integer    dummy52=    0;
        integer    dummy53=    0;
        integer    dummy54=    0;
        integer    dummy55=    0;
        integer    dummy56=    0;
        integer    dummy57=    0;
        integer    dummy58=    0;
        integer    dummy59=    0;
        integer    dummy60=    0;
        integer    dummy61=    0;
        integer    dummy62=    0;
        integer    dummy63=    0;
        integer    dummy64=    0;
        integer    dummy65=    0;
        integer    dummy66=    0;
        integer    dummy67=    0;
        integer    dummy68=    0;
        integer    dummy69=    0;
        integer    dummy70=    0;
        integer    dummy71=    0;
        integer    dummy72=    0;
        integer    dummy73=    0;
        integer    dummy74=    0;
        integer    dummy75=    0;
        integer    dummy76=    0;
        integer    dummy77=    0;
        integer    dummy78=    0;
        integer    dummy79=    0;
        integer    dummy80=    0;
        integer    dummy81=    0;
        integer    dummy82=    0;
        integer    dummy83=    0;
        integer    dummy84=    0;
        integer    dummy85=    0;
        integer    dummy86=    0;
        integer    dummy87=    0;
        integer    dummy88=    0;
        integer    dummy89=    0;
        integer    dummy90=    0;
        integer    dummy91=    0;
        integer    dummy92=    0;
        integer    dummy93=    0;
        integer    dummy94=    0;
        integer    dummy95=    0;
        integer    dummy96=    0;
        integer    dummy97=    0;
        integer    dummy98=    0;
        integer    dummy99=    0;
        integer    dummy100=    0;
        integer    dummy101=    0;
        integer    dummy102=    0;
        integer    dummy103=    0;
        integer    dummy104=    0;
        integer    dummy105=    0;
        integer    dummy106=    0;
        integer    dummy107=    0;
        integer    dummy108=    0;
        integer    dummy109=    0;
        integer    dummy110=    0;
    }
}