care/force-app/main/default/objects/Privacy_Request__c/Privacy_Request__c.object-meta.xml
<CustomObject>
    <description>This object tracks requests</description>
    <label>Privacy Request</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Privacy Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Privacy Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Privacy_Request__c/fields/No_Of_Files_Retrieved__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Files_Retrieved__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Represents the number of files retrieved as part of Data Access Request.</description>
    <inlineHelpText>Represents the number of files retrieved as part of Data Access Request.</inlineHelpText>
    <label>No Of Files Retrieved</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Privacy_Request_Status</valueSetName>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Privacy_Request_Types</valueSetName>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Privacy_Request__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Privacy_Request_Source_Systems</valueSetName>
    </valueSet>
</CustomField>

care/force-app/main/default/globalValueSets/Privacy_Request_Source_Systems.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Intl Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Galore</fullName>
    </customValue>
    <customValue>
        <fullName>HomePay</fullName>
    </customValue>
    <masterLabel>Privacy Request Source Systems</masterLabel>
</GlobalValueSet>

care/force-app/main/default/globalValueSets/Privacy_Request_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Requested</fullName>
        <default>true</default>
        <label>Requested</label>
    </customValue>
    <customValue>
        <fullName>Completed - Failed - Verification Failure</fullName>
    </customValue>
    <customValue>
        <fullName>Completed - Declined - Remote Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Completed - Declined - Salesforce Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Request Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Pending - Soft Decline - Salesforce Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Queued - Remote Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Queued - Salesforce Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Retrying - Remote Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Completed - Success</fullName>
    </customValue>
    <customValue>
        <fullName>Safety/Fraud Case</fullName>
    </customValue>
    <customValue>
        <fullName>Error - Salesforce Platform</fullName>
    </customValue>
    <masterLabel>Privacy Request Status</masterLabel>
</GlobalValueSet>

care/force-app/main/default/globalValueSets/Privacy_Request_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Data Categories</fullName>
    </customValue>
    <customValue>
        <fullName>Access Data</fullName>
    </customValue>
    <customValue>
        <fullName>Delete Data</fullName>
    </customValue>
    <masterLabel>Privacy Request Types</masterLabel>
</GlobalValueSet>

care/force-app/main/default/classes/CCPAAccessDataDeleteFiles.cls
/*
** _________________________________________________________________________________
** Created by:    Sridhar Neeli [www.WaveLabs.in]
** Developer:     Sridhar Neeli, Application Architect Salesforce [sridharn@wavelabs.com]
** Modified Date:  04.02.2020
** =================================================================================
** Description: 
**             This is written as part of SFORCE-3000 CCPA - Access Data - Data Classification for Fields
** SFORCE-3001 CCPA - Access Data - Custom Web Service
** SFORCE-3002 CCPA - Access Data - Prepare a Sample JSON File
** SFORCE-3003 CCPA - Access Data - Query SFDC Fields
** SFORCE-3004 CCPA - Access Data - Encrypted the Queried SFDC Fields
** SFORCE-3005 CCPA - Access Data - Map specific field by record type
** SFORCE-3006 CCPA - Access Data - Generate JSON Files
** SFORCE-3004 CCPA - Access Data - Decrypt Files When US Platform Pulling Them
** SFORCE-3008 CCPA - Access Data - Need a Batch job to asynchronous Prepare Access Data Files
** SFORCE-3009 CCPA - Access Data - Secure Files so only Modify All and View All Data can see
** _______________________________________________________________________________
*/

public class CCPAAccessDataDeleteFiles
{
   
            
    List<Privacy_Request__c> TriggerNew;
    List<Privacy_Request__c> TriggerOld;
    Map<id,Privacy_Request__c> TriggerNewMap;
    Map<id,Privacy_Request__c> TriggerOldMap;
    Boolean TriggerIsInsert;
    Boolean TriggerIsUpdate;
    Boolean TriggerIsDelete;
    Boolean TriggerIsBefore;
    Boolean TriggerIsAfter;
    
    List<Privacy_Request__c> completedSuccessMemList=new List<Privacy_Request__c>();
    public CCPAAccessDataDeleteFiles(){
    }

    public CCPAAccessDataDeleteFiles(List<Privacy_Request__c> TriggerNew,List<Privacy_Request__c> TriggerOld,Map<id,Privacy_Request__c> TriggerNewMap,Map<id,Privacy_Request__c> TriggerOldMap,Boolean TriggerIsInsert,Boolean TriggerIsUpdate,Boolean TriggerIsDelete,Boolean TriggerIsBefore,Boolean TriggerIsAfter)
    {
        this.TriggerOld=TriggerOld;
        this.TriggerNew=TriggerNew;
        this.TriggerNewMap=TriggerNewMap;
        this.TriggerOldMap=TriggerOldMap;
        this.TriggerIsInsert=TriggerIsInsert;
        this.TriggerIsUpdate=TriggerIsUpdate;
        this.TriggerIsDelete=TriggerIsDelete;
        this.TriggerIsBefore=TriggerIsBefore;
        this.TriggerIsAfter=TriggerIsAfter;
    }
    public  void ProcessCCPAAccessDataDeleteFilesInstantRequest()
    { 
            Map<id,Privacy_Request__c> requestAcceptedMap=new Map<id,Privacy_Request__c>();
            for(Privacy_Request__c prObj:(TriggerIsBefore && TriggerIsDelete)?TriggerOld:Triggernew)
            {
                if((prObj.Request_Status__c.contains('Completed') || (TriggerIsBefore && TriggerIsDelete)) && prObj.Source_System__c=='US Platform' 
                && prObj.Request_Type__c=='Access Data')
                {
                    requestAcceptedMap.put(prObj.id,prObj);
                }
            }  
            if(!requestAcceptedMap.isEmpty())
            {
                List<ContentDocumentLink> cdlList=new List<ContentDocumentLink>([select id,contentDocumentId from ContentDocumentLink where LinkedEntityId=:requestAcceptedMap.keySet()]);
                Set<id> cdIdList=new Set<Id>();
                for(ContentDocumentLink cdlObj:cdlList)
                {
                    cdIdList.add(cdlObj.contentDocumentId);
                }
                List<ContentDocument> cdList=new List<ContentDocument>([select id from ContentDocument where id=:cdIdList]);
                if(!cdList.isEmpty()) 
                {
                    Database.delete(cdList,false);Database.emptyRecycleBin(cdList); 
                    for(Id prId:requestAcceptedMap.keySet())
                    {
                        if(!(TriggerIsBefore && TriggerIsDelete))
                        requestAcceptedMap.get(prId).No_Of_Files_Retrieved__c=0;
                    }
                    //if(!requestAcceptedMap.isEmpty()) update requestAcceptedMap.values();
                }
            }
            
            }
            }