care/force-app/main/default/objects/Stripe_Refund__c/Stripe_Refund__c.object-meta.xml
<CustomObject>
    <label>Stripe Refund</label>
    <nameField>
        <displayFormat>REFUND-{0000000}</displayFormat>
        <label>Stripe Refund Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Refunds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Stripe_Refund__c/fields/Amount_Formatted__c.field-meta.xml
<CustomField>
    <fullName>Amount_Formatted__c</fullName>
    <description>This is for use in the flow</description>
    <inlineHelpText>This is for use in the flow</inlineHelpText>
    <label>Amount Formatted</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

care/force-app/main/default/objects/Stripe_Refund__c/fields/AmountFromResponse__c.field-meta.xml
<CustomField>
    <fullName>AmountFromResponse__c</fullName>
    <label>AmountFromResponse</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care/force-app/main/default/objects/Stripe_Refund__c/fields/Charge__c.field-meta.xml
<CustomField>
    <fullName>Charge__c</fullName>
    <label>Charge</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Stripe_Refund__c/fields/Date_Refunded__c.field-meta.xml
<CustomField>
    <fullName>Date_Refunded__c</fullName>
    <label>Date Refunded</label>
    <type>DateTime</type>
</CustomField>

care/force-app/main/default/objects/Stripe_Refund__c/fields/Payment_Intent__c.field-meta.xml
<CustomField>
    <fullName>Payment_Intent__c</fullName>
    <label>Payment Intent</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Stripe_Refund__c/fields/Refund_Id__c.field-meta.xml
<CustomField>
    <fullName>Refund_Id__c</fullName>
    <label>Refund Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/classes/StripeRefund.cls
global with sharing class StripeRefund {
    
    global class StripeRefundInput {
        @InvocableVariable(
            Label='Stripe Refund Response' 
            Description='Stripe Refund Response' 
            Required=true)
        global List<stripeGC.Refund> stripeRefundResponse;
    }

    global class StripeRefundOutput {
        @InvocableVariable(
            Label='Stripe refund as SObject' 
            Description='Stripe refund as SObject' 
            Required=true)
        global List<Stripe_Refund__c> stripeRefundSObjects;
    }
    
    @InvocableMethod(
        Label='Stripe convert refund response to SObject'
        Description='Stripe convert refund response to SObject')
    public static List<StripeRefundOutput> ConvertStripeRefundResponseToSObject(List<StripeRefundInput> responses) {

        List<StripeRefundOutput> stripeRefundOutput = new List<StripeRefundOutput>();
        for(StripeRefundInput each : responses){
            System.debug(each);

            List<Stripe_Refund__c> stripeRefundSObjects = new List<Stripe_Refund__c>();

            for(StripeGC.Refund eachRefund : each.stripeRefundResponse){
                Stripe_Refund__c refundSObject = new Stripe_Refund__c();
                refundSObject.AmountFromResponse__c = eachRefund.amount;
                refundSObject.Charge__c = eachRefund.charge;
                refundSObject.Payment_Intent__c = eachRefund.paymentIntent;
                refundSObject.Refund_Id__c = eachRefund.Id;
                refundSObject.Amount_Formatted__c = Double.valueOf(eachRefund.amount) / 100;
                refundSObject.Date_Refunded__c = Datetime.newInstance(0).addSeconds(eachRefund.created);

                stripeRefundSObjects.add(refundSObject);
            }
            StripeRefundOutput refundOutput = new StripeRefundOutput();
            refundOutput.stripeRefundSObjects = stripeRefundSObjects;
            stripeRefundOutput.add(refundOutput);
        }
        return stripeRefundOutput;
    }
}