care/force-app/main/default/objects/Composer_Service__c/Composer_Service__c.object-meta.xml
<CustomObject>
    <description>Identifies the vertical and license level for a service provider</description>
    <label>Composer Service</label>
    <nameField>
        <displayFormat>CCS-{00}</displayFormat>
        <label>Composer Services Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Composer Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Composer_Service__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is this service active and available to be selected in the composer?</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/License_Level__c.field-meta.xml
<CustomField>
    <fullName>License_Level__c</fullName>
    <description>License level of the vertical being serviced, or Category</description>
    <label>License Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Centers</fullName>
            </value>
            <value>
                <fullName>Nanny Agencies</fullName>
            </value>
            <value>
                <fullName>FCCs</fullName>
            </value>
            <value>
                <fullName>Camps</fullName>
            </value>
            <value>
                <fullName>Activities</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Adult Day Care</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Flat Rate</fullName>
            </value>
            <value>
                <fullName>Camps &amp; Activities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Service_Specific_Fields__c.field-meta.xml
<CustomField>
    <fullName>Service_Specific_Fields__c</fullName>
    <description>Which fields on Opportunity Service Area should be displayed on the Vetting tab?  API names, comma seperated.</description>
    <label>Service Specific Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <description>Vertical name, or Category Group</description>
    <label>Vertical</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Childcare</fullName>
            </value>
            <value>
                <fullName>Childcare Flat Rate</fullName>
            </value>
            <value>
                <fullName>Recruiting Solutions</fullName>
            </value>
            <value>
                <fullName>Senior Care</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/classes/CCCCont_Test.cls
/*****************************************************************************************
Created By: Alan Oshry
Email: alan.oshry@revelanttech.com
Created: 12/02/2020
Description: Test methods for CCCController Apex class
Comments:

********************************************************************************************/
@isTest
private class CCCCont_Test {
    private static CCCController.ServerResponse response;

    @testSetup static void setup() {

        // Create Composer Service records
        CCCTestDataFactory.createComposerServiceRecords();

        // Create Account
        CCCTestDataFactory.createAccount('Test Account');

        // Retrieve our new Account
        Account accountRecord = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];

        // Retrieve our active Senior Care, Housing Composer Service record to assign to the Opportunity
        Composer_Service__c composerServiceRecord = [SELECT Id FROM Composer_Service__c WHERE Vertical__c = 'Senior Care' AND License_Level__c = 'Housing' AND Active__c = TRUE LIMIT 1];
        composerServiceRecord.Service_Specific_Fields__c = 'Age_Range__c,Capacity__c';
        update composerServiceRecord;

        // Create Opportunity
        CCCTestDataFactory.createOpportunity_SalesOrigination(accountRecord.Id, composerServiceRecord.Id);

        // Retrieve our new Opportunity
        Opportunity opportunitySORecord = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity - Sales Origination' LIMIT 1];

        // Create Opportunity Service Area records
        CCCTestDataFactory.createOpportunityServiceAreas(opportunitySORecord.Id);

        // Create Sales Origination Rep user for testing
        CCCTestDataFactory.createSalesOriginationRepUser();
    }

    @isTest static void testGetInitialDataFail_EmptyRecordId() {
        User u = [SELECT Id FROM User WHERE UserName = 'test_so_profile@caredotcom.com'];

        final String recordId = 'XXXXXXXXXXXXXXXX';

        Test.startTest();
        System.runAs(u) {
            response = CCCController.getInitialData(null);
        }
        Test.stopTest();

        System.assertEquals(true, response.hasErrors, 'hasErrors should be true');
        System.assert(response.message.endsWith('Empty recordId parameter passed.'), 'Expected message to end with: Empty recordId parameter passed.');
    }

    @isTest static void testGetInitialDataFail_InvalidOpportunityId() {
        User u = [SELECT Id FROM User WHERE UserName = 'test_so_profile@caredotcom.com'];

        final String invalidRecordId = 'XXXXXXXXXXXXXXXX';
        Opportunity opportunityRecord = [SELECT Id, StageName FROM Opportunity WHERE Name = 'Test Opportunity - Sales Origination' LIMIT 1];

        Test.startTest();
        System.runAs(u) {
            response = CCCController.getInitialData(invalidRecordId);
        }
        Test.stopTest();

        System.assertEquals(true, response.hasErrors, 'hasErrors should be true');
        System.assert(response.message.endsWith('Unable to locate the Opportunity record specified.'), 'Expected message to end with: Unable to locate the Opportunity record specified.');
    }

    @isTest static void testGetInitialDataFail_RootExceptionThrown() {
        User u = [SELECT Id FROM User WHERE UserName = 'test_so_profile@caredotcom.com'];

        CCCUtils.UnitTestFlags flags = new CCCUtils.UnitTestFlags();
        flags.throwRootExceptionFail = true;

        Opportunity opportunityRecord = [SELECT Id, StageName FROM Opportunity WHERE Name = 'Test Opportunity - Sales Origination' LIMIT 1];

        Test.startTest();
        System.runAs(u) {
            response = CCCController.getInitialData(opportunityRecord.Id, flags);
        }
        Test.stopTest();

        System.assertEquals(true, response.hasErrors, 'hasErrors should be true');
        System.assert(response.message.endsWith('Throw Root Exception Unit Test.'), 'Expected message to end with: Throw Root Exception Unit Test.');
    }

    @isTest static void testGetInitialDataPass() {
        User u = [SELECT Id FROM User WHERE UserName = 'test_so_profile@caredotcom.com'];

        Opportunity opportunityRecord = [SELECT Id, StageName FROM Opportunity WHERE Name = 'Test Opportunity - Sales Origination' LIMIT 1];

        Test.startTest();
        System.runAs(u) {
            response = CCCController.getInitialData(opportunityRecord.Id);
        }
        Test.stopTest();

        System.assertEquals(false, response.hasErrors, 'response has error:' + response.message);
        System.assertEquals(null, response.message, 'response has error:' + response.message);
        System.assertEquals('SO', response.recordType);
    }

    @isTest static void testGetAllowEditWrapperPass_True() {
        User u = [SELECT Id FROM User WHERE UserName = 'test_so_profile@caredotcom.com'];


        Opportunity opportunityRecord = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity - Sales Origination' LIMIT 1];

        Test.startTest();
        System.runAs(u) {
            response = CCCController.getAllowEditWrapper(opportunityRecord.Id);
        }
        Test.stopTest();

        System.assertEquals(false, response.hasErrors, 'response has error:' + response.message);
        System.assertEquals(null, response.message, 'response has error:' + response.message);
        System.assertEquals(true, response.allowEdit, 'Expected allowEdit to be true');
    }

    @isTest static void testGetAllowEditFail_RootExceptionThrown() {
        User u = [SELECT Id FROM User WHERE UserName = 'test_so_profile@caredotcom.com'];

        CCCUtils.UnitTestFlags flags = new CCCUtils.UnitTestFlags();
        flags.throwRootExceptionFail = true;

        Opportunity opportunityRecord = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity - Sales Origination' LIMIT 1];

        Test.startTest();
        System.runAs(u) {
            response = CCCController.getAllowEditWrapper(opportunityRecord.Id, flags);
        }
        Test.stopTest();

        System.assertEquals(true, response.hasErrors, 'Expected hasErrors to be true');
        System.assert(response.message.endsWith('Throw Root Exception Unit Test.'), 'Expected message to end with: Throw Root Exception Unit Test.');
    }
}