care/force-app/main/default/objects/Composer_Service__c/Composer_Service__c.object-meta.xml
<CustomObject>
    <description>Identifies the vertical and license level for a service provider</description>
    <label>Composer Service</label>
    <nameField>
        <displayFormat>CCS-{00}</displayFormat>
        <label>Composer Services Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Composer Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Composer_Service__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is this service active and available to be selected in the composer?</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/License_Level__c.field-meta.xml
<CustomField>
    <fullName>License_Level__c</fullName>
    <description>License level of the vertical being serviced, or Category</description>
    <label>License Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Centers</fullName>
            </value>
            <value>
                <fullName>Nanny Agencies</fullName>
            </value>
            <value>
                <fullName>FCCs</fullName>
            </value>
            <value>
                <fullName>Camps</fullName>
            </value>
            <value>
                <fullName>Activities</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Adult Day Care</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Flat Rate</fullName>
            </value>
            <value>
                <fullName>Camps &amp; Activities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Tier_1_Amount__c.field-meta.xml
<CustomField>
    <fullName>Tier_1_Amount__c</fullName>
    <description>Tier 1 Amount</description>
    <label>Tier 1 Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Tier_2_Amount__c.field-meta.xml
<CustomField>
    <fullName>Tier_2_Amount__c</fullName>
    <description>Tier 2 Amount</description>
    <label>Tier 2 Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <description>Vertical name, or Category Group</description>
    <label>Vertical</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Childcare</fullName>
            </value>
            <value>
                <fullName>Childcare Flat Rate</fullName>
            </value>
            <value>
                <fullName>Recruiting Solutions</fullName>
            </value>
            <value>
                <fullName>Senior Care</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Opportunity_Location_Service__c/Opportunity_Location_Service__c.object-meta.xml
<CustomObject>
    <description>Tracks extra services associated with a location for Contract Composer</description>
    <label>Opportunity Location Service</label>
    <nameField>
        <displayFormat>OLS-{0}</displayFormat>
        <label>Opportunity Location Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Location Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Opportunity_Location_Service__c/fields/Advertising_Spend__c.field-meta.xml
<CustomField>
    <fullName>Advertising_Spend__c</fullName>
    <defaultValue>300</defaultValue>
    <description>Advertising Spend</description>
    <label>Advertising Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Location_Service__c/fields/Composer_Service__c.field-meta.xml
<CustomField>
    <fullName>Composer_Service__c</fullName>
    <description>Composer Service</description>
    <label>Composer Service</label>
    <referenceTo>Composer_Service__c</referenceTo>
    <relationshipLabel>Opportunity Location Services</relationshipLabel>
    <relationshipName>Opportunity_Location_Services</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Location_Service__c/fields/Opportunity_Service_Area__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Service_Area__c</fullName>
    <description>Opportunity Service Area</description>
    <label>Opportunity Service Area</label>
    <referenceTo>Opportunity_Service_Area__c</referenceTo>
    <relationshipLabel>Opportunity Location Services</relationshipLabel>
    <relationshipName>Opportunity_Location_Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Location_Service__c/fields/Pricing_Tier__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Tier__c</fullName>
    <defaultValue>&quot;Tier 1&quot;</defaultValue>
    <description>Pricing Tier</description>
    <label>Pricing Tier</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Pricing_Tier</valueSetName>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/Opportunity_Service_Area__c.object-meta.xml
<CustomObject>
    <description>The collection of postal codes for one service area inside a contract composer opportunity</description>
    <label>Opportunity Service Area</label>
    <nameField>
        <label>Display Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Service Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Advertising_Spend__c.field-meta.xml
<CustomField>
    <fullName>Advertising_Spend__c</fullName>
    <defaultValue>300</defaultValue>
    <description>Amount being spent on advertising</description>
    <label>Advertising Spend</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Flat_Rate_Billing_Cadence__c.field-meta.xml
<CustomField>
    <fullName>Flat_Rate_Billing_Cadence__c</fullName>
    <description>Frequency of bills sent to provider, initially used for Flat Rate</description>
    <label>Flat Rate Billing Cadence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quarterly</fullName>
                <default>true</default>
                <label>Quarterly</label>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <isActive>false</isActive>
                <label>Monthly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Master opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Service Areas</relationshipLabel>
    <relationshipName>Opportunity_Service_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Pricing_Tier__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Tier__c</fullName>
    <description>Pricing Tier</description>
    <label>Pricing Tier</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Pricing_Tier</valueSetName>
    </valueSet>
</CustomField>

care/force-app/main/default/globalValueSets/Pricing_Tier.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Tier 1</fullName>
        <default>true</default>
        <label>Tier 1</label>
    </customValue>
    <customValue>
        <fullName>Tier 2</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 3</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 4</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 5</fullName>
    </customValue>
    <customValue>
        <fullName>Custom</fullName>
    </customValue>
    <masterLabel>Pricing Tier</masterLabel>
</GlobalValueSet>

care/force-app/main/default/classes/CCCServiceController.cls
/****************************************************************************
Created By: John Wrightsman
Email: john.wrightsman@revelanttech.com
Created: 11/06/2020
Description: Apex controller for CCCServiceModule lightning component.
Changes:

*****************************************************************************/
public without sharing class CCCServiceController {
    static private String CLASS_NAME = 'CCCServiceController';

    public class ServerResponse extends CCCServerResponse {
        @AuraEnabled public String userId { get; set; }
        @AuraEnabled public String profileName { get; set; }
        @AuraEnabled public Opportunity opportunityRecord { get; set; }
        @AuraEnabled public List<Composer_Service__c> composerServiceRecords { get; set; }
        @AuraEnabled public List<String> permittedVerticals { get; set; }

        public ServerResponse() {
            super();
            this.composerServiceRecords = new List<Composer_Service__c>();
        }
    }


    /**
    * @description Retrieves the Service data for an Opportunity
    * @param recordId (String) - The Opportunity record Id
    * @return (ServerResponse)
    */
    @AuraEnabled public static ServerResponse getServiceData(String recordId) { return getServiceData(recordId, new CCCUtils.UnitTestFlags()); }

    @TestVisible private static ServerResponse getServiceData(String recordId, CCCUtils.UnitTestFlags flags) {
        final String METHOD_NAME = 'getServiceData';

        ServerResponse response = new ServerResponse();
        CCCUtils.ServerResponse rUtils = new CCCUtils.ServerResponse();

        try {

            if (flags.throwRootExceptionFail) throw new CCCUtils.CCCException('Throw Root Exception Unit Test.');

            if (recordId == null) throw new CCCException('Empty recordId parameter passed.');

            // Return the Opportunity Record
            rUtils = CCCUtils.getOpportunityRecord(recordId);
            if (rUtils.hasErrors) throw new CCCException(rUtils.message);
            if (rUtils.opportunityRecord == null) throw new CCCException('Unable to locate the Opportunity record specified.');

            response.opportunityRecord = rUtils.opportunityRecord;

            // Return the active Composer Service records
            response.composerServiceRecords = (List<Composer_Service__c>) CCCQuery.get('Composer_Service__c').equals('Active__c', true).order('Vertical__c ASC, License_Level__c ASC').all();

            // Return user permissions for composer services
            User u = (User) CCCQuery.get('User').field('Profile.Name').equalsId(UserInfo.getUserId()).one();
            response.profileName = u.Profile.Name;
            if (u.Profile.Name == 'Sales Origination Rep') {
                response.permittedVerticals = new List<String>();
                String permittedVerticals = u.Contract_Composer_Permitted_Verticals__c;
                if (permittedVerticals != null) {
                    for (String vertical : permittedVerticals.split(',')) {
                        response.permittedVerticals.add(vertical.trim());
                    }
                }
            }

        } catch(Exception e) { return (ServerResponse) CCCUtils.setErrorResponse(CLASS_NAME, METHOD_NAME, e, (CCCServerResponse) response); }

        return response;
    }


    /**
    * @description Updates the selected Composer Service for an Opportunity
    * @param recordId (String) - The Id of the Opportunity record
    * @param composerServiceRecordId (String) - The Id of the Composer Service record
    * @return ServerResponse
    */
    @AuraEnabled public static ServerResponse saveComposerServiceData(String recordId, String composerServiceRecordId) { return saveComposerServiceData(recordId, composerServiceRecordId, new CCCUtils.UnitTestFlags()); }

    @TestVisible private static ServerResponse saveComposerServiceData(String recordId, String composerServiceRecordId, CCCUtils.UnitTestFlags flags) {
        final String METHOD_NAME = 'saveComposerServiceData';

        CCCServiceController.ServerResponse rService;
        Opportunity opportunityRecord;
        Opportunity updatedOpportunityRecord;
        Composer_Service__c composerServiceRecord;
        ServerResponse response = new ServerResponse();

        try {
            // ContractComposerLog.logDebug(CLASS_NAME, METHOD_NAME, 'Start Method');

            if (flags.throwRootExceptionFail) throw new CCCUtils.CCCException('Throw Root Exception Unit Test.');

            if (recordId == null) throw new CCCException('Empty recordId parameter passed.');
            if (composerServiceRecordId == null) throw new CCCException('Empty composerServiceRecordId parameter passed.');

            // Get Opportunity Record - Make sure it exists in Salesforce
            opportunityRecord = (Opportunity) CCCQuery.get('Opportunity').equalsId(recordId).one();
            if (opportunityRecord == null) throw new CCCException('Unable to locate the Opportunity record specified.');

            // Get Composer Service Record - Make sure it exists in Salesforce
            composerServiceRecord = (Composer_Service__c) CCCQuery.get('Composer_Service__c').equalsId(composerServiceRecordId).one();
            if (composerServiceRecord == null) throw new CCCException('Unable to locate the Composer Service record specified.');

            // Update Opportunity
            update new Opportunity(
                Id =  opportunityRecord.Id,
                Composer_Service__c = composerServiceRecord.Id
            );

            // If the primary service is changing, remove additional services
            // not related to the primary service.
            removeLocationServices(recordId, composerServiceRecordId);
            
            //Recalculate Monthly Ad Budget
            resetLocationRecordsAdSpend(opportunityRecord);

            // Successfull save, retrieve fresh data to return back to the component

            // Get Fresh Data
            rService = getServiceData(recordId);
            if (rService.hasErrors) throw new CCCException(rService.message);

            response.opportunityRecord = rService.opportunityRecord;

        } catch (Exception e) { return (ServerResponse) CCCUtils.setErrorResponse(CLASS_NAME, METHOD_NAME, e, (CCCServerResponse) response); }

        // ContractComposerLog.logDebugAndFlush(CLASS_NAME, METHOD_NAME, 'End Method');

        return response;
    }
    
    /**
    * @description resets the Ad Spend to default values when a new service is selected
    * @param oppRecord (Opportunity) - The opportunity record related to opportunity service areas
    */
    private static void resetLocationRecordsAdSpend(Opportunity oppRecord){
        
        List<Opportunity_Service_Area__c> locationRecords = [SELECT Id, Advertising_Spend__c
                                                       		 FROM Opportunity_Service_Area__c
                                                       		 WHERE Opportunity__c =: oppRecord.Id];
        
    	Opportunity opportunityRecord = [SELECT Composer_Service__r.Tier_1_Amount__c, Composer_Service__r.Vertical__c,
                                                Composer_Service__r.Tier_2_Amount__c
                                        FROM Opportunity
                                        WHERE Id =: oppRecord.Id];

        Boolean isFlatRate = opportunityRecord.Composer_Service__r.Vertical__c.toLowerCase().contains('flat rate');
        
        for(Opportunity_Service_Area__c each : locationRecords){
            if(isFlatRate){
                each.Advertising_Spend__c =  opportunityRecord.Composer_Service__r.Tier_2_Amount__c;
                each.Pricing_Tier__c = 'Tier 2';
                each.Flat_Rate_Billing_Cadence__c = 'Quarterly';
            } else {
                each.Advertising_Spend__c =  opportunityRecord.Composer_Service__r.Tier_1_Amount__c;
                each.Pricing_Tier__c = 'Tier 1';
                each.Flat_Rate_Billing_Cadence__c = '';
            }
        }
        
        update locationRecords;
    }


     /**
    * @description Removes any Opportunity_Location_Service__c records that either
    *              1) do not match the vertical on the selected composer service
    *              2) or that matches the composer service
    * @param opportunityId (String) - The Id of the Opportunity record
    * @param composerServiceId (String) - The Id of the Composer Service record
    */
    @TestVisible private static void removeLocationServices(String opportunityId, String composerServiceId) {

        // Get all location ids on the opportunity
        Set<String> locationIds =
            CCCQuery.get('Opportunity_Service_Area__c')
                    .equals('Opportunity__c', opportunityId)
                    .toMap()
                    ?.keySet();

        if (locationIds != null) {
            // Get the Composer Service record
            Composer_Service__c composerService = (Composer_Service__c)
                CCCQuery.get('Composer_Service__c')
                        .equalsId(composerServiceId)
                        .one();

            // Get all Location Services related to any location on the opportunity
            List<Opportunity_Location_Service__c> locationServices = (List<Opportunity_Location_Service__c>)
                CCCQuery.get('Opportunity_Location_Service__c')
                        .field('Composer_Service__r.Vertical__c')
                        .includes('Opportunity_Service_Area__c', locationIds)
                        .all();

            // Loop through location services and add to a 'delete' list any record that
            // 1) doesn't match the vertical on the composer service record or
            // 2) matches the composer service record
            List<Opportunity_Location_Service__c> locationServicesToDelete = new List<Opportunity_Location_Service__c>();
            for (Opportunity_Location_Service__c ls : locationServices) {
                if (ls.Composer_Service__c == composerService.Id || ls.Composer_Service__r.Vertical__c != composerService.Vertical__c) {
                    locationServicesToDelete.add(ls);
                }
            }

            delete locationServicesToDelete;
        }

    }

}