care/force-app/main/default/objects/Composer_Service__c/Composer_Service__c.object-meta.xml
<CustomObject>
    <description>Identifies the vertical and license level for a service provider</description>
    <label>Composer Service</label>
    <nameField>
        <displayFormat>CCS-{00}</displayFormat>
        <label>Composer Services Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Composer Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Composer_Service__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is this service active and available to be selected in the composer?</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Base_Points__c.field-meta.xml
<CustomField>
    <fullName>Base_Points__c</fullName>
    <description>Base Points to be used in Contract Composer for compensation calculation</description>
    <label>Base Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/License_Level__c.field-meta.xml
<CustomField>
    <fullName>License_Level__c</fullName>
    <description>License level of the vertical being serviced, or Category</description>
    <label>License Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Centers</fullName>
            </value>
            <value>
                <fullName>Nanny Agencies</fullName>
            </value>
            <value>
                <fullName>FCCs</fullName>
            </value>
            <value>
                <fullName>Camps</fullName>
            </value>
            <value>
                <fullName>Activities</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Adult Day Care</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Flat Rate</fullName>
            </value>
            <value>
                <fullName>Camps &amp; Activities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Tier_1_Amount__c.field-meta.xml
<CustomField>
    <fullName>Tier_1_Amount__c</fullName>
    <description>Tier 1 Amount</description>
    <label>Tier 1 Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Tier_1_Bonus_Points__c.field-meta.xml
<CustomField>
    <fullName>Tier_1_Bonus_Points__c</fullName>
    <description>Tier 1 Bonus Points</description>
    <label>Tier 1 Bonus Points</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Tier_2_Amount__c.field-meta.xml
<CustomField>
    <fullName>Tier_2_Amount__c</fullName>
    <description>Tier 2 Amount</description>
    <label>Tier 2 Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Tier_2_Bonus_Points__c.field-meta.xml
<CustomField>
    <fullName>Tier_2_Bonus_Points__c</fullName>
    <description>Tier 2 Bonus Points</description>
    <label>Tier 2 Bonus Points</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Tier_3_Amount__c.field-meta.xml
<CustomField>
    <fullName>Tier_3_Amount__c</fullName>
    <description>Tier 3 Amount</description>
    <label>Tier 3 Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Tier_3_Bonus_Points__c.field-meta.xml
<CustomField>
    <fullName>Tier_3_Bonus_Points__c</fullName>
    <description>Tier 3 Bonus Points</description>
    <label>Tier 3 Bonus Points</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Tier_4_Amount__c.field-meta.xml
<CustomField>
    <fullName>Tier_4_Amount__c</fullName>
    <description>Tier 4 Amount</description>
    <label>Tier 4 Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Tier_4_Bonus_Points__c.field-meta.xml
<CustomField>
    <fullName>Tier_4_Bonus_Points__c</fullName>
    <description>Tier 4 Bonus Points</description>
    <label>Tier 4 Bonus Points</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Tier_5_Amount__c.field-meta.xml
<CustomField>
    <fullName>Tier_5_Amount__c</fullName>
    <description>Tier 5 Amount</description>
    <label>Tier 5 Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Tier_5_Bonus_Points__c.field-meta.xml
<CustomField>
    <fullName>Tier_5_Bonus_Points__c</fullName>
    <description>Tier 5 Bonus Points</description>
    <label>Tier 5 Bonus Points</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Tier_Custom_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Tier_Custom_Threshold__c</fullName>
    <description>Tier Custom Threshold</description>
    <label>Tier Custom Threshold</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Tuition_Discount_Bonus_Points__c.field-meta.xml
<CustomField>
    <fullName>Tuition_Discount_Bonus_Points__c</fullName>
    <description>The number of bonus points given to the sales rep if a tuition discount is added to the location.</description>
    <label>Tuition Discount Bonus Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care/force-app/main/default/objects/Composer_Service__c/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <description>Vertical name, or Category Group</description>
    <label>Vertical</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Childcare</fullName>
            </value>
            <value>
                <fullName>Childcare Flat Rate</fullName>
            </value>
            <value>
                <fullName>Recruiting Solutions</fullName>
            </value>
            <value>
                <fullName>Senior Care</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Opportunity_Location_Service__c/Opportunity_Location_Service__c.object-meta.xml
<CustomObject>
    <description>Tracks extra services associated with a location for Contract Composer</description>
    <label>Opportunity Location Service</label>
    <nameField>
        <displayFormat>OLS-{0}</displayFormat>
        <label>Opportunity Location Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Location Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Opportunity_Location_Service__c/fields/Advertising_Spend__c.field-meta.xml
<CustomField>
    <fullName>Advertising_Spend__c</fullName>
    <defaultValue>300</defaultValue>
    <description>Advertising Spend</description>
    <label>Advertising Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Location_Service__c/fields/Composer_Service__c.field-meta.xml
<CustomField>
    <fullName>Composer_Service__c</fullName>
    <description>Composer Service</description>
    <label>Composer Service</label>
    <referenceTo>Composer_Service__c</referenceTo>
    <relationshipLabel>Opportunity Location Services</relationshipLabel>
    <relationshipName>Opportunity_Location_Services</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Location_Service__c/fields/Opportunity_Service_Area__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Service_Area__c</fullName>
    <description>Opportunity Service Area</description>
    <label>Opportunity Service Area</label>
    <referenceTo>Opportunity_Service_Area__c</referenceTo>
    <relationshipLabel>Opportunity Location Services</relationshipLabel>
    <relationshipName>Opportunity_Location_Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Location_Service__c/fields/Pricing_Tier__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Tier__c</fullName>
    <defaultValue>&quot;Tier 1&quot;</defaultValue>
    <description>Pricing Tier</description>
    <label>Pricing Tier</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Pricing_Tier</valueSetName>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/Opportunity_Service_Area__c.object-meta.xml
<CustomObject>
    <description>The collection of postal codes for one service area inside a contract composer opportunity</description>
    <label>Opportunity Service Area</label>
    <nameField>
        <label>Display Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Service Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Advertising_Spend__c.field-meta.xml
<CustomField>
    <fullName>Advertising_Spend__c</fullName>
    <defaultValue>300</defaultValue>
    <description>Amount being spent on advertising</description>
    <label>Advertising Spend</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Display City</description>
    <label>Display City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Master opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Service Areas</relationshipLabel>
    <relationshipName>Opportunity_Service_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Phone</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Pricing_Tier__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Tier__c</fullName>
    <description>Pricing Tier</description>
    <label>Pricing Tier</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Pricing_Tier</valueSetName>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Display State</description>
    <label>Display State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care/force-app/main/default/objects/Opportunity_Service_Area__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Display Street</description>
    <label>Display Street</label>
    <type>TextArea</type>
</CustomField>

care/force-app/main/default/globalValueSets/Pricing_Tier.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Tier 1</fullName>
        <default>true</default>
        <label>Tier 1</label>
    </customValue>
    <customValue>
        <fullName>Tier 2</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 3</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 4</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 5</fullName>
    </customValue>
    <customValue>
        <fullName>Custom</fullName>
    </customValue>
    <masterLabel>Pricing Tier</masterLabel>
</GlobalValueSet>

care/force-app/main/default/classes/CCCTestDataFactory.cls
/*****************************************************************************************
Created By: Alan Oshry
Email: alan.oshry@revelanttech.com
Created: 11/12/2020
Description: Creates test data for use in Contract Composer Unit Tests
Comments:

********************************************************************************************/
@isTest
public class CCCTestDataFactory {

    public static void createUserSystemAdministrator() {
        User systemAdministrator = new User (
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1].Id,
            LastName = 'lastname',
            Email = 'SystemAdministrator_Test@care_unittest.com',
            Username = 'SystemAdministrator_Test@hcare_unittest.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'System Administrator',
            Alias = 'sysadmin',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US'
        );

        insert systemAdministrator;
    }

    public static void createSalesOriginationManagerUser() {
        Profile p = [SELECT Id FROM Profile WHERE Name='Sales Origination Manager'];
        User u = new User(Alias = 'testsom', Email='test_som_profile@caredotcom.com',
            EmailEncodingKey='UTF-8', LastName='Test SOM Profile', LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = p.Id,
            TimeZoneSidKey='America/Los_Angeles', UserName='test_som_profile@caredotcom.com');
        insert u;
    }

    public static void createSalesOriginationRepUser() {
        Profile p = [SELECT Id FROM Profile WHERE Name='Sales Origination Rep'];
        User u = new User(Alias = 'testsop', Email='test_so_profile@caredotcom.com',
            EmailEncodingKey='UTF-8', LastName='Test SO Profile', LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = p.Id,
            TimeZoneSidKey='America/Los_Angeles', UserName='test_so_profile@caredotcom.com');
        insert u;
    }

    public static void createContractComposerApiUser() {
        Profile p = [SELECT Id FROM Profile WHERE Name='Contract Composer API User'];
        User u = new User(Alias = 'testcca', Email='test_ccapi_profile@caredotcom.com',
            EmailEncodingKey='UTF-8', LastName='Test CCAPI Profile', LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = p.Id,
            TimeZoneSidKey='America/Los_Angeles', UserName='test_ccapi_profile@caredotcom.com');
        insert u;
    }

    public static void createAccount(String name) {
        Account account = new Account();
        account.Name = name;

        insert account;
    }

    public static void createOpportunity_SalesOrigination(String accountId, String composerServiceId) {
        Id recTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sales Origination').getRecordTypeId();

        Opportunity opportunityRecord = new Opportunity();
        opportunityRecord.Name = 'Test Opportunity - Sales Origination';
        opportunityRecord.AccountId = accountId;
        opportunityRecord.CloseDate = System.today().addMonths(1);
        opportunityRecord.RecordTypeId = recTypeId;
        opportunityRecord.StageName = 'Prospecting';
        opportunityRecord.LeadSource = 'Care.com Lead';
        opportunityRecord.Composer_Service__c = composerServiceId;

        insert opportunityRecord;
    }

    public static void createContact(String accountId, String lastName) {
        Contact contactRecord = new Contact();
        contactRecord.AccountId = accountId;
        contactRecord.LastName = lastName;
        contactRecord.Phone = '5555555555';
        contactRecord.Email = System.currentTimeMillis()+'@salesforce.com';

        insert contactRecord;
    }

    public static void createComposerServiceRecords() {
        List<Composer_Service__c> composerServiceRecords;
        Composer_Service__c composerServiceRecord;
        List<String> composerServiceList;
        String[] composerServiceRecordParts;

        // ############################## Create Composer Service Records ##############################
        // List of Composer Service Records in the following format: vertical:license level:base points:active:tier 1 amount:tier 1 bonus points:tier 2 amount:tier 2 bonus points:tier 3 amount:tier 3 bonus points:tier 4 amount:tier 4 bonus points:tier 5 amount:tier 5 bonus points:tier custom threshold:tuition discount bonus points
        composerServiceList = new List<String>();
        composerServiceList.add('Senior Care:Housing:6.0:true:300:1:400:2:500:3:600:4:700:5:800:4');
        composerServiceList.add('Senior Care:Home Care:5.0:true:300:2:400:3:500:4:600:5:700:6:800:4');
        composerServiceList.add('Senior Care:Adult Day Care:7.0:true:300:1:400:2:500:3:600:4:700:5:800:4');
        composerServiceList.add('Senior Care:Adult Day Care:7.0:false:300:1:400:2:500:3:600:4:700:5:800:4');
        composerServiceList.add('Childcare:Activities:4.0:true:300:1:400:6:500:9:600:12:700:12:800:4');
        composerServiceList.add('Childcare:Camps:5.0:true:300:1:400:2:500:3:600:4:700:5:800:4');
        composerServiceList.add('Childcare:Centers:4.0:true:300:1:400:2:500:3:600:4:700:5:800:4');
        composerServiceList.add('Childcare:FCCs:7.0:true:350:2:450:2:550:2:650:2:750:2:850:4');
        composerServiceList.add('Childcare:Nanny Agencies:3.0:true:300:1:400:2:500:3:600:4:700:5:800:4');
        composerServiceList.add('Childcare:Nanny Agencies:3.0:false:300:1:400:2:500:3:600:4:700:5:800:4');
        composerServiceRecords = new List<Composer_Service__c>();

        for (String composerService: composerServiceList) {
            composerServiceRecordParts = composerService.split(':');

            composerServiceRecord = new Composer_Service__c();
            composerServiceRecord.Vertical__c = composerServiceRecordParts[0];
            composerServiceRecord.License_Level__c = composerServiceRecordParts[1];
            composerServiceRecord.Base_Points__c = Decimal.valueOf(composerServiceRecordParts[2]);
            composerServiceRecord.Active__c = (composerServiceRecordParts[3] == 'true');
            composerServiceRecord.Tier_1_Amount__c = Decimal.valueOf(composerServiceRecordParts[4]);
            composerServiceRecord.Tier_1_Bonus_Points__c = Decimal.valueOf(composerServiceRecordParts[5]);
            composerServiceRecord.Tier_2_Amount__c = Decimal.valueOf(composerServiceRecordParts[6]);
            composerServiceRecord.Tier_2_Bonus_Points__c = Decimal.valueOf(composerServiceRecordParts[7]);
            composerServiceRecord.Tier_3_Amount__c = Decimal.valueOf(composerServiceRecordParts[8]);
            composerServiceRecord.Tier_3_Bonus_Points__c = Decimal.valueOf(composerServiceRecordParts[9]);
            composerServiceRecord.Tier_4_Amount__c = Decimal.valueOf(composerServiceRecordParts[10]);
            composerServiceRecord.Tier_4_Bonus_Points__c = Decimal.valueOf(composerServiceRecordParts[11]);
            composerServiceRecord.Tier_5_Amount__c = Decimal.valueOf(composerServiceRecordParts[12]);
            composerServiceRecord.Tier_5_Bonus_Points__c = Decimal.valueOf(composerServiceRecordParts[13]);
            composerServiceRecord.Tier_Custom_Threshold__c = Decimal.valueOf(composerServiceRecordParts[14]);
            composerServiceRecord.Tuition_Discount_Bonus_Points__c = Decimal.valueOf(composerServiceRecordParts[15]);

            composerServiceRecords.add(composerServiceRecord);
        }

        insert composerServiceRecords;
    }

    public static void createOpportunityServiceAreas(String opportunityId) {
        List<Opportunity_Service_Area__c> opportunityServiceAreaRecords;
        List<String> serviceAreaList;
        Opportunity_Service_Area__c opportunityServiceAreaRecord;
        String[] serviceAreaParts;

        // ############################## Create Opportunity Service Areas ##############################
        // List of Service Area data in the following format: name:amount:pricingTier:phone:street:city:state:postalCode:postalCodesCSV
        serviceAreaList = new List<String>();
        serviceAreaList.add('Service Area 1 - Marion County:300:Tier 1:3175079497:5875 Castle Creek Pkwy N Dr #300:Indianpolis:IN:46250:46107,46183,46201,46202,46203,46204,46205,46208,46214,46216,46217,46218,46219,46220,46221,46222,46224,46225,46226,46227,46228,46229,46231,46234,46235,46236,46237,46239,46240,46241,46250,46254,46256,46259,46260,46268,46278');
        serviceAreaList.add('Service Area 2 - Hamilton County:400:Tier 2:3175712400:1 Civic Square:Carmel:IN:46032:46030,46031,46032,46033,46034,46037,46038,46060,46062,46069,46079,46280,46290');
        serviceAreaList.add('Service Area 3 - Johnson County:900:Custom:3177365000:5 E Jefferson St.:Franklin:IN:46131:46106,46124,46131,46142,46143,46162,46164,46181,46184');

        opportunityServiceAreaRecords = new List<Opportunity_Service_Area__c>();
        for (String serviceArea: serviceAreaList) {
            serviceAreaParts = serviceArea.split(':');

            opportunityServiceAreaRecord = new Opportunity_Service_Area__c();
            opportunityServiceAreaRecord.Opportunity__c = opportunityId;
            opportunityServiceAreaRecord.Name = serviceAreaParts[0];
            opportunityServiceAreaRecord.Advertising_Spend__c = Decimal.valueOf(serviceAreaParts[1]);
            opportunityServiceAreaRecord.Pricing_Tier__c = serviceAreaParts[2];
            opportunityServiceAreaRecord.Phone__c = serviceAreaParts[3];
            opportunityServiceAreaRecord.Street__c = serviceAreaParts[4];
            opportunityServiceAreaRecord.City__c = serviceAreaParts[5];
            opportunityServiceAreaRecord.State__c = serviceAreaParts[6];
            opportunityServiceAreaRecord.Postal_Code__c = serviceAreaParts[7];
            opportunityServiceAreaRecord.Postal_Codes__c = serviceAreaParts[8];

            opportunityServiceAreaRecords.add(opportunityServiceAreaRecord);
        }

        insert opportunityServiceAreaRecords;
    }

    public static void createOpportunityLocationService(String locationId, String composerServiceId, String tier, Decimal spend) {

        Opportunity_Location_Service__c locationService = new Opportunity_Location_Service__c();
        locationService.Opportunity_Service_Area__c = locationId;
        locationService.Composer_Service__c = composerServiceId;
        locationService.Pricing_Tier__c = tier;
        locationService.Advertising_Spend__c = spend;

        insert locationService;
    }

	public static void createOpportunityContactRole(String contactId, String opportunityId) {
		OpportunityContactRole opportunityContactRoleRecord = new OpportunityContactRole();
		opportunityContactRoleRecord.ContactId = contactId;
		opportunityContactRoleRecord.OpportunityId = opportunityId;

		insert opportunityContactRoleRecord;
	}

}