care/force-app/main/default/objects/Data_Deletion_Rules__mdt/Data_Deletion_Rules__mdt.object-meta.xml
<CustomObject>
    <description>This is created as SFORCE-2107 but is generalized and can be used to prevent access to deletion of certain records in the system.</description>
    <label>Data Deletion Rules</label>
    <pluralLabel>Data_Deletion_Rules</pluralLabel>
</CustomObject>

care/force-app/main/default/objects/Data_Deletion_Rules__mdt/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>Describes the error message to be displayed when user tries to delete with insufficient previleges</description>
    <inlineHelpText>Describes the error message to be displayed when user tries to delete with insufficient previleges</inlineHelpText>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

care/force-app/main/default/objects/Data_Deletion_Rules__mdt/fields/Override_Data_Deletion__c.field-meta.xml
<CustomField>
    <fullName>Override_Data_Deletion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this check box to override the deletion settings.</description>
    <inlineHelpText>Check this check box to override the deletion settings.</inlineHelpText>
    <label>Override Data Deletion</label>
    <type>Checkbox</type>
</CustomField>

care/force-app/main/default/objects/Data_Deletion_Rules__mdt/fields/Permission_Set_Name__c.field-meta.xml
<CustomField>
    <fullName>Permission_Set_Name__c</fullName>
    <description>Describes the Permission Set name which needs deletion access. To provide multiple values, use the delimiter ;</description>
    <inlineHelpText>Describes the Permission Set name which needs deletion access. To provide multiple values, use the delimiter ;</inlineHelpText>
    <label>Permission Set Name</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

care/force-app/main/default/objects/Data_Deletion_Rules__mdt/fields/Profile_Name__c.field-meta.xml
<CustomField>
    <fullName>Profile_Name__c</fullName>
    <description>Describes the profile name which needs deletion access. To provide multiple values, use the delimiter ;</description>
    <inlineHelpText>Mention the profile name which needs deletion access. To provide multiple values, use the delimiter ;</inlineHelpText>
    <label>Profile Name</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

care/force-app/main/default/objects/Data_Deletion_Rules__mdt/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <description>Describes the record type of the object to be deleted. To provide multiple values, use the delimiter ;</description>
    <inlineHelpText>Mention the record type of the object to be deleted. To provide multiple values, use the delimiter ;</inlineHelpText>
    <label>Record Type</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

care/force-app/main/default/objects/Data_Deletion_Rules__mdt/fields/SObject_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_Name__c</fullName>
    <description>Describes the Object name which needs deletion access.</description>
    <inlineHelpText>Describes the Object name which needs deletion access.</inlineHelpText>
    <label>SObject Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Data_Deletion_Rules__mdt/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <description>Describes the Username which needs deletion access. To provide multiple values, use the delimiter ;</description>
    <inlineHelpText>Mention the Username which needs deletion access. To provide multiple values, use the delimiter ;</inlineHelpText>
    <label>Username</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

care/force-app/main/default/classes/Test_CaseDataDeletionAccessTrigger.cls
@isTest(SeeAllData=true)
private class Test_CaseDataDeletionAccessTrigger{
    
    static testMethod void CheckServiceAgreement(){   
        Test.startTest();
        String seekerRecId=getRecordTypesStatic.recordTypeNameIdMap.get('International Seeker');
        String providerRecId=getRecordTypesStatic.recordTypeNameIdMap.get('International Provider');
        String intlSafetyAlertRecId=getRecordTypesStatic.recordTypeNameIdMap.get('International Safety Alert');
        Account a1=new Account(lastname='testNormal',recordtypeid=seekerRecId,Global_Member_Id__c='12345678',personEmail='sridhar.neeli@care.com',locale__pc='uk');
        insert a1;
        
        Case c1=new Case(accountid=a1.id,Recordtypeid=intlSafetyAlertRecId,Status='Cleared');
        insert c1;

        
        Test.stopTest();
        
    }
    @isTest(SeeAllData=true)
    static void testCaseDataDeletion() 
    {
        List<Data_Deletion_Rules__mdt> ddrList=[SELECT DeveloperName,Error_Message__c,Id,Label,Language,MasterLabel,NamespacePrefix,Override_Data_Deletion__c,Permission_Set_Name__c,Profile_Name__c,QualifiedApiName,Record_Type__c,SObject_Name__c,User_Name__c FROM Data_Deletion_Rules__mdt where sobject_name__c='Case'];
        
        String seekerRecId=getRecordTypesStatic.recordTypeNameIdMap.get('International Seeker');
        String providerRecId=getRecordTypesStatic.recordTypeNameIdMap.get('International Provider');
        String intlSafetyAlertRecId=getRecordTypesStatic.recordTypeNameIdMap.get('International Safety Alert');
        
        Account a=new Account(lastname='testNormal',recordtypeid=seekerRecId,Global_Member_Id__c='12345678',personEmail='sridhar.neeli@care.com',locale__pc='uk');
        insert a;
        delete a;
        Account a1=new Account(lastname='testNormal',recordtypeid=seekerRecId,Global_Member_Id__c='12345678',personEmail='sridhar.neeli@care.com',locale__pc='uk');
        insert a1;
        
        Case c1=new Case(accountid=a1.id,Recordtypeid=intlSafetyAlertRecId,Status='Cleared');
        insert c1;
      //  delete c1;
        
    }
    @isTest(SeeAllData=true)
    static void testStandardAccountDeletion() 
    {
        List<Data_Deletion_Rules__mdt> ddrList=[SELECT DeveloperName,Error_Message__c,Id,Label,Language,MasterLabel,NamespacePrefix,Override_Data_Deletion__c,Permission_Set_Name__c,Profile_Name__c,QualifiedApiName,Record_Type__c,SObject_Name__c,User_Name__c FROM Data_Deletion_Rules__mdt where sobject_name__c='Case'];
        
        String liteRecId=getRecordTypesStatic.recordTypeNameIdMap.get('Lite');
        String providerRecId=getRecordTypesStatic.recordTypeNameIdMap.get('International Provider');
        String intlSafetyAlertRecId=getRecordTypesStatic.recordTypeNameIdMap.get('International Safety Alert');
        
        Account a=new Account(lastname='testNormal',recordtypeid=liteRecId,Global_Member_Id__c='12345678',personEmail='sridhar.neeli@care.com',locale__pc='uk');
        insert a;
       // delete a;

        
        Case c1=new Case(accountid=a.id,Recordtypeid=intlSafetyAlertRecId,Status='Cleared');
        insert c1;
        delete c1;
        
    }
        @isTest(SeeAllData=true)
    static void testCaseIntlSafetyCaseDeletion() 
    {
        List<Data_Deletion_Rules__mdt> ddrList=[SELECT DeveloperName,Error_Message__c,Id,Label,Language,MasterLabel,NamespacePrefix,Override_Data_Deletion__c,Permission_Set_Name__c,Profile_Name__c,QualifiedApiName,Record_Type__c,SObject_Name__c,User_Name__c FROM Data_Deletion_Rules__mdt where sobject_name__c='Case'];
        System.debug('ddrList==>:'+ddrList);
        String seekerRecId=getRecordTypesStatic.recordTypeNameIdMap.get('International Seeker');
        String providerRecId=getRecordTypesStatic.recordTypeNameIdMap.get('International Provider');
        String intlSafetyAlertRecId=getRecordTypesStatic.recordTypeNameIdMap.get('International Safety Alert');
        Account a1=new Account(lastname='testNormal',recordtypeid=seekerRecId,Global_Member_Id__c='12345678',personEmail='sridhar.neeli@care.com',locale__pc='uk');
        insert a1;
        
        Case c1=new Case(accountid=a1.id,Recordtypeid=intlSafetyAlertRecId,Status='Cleared');
        insert c1;
        delete c1;
        
    }
            @isTest(SeeAllData=true)
    static void testCaseUSSafetyCaseDeletion() 
    {
        List<Data_Deletion_Rules__mdt> ddrList=[SELECT DeveloperName,Error_Message__c,Id,Label,Language,MasterLabel,NamespacePrefix,Override_Data_Deletion__c,Permission_Set_Name__c,Profile_Name__c,QualifiedApiName,Record_Type__c,SObject_Name__c,User_Name__c FROM Data_Deletion_Rules__mdt where sobject_name__c='Case'];
        System.debug('ddrList==>:'+ddrList);
        String seekerRecId=getRecordTypesStatic.recordTypeNameIdMap.get('International Seeker');
        String providerRecId=getRecordTypesStatic.recordTypeNameIdMap.get('International Provider');
        String usSafetyAlertRecId=getRecordTypesStatic.recordTypeNameIdMap.get('Safety Alert');
        Account a1=new Account(lastname='testNormal',recordtypeid=seekerRecId,Global_Member_Id__c='12345678',personEmail='sridhar.neeli@care.com',locale__pc='uk'); 
        insert a1;
        
        Case c1=new Case(accountid=a1.id,Recordtypeid=usSafetyAlertRecId,Status='Cleared');
        insert c1;
        delete c1;
        
    }
}