care/force-app/main/default/objects/Topic_Map__mdt/Topic_Map__mdt.object-meta.xml
<CustomObject>
    <description>Allows admins to define how Article Topics map to Case Types or Live Agent Skills.</description>
    <label>Topic Map</label>
    <pluralLabel>Topic Maps</pluralLabel>
</CustomObject>

care/force-app/main/default/objects/Topic_Map__mdt/fields/Button_Id__c.field-meta.xml
<CustomField>
    <fullName>Button_Id__c</fullName>
    <inlineHelpText>The Chat Button Id.  Use only the 15 character id (because that&apos;s what the one the Live agent JavaScript uses).</inlineHelpText>
    <label>Button Id</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Topic_Map__mdt/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <inlineHelpText>When a Case is created from an Article with this Topic, this field indicates which Case Type the Case should be created with.</inlineHelpText>
    <label>Case Type</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/Topic_Map__mdt/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <inlineHelpText>Article Topic (defined via Data Category in Article).</inlineHelpText>
    <label>Topic</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care/force-app/main/default/objects/US_Knowledge__kav/US_Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>Knowledge Articles for US Member Care team.</description>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

care/force-app/main/default/objects/US_Knowledge__kav/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Answer</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

care/force-app/main/default/classes/KnowledgeArticleController_Test.cls
@isTest
public with sharing class KnowledgeArticleController_Test {

    public static ID createArticle(){
        ID knowledgeArticleId;
        Profile p = [SELECT Id from Profile WHERE Name='System Administrator'];
        User u = new User(alias = 'testalia', email='test@care.com',
                emailencodingkey='UTF-8',
                lastname='testLastName',
                languagelocalekey='en_US',
                localesidkey='en_US', profileid = p.Id,
                timezonesidkey='America/Los_Angeles',
                username='test@care.com.nextcaseunittest',
                //Platform__c = 'International',
                //Tier__c = '3',
                Language__c = 'Dutch; German; French; English; Finnish; Danish; Swedish',
                UserPermissionsKnowledgeUser = true
        );
        insert u;

        System.runAs(u){
            //  method to help create data
            US_Knowledge__kav knowledgeArticle = new US_Knowledge__kav(Title='Unit test',Body__c='Sample Body',URLName='sampleurl2');
            insert knowledgeArticle;

            US_Knowledge__kav obj1 = [SELECT Id, KnowledgeArticleId FROM US_Knowledge__kav WHERE Id =: knowledgeArticle.Id];

            US_Knowledge__DataCategorySelection dc = new US_Knowledge__DataCategorySelection();
            dc.parentId = knowledgeArticle.id;
            dc.DataCategoryGroupName = 'Topic';
            dc.DataCategoryName = 'Trust_Safety';
            insert dc;
            KbManagement.PublishingService.publishArticle(obj1.KnowledgeArticleId, true); //PublishStatus = online

            knowledgeArticleId = knowledgeArticle.id;
        }

        return knowledgeArticleId;

    }

    @isTest static void testGetCaseType() {
        ID knowledgeArticleId = KnowledgeArticleController_Test.createArticle();
        String memberType = 'Seeker';

        Test.startTest();
        Topic_Map__mdt topicMap = KnowledgeArticleController.getTopicMap(knowledgeArticleId, memberType);
        String orgId = KnowledgeArticleController.getOrgId();
        Test.stopTest();

        System.assertNotEquals(null, topicMap.Case_Type__c, 'Returned Case Type should not be null');
        System.assertEquals('Trust & Safety', topicMap.Topic__c, 'Returned topic should have Trust & Safety');
        System.assertNotEquals(null, topicMap.Button_Id__c, 'Returned Button Id should not be null');
        System.assertEquals(UserInfo.getOrganizationId(), orgId, 'These values should have matched!');

    }

    @isTest static void testGetArticle() {
        ID knowledgeArticleId = KnowledgeArticleController_Test.createArticle();

        Test.startTest();
		Map<String, String> article = KnowledgeArticleController.getArticle(knowledgeArticleId);
        Test.stopTest();

        System.assertEquals('Unit test', article.get('Title'), 'Returned Title should have been Unit Test');
        System.assertEquals('Sample Body', article.get('Body__c'), 'Returned Body should have been Sample Body');
    }

}